function [comparison,detail]=ComparePronkBridgeOrbits_v3(first,second,tolerances)
%COMPAREPRONKBRIDGEORBITS_V3 Saved-history, one-sided numerical diagnostics.
% Both orbits use the same labeled BL-marked apex and horizontal orientation.
% Linear interpolation within smooth spans is diagnostic, not a rigorous bound.
    a=HybridCycleData_v3.unpack(first);b=HybridCycleData_v3.unpack(second);
    baseline=[10;10;20;20;1;1;0;0;2;.5];
    assert(isequal(first.parameter(:),baseline)&&isequal(second.parameter(:),baseline));
    for data={a,b}
        x=data{1}.state;
        assert(max(abs(x(:,[5,6])),[],'all')<1e-7 ...
            &&max(abs(x(:,[7,9,11,13])-x(:,7)),[],'all')<1e-7 ...
            &&max(abs(x(:,[8,10,12,14])-x(:,8)),[],'all')<1e-7, ...
            'ComparePronkBridgeOrbits_v3:Restriction','Saved histories leave the synchronized-pronk restriction.');
    end
    xa=first.initial_state(:);xb=second.initial_state(:);xa(1)=0;xb(1)=0;
    energyA=QuadrupedEnergy_v3.evaluate(xa,first.initial_mode,baseline);
    energyB=QuadrupedEnergy_v3.evaluate(xb,second.initial_mode,baseline);
    idsA=[a.history.guard_id];idsB=[b.history.guard_id];
    countsA=arrayfun(@(id)sum(idsA==id),1:8);countsB=arrayfun(@(id)sum(idsB==id),1:8);
    eventPhaseGap=Inf;eventStateGap=Inf;eventModeMatch=false;events=struct([]);
    if isequal(countsA,countsB)&&all(countsA==1)
        eventPhaseGap=0;eventStateGap=0;eventModeMatch=true;
        for id=1:8
            ta=a.history(idsA==id).time;tb=b.history(idsB==id).time;
            phases=[(ta-a.start_time)/a.period,(tb-b.start_time)/b.period];
            [leftA,modeLA]=HybridCycleData_v3.sample(a,ta,'left');
            [rightA,modeRA]=HybridCycleData_v3.sample(a,ta,'right');
            [leftB,modeLB]=HybridCycleData_v3.sample(b,tb,'left');
            [rightB,modeRB]=HybridCycleData_v3.sample(b,tb,'right');
            leftA(1)=leftA(1)-a.state(1,1);rightA(1)=rightA(1)-a.state(1,1);
            leftB(1)=leftB(1)-b.state(1,1);rightB(1)=rightB(1)-b.state(1,1);
            gap=max(norm(leftA-leftB,inf),norm(rightA-rightB,inf));
            item=struct('guard_id',id,'phase',phases,'left_state_first',leftA, ...
                'left_state_second',leftB,'right_state_first',rightA,'right_state_second',rightB, ...
                'state_gap',gap,'modes_match',isequal(modeLA,modeLB)&&isequal(modeRA,modeRB));
            if isempty(events),events=item;else,events(end+1)=item;end %#ok<AGROW>
            eventPhaseGap=max(eventPhaseGap,abs(diff(phases)));eventStateGap=max(eventStateGap,gap);
            eventModeMatch=eventModeMatch&&item.modes_match;
        end
    end
    phase=linspace(0,1,2001).';eventPhases=[];
    if ~isempty(a.history),eventPhases=[eventPhases;([a.history.time].'-a.start_time)/a.period];end
    if ~isempty(b.history),eventPhases=[eventPhases;([b.history.time].'-b.start_time)/b.period];end
    keep=true(size(phase));
    for p=eventPhases.',keep=keep&abs(phase-p)>tolerances.event_exclusion_phase;end
    phase=phase(keep);
    [statesA,modesA]=HybridCycleData_v3.sample(a,a.start_time+phase*a.period,'right');
    [statesB,modesB]=HybridCycleData_v3.sample(b,b.start_time+phase*b.period,'right');
    statesA(:,1)=statesA(:,1)-a.state(1,1);statesB(:,1)=statesB(:,1)-b.state(1,1);
    driftA=a.state(end,1)-a.state(1,1);driftB=b.state(end,1)-b.state(1,1);
    comparison=struct('schema_version','saved-pronk-bridge-orbit-comparison-v3-1', ...
        'horizontal_reflection_applied',false,'phase_shift',0, ...
        'phase_convention','Same labeled BL-marked apex; constant horizontal origin removed.', ...
        'apex_state_gap',norm(xa(2:end)-xb(2:end),inf),'energy_gap',abs(energyA-energyB), ...
        'period_gap',abs(a.period-b.period),'drift_gap',abs(driftA-driftB), ...
        'contact_counts_first',countsA,'contact_counts_second',countsB, ...
        'contact_counts_equal',isequal(countsA,countsB),'event_phase_gap',eventPhaseGap, ...
        'one_sided_event_state_gap',eventStateGap,'event_modes_match',eventModeMatch, ...
        'smooth_history_state_gap',max(abs(statesA-statesB),[],'all'), ...
        'smooth_history_modes_match',isequal(modesA,modesB),'sample_count',numel(phase), ...
        'interpolation_scope','Saved one-sided linear interpolation in smooth spans; finite-resolution numerical diagnostic, not closure or a certified trajectory error bound.', ...
        'same_local_numerical_orbit_supported',false,'rigorous_identity_claimed',false);
    comparison.same_local_numerical_orbit_supported= ...
        comparison.apex_state_gap<tolerances.apex_state ...
        &&comparison.energy_gap<tolerances.energy&&comparison.period_gap<tolerances.period ...
        &&comparison.drift_gap<tolerances.drift&&comparison.contact_counts_equal ...
        &&all(countsA==1)&&eventPhaseGap<tolerances.event_phase ...
        &&eventStateGap<tolerances.event_state&&eventModeMatch ...
        &&comparison.smooth_history_state_gap<tolerances.smooth_history ...
        &&comparison.smooth_history_modes_match;
    detail=struct('phase',phase,'states_first',statesA,'states_second',statesB, ...
        'modes_first',modesA,'modes_second',modesB,'events',events, ...
        'raw_first_trajectory',first.trajectory,'raw_second_trajectory',second.trajectory, ...
        'tolerances',tolerances);
end
