function manifest = ExportOrganizedBranches_v3()
%EXPORTORGANIZEDBRANCHES_V3 Organize existing accepted samples without shooting.
% Original scientific files remain untouched. Samples, source admission and
% continuation increments retain their distinct meanings and provenance.
    started = tic;
    v3 = V3Root_v3();
    p1 = 'P1_Single_Flight_Phase_Continua';
    p2 = 'P2_Double_Flight_Phase_Continua';
    created = char(datetime('now','TimeZone','UTC', ...
        'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
    exports = struct([]);
    originalPIP('PIP_candidate_1','PIP_n0_PK_Signed_Samples',10);
    originalPIP('PIP_PK_low_energy_neighborhood', ...
        'PIP_Low_Energy_PK_Signed_Samples',10);
    historicalPIP(1,'Restricted_Daughter_1_Signed_Samples');
    historicalPIP(2,'Restricted_Daughter_2_Signed_Samples');
    originalPIP('PIP_candidate_2','PIP_candidate_2_PK_Signed_Samples',1);
    originalPIP('PIP_candidate_3','PIP_candidate_3_PK_Signed_Samples',1);
    importedBridge();
    standingCampaign('opposed_spread_n0_negative_A1e-3_campaign', ...
        'Opposed_Spread_n0_Negative_Cycle_Samples');
    standingCampaign('opposed_spread_n0_positive_A1e-3_campaign', ...
        'Opposed_Spread_n0_Positive_Cycle_Samples');
    theoryStanding();
    manifest = struct('schema_version','organized-branch-exports-v3-1', ...
        'created_utc',created,'matlab_version',version, ...
        'helper_path',relative([mfilename('fullpath'),'.m']), ...
        'helper_sha256',RoundSHA256_v3([mfilename('fullpath'),'.m']), ...
        'exports',exports,'source_bytes_preserved',true, ...
        'new_shooting_simulations',0,'new_numerical_records',0, ...
        'elapsed_saved_data_postprocessing_seconds',toc(started), ...
        'scope',['These files collect previously accepted saved orbits. ', ...
            'Record counts are not counts of distinct cycles or new amplitudes. ', ...
            'No new closure, primitive-period, gait or bifurcation certificate ', ...
            'is established by this export. Scientific audit files retain ', ...
            'the acceptance, failure and attachment evidence.']);
    RoundJSON_v3(fullfile(v3,'Audits_v3','Organized_Branch_Exports_v3.json'),manifest);
    fprintf('Exported %d saved sample datasets; zero new shooting simulations.\n',numel(exports));

    function originalPIP(taskID,id,expectedCount)
        base = fullfile('Research_v3','next_round','tasks','full',taskID);
        [loaded,origin] = readSource(fullfile(base,'phase_checkpoint.mat'),{'record'});
        record = loaded.record;
        branch = emptyBranch(id,'signed_samples','original signed daughter evidence',1);
        branch.source_manifest = origin;
        branch.critical_parent_energy = record.critical_energy;
        branch.amplitude_coordinate = 'signed projection onto the registered PIP critical direction';
        entries = record.amplitudes;
        for index = 1:numel(entries)
            entry = entries(index);
            if ~entry.accepted,continue;end
            [saved,source] = readSource(fullfile(base,entry.artifact), ...
                {'orbit','replayOrbit','entry'});
            assert(saved.entry.accepted && saved.entry.signed_amplitude == entry.signed_amplitude, ...
                'ExportOrganizedBranches_v3:AcceptanceRecord', ...
                'The original accepted daughter and its checkpoint disagree.');
            branch = appendOrbit(branch,acceptedDaughterOrbit(saved),source, ...
                entry.signed_amplitude,NaN,'original_signed_daughter', ...
                struct('accepted_in_source',true,'selection_index',index));
        end
        assert(branch.count == expectedCount,'ExportOrganizedBranches_v3:RecordCount', ...
            'Expected %d saved accepted records for %s; found %d.',expectedCount,taskID,branch.count);
        writeBranch(branch,p1);
    end

    function historicalPIP(familyIndex,id)
        base = fullfile('Research_v3','runs','full');
        [loaded,origin] = readSource(fullfile(base,'pip_pk_local_report.mat'),{'report'});
        connection = loaded.report.connections(familyIndex);
        branch = emptyBranch(id,'signed_samples','historical restricted signed daughter evidence',1);
        branch.source_manifest = origin;
        branch.critical_parent_energy = connection.critical_energy;
        branch.amplitude_coordinate = 'signed projection onto the historical registered PIP critical direction';
        entries = connection.amplitudes;
        for index = 1:numel(entries)
            entry = entries(index);
            if ~(entry.converged && entry.in_registered_domain ...
                    && entry.replay_full_closure <= 1e-8),continue;end
            [saved,source] = readSource(fullfile(base,entry.artifact), ...
                {'orbit','replayOrbit','entry'});
            assert(saved.entry.converged && saved.entry.in_registered_domain ...
                && saved.entry.replay_full_closure <= 1e-8 ...
                && saved.entry.signed_amplitude == entry.signed_amplitude, ...
                'ExportOrganizedBranches_v3:HistoricalAcceptance', ...
                'The saved historical daughter does not match its accepted source record.');
            branch = appendOrbit(branch,acceptedDaughterOrbit(saved),source, ...
                entry.signed_amplitude,NaN,'historical_signed_daughter', ...
                struct('accepted_in_source',true,'selection_index',index));
        end
        assert(branch.count == 10,'ExportOrganizedBranches_v3:RecordCount', ...
            'Expected ten accepted historical signed records for family %d.',familyIndex);
        writeBranch(branch,p1);
    end

    function importedBridge()
        base = fullfile('Research_v3','next_round','tasks','full', ...
            'imported_PK_to_low_PIP_daughter_negative_0p01');
        [loaded,origin] = readSource(fullfile(base,'bridge_checkpoint.mat'),{'phase'});
        branch = emptyBranch('Imported_PK_Low_Energy_Local_Bridge', ...
            'local_bridge','saved imported-PK source admission and local continuation increments',1);
        branch.source_manifest = origin;
        branch.amplitude_coordinate = 'signed projection onto the registered low-energy PIP critical direction';
        entries = loaded.phase.accepted_points;
        for index = 1:numel(entries)
            [saved,source] = readSource(fullfile(base,entries(index).artifact), ...
                {'solution','report','trial'});
            requireServiceAcceptance(saved);
            assert(saved.trial.amplitude == entries(index).amplitude, ...
                'ExportOrganizedBranches_v3:BridgeAmplitude', ...
                'Bridge checkpoint and saved accepted trial amplitudes disagree.');
            kind = 'local_continuation_increment';
            if index == 1,kind = 'fresh_source_admission';end
            branch = appendOrbit(branch,saved.solution,source,entries(index).amplitude,NaN,kind, ...
                struct('accepted_in_source',true,'selection_index',index, ...
                    'continuation_locality_gate',saved.trial.continuation_locality_gate));
        end
        assert(branch.count == 5 && loaded.phase.accepted_increment_count == 4, ...
            'ExportOrganizedBranches_v3:RecordCount', ...
            'Expected one source admission and four saved local bridge increments.');
        branch.source_admission_record_count = 1;
        branch.previously_executed_increment_count = 4;
        writeBranch(branch,p1);
    end

    function standingCampaign(taskID,id)
        base = fullfile('Research_v3','next_round','tasks','full',taskID);
        [loaded,origin] = readSource(fullfile(base,'restricted_period_two_checkpoint.mat'),{'phase'});
        branch = emptyBranch(id,'primitive_cycle_samples', ...
            'saved opposed-spread n0 restricted campaign records',2);
        branch.source_manifest = origin;
        branch.amplitude_coordinate = 'signed marked touchdown angle';
        entries = loaded.phase.trials;
        for index = 1:numel(entries)
            entry = entries(index);
            if ~entry.accepted,continue;end
            [saved,source] = readSource(fullfile(base,entry.artifact), ...
                {'solution','report','trial'});
            requireServiceAcceptance(saved);
            assert(saved.trial.actual_flight_count == 2 ...
                && saved.trial.touchdown_angle == entry.touchdown_angle, ...
                'ExportOrganizedBranches_v3:StandingAcceptance', ...
                'Standing sample must retain the saved physical two-flight acceptance.');
            branch = appendOrbit(branch,saved.solution,source,entry.touchdown_angle,0,entry.kind, ...
                struct('accepted_in_source',true,'selection_index',index, ...
                    'source_actual_gait_label',entry.actual_gait_label, ...
                    'source_actual_gait_status',entry.actual_gait_status));
        end
        assert(branch.count == 5,'ExportOrganizedBranches_v3:RecordCount', ...
            'Expected five accepted source records for %s.',taskID);
        branch.phase_equivalence_note = ['Positive and negative touchdown-angle representatives ', ...
            'at a fixed resonance index and absolute amplitude are marked half-period ', ...
            'phases of the same labeled cycle. Admission and meaningful correction may ', ...
            'also repeat an existing amplitude. No unique-cycle count is inferred here.'];
        writeBranch(branch,p2);
    end

    function theoryStanding()
        base = fullfile('Research_v3','next_round','theory');
        branch = emptyBranch('Opposed_Spread_n0_n1_Theory_Cycle_Samples', ...
            'primitive_cycle_samples','saved exact restricted predictor replays',2);
        branch.amplitude_coordinate = 'signed marked touchdown angle';
        for resonance = 0:1
            for side = {'negative','positive'}
                artifact = sprintf('opposed_spread_n%d_%s_A1e-3_actual_trace.mat',resonance,side{1});
                [saved,source] = readSource(fullfile(base,artifact),{'orbit','item','predictor'});
                assert(saved.item.passed && saved.item.actual_flight_count == 2, ...
                    'ExportOrganizedBranches_v3:TheoryAcceptance', ...
                    'Only passed saved physical two-flight theory replays may be exported.');
                branch = appendOrbit(branch,saved.orbit,source, ...
                    saved.predictor.touchdown_angle,saved.predictor.resonance_index, ...
                    'exact_predictor_replay',struct('accepted_in_source',true, ...
                    'source_actual_gait_label',saved.item.actual_gait_label, ...
                    'source_actual_gait_status',saved.item.actual_gait_status));
            end
        end
        assert(branch.count == 4,'ExportOrganizedBranches_v3:RecordCount', ...
            'Expected the four preserved signed n0/n1 exact-predictor replays.');
        branch.phase_equivalence_note = ['Opposite signs at each fixed resonance index are ', ...
            'marked half-period phases of the same labeled cycle. These four replay ', ...
            'records do not establish four distinct cycles or four continued branches.'];
        writeBranch(branch,p2);
    end

    function branch = emptyBranch(id,type,origin,expectedFlights)
        branch = struct('schema_version','organized-saved-orbit-dataset-v3-1', ...
            'id',id,'created_utc',created,'dataset_type',type,'origin',origin, ...
            'expected_primitive_flight_count',expectedFlights,'count',0, ...
            'accepted_orbits',{{}},'amplitude',[],'amplitude_coordinate','', ...
            'resonance_index',[],'energy',[],'period',[],'drift',[],'mean_speed',[], ...
            'flight_count',[],'gait_label',{{}},'gait_status',{{}},'full_closure',[], ...
            'record_kind',{{}},'source_paths',{{}},'source_original_paths',{{}}, ...
            'source_sha256',{{}},'source_acceptance',{{}}, ...
            'source_manifest',repmat(struct('path','','original_path','','sha256',''),0,1), ...
            'new_shooting_simulations',0,'new_numerical_records',0, ...
            'unique_cycle_count_claimed',false,'certified_gait_claimed',false, ...
            'bifurcation_certificate_created',false, ...
            'interpretation',['A collection of previously accepted saved records. ', ...
                'Sampling or exporting does not prove global connectivity, ', ...
                'distinct cycles, a named gait, or a bifurcation.']);
    end

    function branch = appendOrbit(branch,orbit,source,amplitude,resonance,kind,acceptance)
        assert(~isempty(orbit),'ExportOrganizedBranches_v3:MissingOrbit', ...
            'An accepted source must contain its independently saved physical orbit.');
        closure = norm(orbit.poincare_state(2:end)-orbit.initial_state(2:end),inf);
        assert(isfinite(closure) && closure <= 1e-8, ...
            'ExportOrganizedBranches_v3:SavedClosure','Saved accepted orbit closure exceeds 1e-8.');
        identification = GaitIdentification_v3(orbit);
        assert(identification.flight_count == branch.expected_primitive_flight_count, ...
            'ExportOrganizedBranches_v3:FlightClassification', ...
            'Saved primitive flight count disagrees with the destination study.');
        energy = QuadrupedEnergy_v3.evaluate(orbit.initial_state,orbit.initial_mode,orbit.parameter);
        period = orbit.period;
        drift = orbit.stride_displacement(1);
        assert(isfinite(energy) && isfinite(period) && period > 0 && isfinite(drift), ...
            'ExportOrganizedBranches_v3:SavedNumerics','Saved orbit summary must be finite.');
        index = branch.count+1;
        branch.accepted_orbits{index} = orbit;
        branch.amplitude(index) = amplitude;
        branch.resonance_index(index) = resonance;
        branch.energy(index) = energy;
        branch.period(index) = period;
        branch.drift(index) = drift;
        branch.mean_speed(index) = drift/period;
        branch.flight_count(index) = identification.flight_count;
        branch.gait_label{index} = char(identification.label);
        branch.gait_status{index} = char(identification.status);
        branch.full_closure(index) = closure;
        branch.record_kind{index} = kind;
        branch.source_paths{index} = source.path;
        branch.source_original_paths{index} = source.original_path;
        branch.source_sha256{index} = source.sha256;
        branch.source_acceptance{index} = acceptance;
        branch.source_manifest(end+1) = source;
        branch.count = index;
    end

    function writeBranch(branch,study)
        for index = 1:numel(branch.source_manifest)
            source = branch.source_manifest(index);
            assert(V3HashMatches_v3(source.sha256, fullfile(v3,source.path)), ...
                'ExportOrganizedBranches_v3:SourceChanged', ...
                'A scientific source changed while exporting %s.',branch.id);
        end
        artifact = fullfile(study,[branch.id,'.mat']);
        % The existing GUI consumes top-level solution cells directly.
        data = struct('branch',branch,'solutions',{branch.accepted_orbits});
        RoundSave_v3(fullfile(v3,artifact),data);
        file = fullfile(v3,artifact);
        details = V3Dir_v3(file);
        assert(details.bytes < 100000000,'ExportOrganizedBranches_v3:ArtifactSize', ...
            'An organized dataset exceeds the working-file size limit.');
        summary = rmfield(branch,'accepted_orbits');
        summary.mat_artifact = artifact;
        summary.mat_sha256 = RoundSHA256_v3(file);
        summary.mat_bytes = details.bytes;
        jsonArtifact = fullfile(study,[branch.id,'.json']);
        RoundJSON_v3(fullfile(v3,jsonArtifact),summary);
        jsonDetails = V3Dir_v3(fullfile(v3,jsonArtifact));
        assert(jsonDetails.bytes < 100000000,'ExportOrganizedBranches_v3:ArtifactSize', ...
            'An organized dataset summary exceeds the working-file size limit.');
        item = struct('id',branch.id,'study',study,'dataset_type',branch.dataset_type, ...
            'mat_artifact',artifact,'json_artifact',jsonArtifact, ...
            'mat_sha256',summary.mat_sha256,'mat_bytes',summary.mat_bytes, ...
            'accepted_source_record_count',branch.count, ...
            'flight_count',unique(branch.flight_count),'new_numerical_records',0, ...
            'source_manifest',branch.source_manifest);
        if isempty(exports),exports = item;else,exports(end+1) = item;end
    end

    function [loaded,source] = readSource(oldRelative,names)
        file = V3Path_v3(fullfile(v3,oldRelative));
        assert(isfile(V3Path_v3(file)),'ExportOrganizedBranches_v3:MissingSource', ...
            'Required scientific source is missing: %s.',oldRelative);
        before = RoundSHA256_v3(file);
        inventory = whos('-file',file);
        available = intersect(names,{inventory.name},'stable');
        loaded = load(V3Path_v3(file),available{:});
        after = RoundSHA256_v3(file);
        assert(strcmp(before,after),'ExportOrganizedBranches_v3:MovingSource', ...
            'Scientific source changed during saved-data reading: %s.',oldRelative);
        source = struct('path',relative(file),'original_path',oldRelative,'sha256',after);
    end

    function value = relative(file)
        prefix = [v3,filesep];
        assert(startsWith(file,prefix),'ExportOrganizedBranches_v3:OutsideV3', ...
            'All saved input and output artifacts must lie inside v3.');
        value = strrep(file(numel(prefix)+1:end),filesep,'/');
    end
end

function orbit = acceptedDaughterOrbit(saved)
    orbit = [];
    if isfield(saved,'replayOrbit'),orbit = saved.replayOrbit;end
    if isempty(orbit) && isfield(saved,'orbit'),orbit = saved.orbit;end
end

function requireServiceAcceptance(saved)
    assert(isfield(saved,'solution') && ~isempty(saved.solution) ...
        && isfield(saved,'trial') && saved.trial.accepted ...
        && isfield(saved,'report') && saved.report.accepted, ...
        'ExportOrganizedBranches_v3:ServiceAcceptance', ...
        'Both the saved shared-service report and the domain trial must accept the orbit.');
end
