function result=PronkTrajectoryEvidence_v3(orbit)
%PRONKTRAJECTORYEVIDENCE_V3 Physical one-sided histories for pronk isotropy.
% An ordered simultaneous-reset trace contains virtual intermediate states at
% the same time. Keep both physical pre/post values, excluding only internal
% same-time rows; never exclude a positive-duration flow sample or event.
    data=HybridCycleData_v3.unpack(orbit);s=data.schema;
    [~,first]=unique(data.time,'stable');[~,last]=unique(data.time,'last');
    rows=unique([first;last]);state=data.state(rows,:);mode=data.mode(rows,:);
    verticalIndices=[s.State.dx,s.State.phi,s.State.dphi,s.Leg.AngleIndices,s.Leg.RateIndices];
    angular=state(:,s.Leg.AngleIndices);rates=state(:,s.Leg.RateIndices);
    counts=zeros(4,2);
    for eventIndex=1:numel(data.history)
        [leg,kind]=HybridCycleData_v3.eventIdentity(data.history(eventIndex),s);
        if isempty(leg),continue;end
        if kind=="touchdown",counts(leg,1)=counts(leg,1)+1;
        elseif kind=="liftoff",counts(leg,2)=counts(leg,2)+1;end
    end
    result=struct('diagnostic_version','physical-one-sided-pronk-history-v3-1', ...
        'history_interpretation','first and last states at each time are physical left/right values', ...
        'physical_one_sided_sample_count',numel(rows), ...
        'omitted_internal_same_time_reset_rows',numel(data.time)-numel(rows), ...
        'phase_independent_parent_witness', ...
        'vertical parent has dx, pitch, leg angles and rates identically zero at every phase', ...
        'maximum_departure_from_vertical_parent',max(abs(state(:,verticalIndices)),[],'all'), ...
        'paired_leg_motion_error',max([abs(angular-angular(:,1)),abs(rates-rates(:,1))],[],'all'), ...
        'synchronized_contact_history',all(mode==mode(:,1),'all'), ...
        'td_lo_counts_per_leg',counts,'one_td_and_lo_per_leg',all(counts==1,'all'), ...
        'drift',orbit.stride_displacement(1), ...
        'reflection_symmetry_loss_witness', ...
        'nonzero drift changes sign under horizontal reflection plus fore-hind exchange', ...
        'minimum_guard_transversality',orbit.minimum_guard_transversality, ...
        'section_transversality',orbit.section_transversality);
end
