function evidence=PronkAttachmentEvidence_v3(connection,settings)
%PRONKATTACHMENTEVIDENCE_V3 Auditable numerical gates for a local attachment.
% This is evidence within the synchronized, fixed-energy chart, conditional
% on its stated smoothness assumptions. Error estimates are not proof bounds.
    sigma=connection.singular_values(:);
    matrixError=connection.matrix_uncertainty_estimate;
    trans=connection.transversality;
    energyError=connection.critical_energy_uncertainty_estimate;
    gates=struct('reliable_parent_derivatives',connection.parent_derivatives_reliable, ...
        'resolved_simple_kernel',sigma(2)>settings.kernel_gap_factor*matrixError, ...
        'critical_kernel_near_zero',sigma(3)<=settings.kernel_zero_factor*max(matrixError,1e-12), ...
        'resolved_left_kernel_transversality',abs(trans.estimate) ...
            >settings.transversality_factor*max(trans.uncertainty_estimate,1e-12), ...
        'both_signed_sequences',false,'critical_direction_alignment',false, ...
        'energy_approach_and_quadratic_scaling',false,'genuine_large_amplitude_corrections',false, ...
        'full_closure_and_tighter_replay',false,'distinct_full_trajectories',false, ...
        'synchronized_primitive_contact_cycles',false,'signed_reflection_agreement',false);
    evidence=struct('schema_version','restricted-pronk-attachment-evidence-v3-2', ...
        'status','candidate_only','gates',gates,'failed_gates',{{}}, ...
        'kernel_gap_to_error_ratio',sigma(2)/max(matrixError,eps), ...
        'transversality_to_error_ratio',abs(trans.estimate)/max(trans.uncertainty_estimate,eps), ...
        'energy_uncertainty_estimate',energyError,'signed_sequences',struct([]), ...
        'signed_reflection_maximum_error',NaN, ...
        'claim','conditional numerical local attachment in the synchronized fixed-parameter pronk subspace', ...
        'full_system_regular_cluster_derivative_claimed',false, ...
        'global_network_or_exhaustiveness_claimed',false);
    points=connection.amplitudes;
    if isempty(points),evidence=finish(evidence,gates);return;end
    accepted=[points.converged]&[points.in_registered_domain];
    points=points(accepted);
    if isempty(points),evidence=finish(evidence,gates);return;end
    sequences=repmat(struct('sign',0,'accepted_count',0,'resolved_energy_shift_count',0, ...
        'quadratic_energy_coefficient',NaN,'maximum_relative_fit_error',Inf, ...
        'approaches_parent',false,'quadratic_scaling_resolved',false, ...
        'largest_amplitude',NaN,'largest_amplitude_genuinely_corrected',false),1,2);
    for signIndex=1:2
        signValue=2*signIndex-3;
        selected=points(sign([points.signed_amplitude])==signValue);
        sequences(signIndex).sign=signValue;
        sequences(signIndex).accepted_count=numel(selected);
        if isempty(selected),continue;end
        [amplitudes,order]=sort(abs([selected.signed_amplitude]));selected=selected(order);
        delta=[selected.energy]-connection.critical_energy;
        resolved=abs(delta)>5*energyError;
        sequences(signIndex).resolved_energy_shift_count=sum(resolved);
        sequences(signIndex).largest_amplitude=amplitudes(end);
        sequences(signIndex).largest_amplitude_genuinely_corrected=selected(end).genuine_correction ...
            &&amplitudes(end)>=max(settings.amplitudes)*(1-1e-12);
        sequences(signIndex).approaches_parent=numel(selected)>=settings.minimum_signed_amplitudes ...
            &&abs(delta(1))<=.2*abs(delta(end))+2*energyError;
        if sum(resolved)>=2
            a2=amplitudes(resolved).^2;shifts=delta(resolved);
            coefficient=sum(a2.*shifts)/sum(a2.^2);
            relativeError=max(abs(shifts-coefficient*a2)./max(abs(shifts),energyError));
            sequences(signIndex).quadratic_energy_coefficient=coefficient;
            sequences(signIndex).maximum_relative_fit_error=relativeError;
            sequences(signIndex).quadratic_scaling_resolved=relativeError<=settings.energy_scaling_relative_tolerance;
        end
    end
    gates.both_signed_sequences=all([sequences.accepted_count]>=settings.minimum_signed_amplitudes);
    gates.critical_direction_alignment=all([points.critical_alignment]>=settings.minimum_critical_alignment) ...
        &&all([points.amplitude_constraint_error]<=10*settings.root_residual_tolerance);
    gates.energy_approach_and_quadratic_scaling=all([sequences.approaches_parent]) ...
        &&all([sequences.quadratic_scaling_resolved]);
    gates.genuine_large_amplitude_corrections=all([sequences.largest_amplitude_genuinely_corrected]);
    gates.full_closure_and_tighter_replay=all([points.full_closure]<=settings.full_closure_tolerance) ...
        &&all([points.replay_full_closure]<=settings.full_closure_tolerance) ...
        &&all([points.replay_signature_match]) ...
        &&all([points.replay_period_difference]<=settings.replay_period_tolerance);
    distinct=true;synchronous=true;
    for k=1:numel(points)
        trace=points(k).trajectory_distinction;classification=points(k).classification;
        distinct=distinct&&trace.maximum_departure_from_vertical_parent>settings.trajectory_distinction_tolerance ...
            &&abs(trace.drift)>settings.trajectory_distinction_tolerance;
        synchronous=synchronous&&trace.synchronized_contact_history ...
            &&trace.paired_leg_motion_error<=settings.synchronization_tolerance ...
            &&trace.one_td_and_lo_per_leg&&classification.flight_count==1 ...
            &&strcmp(classification.primitive.status,'primitive_within_checked_bound') ...
            &&classification.primitive.cover_count==1 ...
            &&trace.minimum_guard_transversality>1e-7&&trace.section_transversality>1e-8;
    end
    gates.distinct_full_trajectories=distinct;
    gates.synchronized_primitive_contact_cycles=synchronous;
    reflectionErrors=[];
    negative=points([points.signed_amplitude]<0);positive=points([points.signed_amplitude]>0);
    for k=1:numel(negative)
        partner=find(abs([positive.signed_amplitude]+negative(k).signed_amplitude)<1e-12,1);
        if isempty(partner),continue;end
        a=negative(k);b=positive(partner);
        reflectionErrors(end+1)=max([norm(a.reduced_coordinates+b.reduced_coordinates,inf), ...
            abs(a.energy-b.energy),abs(a.period-b.period),abs(a.mean_speed+b.mean_speed)]); %#ok<AGROW>
    end
    if ~isempty(reflectionErrors)
        evidence.signed_reflection_maximum_error=max(reflectionErrors);
        gates.signed_reflection_agreement=connection.reflection_symmetry_at_parameters ...
            &&numel(reflectionErrors)>=settings.minimum_signed_amplitudes ...
            &&all(reflectionErrors<=settings.signed_reflection_tolerance);
    end
    evidence.signed_sequences=sequences;
    evidence=finish(evidence,gates);
end
function evidence=finish(evidence,gates)
    evidence.gates=gates;names=fieldnames(gates);passed=struct2cell(gates);
    evidence.failed_gates=names(~cellfun(@(value)logical(value),passed));
    if isempty(evidence.failed_gates)
        evidence.status='numerically_supported_restricted_attachment';
    end
end
