function registration=RegisterPIPAttachmentAccuracyRepair_v3(sourceTaskId,outputDirectory)
%REGISTERPIPATTACHMENTACCURACYREPAIR_V3 Freeze a copy, never the original phase.
% Registration reads saved accepted records; it performs no return-map calls.
    v3=V3Root_v3(mfilename('fullpath'));
    assert(any(strcmp(sourceTaskId,{'PIP_candidate_1','PIP_PK_low_energy_neighborhood'})));
    if nargin<2,outputDirectory=fullfile(v3,'Research_v3/next_round/solver/attachment_accuracy_repair',sourceTaskId);end
    outputDirectory=V3OutputPath_v3(outputDirectory);if ~isfolder(V3Path_v3(outputDirectory)),mkdir(V3Path_v3(outputDirectory));end
    assert(~isfile(V3Path_v3(fullfile(outputDirectory,'input_snapshot.mat')))&&~isfile(V3Path_v3(fullfile(outputDirectory,'registration.json'))), ...
        'RegisterPIPAttachmentAccuracyRepair_v3:Frozen','Preserve an existing registration; use a new explicit output directory.');
    gatePath='Research_v3/next_round/solver/solver_validation_summary.json';gate=jsondecode(fileread(V3Path_v3(fullfile(v3,gatePath))));
    assert(gate.all_required_gates_passed&&numel(gate.cases)>=7&&all([gate.cases.passed]));
    checkHashes(gate.source_hashes);
    modelPath='Research_v3/next_round/opposed_spread_period_two_registration.json';
    model=jsondecode(fileread(V3Path_v3(fullfile(v3,modelPath))));checkHashes(model.engine_hashes);
    sourceFolder=fullfile(v3,'Research_v3/next_round/tasks/full',sourceTaskId);
    sourcePhase=fullfile(sourceFolder,'phase_checkpoint.mat');loaded=load(V3Path_v3(sourcePhase),'record');originalRecord=loaded.record;
    assert(numel(originalRecord.amplitudes)==10&&all([originalRecord.amplitudes.accepted]));
    index=find(abs([originalRecord.amplitudes.signed_amplitude]-.0003)<1e-12);
    assert(isscalar(index));originalEntry=originalRecord.amplitudes(index);
    targetFile=fullfile(sourceFolder,originalEntry.artifact);saved=load(V3Path_v3(targetFile),'correction','seed','orbit');
    originalReport=saved.correction;originalOrbit=saved.orbit;originalSeed=saved.seed;
    assert(originalReport.accepted&&originalReport.solver.acceptedNewtonIterations==0 ...
        &&originalReport.initial_scaled_norm<=1e-10&&originalReport.initial_scaled_norm>1e-12);
    seed=originalReport.seed;seed.state=originalReport.final_candidate;coordinates=originalReport.final_coordinates(:);
    initialJ=originalReport.solver.finalJacobian;matrixSource=originalEntry.artifact;
    if isempty(initialJ),initialJ=originalReport.options.SolverOptions.InitialJacobian;matrixSource='original supplied warm matrix';end
    if isempty(initialJ)||~isequal(size(initialJ),[5,5])||any(~isfinite(initialJ(:))),initialJ=[];end
    assert(numel(coordinates)==5&&all(isfinite(coordinates))&&numel(seed.parameter)==10 ...
        &&isequal(seed.parameter(:),originalRecord.physical_parameter(:)) ...
        &&isequal(originalReport.active_coordinate_indices(:),[2;3;7;8]) ...
        &&~any(seed.mode)&&seed.occurrence==1&&isempty(originalReport.options.Residual));
    inputFile=fullfile(outputDirectory,'input_snapshot.mat');
    RoundSave_v3(inputFile,struct('originalRecord',originalRecord,'originalEntry',originalEntry, ...
        'originalReport',originalReport,'originalOrbit',originalOrbit,'originalSeed',originalSeed, ...
        'seed',seed,'coordinates',coordinates,'initialJ',initialJ));
    inputs=struct('path',{},'sha256',{});
    for k=1:10
        path=fullfile('Research_v3/next_round/tasks/full',sourceTaskId,originalRecord.amplitudes(k).artifact);
        inputs(k)=struct('path',path,'sha256',RoundSHA256_v3(fullfile(v3,path)));
    end
    paths={'Research_v3/Drivers_v3/RunPIPAttachmentAccuracyRepair_v3.m', ...
        'Research_v3/Drivers_v3/RegisterPIPAttachmentAccuracyRepair_v3.m', ...
        'Research_v3/Drivers_v3/PronkAttachmentEvidence_v3.m','Research_v3/Drivers_v3/PronkTrajectoryEvidence_v3.m', ...
        'Numerics_v3/HybridFiniteDifferenceJacobian_v3.m','Orbit_v3/ConstrainedEnergyResidual_v3.m'};
    hashes=struct('path',{},'sha256',{});
    for k=1:numel(paths)
        hashes(k)=struct('path',paths{k},'sha256',RoundSHA256_v3(fullfile(v3,paths{k})));
    end
    registrationFile=fullfile(outputDirectory,'registration.json');
    candidate=struct('id',[sourceTaskId,'_attachment_accuracy_repair_plus_0.0003'], ...
        'source_task_id',sourceTaskId,'method','signed-daughter-attachment-accuracy-repair', ...
        'method_registration',relative(registrationFile),'input_snapshot',relative(inputFile), ...
        'snapshot_sha256',RoundSHA256_v3(inputFile),'signed_amplitude',.0003);
    registration=struct('schema_version','prospective-PIP-attachment-accuracy-repair-v3-1', ...
        'registered_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version, ...
        'candidate',candidate,'original_phase',relative(sourcePhase),'original_phase_sha256',RoundSHA256_v3(sourcePhase), ...
        'original_records',inputs,'source_hashes',hashes,'canonical_source_hashes',gate.source_hashes, ...
        'canonical_gate',gatePath,'canonical_gate_sha256',RoundSHA256_v3(fullfile(v3,gatePath)), ...
        'physical_model_hashes',model.engine_hashes,'target_index',index,'target_amplitude',.0003, ...
        'initial_residual',originalReport.initial_scaled_norm,'old_shortcut_residual_tolerance',1e-10, ...
        'root_residual_acceptance_tolerance',1e-12,'root_function_tolerance',1e-13, ...
        'initial_J_available',~isempty(initialJ),'initial_J_source',matrixSource, ...
        'coordinate_indices',[2;3;7;8],'constraint',originalReport.options.Constraint, ...
        'energy_free_internal_coordinate',true,'fixed_physical_parameters',seed.parameter(:), ...
        'maximum_correction_wall_seconds',240,'full_acceptance',originalReport.acceptance, ...
        'diagnosis','The initial periodicity shortcut at1e-10 admits nearcritical energy error that fails separate attachment accuracy gates. Setting only FunctionTolerance does not bypass this shortcut.', ...
        'revision_scope','Tighter numerical root accuracy for the single +.0003 daughter; frozen amplitude, free internal E, original simulator/FD and unchanged physical full-state/energy/stance/primitive acceptance.', ...
        'record_policy','Replace +.0003 only in a saved copy; original10 records, phase, counters and previous attachment remain unchanged.', ...
        'return_map_evaluations',0,'correction_executed',false,'active_campaign_modified',false);
    RoundSave_v3(fullfile(outputDirectory,'registration.mat'),struct('registration',registration));
    RoundJSON_v3(registrationFile,registration);
    function checkHashes(items)
        for j=1:numel(items)
            assert(V3HashMatches_v3(items(j).sha256, fullfile(v3,items(j).path)), ...
                'RegisterPIPAttachmentAccuracyRepair_v3:SourceEpoch','Source changed: %s.',items(j).path);
        end
    end
    function path=relative(file),path=strrep(file,[v3,filesep],'');end
end
