function registration=RegisterOpposedSpreadCampaign_v3()
%REGISTEROPPOSEDSPREADCAMPAIGN_V3 Freeze two signed n0 tasks before shooting.
% This performs only source/hash checks and registration, never simulation.
    v3=V3Root_v3(mfilename('fullpath'));
    folder=fullfile(v3,'Research_v3/next_round');file=fullfile(folder,'opposed_spread_campaign_registration.json');
    if isfile(V3Path_v3(file)),registration=jsondecode(fileread(V3Path_v3(file)));return;end
    source=jsondecode(fileread(V3Path_v3(fullfile(folder,'opposed_spread_period_two_registration.json'))));
    proof=jsondecode(fileread(V3Path_v3(fullfile(folder,'theory/opposed_spread_period_two_audit.json'))));
    assert(proof.passed&&proof.completed,'A completed opposed-spread physical audit is required.');
    for k=1:numel(source.engine_hashes)
        item=source.engine_hashes(k);
        assert(V3HashMatches_v3(item.sha256, fullfile(v3,item.path)), ...
            'The physical model changed since the exact predictor audit: %s.',item.path);
    end
    records=struct('id',{},'candidate_artifact',{},'candidate_variable',{},'candidate_sha256',{}, ...
        'resonance_index',{},'touchdown_angle',{},'energy',{});
    for k=1:numel(source.candidates)
        item=source.candidates(k);if item.resonance_index~=0,continue;end
        assert(V3HashMatches_v3(item.sha256, fullfile(v3,item.artifact)),'A frozen predictor changed.');
        records(end+1)=struct('id',[item.id,'_campaign'],'candidate_artifact',item.artifact, ...
            'candidate_variable',item.variable,'candidate_sha256',item.sha256, ...
            'resonance_index',item.resonance_index,'touchdown_angle',item.touchdown_angle,'energy',item.energy); %#ok<AGROW>
    end
    assert(numel(records)==2&&all(sign([records.touchdown_angle])==[-1,1]),'Expected two signed n0 representatives.');
    paths={'Orbit_v3/OpposedSpreadFamilyResidual_v3.m','Numerics_v3/PeriodicSolutionSolver_v3.m', ...
        'Numerics_v3/RootSolver_v3.m','Numerics_v3/HybridFiniteDifferenceJacobian_v3.m', ...
        'Research_v3/Drivers_v3/RunOpposedSpreadPeriodTwo_v3.m'};
    hashes=struct('path',{},'sha256',{});
    for k=1:numel(paths),hashes(k)=struct('path',paths{k},'sha256',RoundSHA256_v3(fullfile(v3,paths{k})));end
    replay=source.settings;replay.RelTol=replay.RelTol/10;replay.AbsTol=replay.AbsTol/10;
    replay.MaxStep=replay.MaxStep/2;replay.EventValueTolerance=replay.EventValueTolerance/10;
    replay.EventTimeTolerance=replay.EventTimeTolerance/10;
    replay.SimultaneousTimeTolerance=replay.SimultaneousTimeTolerance/10;
    registration=struct('schema_version','prospective-opposed-spread-campaign-v3-1', ...
        'registered_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version, ...
        'method','exact-opposed-spread-twisted-restriction', ...
        'source_registration','Research_v3/next_round/opposed_spread_period_two_registration.json', ...
        'proof_audit','Research_v3/next_round/theory/opposed_spread_period_two_audit.json', ...
        'proof_document',source.proof_document,'source_hashes',hashes,'physical_engine_hashes',source.engine_hashes, ...
        'integration',source.settings,'replay_integration',replay, ...
        'meaningful_orthogonal_perturbation',1e-4,'minimum_initial_correction_residual',1e-6, ...
        'fd_relative_candidate_steps',[3e-5,1e-5],'fd_maximum_relative_error',.01, ...
        'fd_use_richardson',false,'samples_per_checkpoint',3, ...
        'initial_signed_angle_step',2.5e-4,'accepted_step_growth',1.5,'maximum_signed_angle_step',1e-3, ...
        'minimum_absolute_angle',1e-5,'maximum_absolute_angle',.009, ...
        'directions',[-1,1],'candidates',records, ...
        'branch_method','Prospectively frozen signed-amplitude constraints; formula-assisted predictors, actual BL1 twisted corrector and independent full BL2 replay in both amplitude directions.', ...
        'derivative_scope','Strict three-dimensional BL1 twisted derivative, not the measured-sector BL2 event-order chart.', ...
        'point_caps_are_endpoints',false,'generic_fullspace_continuation',false, ...
        'target_gait_claimed',false,'ancestry_claimed',false,'unrestricted_C2_claimed',false, ...
        'acceptance_tolerances_changed',false,'true_total_campaign_wall_seconds_changed',false);
    RoundSave_v3(fullfile(folder,'opposed_spread_campaign_registration.mat'),struct('registration',registration));
    RoundJSON_v3(file,registration);
end
