function cfg=RoundAdditionalCandidates_v3(cfg)
%ROUNDADDITIONALCANDIDATES_V3 Prospective, separate source-informed hypothesis.
    v3=V3Root_v3(mfilename('fullpath'));folder=fullfile(v3,'Research_v3','next_round');
    file=fullfile(folder,'additional_pip_candidate_registration.json');
    if ~isfile(V3Path_v3(file))
        candidate=struct('id','PIP_PK_low_energy_neighborhood','status','pending_next_round_candidate', ...
            'origin','historical imported-PK energy/mean-speed turning neighborhood', ...
            'energy_bracket',[1.105,1.13],'restriction','synchronized fixed-energy pronk; full-space claim excluded', ...
            'hypothesis','Test ordinary-PIP spectral/attachment evidence near the imported-PK low-energy turn; no attachment assumed.', ...
            'source_evidence','Research_v3/runs/full/family_-1.mat and family_+1.mat', ...
            'source_turning_energy_approximate',1.1171142328,'domain_changed',false, ...
            'registration_utc',char(datetime('now','TimeZone','UTC')));
        registration=struct('schema_version','prospective-additional-PIP-candidate-v3-1', ...
            'registered_utc',candidate.registration_utc,'historical_queue_preserved',true, ...
            'domain_changed',false,'candidates',candidate);
        RoundJSON_v3(file,registration);
    else,registration=jsondecode(fileread(V3Path_v3(file)));end
    cfg.additional_pip_candidates=registration.candidates;
    cfg.additional_pip_candidate_registration='Research_v3/next_round/additional_pip_candidate_registration.json';
end
