function report=GenerateOpposedSpreadFigures_v3()
%GENERATEOPPOSEDSPREADFIGURES_V3 Scientific plotting of saved physical data.
% No numerical flow, guard, reset, return or solver evaluation is performed.
    here=fileparts(mfilename('fullpath'));theory=fileparts(here);
    v3=fileparts(fileparts(fileparts(theory)));
    for folder={'Schema_v3','Dynamics_v3','Simulation_v3','Orbit_v3','Numerics_v3','Research_v3/Drivers_v3'}
        V3LegacyAddPath_v3(fullfile(v3,folder{1}));
    end
    timer=tic;
    paths={'Research_v3/next_round/theory/opposed_spread_n0_positive_A1e-3_actual_trace.mat', ...
        'Research_v3/next_round/theory/opposed_spread_period_two_audit.mat', ...
        'Research_v3/next_round/theory/opposed_spread_phase_equivalence.mat'};
    manifest=struct('path',{},'sha256',{});
    for k=1:numel(paths),manifest(k)=struct('path',paths{k},'sha256',RoundSHA256_v3(fullfile(v3,paths{k})));end
    source=load(V3Path_v3(fullfile(v3,paths{1})),'predictor','single','double','info1','info2','item');
    loaded=load(V3Path_v3(fullfile(v3,paths{2})),'audit');physicalAudit=loaded.audit;assert(physicalAudit.passed);
    loaded=load(V3Path_v3(fullfile(v3,paths{3})),'audit');phaseAudit=loaded.audit;assert(phaseAudit.passed);
    data=HybridCycleData_v3.unpack(source.info2.trajectory);
    history=data.history;tdIds=data.schema.Event.IDs(data.schema.Event.IsTouchdown);
    tdMask=ismember([history.guard_id],tdIds);
    touchdown=localClusters([history(tdMask).time]);liftoff=localClusters([history(~tdMask).time]);
    period=source.info2.period;halfTime=source.info1.period;
    assert(numel(touchdown)==2&&numel(liftoff)==2&&numel(history)==16);
    packet=struct('schema_version','opposed-spread-scientific-figure-data-v3-1', ...
        'created_utc',char(datetime('now','TimeZone','UTC')),'source_manifest',manifest, ...
        'time',data.time,'body_height',data.state(:,3),'body_vertical_velocity',data.state(:,4), ...
        'leg_angles',data.state(:,[7,9,11,13]),'leg_rates',data.state(:,[8,10,12,14]), ...
        'mode',data.mode,'leg_order',{{'BL','BR','FL','FR'}}, ...
        'actual_event_ids',[history.guard_id],'actual_event_times',[history.time], ...
        'touchdown_cohort_times',touchdown,'liftoff_cohort_times',liftoff, ...
        'actual_BL1_phaseflip_time',halfTime,'actual_full_BL2_period',period, ...
        'marked_apex_angles',1e3*[source.predictor.state(7),source.single(7),source.double(7)], ...
        'marked_apex_rates',1e3*[source.predictor.state(8),source.single(8),source.double(8)], ...
        'phase_times',[0,halfTime,period],'phase_labels',{{'x(+A)','x(-A)','x(+A)'}}, ...
        'actual_gait_label',source.item.actual_gait_label,'actual_gait_status',source.item.actual_gait_status, ...
        'actual_flight_count',source.item.actual_flight_count,'physical_cases',physicalAudit.predictor_cases, ...
        'phase_equivalence',phaseAudit,'new_simulations',0,'new_map_evaluations',0, ...
        'interval_orbit_error_bounds_supplied',false);
    amplitude=linspace(-.00999,.00999,801).';
    packet.exact_TD_angle_grid=amplitude;
    packet.exact_energy_shift=-2*sin(amplitude/2).^2; % cos(A)-1 without cancellation.
    packet.proved_local_interval='0<|A|<0.01 rad; A=0 is the vertical PIP limit';
    fig=figure('Visible','off','Color','white','Position',[100,100,1440,1080]);
    cleaner=onCleanup(@()close(fig)); %#ok<NASGU>
    layout=tiledlayout(fig,3,2,'TileSpacing','compact','Padding','compact');
    title(layout,{'n0 opposed spread: one primitive two-return cycle', ...
        'Saved physical traces; opposite signs are apex phases of the same labeled orbit'}, ...
        'FontName','Arial','FontSize',17,'FontWeight','bold','Interpreter','none','Color',[.12,.15,.20]);
    blue=[.10,.31,.66];red=[.72,.18,.19];orange=[.86,.42,.05];teal=[.02,.48,.40];purple=[.46,.24,.62];
    axHeight=nexttile(layout,1);plot(axHeight,data.time,packet.body_height,'Color',[.12,.15,.20],'LineWidth',1.7);
    ylabel(axHeight,'Body height y');title(axHeight,'A. Actual body height','FontWeight','bold');
    axAngle=nexttile(layout,2);
    plot(axAngle,data.time,1e3*packet.leg_angles(:,1),'Color',blue,'LineWidth',1.5,'DisplayName','BL / FL');hold(axAngle,'on');
    plot(axAngle,data.time,1e3*packet.leg_angles(:,2),'Color',red,'LineWidth',1.5,'DisplayName','BR / FR');
    plot(axAngle,packet.phase_times,packet.marked_apex_angles,'ko','MarkerFaceColor','white','MarkerSize',6,'HandleVisibility','off');
    ylabel(axAngle,'Leg angle (mrad)');title(axAngle,'B. Opposed leg angles','FontWeight','bold');
    legend(axAngle,'Location','southoutside','Orientation','horizontal','Box','off','FontSize',11,'TextColor',[.12,.15,.20]);
    axVelocity=nexttile(layout,3);plot(axVelocity,data.time,packet.body_vertical_velocity,'Color',[.12,.15,.20],'LineWidth',1.7);
    ylabel(axVelocity,'Vertical velocity dy');title(axVelocity,'C. Actual vertical velocity','FontWeight','bold');
    axRate=nexttile(layout,4);
    plot(axRate,data.time,1e3*packet.leg_rates(:,1),'Color',blue,'LineWidth',1.5);hold(axRate,'on');
    plot(axRate,data.time,1e3*packet.leg_rates(:,2),'Color',red,'LineWidth',1.5);
    plot(axRate,packet.phase_times,packet.marked_apex_rates,'ko','MarkerFaceColor','white','MarkerSize',6);
    ylabel(axRate,'Leg rate (mrad / unit time)');title(axRate,'D. Actual rate resets and phase flip','FontWeight','bold');
    for ax=[axHeight,axAngle,axVelocity,axRate]
        localAxes(ax);xlim(ax,[0,period]);xticks(ax,linspace(0,period,5));xtickformat(ax,'%.3f');
        xlabel(ax,'Time (nondimensional)');
        for time=touchdown,xline(ax,time,'-','Color',orange,'LineWidth',1,'HandleVisibility','off');end
        for time=liftoff,xline(ax,time,'--','Color',teal,'LineWidth',1,'HandleVisibility','off');end
        xline(ax,halfTime,'-.','Color',purple,'LineWidth',1.4,'HandleVisibility','off');
    end
    xline(axHeight,halfTime,'-.','BL1: x(+A) to x(-A)','Color',purple, ...
        'LineWidth',1.4,'FontSize',10,'LabelOrientation','horizontal','LabelVerticalAlignment','top');
    axEnergy=nexttile(layout,5);plot(axEnergy,1e3*amplitude,1e6*packet.exact_energy_shift,'k-','LineWidth',1.7, ...
        'DisplayName','Exact cos(A)-1');hold(axEnergy,'on');
    n0=physicalAudit.predictor_cases([physicalAudit.predictor_cases.n]==0);
    n1=physicalAudit.predictor_cases([physicalAudit.predictor_cases.n]==1);
    parent0=1+pi^2/160;parent1=1+9*pi^2/160;
    plot(axEnergy,1e3*[n0.touchdown_angle],1e6*([n0.energy]-parent0),'o', ...
        'Color',blue,'MarkerFaceColor',blue,'MarkerSize',7,'DisplayName','n0 saved predictors (+/-A)');
    plot(axEnergy,1e3*[n1.touchdown_angle],1e6*([n1.energy]-parent1),'x', ...
        'Color',purple,'MarkerSize',11,'LineWidth',1.5,'DisplayName','n1 saved predictors (+/-A)');
    plot(axEnergy,0,0,'ko','MarkerFaceColor','white','MarkerSize',5,'HandleVisibility','off');
    localAxes(axEnergy);xlim(axEnergy,[-10,10]);ylim(axEnergy,[-51,2]);
    xlabel(axEnergy,'Signed TD angle A (mrad)');ylabel(axEnergy,'(E(A)-E_n) x 10^6');
    title(axEnergy,'E. Exact restricted energy curve: 0 < |A| < 10 mrad','FontWeight','bold');
    legend(axEnergy,'Location','south','Box','off','FontSize',10,'TextColor',[.12,.15,.20]);
    axEvidence=nexttile(layout,6);axis(axEvidence,'off');
    text(axEvidence,0,1,{'F. Interpretation and executed closure evidence', ...
        '',sprintf('n0, +/-0.001 rad: BL2 closure %.2e',max([n0.BL2_full_closure])), ...
        sprintf('n1, +/-0.001 rad: BL2 closure %.2e',max([n1.BL2_full_closure])), ...
        'Four signed records = two sampled cycles modulo phase.', ...
        'At fixed n: BL1 takes x(+A) to x(-A), then back.', ...
        'The leg labels are unchanged; the full period remains BL2.', ...
        sprintf('n0 period %.6f; zero drift; 16 actual contacts.',period), ...
        'Two positive-duration flights on the time circle.', ...
        'Actual gait: unclassified / ambiguous.', ...
        'Contacts synchronize; left/right leg motions differ.', ...
        'No automatic B2, F2 or G2 assignment.', ...
        'Orange solid: TD; teal dashed: LO (four-leg cohorts).', ...
        'Purple dash-dot: actual BL1 marked apex / phase flip.', ...
        'Saved-trace postprocessing only; no new simulations.'}, ...
        'Units','normalized','FontName','Arial','FontSize',11.5,'Interpreter','none', ...
        'VerticalAlignment','top','Color',[.14,.16,.20]);
    png=fullfile(here,'opposed_spread_n0_physical_and_energy.png');
    native=fullfile(here,'opposed_spread_n0_physical_and_energy.fig');
    exportgraphics(V3Path_v3(fig),png,'Resolution',160,'BackgroundColor','white');savefig(V3Path_v3(fig),native);
    unchanged=true;
    for k=1:numel(manifest),unchanged=unchanged&&V3HashMatches_v3(manifest(k).sha256, fullfile(v3,manifest(k).path));end
    assert(unchanged,'A source evidence file changed during postprocessing.');
    packet.postprocessing_elapsed_seconds=toc(timer);
    save(V3Path_v3(fullfile(here,'opposed_spread_n0_figure_data.mat')),'packet','-v7');
    report=struct('schema_version','opposed-spread-scientific-figure-export-v3-1', ...
        'created_utc',packet.created_utc,'matlab_version',version,'source_manifest',manifest, ...
        'source_hashes_unchanged',unchanged,'new_simulations',0,'new_map_evaluations',0, ...
        'postprocessing_elapsed_seconds',packet.postprocessing_elapsed_seconds, ...
        'helper_path',strrep([mfilename('fullpath'),'.m'],[v3,filesep],''), ...
        'helper_sha256',RoundSHA256_v3([mfilename('fullpath'),'.m']), ...
        'PNG_artifact',strrep(png,[v3,filesep],''),'PNG_sha256',RoundSHA256_v3(png), ...
        'FIG_artifact',strrep(native,[v3,filesep],''),'FIG_sha256',RoundSHA256_v3(native), ...
        'MAT_artifact','Research_v3/next_round/theory/opposed_spread_figures/opposed_spread_n0_figure_data.mat', ...
        'interpretation','Four signed n0/n1 records are two sampled cycles modulo phase; actual gait remains unclassified/ambiguous. No new closure, rigorous error bound or target-family connection is established.');
    RoundJSON_v3(fullfile(here,'figure_export_manifest.json'),report);
    fprintf('Exported opposed-spread PNG/FIG/MAT in %.2fs; unchanged source hashes, no simulations.\n',report.postprocessing_elapsed_seconds);
end
function values=localClusters(values)
    values=sort(values(:).');output=[];
    while ~isempty(values)
        selected=abs(values-values(1))<1e-9;output(end+1)=mean(values(selected)); %#ok<AGROW>
        values=values(~selected);
    end
    values=output;
end
function localAxes(ax)
    set(ax,'Color','white','FontName','Arial','FontSize',11,'LineWidth',.8, ...
        'Box','off','XColor',[.12,.15,.20],'YColor',[.12,.15,.20], ...
        'GridColor',[.6,.6,.6],'GridAlpha',.12,'MinorGridAlpha',.06);
    ax.Title.Color=[.12,.15,.20];ax.XLabel.Color=[.12,.15,.20];ax.YLabel.Color=[.12,.15,.20];
    grid(ax,'on');
end
