classdef HybridSimulator_v3
    %HYBRIDSIMULATOR_V3 Event-driven simulator for general hybrid systems.
    %
    % [TRAJECTORY, RESULT] = SIMULATE(OBJ, SYSTEM, X0, Q0, P, TSPAN,
    % OPTIONS) repeatedly integrates SYSTEM.FLOW in the current mode,
    % locates the earliest active guard, delegates each simultaneous guard
    % batch to SYSTEM.RESOLVEEVENTBATCH, and restarts in the new mode.  The
    % model therefore owns whether a batch is ordered, commuting, or a
    % coupled atomic impact.

    properties (SetAccess = private)
        Options
    end

    methods
        function obj = HybridSimulator_v3(options)
            if nargin < 1
                options = struct();
            end
            obj.Options = HybridSimulator_v3.mergeOptions( ...
                HybridSimulator_v3.defaultOptions(), options);
        end

        function [trajectory, result] = simulate(obj, system, x0, q0, p, ...
                tspan, options)
            if nargin < 7 || isempty(options)
                options = struct();
            end
            simulationOptions = HybridSimulator_v3.mergeOptions( ...
                obj.Options, options);
            HybridSimulator_v3.validateSystem(system);
            validateattributes(tspan, {'numeric'}, ...
                {'vector', 'numel', 2, 'real', 'finite'});
            tspan = tspan(:).';
            if tspan(2) <= tspan(1)
                error('HybridSimulator_v3:InvalidTimeSpan', ...
                    'TSPAN must contain increasing start and final times.');
            end
            x0 = x0(:);
            if isempty(x0) || any(~isfinite(x0))
                error('HybridSimulator_v3:InvalidInitialState', ...
                    'X0 must be a nonempty finite state vector.');
            end

            detector = EventDetector_v3(simulationOptions);
            stopCondition = simulationOptions.StopCondition;
            odeOptions = simulationOptions.ODEOptions;

            currentTime = tspan(1);
            finalTime = tspan(2);
            currentState = x0;
            currentMode = q0;
            trajectory = Trajectory_v3(currentTime, currentState.', currentMode);
            [minimumAdmissibilityMargin, minimumPhysicalMargins] = ...
                HybridSimulator_v3.validateAcceptedState( ...
                    system, currentState, currentMode, p, ...
                    'accepted-state', struct('location', 'initial-state'));

            eventCount = 0;
            batchCount = 0;
            zeroAdvanceCount = 0;
            stopOccurred = false;
            stopRecord = struct();
            reason = "not_terminated";
            message = "";

            while currentTime < finalTime - ...
                    HybridSimulator_v3.timeTolerance(currentTime, ...
                        simulationOptions)
                [segment, event] = detector.integrate(system, currentState, ...
                    currentMode, p, [currentTime, finalTime], ...
                    stopCondition, odeOptions);
                [segmentMargin, segmentPhysicalMargins] = ...
                    HybridSimulator_v3.validateAcceptedSegment( ...
                        system, segment.state, currentMode, p);
                minimumAdmissibilityMargin = min( ...
                    minimumAdmissibilityMargin, segmentMargin);
                minimumPhysicalMargins = ...
                    HybridSimulator_v3.combinePhysicalMargins( ...
                        minimumPhysicalMargins, segmentPhysicalMargins);
                trajectory.appendSegment(segment.time, segment.state, currentMode);

                if ~event.occurred
                    currentTime = segment.time(end);
                    currentState = segment.state(end, :).';
                    reason = "final_time";
                    message = "The requested final time was reached.";
                    break;
                end

                batchCount = batchCount + 1;
                eventState = event.state(:);
                eventTime = event.time;
                advanceTolerance = HybridSimulator_v3.timeTolerance( ...
                    currentTime, simulationOptions);
                if eventTime <= currentTime + advanceTolerance
                    zeroAdvanceCount = zeroAdvanceCount + 1;
                else
                    zeroAdvanceCount = 0;
                end

                if batchCount > simulationOptions.MaxEventBatches
                    currentTime = eventTime;
                    currentState = eventState;
                    reason = "maximum_event_batches";
                    message = "Maximum number of hybrid event batches exceeded.";
                    break;
                end
                if zeroAdvanceCount > simulationOptions.MaxZeroTimeEvents
                    currentTime = eventTime;
                    currentState = eventState;
                    reason = "zeno_detected";
                    message = ["Too many consecutive events occurred without ", ...
                        "a resolved positive time advance."];
                    break;
                end

                currentTime = eventTime;
                currentState = eventState;

                stopFirst = event.stop_occurred && ...
                    ~simulationOptions.ProcessGuardsAtStop;
                if ~stopFirst
                    guardBatch = event.guard_batch;
                    if ~isempty(guardBatch)
                        stateBefore = currentState;
                        modeBefore = currentMode;
                        eventIds = HybridSimulator_v3.descriptorIds(guardBatch);
                        [stateAfter, modeAfter, batchInfo] = ...
                            system.resolveEventBatch(eventIds, currentTime, ...
                                stateBefore, modeBefore, p);
                        stateAfter = HybridSimulator_v3.validateBatchState( ...
                            stateAfter, stateBefore);
                        batchInfo = HybridSimulator_v3.completeBatchInfo( ...
                            batchInfo, eventIds, stateBefore, stateAfter, ...
                            modeBefore, modeAfter);
                        postResetContext = struct( ...
                            'event_ids', ...
                                HybridSimulator_v3.numericEventIds(eventIds), ...
                            'state_before', stateBefore, ...
                            'mode_before', modeBefore, ...
                            'batch_info', batchInfo);
                        [postResetMargin, postResetPhysicalMargins] = ...
                            HybridSimulator_v3.validateAcceptedState( ...
                                system, stateAfter, modeAfter, p, ...
                                'post-reset', postResetContext);
                        minimumAdmissibilityMargin = min( ...
                            minimumAdmissibilityMargin, postResetMargin);
                        minimumPhysicalMargins = ...
                            HybridSimulator_v3.combinePhysicalMargins( ...
                                minimumPhysicalMargins, ...
                                postResetPhysicalMargins);

                        batchRecord = HybridSimulator_v3.makeBatchRecord( ...
                            guardBatch, currentTime, stateBefore, stateAfter, ...
                            modeBefore, modeAfter, batchInfo);
                        physicalBatchIndex = ...
                            trajectory.recordEventBatch(batchRecord);
                        hasTrace = HybridSimulator_v3.hasBatchTrace( ...
                            batchInfo, numel(guardBatch));
                        for k = 1:numel(guardBatch)
                            descriptor = guardBatch(k);
                            if hasTrace
                                scalarStateBefore = ...
                                    batchInfo.event_states_before{k};
                                scalarStateAfter = ...
                                    batchInfo.event_states_after{k};
                                scalarModeBefore = ...
                                    batchInfo.event_modes_before{k};
                                scalarModeAfter = ...
                                    batchInfo.event_modes_after{k};
                            else
                                % Atomic coupled resets need not admit
                                % physically meaningful intermediate states.
                                scalarStateBefore = stateBefore;
                                scalarStateAfter = stateAfter;
                                scalarModeBefore = modeBefore;
                                scalarModeAfter = modeAfter;
                            end
                            eventMetadata = struct( ...
                                'event_batch_index', physicalBatchIndex, ...
                                'event_batch_size', numel(guardBatch), ...
                                'event_batch_position', k, ...
                                'event_batch_semantics', ...
                                    string(batchInfo.semantics), ...
                                'event_batch_atomic', ...
                                    logical(batchInfo.atomic));
                            entry = HybridSimulator_v3.makeEventEntry( ...
                                descriptor, currentTime, ...
                                scalarStateBefore, scalarStateAfter, ...
                                scalarModeBefore, scalarModeAfter, false, ...
                                eventMetadata);
                            trajectory.recordEvent(entry);
                            if hasTrace
                                trajectory.appendSample(currentTime, ...
                                    scalarStateAfter.', scalarModeAfter);
                            end
                        end
                        if ~hasTrace
                            trajectory.appendSample(currentTime, ...
                                stateAfter.', modeAfter);
                        end

                        currentState = stateAfter;
                        currentMode = modeAfter;
                        eventCount = eventCount + numel(guardBatch);
                        if eventCount >= simulationOptions.MaxEvents
                            reason = "maximum_events";
                            message = "Maximum number of hybrid events reached.";
                        end
                    end
                end
                if reason == "maximum_events"
                    break;
                end

                if event.stop_occurred
                    stopOccurred = true;
                    stopBatch = event.stop_batch;
                    if isempty(stopBatch)
                        stopBatch = HybridSimulator_v3.defaultStopDescriptor();
                    end
                    for k = 1:numel(stopBatch)
                        descriptor = stopBatch(k);
                        entry = HybridSimulator_v3.makeEventEntry( ...
                            descriptor, currentTime, currentState, currentState, ...
                            currentMode, currentMode, true);
                        if simulationOptions.RecordStopEvent
                            trajectory.recordEvent(entry);
                        end
                        if k == 1
                            stopRecord = entry;
                        end
                    end
                    reason = "stop_condition";
                    message = "The requested stopping condition was reached.";
                    break;
                end

                if isempty(event.guard_batch)
                    reason = "unresolved_event";
                    message = ["The ODE solver reported an event, but no active ", ...
                        "guard passed clustering checks."];
                    break;
                end
            end

            if reason == "not_terminated"
                if currentTime >= finalTime - ...
                        HybridSimulator_v3.timeTolerance(finalTime, ...
                            simulationOptions)
                    reason = "final_time";
                    message = "The requested final time was reached.";
                else
                    reason = "terminated";
                end
            end

            success = ismember(reason, ["final_time", "stop_condition"]);
            sectionReturnReport = struct();
            if reason == "stop_condition"
                [sectionMargin, sectionPhysicalMargins, ...
                        sectionReturnReport] = ...
                    HybridSimulator_v3.validateAcceptedState( ...
                        system, currentState, currentMode, p, ...
                        'section-return', ...
                        struct('stop_event', stopRecord));
                minimumAdmissibilityMargin = min( ...
                    minimumAdmissibilityMargin, sectionMargin);
                minimumPhysicalMargins = ...
                    HybridSimulator_v3.combinePhysicalMargins( ...
                        minimumPhysicalMargins, sectionPhysicalMargins);
            end
            terminationMetadata = struct( ...
                'success', success, ...
                'message', message, ...
                'stop_occurred', stopOccurred, ...
                'event_count', eventCount, ...
                'event_batch_count', batchCount, ...
                'zero_advance_count', zeroAdvanceCount, ...
                'admissible', true, ...
                'minimum_stance_admissibility_margin', ...
                    minimumAdmissibilityMargin, ...
                'minimum_physical_margins', minimumPhysicalMargins, ...
                'section_return_admissibility', sectionReturnReport);
            trajectory.setTermination(reason, currentTime, currentState, ...
                currentMode, terminationMetadata);
            trajectory.metadata.event_count = eventCount;
            trajectory.metadata.event_batch_count = batchCount;
            trajectory.metadata.physical_event_batch_count = ...
                numel(trajectory.event_batches);
            trajectory.metadata.admissible = true;
            trajectory.metadata.minimum_stance_admissibility_margin = ...
                minimumAdmissibilityMargin;
            trajectory.metadata.minimum_physical_margins = ...
                minimumPhysicalMargins;
            trajectory.metadata.section_return_admissibility = ...
                sectionReturnReport;

            result = struct( ...
                'success', success, ...
                'termination_reason', reason, ...
                'message', message, ...
                'stop_occurred', stopOccurred, ...
                'stop_event', stopRecord, ...
                'reached_final_time', reason == "final_time", ...
                'final_time', currentTime, ...
                'final_state', currentState, ...
                'final_mode', currentMode, ...
                'event_count', eventCount, ...
                'event_batch_count', batchCount, ...
                'physical_event_batch_count', ...
                    numel(trajectory.event_batches), ...
                'admissible', true, ...
                'minimum_stance_admissibility_margin', ...
                    minimumAdmissibilityMargin, ...
                'minimum_physical_margins', minimumPhysicalMargins, ...
                'section_return_admissibility', sectionReturnReport, ...
                'event_history', trajectory.event_history, ...
                'event_batches', trajectory.event_batches);
        end
    end

    methods (Static, Access = private)
        function options = defaultOptions()
            options = struct( ...
                'StopCondition', [], ...
                'ProcessGuardsAtStop', false, ...
                'RecordStopEvent', true, ...
                'MaxEvents', 1000, ...
                'MaxEventBatches', 1000, ...
                'MaxZeroTimeEvents', 32, ...
                'ODEOptions', odeset(), ...
                'ODESolver', @ode45, ...
                'RelTol', 1e-9, ...
                'AbsTol', 1e-11, ...
                'MaxStep', [], ...
                'EventValueTolerance', 1e-8, ...
                'EventTimeTolerance', 1e-10, ...
                'SimultaneousTimeTolerance', 1e-8, ...
                'DirectionalDerivativeTolerance', 1e-10, ...
                'DerivativeStep', 1e-7, ...
                'ArmingTolerance', 1e-9, ...
                'InteriorBias', 1e-9);
        end

        function output = mergeOptions(defaults, supplied)
            output = defaults;
            if isempty(supplied)
                return;
            end
            if ~isstruct(supplied) || ~isscalar(supplied)
                error('HybridSimulator_v3:InvalidOptions', ...
                    'OPTIONS must be a scalar structure.');
            end
            aliases = struct( ...
                'GuardTolerance', 'EventValueTolerance', ...
                'EventTolerance', 'EventValueTolerance', ...
                'SimultaneousTolerance', 'SimultaneousTimeTolerance');
            names = fieldnames(supplied);
            for k = 1:numel(names)
                name = names{k};
                target = name;
                if isfield(aliases, name)
                    target = aliases.(name);
                end
                % Unknown extension fields are intentionally preserved for
                % detector and stopping-condition collaborators.
                output.(target) = supplied.(name);
            end
            validateattributes(output.MaxEvents, {'numeric'}, ...
                {'scalar', 'integer', 'positive'});
            validateattributes(output.MaxEventBatches, {'numeric'}, ...
                {'scalar', 'integer', 'positive'});
            validateattributes(output.MaxZeroTimeEvents, {'numeric'}, ...
                {'scalar', 'integer', 'nonnegative'});
        end

        function validateSystem(system)
            required = {'flow', 'activeGuards', 'reset', 'transition', ...
                'resolveEventBatch'};
            for k = 1:numel(required)
                if ~ismethod(system, required{k})
                    error('HybridSimulator_v3:InvalidSystem', ...
                        'SYSTEM must implement the %s method.', required{k});
                end
            end
        end

        function [margin, physicalMargins] = validateAcceptedSegment( ...
                system, states, mode, p)
            margin = Inf;
            physicalMargins = HybridSimulator_v3.emptyPhysicalMargins();
            for sample = 1:size(states, 1)
                [sampleMargin, samplePhysicalMargins] = ...
                    HybridSimulator_v3.validateAcceptedState( ...
                        system, states(sample, :).', mode, p, ...
                        'accepted-state', ...
                        struct('sample_index', sample));
                margin = min(margin, sampleMargin);
                physicalMargins = ...
                    HybridSimulator_v3.combinePhysicalMargins( ...
                        physicalMargins, samplePhysicalMargins);
            end
        end

        function [margin, physicalMargins, diagnostics] = ...
                validateAcceptedState(system, state, mode, p, ...
                context, contextData)
            margin = Inf;
            physicalMargins = HybridSimulator_v3.emptyPhysicalMargins();
            diagnostics = struct();
            if ~ismethod(system, 'assertAdmissible')
                return
            end
            try
                diagnostics = system.assertAdmissible( ...
                    state, mode, p, context, contextData);
            catch exception
                if HybridSimulator_v3.tooManyInputs(exception)
                    diagnostics = system.assertAdmissible(state, mode, p);
                else
                    rethrow(exception)
                end
            end
            if isempty(diagnostics) || ~isstruct(diagnostics)
                return
            end
            if isfield(diagnostics, 'admissible') && ...
                    isscalar(diagnostics.admissible) && ...
                    ~logical(diagnostics.admissible)
                error('HybridSimulator_v3:InadmissibleState', ...
                    'The model rejected an accepted hybrid state.');
            end
            fields = {'minimum_stance_admissibility_margin', ...
                'stance_admissibility_margins', 'admissibility_margins'};
            for index = 1:numel(fields)
                if isfield(diagnostics, fields{index})
                    values = diagnostics.(fields{index});
                    values = values(isfinite(values));
                    if ~isempty(values)
                        margin = min(values(:));
                    end
                    break
                end
            end
            physicalMargins = ...
                HybridSimulator_v3.physicalMarginsFromReport(diagnostics);
            if isfield(diagnostics, 'minimum_physical_margin') && ...
                    isscalar(diagnostics.minimum_physical_margin)
                margin = min(margin, diagnostics.minimum_physical_margin);
            end
        end

        function margins = physicalMarginsFromReport(report)
            margins = HybridSimulator_v3.emptyPhysicalMargins();
            mapping = { ...
                'minimum_physical_margin', 'global'; ...
                'minimum_swing_foot_clearance', 'swing_foot_clearance'; ...
                'minimum_stance_compression', 'stance_compression'; ...
                'minimum_leg_length_margin', 'leg_length'; ...
                'minimum_hip_clearance', 'hip_clearance'; ...
                'torso_clearance', 'torso_clearance'; ...
                'minimum_complementarity_margin', 'complementarity_margin'};
            for index = 1:size(mapping, 1)
                source = mapping{index, 1};
                target = mapping{index, 2};
                if isfield(report, source) && ...
                        isscalar(report.(source))
                    margins.(target) = report.(source);
                end
            end
            if isfield(report, 'per_leg_minimum_physical_margin')
                margins.per_leg = ...
                    report.per_leg_minimum_physical_margin(:);
            end
            if isfield(report, 'active_tolerances')
                margins.active_tolerances = report.active_tolerances;
            end
        end

        function margins = emptyPhysicalMargins()
            margins = struct( ...
                'global', Inf, ...
                'swing_foot_clearance', Inf, ...
                'stance_compression', Inf, ...
                'leg_length', Inf, ...
                'hip_clearance', Inf, ...
                'torso_clearance', Inf, ...
                'complementarity_margin', Inf, ...
                'per_leg', [], ...
                'active_tolerances', struct());
        end

        function output = combinePhysicalMargins(left, right)
            if isempty(left)
                output = right;
                return
            end
            if isempty(right)
                output = left;
                return
            end
            output = left;
            scalarFields = {'global', 'swing_foot_clearance', ...
                'stance_compression', 'leg_length', 'hip_clearance', ...
                'torso_clearance', 'complementarity_margin'};
            for index = 1:numel(scalarFields)
                name = scalarFields{index};
                output.(name) = min(left.(name), right.(name));
            end
            if isempty(left.per_leg)
                output.per_leg = right.per_leg;
            elseif ~isempty(right.per_leg) && ...
                    numel(left.per_leg) == numel(right.per_leg)
                output.per_leg = min(left.per_leg, right.per_leg);
            end
            if isempty(fieldnames(output.active_tolerances)) && ...
                    ~isempty(fieldnames(right.active_tolerances))
                output.active_tolerances = right.active_tolerances;
            end
        end

        function ids = numericEventIds(eventIds)
            ids = [];
            if isnumeric(eventIds) || islogical(eventIds)
                ids = eventIds(:);
                return
            end
            if iscell(eventIds) && all(cellfun( ...
                    @(value) isnumeric(value) && isscalar(value), eventIds))
                ids = cell2mat(eventIds(:));
            end
        end

        function tf = tooManyInputs(exception)
            tf = any(strcmp(exception.identifier, { ...
                'MATLAB:TooManyInputs', 'MATLAB:maxrhs', ...
                'MATLAB:TooManyInputArguments'}));
        end

        function entry = makeEventEntry(descriptor, time, stateBefore, ...
                stateAfter, modeBefore, modeAfter, isStop, extraMetadata)
            if nargin < 8 || isempty(extraMetadata)
                extraMetadata = struct();
            end
            metadata = struct();
            if isfield(descriptor, 'metadata')
                metadata = descriptor.metadata;
            end
            metadata = HybridSimulator_v3.mergeMetadata( ...
                metadata, extraMetadata);
            guardName = string(descriptor.name);
            entry = struct( ...
                'index', 0, ...
                'type', guardName, ...
                'time', time, ...
                'guard_id', descriptor.id, ...
                'guard_name', guardName, ...
                'state_before', stateBefore, ...
                'state_after', stateAfter, ...
                'mode_before', modeBefore, ...
                'mode_after', modeAfter, ...
                'value', descriptor.value, ...
                'directional_derivative', ...
                    descriptor.directional_derivative, ...
                'priority', descriptor.priority, ...
                'is_stop', logical(isStop), ...
                'metadata', metadata);
        end

        function ids = descriptorIds(descriptors)
            ids = cell(numel(descriptors), 1);
            for index = 1:numel(descriptors)
                ids{index} = descriptors(index).id;
            end
        end

        function state = validateBatchState(state, stateBefore)
            state = state(:);
            if numel(state) ~= numel(stateBefore) || any(~isfinite(state))
                error('HybridSimulator_v3:InvalidReset', ...
                    ['SYSTEM.RESOLVEEVENTBATCH must return a finite state ', ...
                     'with unchanged dimension.']);
            end
        end

        function info = completeBatchInfo(info, eventIds, stateBefore, ...
                stateAfter, modeBefore, modeAfter)
            if ~isstruct(info) || ~isscalar(info)
                error('HybridSimulator_v3:InvalidBatchInfo', ...
                    'Batch resolution must return a scalar BATCHINFO structure.');
            end
            if ~isfield(info, 'semantics') ...
                    || strlength(string(info.semantics)) == 0
                error('HybridSimulator_v3:InvalidBatchInfo', ...
                    'BATCHINFO must identify its physical semantics.');
            end
            defaults = struct( ...
                'atomic', true, 'fallback', false, ...
                'event_ids', {eventIds}, ...
                'event_count', numel(eventIds), ...
                'state_before', stateBefore, 'state_after', stateAfter, ...
                'mode_before', modeBefore, 'mode_after', modeAfter, ...
                'commutativity_checked', false, ...
                'reset_order_commutes', NaN, ...
                'transition_order_commutes', NaN, ...
                'commutativity_error', NaN);
            fields = fieldnames(defaults);
            for index = 1:numel(fields)
                field = fields{index};
                if ~isfield(info, field)
                    info.(field) = defaults.(field);
                end
            end
            % These fields describe the simulator-observed batch and cannot
            % be overridden by stale model metadata.
            info.event_ids = eventIds;
            info.event_count = numel(eventIds);
            info.state_before = stateBefore;
            info.state_after = stateAfter;
            info.mode_before = modeBefore;
            info.mode_after = modeAfter;
            info.semantics = string(info.semantics);
            info.atomic = logical(info.atomic);
            info.fallback = logical(info.fallback);
        end

        function tf = hasBatchTrace(info, count)
            fields = {'event_states_before', 'event_states_after', ...
                'event_modes_before', 'event_modes_after'};
            tf = true;
            for index = 1:numel(fields)
                field = fields{index};
                tf = tf && isfield(info, field) ...
                    && iscell(info.(field)) ...
                    && numel(info.(field)) == count;
            end
        end

        function record = makeBatchRecord(descriptors, time, stateBefore, ...
                stateAfter, modeBefore, modeAfter, batchInfo)
            names = strings(numel(descriptors), 1);
            priorities = zeros(numel(descriptors), 1);
            for index = 1:numel(descriptors)
                names(index) = string(descriptors(index).name);
                priorities(index) = descriptors(index).priority;
            end
            record = struct( ...
                'index', 0, ...
                'time', time, ...
                'event_ids', {HybridSimulator_v3.descriptorIds(descriptors)}, ...
                'event_names', names, ...
                'priorities', priorities, ...
                'state_before', stateBefore, ...
                'state_after', stateAfter, ...
                'mode_before', modeBefore, ...
                'mode_after', modeAfter, ...
                'semantics', string(batchInfo.semantics), ...
                'batch_info', batchInfo);
        end

        function output = mergeMetadata(left, right)
            if ~isstruct(left) || ~isscalar(left)
                left = struct('descriptor_metadata', left);
            end
            output = left;
            names = fieldnames(right);
            for index = 1:numel(names)
                output.(names{index}) = right.(names{index});
            end
        end

        function descriptor = defaultStopDescriptor()
            descriptor = struct( ...
                'id', 1, 'name', "stop", 'value', 0, ...
                'direction', 0, 'isterminal', true, ...
                'priority', -Inf, 'enabled', true, 'kind', "stop", ...
                'leg_index', [], 'interior_sign', [], ...
                'directional_derivative', NaN, 'metadata', struct());
        end

        function tolerance = timeTolerance(time, options)
            tolerance = max(options.EventTimeTolerance, ...
                64 * eps(max(1, abs(time))));
        end
    end
end
