classdef QuadrupedSchema_v3
    %QUADRUPEDSCHEMA_V3 Canonical v3 quadruped state and parameter schema.
    %
    % This class is the sole source of coordinate, leg, mode, and contact-
    % event ordering for the v3 quadruped.  Production code should consume
    % these indices rather than reproduce numeric permutations locally.

    properties (SetAccess = private)
        SchemaVersion
        StateSchemaVersion
        ParameterSchemaVersion
        State
        Parameter
        Leg
        Event
        Root
    end

    properties (Dependent, SetAccess = private)
        StateNames
        ParameterNames
        LegNames
        EventNames
        StateDimension
        ParameterDimension
        TranslationIndex
        PhaseIndex
        DefaultUnknownIndices
        DefaultPeriodicIndices
        DefaultTangentIndices
    end

    methods
        function obj = QuadrupedSchema_v3()
            obj.SchemaVersion = 'quadruped-v3.1';
            obj.StateSchemaVersion = 'quadruped-state-v3.1';
            obj.ParameterSchemaVersion = 'quadruped-parameter-v3.1';

            stateNames = { ...
                'x', 'dx', 'y', 'dy', 'phi', 'dphi', ...
                'alphaBL', 'dalphaBL', 'alphaBR', 'dalphaBR', ...
                'alphaFL', 'dalphaFL', 'alphaFR', 'dalphaFR'};
            obj.State = struct( ...
                'x', 1, 'dx', 2, 'y', 3, 'dy', 4, ...
                'phi', 5, 'dphi', 6, ...
                'alphaBL', 7, 'dalphaBL', 8, ...
                'alphaBR', 9, 'dalphaBR', 10, ...
                'alphaFL', 11, 'dalphaFL', 12, ...
                'alphaFR', 13, 'dalphaFR', 14, ...
                'Names', {stateNames}, 'Dimension', 14);

            parameterNames = { ...
                'k_l_b', 'k_l_f', 'k_s_b', 'k_s_f', ...
                'l_l_b', 'l_l_f', 'rsla_b', 'rsla_f', ...
                'j_pitch', 'l_com'};
            obj.Parameter = struct( ...
                'k_l_b', 1, 'k_l_f', 2, ...
                'k_s_b', 3, 'k_s_f', 4, ...
                'l_l_b', 5, 'l_l_f', 6, ...
                'rsla_b', 7, 'rsla_f', 8, ...
                'j_pitch', 9, 'l_com', 10, ...
                'Names', {parameterNames}, 'Dimension', 10);

            legNames = {'BL', 'BR', 'FL', 'FR'};
            obj.Leg = struct( ...
                'Names', {legNames}, ...
                'Indices', 1:4, ...
                'AngleIndices', [7, 9, 11, 13], ...
                'RateIndices', [8, 10, 12, 14], ...
                'BackMask', logical([1, 1, 0, 0]), ...
                'FrontMask', logical([0, 0, 1, 1]), ...
                'Count', 4, ...
                'ModeOrder', {legNames});

            eventNames = { ...
                'BL_TD', 'BL_LO', 'BR_TD', 'BR_LO', ...
                'FL_TD', 'FL_LO', 'FR_TD', 'FR_LO'};
            obj.Event = struct( ...
                'Names', {eventNames}, ...
                'IDs', 1:8, ...
                'LegIndices', [1, 1, 2, 2, 3, 3, 4, 4], ...
                'IsTouchdown', logical([1, 0, 1, 0, 1, 0, 1, 0]), ...
                'Directions', [-1, 1, -1, 1, -1, 1, -1, 1], ...
                'Count', 8);

            obj.Root = struct( ...
                'TranslationIndex', 1, ...
                'PhaseIndex', 4, ...
                'UnknownIndices', 2:14, ...
                'PeriodicIndices', [2, 3, 5:14], ...
                'TangentIndices', [2, 3, 5:14]);
        end

        function names = get.StateNames(obj)
            names = obj.State.Names;
        end

        function names = get.ParameterNames(obj)
            names = obj.Parameter.Names;
        end

        function names = get.LegNames(obj)
            names = obj.Leg.Names;
        end

        function names = get.EventNames(obj)
            names = obj.Event.Names;
        end

        function value = get.StateDimension(obj)
            value = obj.State.Dimension;
        end

        function value = get.ParameterDimension(obj)
            value = obj.Parameter.Dimension;
        end

        function value = get.TranslationIndex(obj)
            value = obj.Root.TranslationIndex;
        end

        function value = get.PhaseIndex(obj)
            value = obj.Root.PhaseIndex;
        end

        function value = get.DefaultUnknownIndices(obj)
            value = obj.Root.UnknownIndices;
        end

        function value = get.DefaultPeriodicIndices(obj)
            value = obj.Root.PeriodicIndices;
        end

        function value = get.DefaultTangentIndices(obj)
            value = obj.Root.TangentIndices;
        end

        function x = validateState(obj, x)
            if ~(isnumeric(x) && isreal(x) && isvector(x) ...
                    && numel(x) == obj.State.Dimension ...
                    && all(isfinite(x(:))))
                error('QuadrupedSchema_v3:InvalidState', ...
                    'Quadruped state must be a finite real 14-vector.');
            end
            x = double(x(:));
        end

        function q = validateMode(obj, q)
            if ~(isnumeric(q) || islogical(q)) || ~isreal(q) ...
                    || numel(q) ~= obj.Leg.Count ...
                    || any(~isfinite(double(q(:)))) ...
                    || any((double(q(:)) ~= 0) & (double(q(:)) ~= 1))
                error('QuadrupedSchema_v3:InvalidMode', ...
                    'Quadruped mode must contain four binary entries [BL BR FL FR].');
            end
            q = logical(q(:));
        end

        function p = validateParameter(obj, p)
            if ~(isnumeric(p) && isreal(p) && isvector(p) ...
                    && numel(p) == obj.Parameter.Dimension)
                error('QuadrupedSchema_v3:InvalidParameter', ...
                    'Quadruped parameter must be a real 10-vector.');
            end
            p = double(p(:));
            index = obj.Parameter;
            finiteIndices = [index.k_l_b, index.k_l_f, ...
                index.k_s_b, index.k_s_f, index.l_l_b, index.l_l_f, ...
                index.rsla_b, index.rsla_f, index.l_com];
            if any(~isfinite(p(finiteIndices))) ...
                    || ~(isfinite(p(index.j_pitch)) ...
                        || isinf(p(index.j_pitch))) ...
                    || p(index.k_l_b) <= 0 || p(index.k_l_f) <= 0 ...
                    || p(index.k_s_b) < 0 || p(index.k_s_f) < 0 ...
                    || p(index.l_l_b) <= 0 || p(index.l_l_f) <= 0 ...
                    || p(index.j_pitch) <= 0 ...
                    || p(index.l_com) <= 0 || p(index.l_com) >= 1
                error('QuadrupedSchema_v3:InvalidParameter', ...
                    ['Parameters require k_l_b,k_l_f,l_l_b,l_l_f>0; ' ...
                    'k_s_b,k_s_f>=0; finite rsla_b,rsla_f; ' ...
                    'j_pitch>0 or Inf; and 0<l_com<1.']);
            end
        end

        function expanded = expandParameters(obj, p)
            %EXPANDPARAMETERS Expand back/front scalars in [BL BR FL FR].
            p = obj.validateParameter(p);
            index = obj.Parameter;
            lCom = p(index.l_com);
            expanded = struct( ...
                'k_l', [p(index.k_l_b); p(index.k_l_b); ...
                    p(index.k_l_f); p(index.k_l_f)], ...
                'k_s', [p(index.k_s_b); p(index.k_s_b); ...
                    p(index.k_s_f); p(index.k_s_f)], ...
                'l_0', [p(index.l_l_b); p(index.l_l_b); ...
                    p(index.l_l_f); p(index.l_l_f)], ...
                'rsla', [p(index.rsla_b); p(index.rsla_b); ...
                    p(index.rsla_f); p(index.rsla_f)], ...
                's', [-lCom; -lCom; 1 - lCom; 1 - lCom], ...
                'j_pitch', p(index.j_pitch), ...
                'l_com', lCom);
        end

        function index = parameterIndex(obj, name)
            if ~(ischar(name) || (isstring(name) && isscalar(name)))
                error('QuadrupedSchema_v3:InvalidParameterName', ...
                    'Parameter name must be a text scalar.');
            end
            index = find(strcmp(char(name), obj.Parameter.Names), 1);
            if isempty(index)
                error('QuadrupedSchema_v3:InvalidParameterName', ...
                    'Unknown v3 quadruped parameter "%s".', char(name));
            end
        end

        function id = eventId(obj, event)
            if ischar(event) || (isstring(event) && isscalar(event))
                id = find(strcmpi(char(event), obj.Event.Names), 1);
                if isempty(id)
                    error('QuadrupedSchema_v3:InvalidEvent', ...
                        'Unknown quadruped event name "%s".', char(event));
                end
                return;
            end
            if ~(isnumeric(event) && isreal(event) && isscalar(event) ...
                    && isfinite(event) && event == fix(event) ...
                    && event >= 1 && event <= obj.Event.Count)
                error('QuadrupedSchema_v3:InvalidEvent', ...
                    'Quadruped event ID must be an integer from 1 through 8.');
            end
            id = double(event);
        end

        function [legIndex, isTouchdown] = eventLegKind(obj, event)
            id = obj.eventId(event);
            legIndex = obj.Event.LegIndices(id);
            isTouchdown = obj.Event.IsTouchdown(id);
        end

        function catalog = eventCatalog(obj)
            catalog = repmat(struct( ...
                'id', 0, 'name', '', 'leg_index', 0, 'leg_name', '', ...
                'kind', '', 'direction', 0, 'priority', 0), ...
                obj.Event.Count, 1);
            for id = obj.Event.IDs
                legIndex = obj.Event.LegIndices(id);
                catalog(id).id = id;
                catalog(id).name = obj.Event.Names{id};
                catalog(id).leg_index = legIndex;
                catalog(id).leg_name = obj.Leg.Names{legIndex};
                if obj.Event.IsTouchdown(id)
                    catalog(id).kind = 'touchdown';
                else
                    catalog(id).kind = 'liftoff';
                end
                catalog(id).direction = obj.Event.Directions(id);
                catalog(id).priority = id;
            end
        end

        function metadata = metadata(obj)
            %METADATA Serializable schema metadata for branches and fixtures.
            metadata = struct( ...
                'state_names', {obj.State.Names}, ...
                'parameter_names', {obj.Parameter.Names}, ...
                'leg_order', {obj.Leg.Names}, ...
                'event_order', {obj.Event.Names}, ...
                'state_schema_version', obj.StateSchemaVersion, ...
                'parameter_schema_version', obj.ParameterSchemaVersion, ...
                'schema_version', obj.SchemaVersion);
        end
    end

    methods (Static)
        function obj = shared()
            %SHARED Return an immutable process-local schema instance.
            persistent cachedSchema
            if isempty(cachedSchema)
                cachedSchema = QuadrupedSchema_v3();
            end
            obj = cachedSchema;
        end
    end
end
