function [corrected, info] = ApplyFloquetBranchCorrector(context, callback)
%APPLYFLOQUETBRANCHCORRECTOR Invoke a generic or experiment-specific corrector.
%
% A custom CALLBACK has the uniform signature
%   [corrected,info] = callback(context)
% where context contains Record, Direction, X, E, Parameters, PredictorInfo,
% CorrectorOptions, Amplitude, and Sign. INFO must be a scalar struct with a
% scalar logical-like `accepted` field. Empty CALLBACK uses CorrectBranchSwitch.

    required = {'Record','Direction','X','E','Parameters', ...
        'PredictorInfo','CorrectorOptions','Amplitude','Sign'};
    if ~isstruct(context) || ~isscalar(context) || ...
            ~all(isfield(context, required))
        error('TemplateExperiment:CorrectorContext', ...
            'Corrector context is missing required fields.');
    end
    if isempty(callback)
        [corrected, info] = floquet.correctBranchSwitch( ...
            context.X, context.E, context.Parameters, ...
            context.PredictorInfo, context.CorrectorOptions);
    elseif isa(callback, 'function_handle')
        [corrected, info] = callback(context);
    else
        error('TemplateExperiment:InvalidCorrectorFunction', ...
            'BranchSwitch.CorrectorFunction must be empty or a function handle.');
    end
    corrected = corrected(:);
    if ~isnumeric(corrected) || ~isreal(corrected) || ...
            numel(corrected) ~= 22 || any(~isfinite(corrected)) || ...
            corrected(22) <= 0
        error('TemplateExperiment:CorrectorOutput', ...
            'Corrector callback must return a finite real 22-state solution.');
    end
    if ~isstruct(info) || ~isscalar(info) || ~isfield(info, 'accepted') || ...
            ~(isscalar(info.accepted) && (islogical(info.accepted) || ...
              (isnumeric(info.accepted) && isfinite(info.accepted) && ...
               any(info.accepted == [0 1]))))
        error('TemplateExperiment:CorrectorInfo', ...
            'Corrector callback info must contain scalar logical accepted.');
    end
    info.accepted = logical(info.accepted);
end
