function config = BuildFloquetWorkflowConfig(experimentRoot, floquetRoot)
%BUILDFLOQUETWORKFLOWCONFIG Build the canonical fail-closed config schema.
%
%   CONFIG = FLOQUET.WORKFLOW.INTERNAL.BUILDFLOQUETWORKFLOWCONFIG(ROOT,
%   FLOQUETROOT) owns the default five-stage workflow structure and every
%   derived artifact path. It deliberately does not select or fingerprint a
%   parent branch. Callers may set only their experiment identity, frozen
%   parent provenance, and explicitly justified numerical overrides.

    if nargin < 2
        floquetRoot = '';
    end
    experimentRoot = ScalarPath(experimentRoot, false, ...
        'FloquetWorkflow:ExperimentRoot');
    floquetRoot = ScalarPath(floquetRoot, true, ...
        'FloquetWorkflow:FloquetRoot');

    directories = WorkflowDirectories(experimentRoot);
    discoveryCheckpoint = fullfile(directories.Checkpoints, ...
        'floquet_scan_checkpoint.mat');
    continuationCheckpoint = fullfile(directories.Checkpoints, ...
        'daughter_continuation_checkpoint.mat');

    config = struct();
    config.SchemaVersion = 'floquet-workflow-config-v2';
    config.ArtifactLayoutVersion = 'numbered-artifacts-v1';
    config.ExperimentName = '';
    config.ExperimentRoot = experimentRoot;
    config.FloquetRoot = floquetRoot;
    config.OverwriteResults = false;
    config.ParentBranchFile = '';
    config.ExpectedParentSHA256 = '';

    config.AnalysisOptions = struct( ...
        'Verbose', true, ...
        'CheckpointFile', discoveryCheckpoint, ...
        'CheckpointEvery', 1, ...
        'ResumeFromCheckpoint', isfile(discoveryCheckpoint), ...
        'DeleteCheckpointOnSuccess', true);
    config.Discovery = struct('ExportOnly', false);

    config.Selection = struct('Confirmed', false, ...
        'CandidateIDs', {{}});
    config.Refinement = struct( ...
        'Options', struct(), ...
        'ConfigureGroup', [], ...
        'DxMonotonicityNeighborRadius', 1, ...
        'DxMonotonicityTolerance', []);
    config.BranchSwitch = struct( ...
        'Amplitudes', [5e-4 1e-3 2e-3], ...
        'Signs', [-1 1], ...
        'DirectionResolver', [], ...
        'CorrectorFunction', [], ...
        'PredictorOptions', struct(), ...
        'CorrectorOptions', struct());

    emptySelections = struct('RayID', {}, ...
        'SeedAttemptIndices', {}, 'SeedAmplitudes', {}, ...
        'SourceSeedSHA256', {});
    config.Continuation = struct( ...
        'Enabled', false, ...
        'Confirmed', false, ...
        'RaySelections', emptySelections, ...
        'Overwrite', false, ...
        'CheckpointFile', continuationCheckpoint, ...
        'ResumeFromCheckpoint', isfile(continuationCheckpoint), ...
        'DeleteCheckpointOnSuccess', true, ...
        'StoreResultsInInventory', false, ...
        'StatusFcn', [], ...
        'ControlFcn', [], ...
        'Options', struct());

    config.Validation = struct( ...
        'ReferenceDaughterBranchFiles', {{}}, ...
        'Function', []);
    config.Directories = directories;
    config.Files = WorkflowFiles(directories, continuationCheckpoint);
end

function directories = WorkflowDirectories(root)
    artifactRoot = fullfile(root, 'artifacts');
    directories = struct( ...
        'Artifacts', artifactRoot, ...
        'Discovery', fullfile(artifactRoot, '01_discovery'), ...
        'Refinement', fullfile(artifactRoot, '02_refinement'), ...
        'SeedSearch', fullfile(artifactRoot, '03_seed_search'), ...
        'DaughterBranches', fullfile(artifactRoot, ...
            '04_daughter_branches'), ...
        'Validation', fullfile(artifactRoot, '05_validation'), ...
        'Checkpoints', fullfile(root, 'checkpoints'), ...
        'Views', fullfile(root, 'views'), ...
        'Logs', fullfile(root, 'logs'));
end

function files = WorkflowFiles(directories, continuationCheckpoint)
    files = struct( ...
        'Discovery', fullfile(directories.Discovery, ...
            'floquet_analysis.mat'), ...
        'CandidateInventory', fullfile(directories.Discovery, ...
            'candidate_inventory.csv'), ...
        'RejectedPoints', fullfile(directories.Discovery, ...
            'rejected_points.csv'), ...
        'RejectedIntervals', fullfile(directories.Discovery, ...
            'rejected_intervals.csv'), ...
        'Refinement', fullfile(directories.Refinement, ...
            'refined_candidates.mat'), ...
        'RefinementSummary', fullfile(directories.Refinement, ...
            'refinement_summary.csv'), ...
        'Seeds', fullfile(directories.SeedSearch, ...
            'daughter_seed_search.mat'), ...
        'SeedAttempts', fullfile(directories.SeedSearch, ...
            'daughter_seed_attempts.csv'), ...
        'Daughters', fullfile(directories.DaughterBranches, ...
            'inventory.mat'), ...
        'DaughterInventory', fullfile(directories.DaughterBranches, ...
            'inventory.csv'), ...
        'DaughterDirectory', directories.DaughterBranches, ...
        'DaughterCheckpoint', continuationCheckpoint, ...
        'Validation', fullfile(directories.Validation, ...
            'validation_report.mat'), ...
        'ValidationSummary', fullfile(directories.Validation, ...
            'validation_summary.csv'));
end

function value = ScalarPath(value, allowEmpty, identifier)
    if ~((ischar(value) && (isrow(value) || isempty(value))) || ...
            (isstring(value) && isscalar(value)))
        error(identifier, 'Path must be scalar text.');
    end
    value = strtrim(char(string(value)));
    if ~allowEmpty && isempty(value)
        error(identifier, 'Experiment root cannot be empty.');
    end
end
