function audit=AuditPIPAttachmentStopping_v3(outputDirectory,sourceTaskId)
%AUDITPIPATTACHMENTSTOPPING_V3 Saved-record algebra only; no map evaluations.
    v3=V3Root_v3(mfilename('fullpath'));
    if nargin<1,outputDirectory=fullfile(v3,'Research_v3/next_round/solver/pip_attachment_stopping');end
    outputDirectory=V3OutputPath_v3(outputDirectory);if ~isfolder(V3Path_v3(outputDirectory)),mkdir(V3Path_v3(outputDirectory));end
    if nargin<2,sourceTaskId='PIP_candidate_1';end
    assert(any(strcmp(sourceTaskId,{'PIP_candidate_1','PIP_PK_low_energy_neighborhood'})));
    input=fullfile('Research_v3/next_round/tasks/full',sourceTaskId);
    path=fullfile(v3,input,'phase_checkpoint.json');record=jsondecode(fileread(V3Path_v3(path)));
    points=record.amplitudes;E0=record.critical_energy;energyError=record.attachment_evidence.energy_uncertainty_estimate;
    detail=struct([]);
    for k=1:numel(points)
        entry=points(k);file=fullfile(v3,input,entry.artifact);
        saved=load(V3Path_v3(file),'correction','seed','orbit');report=saved.correction;
        r=report.solver.residual(:);w=report.final_coordinates(:);J=report.solver.finalJacobian;
        role='saved final root linear model';
        if isempty(J)
            J=report.options.SolverOptions.InitialJacobian;role='unused supplied warm matrix from a different amplitude';
        end
        s=[];condition=NaN;step=NaN(size(w));linearResidual=NaN;
        if ~isempty(J)&&all(isfinite(J(:)))&&size(J,1)==numel(r)&&size(J,2)==numel(w)
            s=svd(J);condition=s(1)/s(end);step=-J\r;linearResidual=norm(J*step+r,inf);
        end
        physicalE=QuadrupedEnergy_v3.evaluate(report.final_candidate,report.seed.mode,report.seed.parameter);
        row=struct('signed_amplitude',entry.signed_amplitude,'artifact',entry.artifact, ...
            'artifact_sha256',RoundSHA256_v3(file),'accepted',report.accepted, ...
            'energy',entry.energy,'energy_shift',entry.energy-E0, ...
            'energy_coefficient', (entry.energy-E0)/entry.signed_amplitude^2, ...
            'energy_shift_resolved',abs(entry.energy-E0)>5*energyError, ...
            'initial_residual',report.initial_scaled_norm,'final_residual',report.final_scaled_norm, ...
            'physical_full_closure',report.full_closure,'constraint_error',report.constraint_residual, ...
            'accepted_Newton_steps',report.solver.acceptedNewtonIterations, ...
            'initial_J_used',member(report.solver.output,'initialJacobianUsed',NaN),'solver',member(report.solver,'solver','unknown'), ...
            'message',report.solver.message,'root_residual_vector',r,'coordinates',w, ...
            'internal_energy_consistency',abs(physicalE-w(end)), ...
            'Jacobian_role',role,'Jacobian_singular_values',s,'Jacobian_condition_estimate',condition, ...
            'linear_remaining_step_estimate',step,'linear_remaining_energy_estimate',step(end), ...
            'linear_solve_backward_residual',linearResidual, ...
            'core_objective_count',report.solver.mapEvaluationCount, ...
            'elapsed_seconds',report.elapsed_seconds);
        if isempty(detail),detail=row;else,detail(end+1)=row;end
    end
    pairs=struct([]);
    negative=find([points.signed_amplitude]<0);
    for pairIndex=1:numel(negative)
        k=negative(pairIndex);
        a=points(k);j=find(abs([points.signed_amplitude]+a.signed_amplitude)<1e-12,1);b=points(j);
        coordinateError=norm(a.reduced_coordinates+b.reduced_coordinates,inf);
        delta=[coordinateError,abs(a.energy-b.energy),abs(a.period-b.period),abs(a.mean_speed+b.mean_speed)];
        row=struct('absolute_amplitude',abs(a.signed_amplitude),'reduced_coordinate_error',delta(1), ...
            'energy_error',delta(2),'period_error',delta(3),'mean_speed_error',delta(4), ...
            'maximum_error',max(delta),'reflection_gate_passed',max(delta)<=record.settings.signed_reflection_tolerance);
        if isempty(pairs),pairs=row;else,pairs(end+1)=row;end
    end
    sequences=struct([]);
    for signValue=[-1,1]
        selected=points(sign([points.signed_amplitude])==signValue);
        a=abs([selected.signed_amplitude]);delta=[selected.energy]-E0;resolved=abs(delta)>5*energyError;
        coefficient=sum(a(resolved).^2.*delta(resolved))/sum(a(resolved).^4);
        relativeError=abs(delta-coefficient*a.^2)./max(abs(delta),energyError);
        row=struct('sign',signValue,'amplitudes',a,'energy_shifts',delta,'resolved',resolved, ...
            'fitted_coefficient',coefficient,'per_point_relative_fit_error',relativeError, ...
            'maximum_resolved_fit_error',max(relativeError(resolved)));
        if isempty(sequences),sequences=row;else,sequences(end+1)=row;end
    end
    audit=struct('schema_version','saved-PIP-attachment-stopping-audit-v3-1', ...
        'completed_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version, ...
        'source_checkpoint',input,'checkpoint_json_sha256',RoundSHA256_v3(path), ...
        'original_attachment_evidence',record.attachment_evidence, ...
        'critical_energy',E0,'energy_uncertainty',energyError,'records',detail,'signed_pairs',pairs, ...
        'energy_fits',sequences,'return_map_evaluations',0,'correction_executed',false, ...
        'conditioning_scope','Saved current or explicitly unused warm linear models, not newly validated derivatives or rigorous forward-error bounds.', ...
        'recommended_first_amplitude',.0003,'recommended_function_tolerance',1e-14, ...
        'recommended_residual_acceptance_tolerance',1e-13,'physical_acceptance_thresholds_changed',false);
    RoundSave_v3(fullfile(outputDirectory,'audit.mat'),struct('audit',audit));
    RoundJSON_v3(fullfile(outputDirectory,'audit.json'),audit);
    for k=1:numel(detail)
        row=detail(k);fprintf('%+.4g dE=%+.12g r=%.3g Newton=%d cond=%.3g predicted_dE=%+.4g\n', ...
            row.signed_amplitude,row.energy_shift,row.final_residual,row.accepted_Newton_steps, ...
            row.Jacobian_condition_estimate,row.linear_remaining_energy_estimate);
    end
    disp(pairs);
end
function value=member(source,name,fallback)
    value=fallback;if isfield(source,name),value=source.(name);end
end
