function audit=AuditFinalMeasuredBL2_v3()
%AUDITFINALMEASUREDBL2_V3 Saved-report forensics only; no map or corrector.
    v3=V3Root_v3(mfilename('fullpath'));
    V3LegacyAddPath_v3(fullfile(v3,'Research_v3','Drivers_v3'));
    relativeFolder='Research_v3/next_round/tasks/full/PIP_n0_measured_flip_BL2_front_hind';
    artifact=[relativeFolder,'/sector_01_signed_-0.001_revision_000_attempt_001.mat'];
    loaded=load(V3Path_v3(fullfile(v3,artifact)),'report','trial');report=loaded.report;root=report.solver;
    saved=load(V3Path_v3(fullfile(v3,relativeFolder,'family_switch_checkpoint.mat')),'phase');phase=saved.phase;
    fd=root.jacobianDiagnostics;observations=fd.eventOrderChartObservations;
    columns=struct('index',{},'reliable',{},'finite',{},'difference_type',{}, ...
        'estimated_relative_error',{},'callback_attempts',{},'topology_changed',{},'failure_reasons',{});
    for k=1:numel(fd.columns)
        column=fd.columns(k);reasons={};
        for candidate=column.candidates,reasons=[reasons,candidate.failureReasons];end %#ok<AGROW>
        columns(end+1)=struct('index',column.index,'reliable',column.reliable, ...
            'finite',all(isfinite(column.derivativeEstimate)), ...
            'difference_type',column.differenceType,'estimated_relative_error',column.estimatedError, ...
            'callback_attempts',column.mapEvaluations,'topology_changed',any([column.candidates.topologyChanged]), ...
            'failure_reasons',{unique(reasons,'stable')}); %#ok<AGROW>
    end
    rejected=find(~[observations.accepted]);
    rejectedReasons=unique({observations(rejected).reason},'stable');
    preMapFailures=root.functionEvaluationCount-root.mapEvaluationCount-root.cacheHitCount;
    completeReasons=numel(rejectedReasons)==1&&contains(rejectedReasons{1},'Complete physical map context is required.');
    allTail=isequal(rejected(:).',(numel(observations)-numel(rejected)+1):numel(observations));
    mapLimit=report.options.SolverOptions.MaxFunctionEvaluations;
    attributionSupported=preMapFailures==root.invalidEvaluationCount ...
        &&preMapFailures==numel(rejected)&&root.mapEvaluationCount<mapLimit ...
        &&report.elapsed_seconds>report.options.MaxWallSeconds&&completeReasons&&allTail;
    gate=load(V3Path_v3(fullfile(v3,'Research_v3/next_round/solver/solver_validation_summary.mat')),'summary');
    audit=struct('schema_version','saved-final-measured-BL2-forensics-v3-1', ...
        'created_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version, ...
        'artifact',artifact,'artifact_sha256',RoundSHA256_v3(fullfile(v3,artifact)), ...
        'canonical_source_hashes',gate.summary.source_hashes, ...
        'accepted',report.accepted,'phase_state',phase.state,'phase',phase.phase, ...
        'next_prediction',phase.next_trial,'registered_predictions',numel(phase.predictions), ...
        'has_saved_partial_trial',isfield(phase,'partial_trial'), ...
        'initial_residual',report.initial_scaled_norm,'final_residual',report.final_scaled_norm, ...
        'full_closure',report.full_closure,'full_closure_tolerance',report.acceptance.FullClosureTolerance, ...
        'primary_failure',report.primary_failure,'finalization_failure',report.finalization_failure, ...
        'replay_failure',report.replay_failure,'independent_replay_performed',~isempty(fieldnames(report.independent_replay)), ...
        'accepted_Newton_steps',root.acceptedNewtonIterations,'Jacobian_evaluations',root.jacobianEvaluationCount, ...
        'function_evaluations',root.functionEvaluationCount,'core_map_evaluations',root.mapEvaluationCount, ...
        'cache_hits',root.cacheHitCount,'invalid_evaluations',root.invalidEvaluationCount, ...
        'pre_map_failure_count_from_counters',preMapFailures,'map_evaluation_limit',mapLimit, ...
        'shared_service_elapsed_seconds',report.elapsed_seconds,'shared_service_wall_limit_seconds',report.options.MaxWallSeconds, ...
        'final_Jacobian_dimensions',size(root.finalJacobian), ...
        'finite_columns',find(all(isfinite(root.finalJacobian),1)), ...
        'reliable_columns',find(fd.perColumnReliability).','columns',columns, ...
        'final_FD_callback_attempts',fd.mapEvaluations,'chart_observation_count',numel(observations), ...
        'chart_accepted_count',sum([observations.accepted]),'chart_rejected_indices',rejected, ...
        'chart_rejection_reasons',{rejectedReasons}, ...
        'any_completed_candidate_topology_mismatch',any([columns.topology_changed]), ...
        'wall_budget_attribution_supported_by_counters',attributionSupported, ...
        'original_WallBudget_identifier_retained_in_FD_reasons',false, ...
        'diagnosis','The last refreshed FD was cut off before five tail map evaluations. Root pre-map wall guards lost their identifier in hybridObjective, and the metadata decorator reported missing context. Completed samples do not show a physical event-order chart mismatch.', ...
        'rank_scope','The complete reliable matrix is unavailable; this partial matrix does not certify rank, conditioning, branch existence or a mathematical chart obstruction.', ...
        'return_map_evaluations_in_forensics',0,'core_or_active_driver_changed',false);
    assert(attributionSupported,'AuditFinalMeasuredBL2_v3:Attribution','Saved counters do not support the asserted deadline diagnosis.');
    output=fullfile(v3,'Research_v3/next_round/solver/final_measured_BL2_forensics');
    RoundSave_v3(fullfile(output,'audit.mat'),struct('audit',audit));RoundJSON_v3(fullfile(output,'audit.json'),audit);
    fid=fopen(V3Path_v3(fullfile(output,'audit.txt')),'w');assert(fid>=0);finish=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'Final measured n0 BL2 attempt: incomplete refreshed FD after wall budget\n\n');
    fprintf(fid,'Bound report: %s\nSHA256: %s\n',artifact,audit.artifact_sha256);
    fprintf(fid,'Unaccepted: residual %.12g -> %.12g; closure %.12g > %.12g. %d accepted Newton steps; %d Jacobian evaluations.\n',audit.initial_residual,audit.final_residual,audit.full_closure,audit.full_closure_tolerance,audit.accepted_Newton_steps,audit.Jacobian_evaluations);
    fprintf(fid,'Primary exit %d: %s\nFinalization: %s\nIndependent replay performed: %d\n',report.primary_failure.exitflag,report.primary_failure.message,report.finalization_failure.message,audit.independent_replay_performed);
    fprintf(fid,'Root counts: %d objective calls, %d actual map evaluations, %d cache hits, %d invalid evaluations. Difference is %d failures before a map. Map limit %d was not reached.\n',audit.function_evaluations,audit.core_map_evaluations,audit.cache_hits,audit.invalid_evaluations,preMapFailures,mapLimit);
    fprintf(fid,'Service elapsed %.9f s exceeds its %.9f s limit. Final FD: %d callback attempts, %d accepted physical-chart observations, %d rejected at tail indices %s.\n',audit.shared_service_elapsed_seconds,audit.shared_service_wall_limit_seconds,fd.mapEvaluations,audit.chart_accepted_count,numel(rejected),mat2str(rejected));
    fprintf(fid,'13x13 matrix: columns1-11 reliable central; column12 finite one-sided-forward and unreliable; column13 unavailable/NaN. All rejected samples report missing physical map context, and all completed candidates have topologyChanged=false.\n');
    fprintf(fid,'The counter identity establishes pre-map failure. Root source has only wall and map-count guards before map evaluation; map count is far below its limit. The original WallBudget identifier was not retained in these FD reasons, so the generic primary message alone is not a scientific chart-obstruction diagnosis.\n');
    fprintf(fid,'Best candidate and partial trial are retained; remaining registered predictions were not executed. No full rank, conditioning, daughter existence or nonexistence claim follows. This audit evaluates zero maps and changes no model, core, driver or task state.\n');
end
