function summary=ExportSourceForensicFollowup_v3()
%EXPORTSOURCEFORENSICFOLLOWUP_V3 Compact read-only campaign-file inspection.
    output=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(output)));V3LegacyAddPath_v3(genpath(V3Path_v3(v3)));
    failedPath='Research_v3/next_round/tasks/full/PIP_candidate_1/daughter_-0.0003_attempt_1.mat';
    acceptedPath='Research_v3/next_round/tasks/full/PIP_candidate_1/daughter_-0.0001_attempt_1.mat';
    bad=load(V3Path_v3(fullfile(v3,failedPath)));good=load(V3Path_v3(fullfile(v3,acceptedPath)));
    r=bad.correction;previous=good.correction;columns=r.solver.jacobianDiagnostics.columns;
    reliability=struct([]);for k=1:numel(columns)
        reliability=[reliability,struct('index',k,'step',columns(k).selectedStep, ...
            'reliable',columns(k).reliable,'estimated_error',columns(k).estimatedError, ...
            'failure_reasons',{columns(k).failureReasons})]; %#ok<AGROW>
    end
    singularValues=svd(previous.solver.finalJacobian);
    cost=struct('failed_artifact',failedPath,'failed_sha256',RoundSHA256_v3(fullfile(v3,failedPath)), ...
        'initial_residual',r.initial_physical_norm,'final_residual',r.final_physical_norm, ...
        'assigned_remaining_wall_seconds',r.options.MaxWallSeconds,'elapsed_seconds',r.elapsed_seconds, ...
        'accepted_Newton_iterations',r.solver.acceptedNewtonIterations, ...
        'actual_map_evaluations',r.solver.mapEvaluationCount, ...
        'objective_attempts',r.solver.functionEvaluationCount, ...
        'FD_attempts',r.solver.jacobianDiagnostics.mapEvaluations,'columns',reliability, ...
        'primary_failure',r.primary_failure,'accepted_previous_artifact',acceptedPath, ...
        'previous_full_closure',previous.full_closure,'previous_Newton_iterations',previous.solver.acceptedNewtonIterations, ...
        'previous_finite_Jacobian',previous.solver.finalJacobian, ...
        'previous_Jacobian_singular_values',singularValues, ...
        'previous_Jacobian_condition_estimate',singularValues(1)/singularValues(end), ...
        'interpretation','A3.78-second remainder starved all FD columns; the failed artifact supplies no conditioning estimate. The prior constrained branch Jacobian is finite and the prior correction converged.', ...
        'prospective_optimization','Checkpoint before a new daughter when the remaining slice cannot build its derivative. Warm-start the next same-sign point from the preceding accepted orbit and finite Jacobian in the same physical chart and equations, retain Broyden refresh5 and fresh acceptance. A quadratic energy predictor is a separately recorded reflection-symmetry hypothesis, not branch evidence.');
    save(V3Path_v3(fullfile(output,'pip_amplitude_cost_inspection.mat')),'cost','-v7');
    RoundJSON_v3(fullfile(output,'pip_amplitude_cost_audit.json'),cost);
    path='Research_v3/next_round/tasks/full/P1_source_25_B/column_00001_revision_000_correction.mat';
    high=load(V3Path_v3(fullfile(v3,path)));x=high.predictor.state;p=high.predictor.parameter;q=high.predictor.mode;
    trace=high.solverReport.partial_evidence.failure_trace;failure=trace.execution.failure;
    events=trace.trajectory.event_history;timeline=struct([]);model=Quadrupedal_Dynamics_v3();
    for k=1:numel(events)
        event=events(k);before=model.guardFunctions(event.time,event.state_before,event.mode_before,p);
        after=model.guardFunctions(event.time,event.state_after,event.mode_after,p);
        row=struct('type',char(event.type),'time',event.time,'mode_before',event.mode_before, ...
            'mode_after',event.mode_after,'state_before',event.state_before,'state_after',event.state_after, ...
            'guard_derivatives_before',[before.directional_derivative].', ...
            'guard_derivatives_after',[after.directional_derivative].');
        timeline=[timeline,row]; %#ok<AGROW>
    end
    source=struct('artifact',path,'sha256',RoundSHA256_v3(fullfile(v3,path)), ...
        'physical_parameter',p,'initial_state',x,'initial_mode',q, ...
        'energy',QuadrupedEnergy_v3.evaluate(x,q,p), ...
        'angle_deviation_from_common',x([7,9,11,13])-mean(x([7,9,11,13])), ...
        'rate_deviation_from_common',x([8,10,12,14])-mean(x([8,10,12,14])), ...
        'pitch',x(5),'pitch_rate',x(6), ...
        'first_failure_time',trace.first_physical_failure.time, ...
        'first_negative_compressions',trace.first_physical_failure.diagnostics.stance_compressions, ...
        'failure_identifier',failure.identifier,'failure_message',failure.message, ...
        'last_valid_state',failure.last_valid_state,'last_valid_mode',failure.last_valid_mode, ...
        'timeline',timeline,'exact_pronk_projection_executed',false, ...
        'recommendation','Measure post-reset guard direction at the failed contact. Tiny signed angle differences make this almost-pronk, but a fresh exact-pronk projection/correction remains an experiment and cannot be presumed to repair immediate tensile contact.');
    save(V3Path_v3(fullfile(output,'high_PK_source_forensics.mat')),'source','-v7');
    RoundJSON_v3(fullfile(output,'high_PK_source_forensics.json'),source);
    lower=load(V3Path_v3(fullfile(output,'domain_lower_energy_audit.mat')));
    raw=load(V3Path_v3(fullfile(output,'domain_lower_minimum_trace.mat')));trace=raw.trace;
    lower.summary.minimum_source_trace=struct('success',trace.execution.success, ...
        'last_valid_time',trace.execution.final_time,'last_valid_state',trace.execution.final_state, ...
        'last_valid_mode',trace.execution.final_mode,'first_physical_failure_time',trace.first_physical_failure.time, ...
        'first_negative_compressions',trace.first_physical_failure.diagnostics.stance_compressions, ...
        'failure_identifier',trace.execution.failure.identifier, ...
        'failure_message',trace.execution.failure.message,'actual_events',trace.actual_events, ...
        'interpretation','The initial state is physically valid; later autonomous contact failure prevents a closed-gait claim.');
    summary=lower.summary;rows=lower.rows;
    save(V3Path_v3(fullfile(output,'domain_lower_energy_audit.mat')),'summary','rows','-v7');
    RoundJSON_v3(fullfile(output,'domain_lower_energy_audit.json'),summary);
    disp(cost);disp(source);
end
