function audit=ExportPeriodicSolverAudit_v3(outputDirectory)
%EXPORTPERIODICSOLVERAUDIT_V3 Export actual focused numerical evidence in MATLAB.
    if nargin<1,outputDirectory=fileparts(mfilename('fullpath'));end
    outputDirectory=V3OutputPath_v3(outputDirectory);
    a=load(V3Path_v3(fullfile(outputDirectory,'case1_pip.mat')));b=load(V3Path_v3(fullfile(outputDirectory,'case1_pk.mat')));
    c=load(V3Path_v3(fullfile(outputDirectory,'case2_actual_correction.mat')));
    before=load(V3Path_v3(fullfile(outputDirectory,'case2_before_broyden.mat')));
    arc=load(V3Path_v3(fullfile(outputDirectory,'case3_arclength.mat')));
    amplitude=load(V3Path_v3(fullfile(outputDirectory,'case3_signed_amplitude.mat')));
    failed=load(V3Path_v3(fullfile(outputDirectory,'case4_failed_imported.mat')));
    parent=load(V3Path_v3(fullfile(outputDirectory,'case5_parent_failure_reproduced.mat')));
    gap=load(V3Path_v3(fullfile(outputDirectory,'case5_tolerance_gap.mat')));
    cover=load(V3Path_v3(fullfile(outputDirectory,'case6_marked_occurrence.mat')));
    audit=struct('schema_version','periodic-solver-executed-audit-v3-1', ...
        'matlab_version',version,'platform',computer,'exported_utc',char(datetime('now','TimeZone','UTC')), ...
        'known_PIP',compact(a.pipReport),'known_PK',compact(b.pkReport), ...
        'nonlinear_correction',compact(c.correctionReport),'correction_before_reuse',compact(before.correctionReport), ...
        'arclength',compact(arc.arcReport),'signed_amplitude',compact(amplitude.amplitudeReport), ...
        'failed_imported',compact(failed.failedReport),'marked_occurrence',cover.result, ...
        'historical_parent',historical(parent.oldSummary), ...
        'reproduced_parent',struct('primary_message',parent.reproduced.primaryMessage, ...
        'primary_exitflag',parent.reproduced.primaryExitflag,'finalization_message',parent.reproduced.finalizationMessage, ...
        'accepted_Newton_iterations',parent.reproduced.acceptedNewtonIterations, ...
        'map_evaluations',parent.reproduced.mapEvaluationCount, ...
        'invalid_evaluations',parent.reproduced.invalidEvaluationCount, ...
        'jacobian_reliable',parent.reproduced.jacobianReliable, ...
        'per_column_reliability',parent.reproduced.perColumnReliability, ...
        'residual_norm',parent.reproduced.residualNorm, ...
        'failure_reasons',{columnReasons(parent.reproduced.jacobianDiagnostics)}), ...
        'tolerance_gap',struct('found',gap.gap.found,'perturbation',gap.gap.magnitude, ...
        'old_reduced_norm',norm(gap.gap.reduced,inf),'old_full_closure',gap.gap.details.full_physical_closure_norm, ...
        'old_primary_converged',gap.gapLegacy.primaryConverged,'old_final_accepted',gap.gapLegacy.converged, ...
        'corrected',compact(gap.gapReport)));
    audit.correction_before_reuse.failure_reasons=columnReasons(before.correctionReport.solver.jacobianDiagnostics);
    trace=failed.failedReport.partial_evidence.failure_trace;
    audit.failed_imported.trace_completed_samples=numel(trace.trajectory.time);
    audit.failed_imported.trace_events=numel(trace.trajectory.event_history);
    audit.failed_imported.first_physical_failure=trace.first_physical_failure;
    save(V3Path_v3(fullfile(outputDirectory,'solver_executed_audit.mat')),'audit','-v7');
    f=fopen(V3Path_v3(fullfile(outputDirectory,'solver_executed_audit.json')),'w');cleanup=onCleanup(@()fclose(f));
    fprintf(f,'%s\n',jsonencode(audit,'PrettyPrint',true));
    figureHandle=figure('Visible','off','Color','w','Position',[100,100,1100,430]);
    if isprop(figureHandle,'Theme'),figureHandle.Theme='light';end
    figureCleanup=onCleanup(@()close(figureHandle));
    tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
    nexttile;
    values=[audit.nonlinear_correction.initial_scaled_norm,audit.nonlinear_correction.final_scaled_norm; ...
        audit.tolerance_gap.corrected.initial_scaled_norm,audit.tolerance_gap.corrected.final_scaled_norm];
    bar(values);set(gca,'YScale','log','XTickLabel',{'Meaningful PK perturbation','Former tolerance gap'});
    ylabel('Scaled residual infinity norm');legend({'Initial','Corrected'},'Location','northwest','AutoUpdate','off');
    yline(1e-10,'--','Reduced acceptance','HandleVisibility','off');title('Actual nonlinear correction');grid on;
    nexttile;
    closed=[audit.known_PIP.full_closure,audit.known_PK.full_closure,audit.nonlinear_correction.full_closure, ...
        audit.arclength.full_closure,audit.signed_amplitude.full_closure,audit.tolerance_gap.corrected.full_closure];
    bar(closed,'FaceColor',[.16,.44,.59]);set(gca,'YScale','log','XTickLabel',{'PIP','PK','Perturbed','Arc','Amplitude','Gap'});
    ylabel('Fresh full closure infinity norm');yline(1e-8,'--','Fixed full closure gate','HandleVisibility','off');
    ylim([1e-12,3e-8]);
    title('Independent tighter replay');grid on;
    axesHandles=findall(figureHandle,'Type','axes');
    set(axesHandles,'Color','w','XColor',[.1,.1,.1],'YColor',[.1,.1,.1], ...
        'GridColor',[.65,.65,.65],'FontSize',11);
    set(findall(figureHandle,'Type','text'),'Color',[.1,.1,.1]);
    exportgraphics(V3Path_v3(figureHandle),fullfile(outputDirectory,'solver_validation_metrics.png'),'Resolution',180);
    disp(audit);
end
function out=historical(saved)
    out=struct('residual_norm',saved.residual_norm,'exitflag',saved.exitflag, ...
        'overwritten_final_message',saved.message,'original_solver_message',saved.output.message, ...
        'iterations',saved.output.iterations,'solver_function_count',saved.output.funcCount, ...
        'accepted_Newton_iterations',saved.accepted_iterations,'invalid_evaluations',saved.invalid_evaluations, ...
        'map_evaluations',saved.map_evaluations,'jacobian_reliable',saved.jacobian_reliable, ...
        'per_column_reliability',saved.per_column_reliability, ...
        'full_metadata_artifact','case5_parent_failure_reproduced.mat');
end
function out=compact(report)
    out=struct('accepted',report.accepted,'status',report.status,'initial_scaled_norm',report.initial_scaled_norm, ...
        'initial_physical_norm',report.initial_physical_norm,'final_scaled_norm',report.final_scaled_norm, ...
        'final_physical_norm',report.final_physical_norm,'full_closure',report.full_closure, ...
        'constraint_residual',report.constraint_residual,'elapsed_seconds',report.elapsed_seconds, ...
        'primary_failure',report.primary_failure,'finalization_failure',report.finalization_failure, ...
        'replay_failure',report.replay_failure,'integration',report.integration,'replay_integration',report.replay_integration);
    for name={'acceptedNewtonIterations','functionEvaluationCount','mapEvaluationCount','invalidEvaluationCount', ...
            'jacobianEvaluationCount','jacobianReliable','primaryMessage','primaryExitflag'}
        if isfield(report.solver,name{1}),out.(name{1})=report.solver.(name{1});end
    end
    if isfield(report,'period'),out.period=report.period;end
    if isfield(report.classification,'label'),out.gait=report.classification.label;out.flight_count=report.classification.flight_count;end
    if isfield(report.physical_inequalities,'maximum_energy_error')
        out.energy_error=report.physical_inequalities.maximum_energy_error;
        out.stance_constraint_error=report.physical_inequalities.maximum_stance_constraint;
    end
end
function reasons=columnReasons(info)
    reasons={};if ~isfield(info,'columns'),return;end
    for k=1:numel(info.columns)
        for r=1:numel(info.columns(k).failureReasons)
            reasons{end+1}=sprintf('column %d: %s',k,info.columns(k).failureReasons{r}); %#ok<AGROW>
        end
    end
end
