function summary=PilotOpposedSpread_v3(predictorArtifact,outputDirectory)
%PILOTOPPOSEDSPREAD_V3 Exact predictor admission and real reduced correction.
    v3=V3Root_v3(mfilename('fullpath'));V3LegacyAddPath_v3(genpath(V3Path_v3(v3)));
    if nargin<2,outputDirectory=fullfile(fileparts(mfilename('fullpath')),'opposed_spread');end
    outputDirectory=V3OutputPath_v3(outputDirectory);if ~isfolder(V3Path_v3(outputDirectory)),mkdir(V3Path_v3(outputDirectory));end
    source=load(V3Path_v3(fullfile(v3,predictorArtifact)),'predictor');predictor=source.predictor;
    proof=load(V3Path_v3(fullfile(v3,predictor.audit_artifact)),'audit');
    selected=find(strcmp({proof.audit.predictor_cases.id},predictor.id));
    assert(proof.audit.passed&&numel(selected)==1&&proof.audit.predictor_cases(selected).passed, ...
        'A separately frozen passed actual-map predictor audit is required.');
    p=predictor.parameter(:);q=logical(predictor.mode(:));x=predictor.state(:);
    w=[predictor.a;predictor.b;predictor.energy];assert(norm(w(1:2))>1e-6);
    integration=proof.audit.registration.settings;
    replay=struct('RelTol',1e-13,'AbsTol',1e-15,'MaxStep',.0025, ...
        'EventValueTolerance',1e-11,'EventTimeTolerance',1e-13, ...
        'SimultaneousTimeTolerance',1e-11);
    oneMap=makeMap(1);twoMap=makeMap(2);
    oneFamily=EnergyFamilyResidual_v3(PeriodicOrbitResidual_v3(oneMap,x),x,q,p);
    twoFamily=EnergyFamilyResidual_v3(PeriodicOrbitResidual_v3(twoMap,x),x,q,p);
    normal=predictor.amplitude_normal(:);reference=predictor.amplitude_reference(:);
    constraint=struct('reference',reference,'normal',normal,'target',predictor.signed_kernel_coordinate);
    adapter=OpposedSpreadFamilyResidual_v3(oneFamily,twoFamily,constraint);
    assert(norm(adapter.fullState(w)-x,inf)<1e-12,'Frozen predictor and exact physical lift disagree.');
    epsilon=(-1)^predictor.resonance_index;omega=sqrt(20);
    formula=[epsilon*predictor.flight_time*sin(predictor.touchdown_angle)/omega; ...
        epsilon*omega*predictor.touchdown_angle;cos(predictor.touchdown_angle)+.5*predictor.flight_time^2];
    assert(norm(formula-w,inf)<1e-12,'Frozen exact predictor does not match its registered formula.');
    delta=1e-4;perturbation=delta*[-normal(2);normal(1);0];perturbed=w+perturbation;
    seed=struct('state',x,'mode',q,'parameter',p,'return_policy','BL-marked-apex-return','occurrence',2, ...
        'provenance',struct('kind','separately-registered-exact-opposed-spread', ...
        'predictor_artifact',predictorArtifact,'audit_artifact',predictor.audit_artifact));
    sources={'Orbit_v3/OpposedSpreadFamilyResidual_v3.m','Orbit_v3/EnergyFamilyResidual_v3.m', ...
        'Numerics_v3/PeriodicSolutionSolver_v3.m','Numerics_v3/RootSolver_v3.m', ...
        'Numerics_v3/HybridFiniteDifferenceJacobian_v3.m','Orbit_v3/PoincareMap_v3.m', ...
        'Simulation_v3/HybridSimulator_v3.m','Simulation_v3/EventDetector_v3.m', ...
        'Research_v3/next_round/solver/PilotOpposedSpread_v3.m'};
    hashes=struct('path',{},'sha256',{});for k=1:numel(sources)
        hashes(k)=struct('path',sources{k},'sha256',RoundSHA256_v3(fullfile(v3,sources{k})));
    end
    registration=struct('schema_version','prospective-opposed-spread-corrector-v3-1', ...
        'frozen_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version,'platform',computer, ...
        'predictor_artifact',predictorArtifact,'predictor_sha256',RoundSHA256_v3(fullfile(v3,predictorArtifact)), ...
        'audit_artifact',predictor.audit_artifact,'audit_sha256',RoundSHA256_v3(fullfile(v3,predictor.audit_artifact)), ...
        'physical_parameter',p,'resonance_index',predictor.resonance_index, ...
        'touchdown_angle',predictor.touchdown_angle,'flight_time',predictor.flight_time, ...
        'exact_coordinates',w,'exact_state',x,'state_swap',adapter.StatePermutation, ...
        'reference',reference,'normal',normal,'signed_amplitude',constraint.target, ...
        'perturbation',perturbation,'perturbed_coordinates',perturbed,'perturbed_state',adapter.fullState(perturbed), ...
        'integration',integration,'replay_integration',replay,'combined_wall_seconds',240, ...
        'source_hashes',hashes,'scope','Exact baseline paired opposed-spread restriction; not the earlier front-only experiment.', ...
        'marked_policy_hypothesis','BL/BR exchange is used only on the measured synchronous TD/LO restriction, with actual marked return ownership.', ...
        'predictor_admission_interpretation','Zero Newton iterations indicate replay admission of the exact predictor, not nonlinear correction.', ...
        'correction_requirement','Perturbation must have initial norm greater than1e-6 and at least one accepted Newton iteration, then actual independent full BL2 acceptance.', ...
        'acceptance_tolerances_changed',false,'ancestry_claimed',false,'unrestricted_C2_claimed',false);
    save(V3Path_v3(fullfile(outputDirectory,'registration.mat')),'registration','predictor','seed','w','perturbed','constraint','-v7');
    RoundJSON_v3(fullfile(outputDirectory,'registration.json'),registration);
    fprintf('Frozen opposed-spread pilot n%d A%.5g: exact predictor plus delta%.5g orthogonal correction.\n', ...
        predictor.resonance_index,predictor.touchdown_angle,delta);
    fd=HybridFiniteDifferenceJacobian_v3(struct('RelativeCandidateSteps',[3e-5,1e-5], ...
        'MaximumRelativeError',.01,'UseRichardson',false));
    options=struct('Residual',adapter,'Coordinates',w,'AugmentedParameter',[p;w(3)], ...
        'MaxWallSeconds',60,'MaxReturnTime',10,'ReplayIntegration',replay, ...
        'SolverOptions',struct('Algorithm','newton','MaxIterations',25,'MaxFunctionEvaluations',700, ...
        'Jacobian',fd,'UseBroyden',true,'JacobianRefreshInterval',5));
    combined=tic;[exactOrbit,exactReport]=PeriodicSolutionSolver_v3(seed,options);
    save(V3Path_v3(fullfile(outputDirectory,'exact_predictor_admission.mat')),'exactOrbit','exactReport','options','-v7');
    perturbSeed=seed;perturbSeed.state=adapter.fullState(perturbed);
    perturbSeed.provenance.kind='registered-meaningful-opposed-spread-perturbation';
    perturbSeed.provenance.coordinate_perturbation=perturbation;
    correctionOptions=options;correctionOptions.Coordinates=perturbed;
    correctionOptions.MaxWallSeconds=max(.001,240-toc(combined));
    [correctedOrbit,correctionReport]=PeriodicSolutionSolver_v3(perturbSeed,correctionOptions);
    save(V3Path_v3(fullfile(outputDirectory,'nonlinear_correction.mat')),'perturbSeed','perturbed', ...
        'correctedOrbit','correctionReport','correctionOptions','-v7');
    summary=struct('schema_version','opposed-spread-corrector-result-v3-1', ...
        'completed_utc',char(datetime('now','TimeZone','UTC')),'combined_elapsed_seconds',toc(combined), ...
        'exact_predictor',compact(exactReport),'nonlinear_correction',compact(correctionReport), ...
        'exact_predictor_admitted',exactReport.accepted, ...
        'meaningful_nonlinear_correction_passed',correctionReport.accepted ...
        &&correctionReport.initial_scaled_norm>1e-6&&correctionReport.solver.acceptedNewtonIterations>0, ...
        'source_hashes',hashes,'ancestry_claimed',false,'new_gait_claimed',false);
    if exactReport.accepted
        assert(exactOrbit.section_chart.BL_touchdowns_per_return==2&&exactReport.primitive.status=="primitive_within_checked_bound");
    end
    if correctionReport.accepted
        assert(correctedOrbit.section_chart.BL_touchdowns_per_return==2&&correctionReport.primitive.status=="primitive_within_checked_bound");
    end
    save(V3Path_v3(fullfile(outputDirectory,'summary.mat')),'summary','-v7');
    RoundJSON_v3(fullfile(outputDirectory,'summary.json'),summary);disp(summary);
    function map=makeMap(count)
        policy=BLMarkedApexReturnPolicy_v3(struct('BLTouchdownsPerReturn',count));
        map=PoincareMap_v3(Quadrupedal_Dynamics_v3(),PoincareSection_v3.apex(4), ...
            HybridSimulator_v3(integration),policy,struct('MaxReturnTime',10,'MaxSectionCrossings',32));
    end
    function result=compact(report)
        result=struct('accepted',report.accepted,'status',report.status,'elapsed_seconds',report.elapsed_seconds, ...
            'initial_residual',report.initial_scaled_norm,'final_residual',report.final_scaled_norm, ...
            'actual_full_BL2_closure',report.full_closure,'constraint_residual',report.constraint_residual, ...
            'independent_BL2_replay_performed',~isempty(fieldnames(report.independent_replay)), ...
            'primary_failure',report.primary_failure,'finalization_failure',report.finalization_failure,'replay_failure',report.replay_failure);
        if isfield(report.solver,'acceptedNewtonIterations')
            result.accepted_Newton_iterations=report.solver.acceptedNewtonIterations;
            result.core_objective_map_count=report.solver.mapEvaluationCount;
            result.Jacobian_evaluations=report.solver.jacobianEvaluationCount;
            result.jacobian_reliable=report.solver.jacobianReliable;
            result.final_coordinates=report.final_coordinates;
            info=report.solver.evaluationInfo;
            for name={'invariant_leak','contact_cohort_spans','full_twisted_closure_norm','physical_two_return_evaluated'}
                if isfield(info,name{1}),result.(name{1})=info.(name{1});end
            end
        end
        if report.accepted
            result.primitive=report.primitive;result.classification=report.classification;
            result.physical_inequalities=report.physical_inequalities;
            result.BL_occurrence=report.independent_replay.map_info.section_chart.BL_touchdowns_per_return;
            result.actual_contact_counts=report.independent_replay.map_info.event_counts_per_leg;
            result.period=report.period;result.drift=report.drift;
        end
    end
end
