function summary=PilotTwistedFrontReturn_v3(outputDirectory)
%PILOTTWISTEDFRONTRETURN_V3 One preregistered 240-second n0 front-swap pilot.
    v3=V3Root_v3(mfilename('fullpath'));
    V3LegacyAddPath_v3(genpath(V3Path_v3(v3)));
    if nargin<1,outputDirectory=fullfile(fileparts(mfilename('fullpath')),'twisted_return');end
    outputDirectory=V3OutputPath_v3(outputDirectory);if ~isfolder(V3Path_v3(outputDirectory)),mkdir(V3Path_v3(outputDirectory));end
    parentPath='Research_v3/next_round/theory/n0_parent_service_admission.mat';
    catalogPath='Research_v3/next_round/theory/n0_flip_BL2_sector_candidates.mat';
    parent=load(V3Path_v3(fullfile(v3,parentPath)),'parentOrbit','parentReport','parentSeed');
    loaded=load(V3Path_v3(fullfile(v3,catalogPath)),'catalog');catalog=loaded.catalog;
    assert(parent.parentReport.accepted&&~isempty(parent.parentOrbit),'The registered n0 parent must already be independently admitted.');
    x=parent.parentOrbit.initial_state;q=parent.parentOrbit.initial_mode;p=parent.parentOrbit.parameter;
    assert(~any(q)&&numel(p)==10&&isequal(p,[10;10;20;20;1;1;0;0;2;.5]));
    integration=struct('RelTol',1e-11,'AbsTol',1e-13,'MaxStep',.005);
    oneMap=makeMap(1,integration);twoMap=makeMap(2,integration);
    oneFamily=EnergyFamilyResidual_v3(PeriodicOrbitResidual_v3(oneMap,x),x,q,p);
    twoFamily=EnergyFamilyResidual_v3(PeriodicOrbitResidual_v3(twoMap,x),x,q,p);
    indices=oneFamily.CoordinateIndices;u=oneFamily.packState(x);
    E=QuadrupedEnergy_v3.evaluate(x,q,p);
    direction=catalog.candidates(1).physical_direction(:);
    assert(norm(direction)==1||abs(norm(direction)-1)<1e-12);
    target=.001;normal=[direction(indices);0];reference=[u;E];
    constraint=struct('reference',reference,'normal',normal,'target',target);
    adapter=TwistedReturnFamilyResidual_v3(oneFamily,twoFamily,constraint);
    S=eye(14);S=S(adapter.StatePermutation,:);Su=eye(numel(indices));Su=Su(adapter.CoordinatePermutation,:);
    assert(norm(S*x-x,inf)<1e-12&&norm(S*direction+direction,inf)<1e-12);
    tangentPositions=oneFamily.ClosureIndices;
    linearTwist=catalog.source_full_matrix-Su;
    leafTwist=linearTwist(tangentPositions,tangentPositions);
    singularValues=svd(leafTwist);nullThreshold=1e-6;
    seedState=x+target*direction;seedE=QuadrupedEnergy_v3.evaluate(seedState,q,p);
    coordinates=[oneFamily.packState(seedState);seedE];
    seed=parent.parentSeed;seed.state=seedState;seed.occurrence=2;
    seed.provenance=struct('kind','preregistered-front-twisted-BL1-to-physical-BL2-pilot', ...
        'parent_artifact',parentPath,'catalog_artifact',catalogPath,'signed_amplitude',target);
    sources={'Orbit_v3/TwistedReturnFamilyResidual_v3.m','Numerics_v3/PeriodicSolutionSolver_v3.m', ...
        'Numerics_v3/RootSolver_v3.m','Numerics_v3/EventOrderChartJacobian_v3.m', ...
        'Orbit_v3/PoincareMap_v3.m','Simulation_v3/HybridSimulator_v3.m','Simulation_v3/EventDetector_v3.m'};
    hashes=struct('path',{},'sha256',{});for k=1:numel(sources)
        hashes(k)=struct('path',sources{k},'sha256',RoundSHA256_v3(fullfile(v3,sources{k})));
    end
    registration=struct('schema_version','prospective-front-twisted-return-pilot-v3-1', ...
        'frozen_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version,'platform',computer, ...
        'parent_artifact',parentPath,'parent_sha256',RoundSHA256_v3(fullfile(v3,parentPath)), ...
        'catalog_artifact',catalogPath,'catalog_sha256',RoundSHA256_v3(fullfile(v3,catalogPath)), ...
        'source_energy',catalog.source_energy,'initial_energy',seedE,'physical_parameter',p, ...
        'physical_coordinate_indices',indices,'state_swap_matrix',S,'coordinate_swap_matrix',Su, ...
        'measured_parent_return_matrix',catalog.source_full_matrix,'measured_front_direction',direction, ...
        'energy_leaf_twisted_matrix',leafTwist,'energy_leaf_twisted_singular_values',singularValues, ...
        'measured_leaf_nullity',sum(singularValues<nullThreshold),'nullity_threshold',nullThreshold, ...
        'rank_qualification','The front flip and a conserved-energy-independent pronk +1 mode can both remain null at the parent; no simple-kernel or regular-branch claim.', ...
        'front_multiplier',catalog.candidates(1).measured_multiplier,'signed_amplitude',target, ...
        'reference',reference,'normal',normal,'source_hashes',hashes, ...
        'Newton_equations','Actual BL1 return minus physical FL/FR swap, omit the invariant energy-pivot closure, append H-E and signed amplitude.', ...
        'finalization','Actual BL2 map supplies full physical closure and trajectory; shared service performs new tighter BL2 replay and primitive checks.', ...
        'hypothesis','Front swap preserves fixed paired-leg model, flight apex and BL marked identity; experiment assumes the registered regular actual return exists.', ...
        'regularity_scope','Common first derivative only under recorded event-order chart hypotheses; no unrestricted C2 certificate.', ...
        'hind_swap_scope','No hind-swap experiment: exchanging BL/BR changes marked identity and requires separate local ownership verification.', ...
        'max_service_wall_seconds',240,'integration',integration, ...
        'replay_integration',struct('RelTol',1e-12,'AbsTol',1e-14,'MaxStep',.0025), ...
        'acceptance_tolerances_changed',false,'ancestry_claimed',false);
    save(V3Path_v3(fullfile(outputDirectory,'registration.mat')),'registration','seed','coordinates','constraint','-v7');
    RoundJSON_v3(fullfile(outputDirectory,'registration.json'),registration);
    fprintf('Frozen front twisted pilot: E %.15g, signed amplitude %.4g, BL1 Newton / BL2 acceptance.\n',E,target);
    % Check actual front-swap equivariance on the nonzero registered seed.
    [initialResidual,initialInfo]=adapter.evaluateWithInfo(coordinates,[p;seedE],q);
    [swappedNext,swappedMap]=oneMap.evaluate(S*seedState,q,p);
    expectedSwappedNext=S*initialInfo.next_state;
    equivariance=norm(swappedNext(2:end)-expectedSwappedNext(2:end),inf);
    preflight=struct('initial_twisted_norm',norm(initialResidual,inf), ...
        'initial_ordinary_BL1_closure',initialInfo.one_return_info.full_physical_closure_norm, ...
        'front_swap_equivariance_error',equivariance,'energy_invariance_error',initialInfo.front_swap_energy_difference, ...
        'actual_one_return_occurrence',initialInfo.map_info.section_chart.BL_touchdowns_per_return, ...
        'actual_finalization_map_occurrence',adapter.Map.ReturnPolicy.BLTouchdownsPerReturn, ...
        'amplitude_equation_error',initialInfo.constraint_residual,'nonperiodic_objective_valid',initialInfo.admissible);
    save(V3Path_v3(fullfile(outputDirectory,'preflight.mat')),'preflight','initialResidual','initialInfo','swappedNext','swappedMap','-v7');
    RoundJSON_v3(fullfile(outputDirectory,'preflight.json'),preflight);
    assert(equivariance<=1e-8&&initialInfo.admissible&&abs(initialInfo.constraint_residual)<1e-12, ...
        'Actual front-swap equivariance, admissibility or signed amplitude preflight failed.');
    fd=EventOrderChartJacobian_v3(struct('PhysicalParameter',p,'RelativeCandidateSteps',[3e-4,1e-4], ...
        'MaximumRelativeError',.01,'UseRichardson',false,'BLTouchdownsPerReturn',1));
    options=struct('Residual',adapter,'Coordinates',coordinates,'AugmentedParameter',[p;seedE], ...
        'MaxWallSeconds',240,'MaxReturnTime',10,'ReplayIntegration',registration.replay_integration, ...
        'SolverOptions',struct('Algorithm','newton','MaxIterations',25,'MaxFunctionEvaluations',1000, ...
        'Jacobian',fd,'UseBroyden',true,'JacobianRefreshInterval',5));
    started=tic;[solution,report]=PeriodicSolutionSolver_v3(seed,options);elapsed=toc(started);
    summary=struct('schema_version','front-twisted-return-pilot-result-v3-1', ...
        'completed_utc',char(datetime('now','TimeZone','UTC')),'accepted',report.accepted, ...
        'status',report.status,'elapsed_seconds',elapsed,'initial_twisted_norm',report.initial_scaled_norm, ...
        'final_twisted_norm',report.final_scaled_norm,'correction_full_BL2_closure',report.full_closure, ...
        'independent_BL2_replay_performed',~isempty(fieldnames(report.independent_replay)), ...
        'constraint_residual',report.constraint_residual,'preflight',preflight,'source_hashes',hashes, ...
        'primary_failure',report.primary_failure,'finalization_failure',report.finalization_failure, ...
        'replay_failure',report.replay_failure,'ancestry_claimed',false,'new_gait_claimed',false);
    if isfield(report,'solver')&&isfield(report.solver,'evaluationInfo')
        final=report.solver.evaluationInfo;
        for name={'full_twisted_closure_norm','physical_two_return_evaluated','front_spread','augmented_energy'}
            if isfield(final,name{1}),summary.(name{1})=final.(name{1});end
        end
        summary.accepted_Newton_iterations=report.solver.acceptedNewtonIterations;
        summary.core_objective_map_count=report.solver.mapEvaluationCount;
        summary.jacobian_reliable=report.solver.jacobianReliable;
    end
    if report.accepted
        summary.accepted_BL_occurrence=solution.section_chart.BL_touchdowns_per_return;
        summary.primitive=report.primitive;summary.classification=report.classification;
        summary.physical_inequalities=report.physical_inequalities;
        summary.new_gait_claimed=false; % Classification is evidence, not ancestry.
        assert(summary.accepted_BL_occurrence==2&&report.primitive.status=="primitive_within_checked_bound");
    end
    save(V3Path_v3(fullfile(outputDirectory,'pilot.mat')),'solution','report','summary','options','-v7');
    RoundJSON_v3(fullfile(outputDirectory,'pilot.json'),summary);disp(summary);
    function map=makeMap(count,tolerances)
        policy=BLMarkedApexReturnPolicy_v3(struct('BLTouchdownsPerReturn',count));
        map=PoincareMap_v3(Quadrupedal_Dynamics_v3(),PoincareSection_v3.apex(4), ...
            HybridSimulator_v3(tolerances),policy,struct('MaxReturnTime',10,'MaxSectionCrossings',32));
    end
end
