function registration=RegisterPIPScanMethod_v3()
%REGISTERPIPSCANMETHOD_V3 Register the audited parent-scan cost repair.
    root=V3Root_v3(mfilename('fullpath'));
    V3LegacyAddPath_v3(genpath(V3Path_v3(root)));folder=fullfile(root,'Research_v3','next_round');
    file=fullfile(folder,'pip_parent_scan_method_revision.json');
    if isfile(V3Path_v3(file)),registration=jsondecode(fileread(V3Path_v3(file)));return;end
    gate=jsondecode(fileread(V3Path_v3(fullfile(folder,'solver','pip_analytic_audit.json'))));
    assert(gate.passed,'Analytic parent gate must pass before scan registration.');
    hash=RoundSHA256_v3(fullfile(root,'Numerics_v3','RestrictedPIPParentMatrix_v3.m'));
    assert(strcmp(hash,gate.registration.helper_sha256),'Parent helper changed after its independent audit.');
    registration=struct('schema_version','prospective-PIP-scan-method-revision-v3-1', ...
        'registered_utc',char(datetime('now','TimeZone','UTC')), ...
        'measured_obstacle','Several240s slices reached only coarse parent sampling or a few bisections.', ...
        'method','Analytic vertical orbit plus integrated2x2 stance variational fundamental matrix for identify/refine only.', ...
        'validated_energy_interval',[1.0001,3],'physical_parameter',gate.registration.physical_parameter, ...
        'helper_sha256',hash,'independent_gate','Research_v3/next_round/solver/pip_analytic_audit.mat', ...
        'maximum_fresh_FD_comparison_error',max([gate.fresh_comparisons.relative_matrix_error]), ...
        'critical_subspace_validation','Three actual production return-map FD steps retained.', ...
        'transversality_validation','Four actual production return-map FD matrices retained.', ...
        'daughter_acceptance','Shared constrained correction and independent tighter physical replay unchanged.', ...
        'acceptance_tolerances_changed',false, ...
        'evaluation_counter_scope','Return-map/root-residual evaluations; variational RHS work is charged by measured wall time.');
    RoundJSON_v3(file,registration);RoundSave_v3(fullfile(folder,'pip_parent_scan_method_revision.mat'),struct('registration',registration));
end
