function summary=ValidateFrontBroydenMetadata_v3()
%VALIDATEFRONTBROYDENMETADATA_V3 Saved real BL1 traces and missing-history gate.
    v3=V3Root_v3(mfilename('fullpath'));V3LegacyAddPath_v3(genpath(V3Path_v3(v3)));
    folder=fullfile(fileparts(mfilename('fullpath')),'twisted_return');
    loaded=load(V3Path_v3(fullfile(folder,'pilot.mat')),'report');report=loaded.report;
    original=report.options.Residual;
    adapter=TwistedReturnFamilyResidual_v3(original.OneFamily,original.TwoFamily,original.Constraint, ...
        struct('CommonC1BroydenMetadata',true));
    initial=report.initial_evaluation;final=report.solver.evaluationInfo;
    path='Orbit_v3/TwistedReturnFamilyResidual_v3.m';
    registration=struct('schema_version','prospective-front-C1-Broyden-metadata-gate-v3-1', ...
        'frozen_utc',char(datetime('now','TimeZone','UTC')),'adapter_sha256',RoundSHA256_v3(fullfile(v3,path)), ...
        'helper_sha256',RoundSHA256_v3(fullfile(v3,'Numerics_v3/EventOrderChartJacobian_v3.m')), ...
        'source_pilot_sha256',RoundSHA256_v3(fullfile(folder,'pilot.mat')), ...
        'scope','Metadata-only optional compatibility on verified real one-BL trajectories; no correction or physical replay in this gate.', ...
        'negative_control','Remove the actual event history; normalization must be rejected and raw signatures preserved.', ...
        'acceptance_tolerances_changed',false,'new_correction_claimed',false);
    RoundJSON_v3(fullfile(folder,'Broyden_metadata_registration.json'),registration);
    [first,firstDiagnostic]=adapter.normalizeBroydenMetadata(initial);
    [last,lastDiagnostic]=adapter.normalizeBroydenMetadata(final);
    missing=final;missing.map_info=rmfield(missing.map_info,'event_history');
    [rejected,rejectedDiagnostic]=adapter.normalizeBroydenMetadata(missing);
    names={'cyclic_event_signature','section_relative_event_signature','event_cluster_signature'};
    commonKeys=true;rawPreserved=true;rejectionRaw=true;
    for k=1:numel(names)
        name=names{k};commonKeys=commonKeys&&isequal(first.(name),last.(name));
        rawPreserved=rawPreserved&&isequal(first.one_return_info.(name),initial.one_return_info.(name)) ...
            &&isequal(last.one_return_info.(name),final.one_return_info.(name));
        rejectionRaw=rejectionRaw&&isequal(rejected.(name),missing.(name));
    end
    summary=struct('schema_version','front-C1-Broyden-metadata-gate-v3-1','passed',false, ...
        'initial_actual_chart',firstDiagnostic,'final_actual_chart',lastDiagnostic, ...
        'verified_common_compatibility_keys',commonKeys,'raw_one_return_preserved',rawPreserved, ...
        'missing_event_history_rejected',~rejectedDiagnostic.accepted, ...
        'rejection_reason',rejectedDiagnostic.reason,'rejected_raw_signatures_preserved',rejectionRaw, ...
        'adapter_sha256',registration.adapter_sha256,'helper_sha256',registration.helper_sha256, ...
        'map_info_unchanged',isequaln(first.map_info,initial.map_info)&&isequaln(last.map_info,final.map_info), ...
        'new_correction_claimed',false,'no_physics_or_acceptance_change',true);
    summary.passed=firstDiagnostic.accepted&&lastDiagnostic.accepted&&commonKeys&&rawPreserved ...
        &&~rejectedDiagnostic.accepted&&rejectionRaw&&summary.map_info_unchanged;
    save(V3Path_v3(fullfile(folder,'Broyden_metadata_gate.mat')),'summary','registration','first','last','rejected','-v7');
    RoundJSON_v3(fullfile(folder,'Broyden_metadata_gate.json'),summary);disp(summary);
    assert(summary.passed,'ValidateFrontBroydenMetadata_v3:Failed','Actual metadata and missing-history gate failed.');
end
