classdef ContinuousDynamics_v3
    %CONTINUOUSDYNAMICS_V3 Four-leg SLIP flow in the canonical v3 schema.
    %
    % The mode is q=[BL;BR;FL;FR].  Contacting massless legs enforce the
    % existing fixed-horizontal-foot constraint.  Swing-leg dynamics follow
    % from the infinitesimal-leg Lagrangian with alpha measured relative to
    % the torso and rsla the equilibrium value of alpha.

    properties (SetAccess = private)
        Schema
        AdmissibilityComponent
        GeometryTolerance = 1e-10
        AdmissibilityTolerance = 1e-8
    end

    methods
        function obj = ContinuousDynamics_v3(schema, options)
            if nargin < 1 || isempty(schema)
                schema = QuadrupedSchema_v3.shared();
                if nargin < 2 || isempty(options)
                    options = struct();
                end
            elseif isstruct(schema) && nargin == 1
                options = schema;
                schema = QuadrupedSchema_v3.shared();
            elseif nargin < 2 || isempty(options)
                options = struct();
            end
            if ~isa(schema, 'QuadrupedSchema_v3')
                error('ContinuousDynamics_v3:InvalidSchema', ...
                    'Schema must be a QuadrupedSchema_v3 instance.');
            end
            obj.Schema = schema;
            admissibilityOptions = struct();
            if isfield(options, 'AdmissibilityOptions')
                admissibilityOptions = options.AdmissibilityOptions;
                options = rmfield(options, 'AdmissibilityOptions');
            end
            obj = obj.applyOptions(options);
            if ~isfield(admissibilityOptions, 'GeometryTolerance')
                admissibilityOptions.GeometryTolerance = ...
                    obj.GeometryTolerance;
            end
            if ~isfield(admissibilityOptions, 'StanceTensionTolerance')
                admissibilityOptions.StanceTensionTolerance = ...
                    obj.AdmissibilityTolerance;
            end
            obj.AdmissibilityComponent = QuadrupedAdmissibility_v3( ...
                schema, admissibilityOptions);
        end

        function [dxdt, diagnostics] = evaluate(obj, t, x, q, p) %#ok<INUSD>
            [x, q, p] = obj.validateInputs(x, q, p);
            state = obj.Schema.State;
            leg = obj.Schema.Leg;
            expanded = obj.Schema.expandParameters(p);

            positionX = x(state.x);
            velocityX = x(state.dx);
            positionY = x(state.y);
            velocityY = x(state.dy);
            phi = x(state.phi);
            dphi = x(state.dphi);
            alpha = x(leg.AngleIndices);
            storedDalpha = x(leg.RateIndices);

            theta = phi + alpha;
            cosineTheta = cos(theta);
            hipPositions = [ ...
                positionX + expanded.s .* cos(phi), ...
                positionY + expanded.s .* sin(phi)].';
            hipHeight = hipPositions(2, :).';

            stanceMask = logical(q);
            singularStance = stanceMask ...
                & abs(cosineTheta) <= obj.GeometryTolerance;
            if any(singularStance)
                names = strjoin(leg.Names(singularStance.'), ', ');
                error('ContinuousDynamics_v3:SingularLegGeometry', ...
                    'Stance leg geometry is singular for %s.', names);
            end

            % A swing leg has its prescribed rest length and needs no
            % ground-intersection solve.  Dividing hip height by cos(theta)
            % is both unnecessary and singular for a horizontal swing leg.
            % The constrained geometric length is evaluated only in stance.
            legLength = expanded.l_0;
            compression = zeros(leg.Count, 1);
            legLength(stanceMask) = hipHeight(stanceMask) ...
                ./ cosineTheta(stanceMask);
            compression(stanceMask) = expanded.l_0(stanceMask) ...
                - legLength(stanceMask);
            axialLegForce = zeros(leg.Count, 1);
            axialLegForce(stanceMask) = expanded.k_l(stanceMask) ...
                .* compression(stanceMask);

            % Do not clamp negative compression.  ODE solvers evaluate trial
            % stages beyond an event root, so rejection is performed by
            % assertAdmissible on accepted hybrid states rather than here.
            perLegForceVectors = [ ...
                -axialLegForce .* sin(theta), ...
                 axialLegForce .* cos(theta)].';
            totalForce = sum(perLegForceVectors, 2);
            forceX = totalForce(1);
            forceY = totalForce(2);
            perLegTorque = expanded.s .* axialLegForce .* cos(alpha);
            pitchTorque = sum(perLegTorque);

            accelerationX = forceX;
            accelerationY = forceY - 1;
            if isinf(expanded.j_pitch)
                accelerationPhi = 0;
            else
                accelerationPhi = pitchTorque / expanded.j_pitch;
            end

            outputDalpha = storedDalpha;
            accelerationAlpha = zeros(leg.Count, 1);
            swingTorsionalAcceleration = zeros(leg.Count, 1);
            for legIndex = leg.Indices
                if stanceMask(legIndex)
                    if leg.BackMask(legIndex)
                        [outputDalpha(legIndex), accelerationAlpha(legIndex)] = ...
                            obj.backConstraintRates(x, ...
                            leg.AngleIndices(legIndex), expanded.l_com, ...
                            accelerationX, accelerationY, accelerationPhi);
                    else
                        [outputDalpha(legIndex), accelerationAlpha(legIndex)] = ...
                            obj.frontConstraintRates(x, ...
                            leg.AngleIndices(legIndex), expanded.l_com, ...
                            accelerationX, accelerationY, accelerationPhi);
                    end
                else
                    accelerationAlpha(legIndex) = obj.swingLegAcceleration( ...
                        forceX, forceY, phi, dphi, accelerationPhi, ...
                        alpha(legIndex), expanded.s(legIndex), ...
                        expanded.l_0(legIndex), expanded.k_s(legIndex), ...
                        expanded.rsla(legIndex));
                    swingTorsionalAcceleration(legIndex) = ...
                        -(expanded.k_s(legIndex) ...
                        / expanded.l_0(legIndex)^2) ...
                        * (alpha(legIndex) - expanded.rsla(legIndex));
                end
            end

            dxdt = zeros(state.Dimension, 1);
            dxdt(state.x) = velocityX;
            dxdt(state.dx) = accelerationX;
            dxdt(state.y) = velocityY;
            dxdt(state.dy) = accelerationY;
            dxdt(state.phi) = dphi;
            dxdt(state.dphi) = accelerationPhi;
            dxdt(leg.AngleIndices) = outputDalpha;
            dxdt(leg.RateIndices) = accelerationAlpha;

            if any(~isfinite(dxdt))
                error('ContinuousDynamics_v3:NonfiniteFlow', ...
                    'Quadruped flow became nonfinite.');
            end

            physicalAdmissibility = obj.AdmissibilityComponent.evaluate( ...
                x, q, p, 'ode-stage');
            admissibilityMargins = compression ...
                + obj.AdmissibilityTolerance;
            stanceAdmissibilityMargins = Inf(leg.Count, 1);
            stanceAdmissibilityMargins(stanceMask) = ...
                admissibilityMargins(stanceMask);
            stanceAdmissible = ~stanceMask ...
                | admissibilityMargins >= 0;
            invalidStanceLegs = find(~stanceAdmissible);
            diagnostics = struct( ...
                'hip_positions', hipPositions, ...
                'absolute_leg_angles', theta, ...
                'leg_lengths', legLength, ...
                'compression', compression, ...
                'axial_leg_forces', axialLegForce, ...
                'per_leg_force_vectors', perLegForceVectors, ...
                'total_force', totalForce, ...
                'pitch_torque', pitchTorque, ...
                'per_leg_pitch_torque', perLegTorque, ...
                'mode', q, ...
                'admissibility_tolerance', obj.AdmissibilityTolerance, ...
                'admissibility_margins', admissibilityMargins, ...
                'stance_admissibility_margins', ...
                    stanceAdmissibilityMargins, ...
                'minimum_stance_admissibility_margin', ...
                    min(stanceAdmissibilityMargins), ...
                'stance_admissible', stanceAdmissible, ...
                'admissible', physicalAdmissibility.global_validity, ...
                'invalid_stance_legs', invalidStanceLegs, ...
                'physical_admissibility', physicalAdmissibility, ...
                'global_validity', ...
                    physicalAdmissibility.global_validity, ...
                'minimum_physical_margin', ...
                    physicalAdmissibility.minimum_physical_margin, ...
                'physical_failure_reasons', ...
                    {physicalAdmissibility.failure_reasons}, ...
                'swing_foot_clearances', ...
                    physicalAdmissibility.swing_foot_clearances, ...
                'complementarity_residuals', ...
                    physicalAdmissibility.complementarity_residuals, ...
                'projected_leg_rates', outputDalpha, ...
                'leg_angular_accelerations', accelerationAlpha, ...
                'swing_torsional_acceleration', ...
                    swingTorsionalAcceleration, ...
                'schema_metadata', obj.Schema.metadata(), ...
                ... % Compatibility diagnostic aliases; no ordering is copied.
                'leg_force', axialLegForce, ...
                'force_x', forceX, ...
                'force_y', forceY, ...
                'torque', pitchTorque, ...
                'hip_height', hipHeight, ...
                'leg_length', legLength, ...
                'projected_leg_rate', outputDalpha);
        end

        function diagnostics = admissibilityReport(obj, x, q, p, ...
                context, contextData)
            %ADMISSIBILITYREPORT Model-owned physical geometry report.
            if nargin < 5 || isempty(context)
                context = 'accepted-state';
            end
            if nargin < 6
                contextData = struct();
            end
            diagnostics = obj.AdmissibilityComponent.evaluate( ...
                x, q, p, context, contextData);
        end

        function diagnostics = assertAdmissible(obj, x, q, p, ...
                context, contextData)
            %ASSERTADMISSIBLE Reject an inadmissible accepted hybrid state.
            % Transient Runge--Kutta stages use evaluate(), which reports
            % the permissive 'ode-stage' policy without throwing.
            if nargin < 5 || isempty(context)
                context = 'accepted-state';
            end
            if nargin < 6
                contextData = struct();
            end
            diagnostics = obj.admissibilityReport( ...
                x, q, p, context, contextData);
            if ~diagnostics.global_validity
                tensileLegs = diagnostics.invalid_stance_legs;
                tensileLegs = tensileLegs( ...
                    diagnostics.stance_compressions(tensileLegs) ...
                    < -diagnostics.active_tolerances.stance_tension);
                if ~isempty(tensileLegs)
                    names = strjoin(obj.Schema.Leg.Names(tensileLegs), ', ');
                    error('ContinuousDynamics_v3:TensileStance', ...
                        ['Stance compression is below the admissibility ' ...
                        'tolerance for leg(s) %s.'], names);
                end
                message = strjoin(diagnostics.failure_reasons, ', ');
                error('ContinuousDynamics_v3:PhysicallyInadmissible', ...
                    'Quadruped %s is physically inadmissible: %s.', ...
                    diagnostics.context, message);
            end
        end

        function ddalpha = swingLegAcceleration(~, forceX, forceY, phi, ...
                dphi, accelerationPhi, alpha, hipOffset, legLength, ...
                torsionalStiffness, restSwingLegAngle)
            %SWINGLEGACCELERATION Derived relative-angle swing equation.
            theta = phi + alpha;
            ddalpha = -accelerationPhi ...
                - (forceX .* cos(theta) + forceY .* sin(theta)) ...
                    ./ legLength ...
                - (hipOffset ./ legLength) .* accelerationPhi ...
                    .* sin(alpha) ...
                + (hipOffset ./ legLength) .* dphi.^2 .* cos(alpha) ...
                - (torsionalStiffness ./ legLength.^2) ...
                    .* (alpha - restSwingLegAngle);
        end

        function [dalpha, ddalpha] = stanceConstraintRates( ...
                obj, x, legIndex, p, accelerationX, accelerationY, accelerationPhi)
            [x, ~, p] = obj.validateInputs(x, ...
                false(obj.Schema.Leg.Count, 1), p);
            if ~(isnumeric(legIndex) && isscalar(legIndex) ...
                    && isfinite(legIndex) && legIndex == fix(legIndex) ...
                    && any(legIndex == obj.Schema.Leg.Indices))
                error('ContinuousDynamics_v3:InvalidLeg', ...
                    'Leg index must identify BL, BR, FL, or FR.');
            end
            expanded = obj.Schema.expandParameters(p);
            angleIndex = obj.Schema.Leg.AngleIndices(legIndex);
            if obj.Schema.Leg.BackMask(legIndex)
                [dalpha, ddalpha] = obj.backConstraintRates( ...
                    x, angleIndex, expanded.l_com, accelerationX, ...
                    accelerationY, accelerationPhi);
            else
                [dalpha, ddalpha] = obj.frontConstraintRates( ...
                    x, angleIndex, expanded.l_com, accelerationX, ...
                    accelerationY, accelerationPhi);
            end
        end
    end

    methods (Access = private)
        function obj = applyOptions(obj, options)
            if ~isstruct(options) || ~isscalar(options)
                error('ContinuousDynamics_v3:InvalidOptions', ...
                    'Options must be supplied as a scalar structure.');
            end
            names = fieldnames(options);
            allowed = {'GeometryTolerance', 'AdmissibilityTolerance'};
            for i = 1:numel(names)
                if ~any(strcmp(names{i}, allowed))
                    error('ContinuousDynamics_v3:InvalidOptions', ...
                        'Unknown option "%s".', names{i});
                end
                value = options.(names{i});
                if ~(isnumeric(value) && isreal(value) && isscalar(value) ...
                        && isfinite(value) && value > 0)
                    error('ContinuousDynamics_v3:InvalidOptions', ...
                        '%s must be a positive finite scalar.', names{i});
                end
                obj.(names{i}) = double(value);
            end
        end

        function [x, q, p] = validateInputs(obj, x, q, p)
            x = obj.Schema.validateState(x);
            q = obj.Schema.validateMode(q);
            p = obj.Schema.validateParameter(p);
        end

        function [dalphaBack, ddalphaBack] = backConstraintRates( ...
                obj, x, angleIndex, lCom, ddx, ddy, ddphi)
            state = obj.Schema.State;
            alphaBack = x(angleIndex);
            legIndex = find(obj.Schema.Leg.AngleIndices == angleIndex, 1);
            dalphaBack = x(obj.Schema.Leg.RateIndices(legIndex));
            dphi = x(state.dphi);
            dx = x(state.dx);
            dy = x(state.dy);
            phi = x(state.phi);
            y = x(state.y);

            t2 = cos(alphaBack);
            t3 = sin(phi);
            t4 = alphaBack + phi;
            t7 = dalphaBack^2;
            t8 = dphi^2;
            t11 = cos(t4);
            t12 = sin(t4);
            t13 = phi + t4;
            t16 = 2 * t4;

            dalphaBack = -(dx + 2 * dphi * y + dx * cos(t16) ...
                + dy * sin(t16) - dphi * lCom * t3 ...
                - dphi * lCom * sin(alphaBack + t4)) ...
                / (2 * y - 2 * lCom * t3);

            t18 = 3 * t4;
            t14 = sin(t13);
            t15 = cos(t13);
            t17 = alphaBack + t16;
            denominator = -2 * lCom * t14 + 4 * t11 * y ...
                + 2 * lCom * sin(alphaBack);
            if abs(denominator) <= obj.GeometryTolerance
                error('ContinuousDynamics_v3:SingularConstraint', ...
                    'Back-leg stance acceleration constraint is singular.');
            end
            ddalphaBack = -( ...
                3 * ddx * t11 + ddy * t12 + ddx * cos(t18) ...
                + ddy * sin(t18) + lCom * t8 * cos(t17) ...
                - ddphi * lCom * sin(t17) + 8 * dalphaBack * dy * t11 ...
                + 8 * dphi * dy * t11 - ddphi * lCom * t14 ...
                + 4 * ddphi * t11 * y - 4 * lCom * t2 * t7 ...
                - 6 * lCom * t2 * t8 + 4 * lCom * t7 * t15 ...
                + lCom * t8 * t15 + 8 * t7 * t12 * y ...
                + 8 * t8 * t12 * y ...
                - 12 * dalphaBack * dphi * lCom * t2 ...
                + 4 * dalphaBack * dphi * lCom * t15 ...
                + 16 * dalphaBack * dphi * t12 * y) / denominator;
        end

        function [dalphaFront, ddalphaFront] = frontConstraintRates( ...
                obj, x, angleIndex, lCom, ddx, ddy, ddphi)
            state = obj.Schema.State;
            alphaFront = x(angleIndex);
            dphi = x(state.dphi);
            dx = x(state.dx);
            dy = x(state.dy);
            phi = x(state.phi);
            y = x(state.y);

            t2 = cos(phi);
            t3 = sin(phi);
            t4 = alphaFront + phi;
            t6 = lCom - 1;
            t5 = tan(t4);
            t8 = t3 * t6;
            t7 = t5^2;
            t10 = -t8;
            t12 = t2 * t5 * t6;
            t9 = t7 + 1;
            t13 = 1 / t9;
            denominator = t8 - y;
            if abs(denominator) <= obj.GeometryTolerance
                error('ContinuousDynamics_v3:SingularConstraint', ...
                    'Front-leg stance constraint is singular.');
            end

            dalphaFront = (t13 * (dx + dy * t5 ...
                - dphi * (t10 + t12 + t9 * denominator))) / denominator;

            t18 = -2 * t5 * t9 * denominator;
            t19 = dalphaFront * t18;
            t11 = dy * t9;
            ddalphaFront = (t13 * ( ...
                ddx + dphi * (t11 + t19 ...
                    + dphi * (t18 + t2 * t6 + t5 * t8 ...
                        - 2 * t2 * t6 * t9) ...
                    - dalphaFront * t2 * t6 * t9) ...
                - dalphaFront * (-t11 ...
                    + dphi * (t2 * t6 * t9 ...
                        + 2 * t5 * t9 * denominator) ...
                    + 2 * dalphaFront * t5 * t9 * denominator) ...
                + ddy * t5 ...
                - ddphi * (t10 + t12 + t9 * denominator) ...
                + dy * (dalphaFront * t9 + dphi * t9))) / denominator;
        end
    end
end
