classdef ContinuousDynamics_v3
    %CONTINUOUSDYNAMICS_V3 Legacy-compatible 14-state quadruped flow.
    %
    % The contact mode is q=[BL;FL;BR;FR].  Stance leg angles enforce a
    % horizontally fixed massless foot; swing legs follow the production v2
    % equations.  No energy-conservation assumption is used by this component.

    methods
        function [dxdt, diagnostics] = evaluate(obj, t, x, q, p) %#ok<INUSD>
            [x, q, p] = ContinuousDynamics_v3.validateInputs(x, q, p);

            k = p(1);
            ks = p(2);
            J = p(3);
            restLength = p(4);
            % p(5), the documented neutral swing angle, is intentionally
            % unused: production v2 restores each swing angle toward zero.
            lb = p(6);
            kr = p(7);

            kb = 2 * k / (1 + 1 / kr);
            kf = 2 * k / (1 + kr);

            velocityX = x(2);
            y = x(3);
            velocityY = x(4);
            phi = x(5);
            dphi = x(6);
            alpha = x([7, 9, 11, 13]);
            storedDalpha = x([8, 10, 12, 14]);

            backHipHeight = y - lb * sin(phi);
            frontHipHeight = y + (1 - lb) * sin(phi);
            hipHeight = [backHipHeight; frontHipHeight; ...
                backHipHeight; frontHipHeight];
            theta = phi + alpha;
            stiffness = [kb; kf; kb; kf];

            force = zeros(4, 1);
            for leg = 1:4
                if q(leg)
                    if cos(theta(leg)) == 0
                        error('ContinuousDynamics_v3:SingularLegGeometry', ...
                            'Stance leg %d has cos(phi+alpha)=0.', leg);
                    end
                    force(leg) = (restLength ...
                        - hipHeight(leg) / cos(theta(leg))) * stiffness(leg);
                end
            end

            forceX = -sum(force .* sin(theta));
            forceY = sum(force .* cos(theta));
            torque = -force(1) * lb * cos(alpha(1)) ...
                + force(2) * (1 - lb) * cos(alpha(2)) ...
                - force(3) * lb * cos(alpha(3)) ...
                + force(4) * (1 - lb) * cos(alpha(4));

            accelerationX = forceX;
            accelerationY = forceY - 1;
            accelerationPhi = torque / J;

            outputDalpha = storedDalpha;
            accelerationAlpha = zeros(4, 1);
            angleIndices = [7, 9, 11, 13];

            for leg = 1:4
                if q(leg)
                    if leg == 1 || leg == 3
                        [outputDalpha(leg), accelerationAlpha(leg)] = ...
                            obj.backConstraintRates(x, angleIndices(leg), lb, ...
                            accelerationX, accelerationY, accelerationPhi);
                    else
                        [outputDalpha(leg), accelerationAlpha(leg)] = ...
                            obj.frontConstraintRates(x, angleIndices(leg), lb, ...
                            accelerationX, accelerationY, accelerationPhi);
                    end
                elseif leg == 1 || leg == 3
                    accelerationAlpha(leg) = -( ...
                        torque / J ...
                        - torque * lb * sin(alpha(leg)) / (J * restLength) ...
                        + forceX * cos(alpha(leg) + phi) / restLength ...
                        + forceY * sin(alpha(leg) + phi) / restLength ...
                        + alpha(leg) * ks / restLength^2 ...
                        + dphi^2 * lb * cos(alpha(leg)) / restLength);
                else
                    accelerationAlpha(leg) = -( ...
                        torque / J ...
                        + torque * (1 - lb) * sin(alpha(leg)) ...
                            / (J * restLength) ...
                        + forceX * cos(alpha(leg) + phi) / restLength ...
                        + forceY * sin(alpha(leg) + phi) / restLength ...
                        + alpha(leg) * ks / restLength^2 ...
                        - dphi^2 * (1 - lb) * cos(alpha(leg)) / restLength);
                end
            end

            dxdt = [ ...
                velocityX; accelerationX; ...
                velocityY; accelerationY; ...
                dphi; accelerationPhi; ...
                outputDalpha(1); accelerationAlpha(1); ...
                outputDalpha(2); accelerationAlpha(2); ...
                outputDalpha(3); accelerationAlpha(3); ...
                outputDalpha(4); accelerationAlpha(4)];

            if any(~isfinite(dxdt))
                error('ContinuousDynamics_v3:NonfiniteFlow', ...
                    'Quadruped flow became nonfinite.');
            end

            if nargout > 1
                diagnostics = struct( ...
                    'leg_force', force, ...
                    'force_x', forceX, ...
                    'force_y', forceY, ...
                    'torque', torque, ...
                    'hip_height', hipHeight, ...
                    'leg_length', hipHeight ./ cos(theta), ...
                    'projected_leg_rate', outputDalpha);
            end
        end

        function [dalpha, ddalpha] = stanceConstraintRates( ...
                obj, x, legIndex, p, accelerationX, accelerationY, accelerationPhi)
            [x, ~, p] = ContinuousDynamics_v3.validateInputs( ...
                x, false(4, 1), p);
            if ~(isnumeric(legIndex) && isscalar(legIndex) ...
                    && isfinite(legIndex) && legIndex == fix(legIndex) ...
                    && legIndex >= 1 && legIndex <= 4)
                error('ContinuousDynamics_v3:InvalidLeg', ...
                    'Leg index must be an integer from 1 through 4.');
            end
            angleIndices = [7, 9, 11, 13];
            if legIndex == 1 || legIndex == 3
                [dalpha, ddalpha] = obj.backConstraintRates( ...
                    x, angleIndices(legIndex), p(6), accelerationX, ...
                    accelerationY, accelerationPhi);
            else
                [dalpha, ddalpha] = obj.frontConstraintRates( ...
                    x, angleIndices(legIndex), p(6), accelerationX, ...
                    accelerationY, accelerationPhi);
            end
        end
    end

    methods (Access = private)
        function [dalphaB, ddalphaB] = backConstraintRates( ...
                ~, x, angleIndex, lb, ddx, ddy, ddphi)
            alphaB = x(angleIndex);
            dalphaB = x(angleIndex + 1);
            dphi = x(6);
            dx = x(2);
            dy = x(4);
            phi = x(5);
            y = x(3);

            t2 = cos(alphaB);
            t3 = sin(phi);
            t4 = alphaB + phi;
            t7 = dalphaB^2;
            t8 = dphi^2;
            t11 = cos(t4);
            t12 = sin(t4);
            t13 = phi + t4;
            t16 = 2 * t4;

            dalphaB = -(dx + 2 * dphi * y + dx * cos(t16) ...
                + dy * sin(t16) - dphi * lb * t3 ...
                - dphi * lb * sin(alphaB + t4)) ...
                / (2 * y - 2 * lb * t3);

            t18 = 3 * t4;
            t14 = sin(t13);
            t15 = cos(t13);
            t17 = alphaB + t16;
            denominator = -2 * lb * t14 + 4 * t11 * y ...
                + 2 * lb * sin(alphaB);
            ddalphaB = -( ...
                3 * ddx * t11 + ddy * t12 + ddx * cos(t18) ...
                + ddy * sin(t18) + lb * t8 * cos(t17) ...
                - ddphi * lb * sin(t17) + 8 * dalphaB * dy * t11 ...
                + 8 * dphi * dy * t11 - ddphi * lb * t14 ...
                + 4 * ddphi * t11 * y - 4 * lb * t2 * t7 ...
                - 6 * lb * t2 * t8 + 4 * lb * t7 * t15 ...
                + lb * t8 * t15 + 8 * t7 * t12 * y ...
                + 8 * t8 * t12 * y - 12 * dalphaB * dphi * lb * t2 ...
                + 4 * dalphaB * dphi * lb * t15 ...
                + 16 * dalphaB * dphi * t12 * y) / denominator;
        end

        function [dalphaF, ddalphaF] = frontConstraintRates( ...
                ~, x, angleIndex, lb, ddx, ddy, ddphi)
            alphaF = x(angleIndex);
            dalphaF = x(angleIndex + 1); %#ok<NASGU>
            dphi = x(6);
            dx = x(2);
            dy = x(4);
            phi = x(5);
            y = x(3);

            t2 = cos(phi);
            t3 = sin(phi);
            t4 = alphaF + phi;
            t6 = lb - 1;
            t5 = tan(t4);
            t8 = t3 * t6;
            t7 = t5^2;
            t10 = -t8;
            t12 = t2 * t5 * t6;
            t9 = t7 + 1;
            t13 = 1 / t9;

            dalphaF = (t13 * (dx + dy * t5 ...
                - dphi * (t10 + t12 + t9 * (t8 - y)))) / (t8 - y);

            t18 = -2 * t5 * t9 * (t8 - y);
            t19 = dalphaF * t18;
            t11 = dy * t9;
            ddalphaF = (t13 * ( ...
                ddx + dphi * (t11 + t19 ...
                    + dphi * (t18 + t2 * t6 + t5 * t8 ...
                        - 2 * t2 * t6 * t9) ...
                    - dalphaF * t2 * t6 * t9) ...
                - dalphaF * (-t11 ...
                    + dphi * (t2 * t6 * t9 ...
                        + 2 * t5 * t9 * (t8 - y)) ...
                    + 2 * dalphaF * t5 * t9 * (t8 - y)) ...
                + ddy * t5 ...
                - ddphi * (t10 + t12 + t9 * (t8 - y)) ...
                + dy * (dalphaF * t9 + dphi * t9))) / (t8 - y);
        end
    end

    methods (Static)
        function [x, q, p] = validateInputs(x, q, p)
            if ~(isnumeric(x) && isreal(x) && isvector(x) ...
                    && numel(x) == 14 && all(isfinite(x(:))))
                error('ContinuousDynamics_v3:InvalidState', ...
                    'Quadruped state must be a finite real 14-vector.');
            end
            if ~(isnumeric(p) && isreal(p) && isvector(p) && numel(p) == 7)
                error('ContinuousDynamics_v3:InvalidParameter', ...
                    'Quadruped parameter must be a real 7-vector.');
            end
            p = double(p(:));
            if any(~isfinite(p([1, 2, 4, 5, 6, 7]))) ...
                    || ~(isfinite(p(3)) || isinf(p(3))) ...
                    || p(1) <= 0 || p(2) < 0 || p(3) <= 0 ...
                    || p(4) <= 0 || p(6) <= 0 || p(6) >= 1 || p(7) <= 0
                error('ContinuousDynamics_v3:InvalidParameter', ...
                    ['Parameters require k>0, ks>=0, J>0 (finite or Inf), ' ...
                    'l>0, finite osa, 0<lb<1, and kr>0.']);
            end
            x = double(x(:));
            q = ModeTransition_v3.validateModeVector(q);
        end
    end
end
