function [legVertices, legFaces] = ComputeLegGraphics_v3( ...
        hipPosition, legLength, restLength, absoluteAngle)
%COMPUTELEGGRAPHICS_V3 Patch geometry for one telescoping SLIP leg.
%   Adapted from ComputeLegGraphics.m in the v2 graphics toolbox by the
%   DLARlab SLIP Model Zoo authors.  The endpoint is constrained to the
%   physical foot implied by LEGLENGTH and ABSOLUTEANGLE.

if ~(isnumeric(hipPosition) && numel(hipPosition) == 2 && ...
        all(isfinite(hipPosition(:))))
    error('ComputeLegGraphics_v3:InvalidHip', ...
        'hipPosition must be a finite two-vector.');
end
if ~(isscalar(legLength) && isfinite(legLength) && legLength > 0 && ...
        isscalar(restLength) && isfinite(restLength) && restLength > 0 && ...
        isscalar(absoluteAngle) && isfinite(absoluteAngle))
    error('ComputeLegGraphics_v3:InvalidGeometry', ...
        'Leg lengths must be positive and all geometry inputs finite.');
end

% A narrow spring ribbon preserves the v2 visual language while keeping
% every vertex tied to the actual current length.
nCoils = 7;
centerlineY = linspace(0, -0.62 * legLength, 2 * nCoils + 1).';
zigzagX = zeros(size(centerlineY));
zigzagX(2:end-1) = 0.045 * (-1).^(1:numel(zigzagX)-2);
springLocal = [zigzagX, centerlineY];

shaftWidth = min(0.055, 0.08 * restLength);
shaftLocal = [ ...
    -shaftWidth, -0.58 * legLength; ...
     shaftWidth, -0.58 * legLength; ...
     shaftWidth, -legLength; ...
    -shaftWidth, -legLength];

rotation = [cos(absoluteAngle), -sin(absoluteAngle); ...
            sin(absoluteAngle),  cos(absoluteAngle)];
transform = @(v) (rotation * v.').'+reshape(hipPosition, 1, 2);
spring = transform(springLocal);
shaft = transform(shaftLocal);

legVertices = struct( ...
    'Spring', spring, ...
    'Shaft', shaft, ...
    'Foot', shaft([3, 4], :));
legFaces = struct( ...
    'Spring', [(1:size(spring, 1)-1).', (2:size(spring, 1)).'], ...
    'Shaft', 1:4, ...
    'Foot', 1:2);
end
