function study = QuadrupedalContinuationStudy_v3(options)
%QUADRUPEDALCONTINUATIONSTUDY_V3 Reproducible Round-4 production study.
%   STUDY = QUADRUPEDALCONTINUATIONSTUDY_V3() uses only the event-driven
%   v3 map.  Event times and gait labels are observations, never unknowns.
%   The production seed has structural left/right simultaneous clusters;
%   root and Floquet derivatives are therefore formed on the left/right
%   invariant section chart and are labelled as symmetry restricted.
%
%   The saved artifact contains numerical summaries rather than MATLAB
%   handle objects, so it can be audited without reconstructing a session.

    if nargin < 1 || isempty(options)
        options = struct();
    end
    v3Root = fileparts(fileparts(mfilename('fullpath')));
    addStudyPaths(v3Root);
    defaults = defaultOptions(v3Root);
    options = mergeOptions(defaults, options);

    if options.ReuseSaved && isfile(options.SaveFile)
        saved = load(options.SaveFile, 'study');
        if isfield(saved, 'study')
            study = saved.study;
            if options.ResumePhysicalSearch
                study = resumePhysicalSearch(study, options);
            end
            return
        end
    end

    totalTimer = tic;
    study = struct();
    study.study_name = 'Round4 actual quadruped production validation';
    study.executed_at = char(datetime('now', 'TimeZone', 'local', ...
        'Format', 'yyyy-MM-dd HH:mm:ss Z'));
    study.matlab_version = version;
    study.platform = computer;
    study.options = options;
    study.model = 'Quadrupedal_Dynamics_v3';
    study.return_policy = 'EventCycleReturnPolicy_v3';
    study.prescribed_event_times = false;
    study.prescribed_gait_label = false;

    [baseOrbit, baseReport, framework] = QuadrupedalExample_v3(struct( ...
        'FixtureFile', options.FixtureFile, ...
        'FixtureColumn', options.FixtureColumn, ...
        'LegacyParameterPolicy', options.LegacyParameterPolicy, ...
        'Refine', false));
    schema = framework.schema;
    problem = framework.residual;
    baseUnknown = baseReport.converted_seed(:);
    baseParameter = baseOrbit.parameter(:);
    baseMode = baseOrbit.initial_mode;
    activeIndex = schema.parameterIndex(options.ActiveParameter);
    reducedBase = packLeftRightUnknown(baseUnknown);

    study.schema_metadata = schema.metadata();
    study.base = orbitSummary(baseOrbit, baseReport.residual_norm);
    study.base.fixture_path = baseReport.fixture_path;
    study.base.unknown = baseUnknown;
    study.base.reduced_unknown = reducedBase;
    study.base.parameter = baseParameter;
    study.base.mode = baseMode;
    study.base.is_event_discovered = true;
    study.base.has_structural_simultaneous_cluster = ...
        any(cellfun(@(members) numel(members) > 1, ...
        baseOrbit.event_cluster_members));
    saveStudyCheckpoint(study, options, 'base-constructed');

    reducedResidual = @(z, p, q, context) ...
        evaluateLeftRightResidual(z, p, q, problem, context);

    seedTimer = tic;
    study.asymmetric_seed_preparation = prepareAsymmetricSeed( ...
        reducedResidual, reducedBase, baseParameter, baseMode, ...
        activeIndex, options, problem);
    study.asymmetric_seed_preparation.elapsed_seconds = toc(seedTimer);
    saveStudyCheckpoint(study, options, 'asymmetric-seed-prepared');
    [validationSeed, validationParameter, validationMode] = ...
        selectPreparedSeed(study.asymmetric_seed_preparation, ...
        reducedBase, baseParameter, baseMode);

    simpleTimer = tic;
    study.simple_continuation = runSimpleContinuation( ...
        reducedResidual, validationSeed, validationParameter, ...
        validationMode, ...
        activeIndex, options, problem);
    study.simple_continuation.elapsed_seconds = toc(simpleTimer);
    saveStudyCheckpoint(study, options, 'simple-continuation-complete');

    [referenceReduced, referenceParameter, referenceMode] = ...
        selectAsymmetricReference(study.simple_continuation, ...
        validationSeed, validationParameter, validationMode, activeIndex);

    rootTimer = tic;
    study.default_hybrid_root = runDefaultHybridCorrection( ...
        reducedResidual, referenceReduced, referenceParameter, ...
        referenceMode, problem, options);
    study.default_hybrid_root.elapsed_seconds = toc(rootTimer);
    saveStudyCheckpoint(study, options, 'default-hybrid-root-complete');
    if study.default_hybrid_root.converged
        referenceReduced = study.default_hybrid_root.solution(:);
    end

    pseudoTimer = tic;
    study.pseudo_arclength = runPseudoArclength( ...
        reducedResidual, referenceReduced, referenceParameter, ...
        referenceMode, activeIndex, options, problem);
    study.pseudo_arclength.elapsed_seconds = toc(pseudoTimer);
    saveStudyCheckpoint(study, options, 'pseudo-arclength-complete');

    referenceUnknown = unpackLeftRightUnknown(referenceReduced);
    [~, referenceDetails] = problem.evaluateWithInfo( ...
        referenceUnknown, referenceParameter, referenceMode);
    referenceOrbit = problem.createOrbit(referenceUnknown, ...
        referenceParameter, referenceMode, referenceDetails);

    floquetTimer = tic;
    if options.RunFloquet
        study.floquet = runFloquetGridStudy( ...
            framework.map, referenceOrbit, schema, framework.simulator, ...
            options.FloquetStepGrids, options);
    else
        study.floquet = struct('attempted', false, 'status', 'not-run', ...
            'reason', 'RunFloquet=false');
    end
    study.floquet.elapsed_seconds = toc(floquetTimer);
    saveStudyCheckpoint(study, options, 'floquet-grid-study-complete');

    searchTimer = tic;
    if options.RunPhysicalSearch
        study.physical_search = runPhysicalSearch( ...
            problem, baseUnknown, baseParameter, baseMode, schema, options);
    else
        study.physical_search = emptyPhysicalSearch('RunPhysicalSearch=false');
    end
    study.physical_search.elapsed_seconds = toc(searchTimer);
    saveStudyCheckpoint(study, options, 'physical-search-complete');

    study.branch_switch_candidate_search = ...
        assessPhysicalBranchSwitchCandidates(study.floquet, ...
        referenceParameter(activeIndex), options);
    study.reference_orbit = orbitSummary(referenceOrbit, ...
        norm(referenceDetails.periodic_residual, inf));
    study.reference_orbit.parameter = referenceParameter;
    study.reference_orbit.mode = referenceMode;
    study.reference_orbit.unknown = referenceUnknown;
    study.total_elapsed_seconds = toc(totalTimer);
    study.completed = true;
    study.requirements = requirementSummary(study, options);

    saveStudyCheckpoint(study, options, 'complete');
end

function result = prepareAsymmetricSeed(residual, z0, p0, q0, ...
        activeIndex, options, problem)
    % This secant homotopy prepares a point safely separated from the
    % front/back simultaneous-cluster boundary.  Its points are explicitly
    % excluded from the validated production continuation count.
    result = struct('attempted', true, 'status', 'failed', ...
        'counted_as_validated_continuation', false, ...
        'derivative_model', 'forward-secant-seed-preparation-only', ...
        'accepted_count', 0, 'failure_count', 0, ...
        'requested_values', [], 'points', struct([]), ...
        'failures', struct([]), 'reason', '');
    values = p0(activeIndex) + linspace(0, ...
        options.SeedParameterOffset, options.SeedPreparationPointCount);
    result.requested_values = values;
    fd = FiniteDifferenceJacobian_v3(struct( ...
        'Method', 'forward', 'RelativeStep', options.SecantRelativeStep, ...
        'FailurePolicy', 'nan'));
    solver = RootSolver_v3(struct( ...
        'Jacobian', fd, 'Algorithm', 'newton', ...
        'FunctionTolerance', options.RootFunctionTolerance, ...
        'ResidualAcceptanceTolerance', options.RootAcceptanceTolerance, ...
        'MaxIterations', options.RootMaxIterations, ...
        'MaxFunctionEvaluations', options.RootMaxFunctionEvaluations));
    continuation = NumericalContinuation1D_v3(struct( ...
        'RootSolver', solver, 'ActiveParameterIndex', activeIndex, ...
        'StopOnFailure', true));
    try
        branch = continuation.run(residual, z0, p0, q0, values);
        result.accepted_count = branch.count;
        result.failure_count = numel(branch.failures);
        result.points = summarizeContinuationPoints( ...
            branch.points, problem, true);
        result.failures = summarizeContinuationPoints( ...
            branch.failures, problem, false);
        if branch.count == numel(values) && branch.success
            result.status = 'prepared';
        else
            result.reason = sprintf('Prepared %d of %d seed points.', ...
                branch.count, numel(values));
        end
    catch exception
        result.reason = exceptionReport(exception);
    end
end

function [z, p, q] = selectPreparedSeed(preparation, z0, p0, q0)
    z = z0;
    p = p0;
    q = q0;
    if isfield(preparation, 'points') && ~isempty(preparation.points)
        accepted = find([preparation.points.converged], 1, 'last');
        if ~isempty(accepted)
            point = preparation.points(accepted);
            z = point.reduced_unknown(:);
            p = point.parameter(:);
            q = point.mode;
        end
    end
end

function result = runSimpleContinuation(residual, z0, p0, q0, ...
        activeIndex, options, problem)
    result = struct('attempted', true, 'status', 'failed', ...
        'derivative_model', ...
            'left-right-symmetry-restricted-hybrid-classical', ...
        'active_parameter', options.ActiveParameter, ...
        'active_parameter_index', activeIndex, 'requested_values', [], ...
        'accepted_count', 0, 'failure_count', 0, 'points', struct([]), ...
        'failures', struct([]), 'topology_compatible', false, ...
        'cyclic_signatures', {{}}, 'section_signatures', {{}}, ...
        'cluster_signatures', {{}}, 'reason', '');
    values = p0(activeIndex) + linspace( ...
        options.SimpleParameterOffset(1), ...
        options.SimpleParameterOffset(2), options.SimplePointCount);
    result.requested_values = values;
    fd = continuationHybridJacobian(options);
    solver = RootSolver_v3(struct( ...
        'Jacobian', fd, 'Algorithm', 'newton', ...
        'FunctionTolerance', options.RootFunctionTolerance, ...
        'ResidualAcceptanceTolerance', options.RootAcceptanceTolerance, ...
        'MaxIterations', options.RootMaxIterations, ...
        'MaxFunctionEvaluations', options.RootMaxFunctionEvaluations));
    continuation = NumericalContinuation1D_v3(struct( ...
        'RootSolver', solver, 'ActiveParameterIndex', activeIndex, ...
        'StopOnFailure', true));
    try
        branch = continuation.run(residual, z0, p0, q0, values);
        result.accepted_count = branch.count;
        result.failure_count = numel(branch.failures);
        result.points = summarizeContinuationPoints( ...
            branch.points, problem, true);
        result.failures = summarizeContinuationPoints( ...
            branch.failures, problem, false);
        result = attachTopologyAudit(result);
        if branch.count >= options.SimplePointCount && branch.success && ...
                result.topology_compatible
            result.status = 'passed';
        else
            result.reason = sprintf( ...
                ['Accepted %d of %d requested points; topology ', ...
                 'compatible=%d.'], branch.count, ...
                options.SimplePointCount, result.topology_compatible);
        end
    catch exception
        result.reason = exceptionReport(exception);
    end
end

function result = runDefaultHybridCorrection(residual, zReference, ...
        pReference, qReference, problem, options)
    result = struct('attempted', true, 'status', 'failed', ...
        'converged', false, ...
        'derivative_model', ...
            'left-right-symmetry-restricted-hybrid-classical', ...
        'jacobian_class', 'HybridFiniteDifferenceJacobian_v3', ...
        'initial_guess', [], 'solution', [], 'initial_residual_norm', NaN, ...
        'final_residual_norm', Inf, 'map_evaluations', 0, ...
        'function_evaluations', 0, 'cache_hits', 0, ...
        'jacobian_evaluations', 0, 'accepted_newton_iterations', 0, ...
        'invalid_trial_count', 0, 'selected_steps', [], ...
        'estimated_column_errors', [], 'per_column_reliability', [], ...
        'event_cluster_signature', '', 'section_relative_signature', '', ...
        'cyclic_signature', '', 'mode_candidates', {{}}, 'reason', '');
    result.constructed_without_jacobian_override = true;
    perturbation = options.RootCorrectionPerturbation(:);
    if isscalar(perturbation)
        perturbation = perturbation .* defaultRootDirection(numel(zReference));
    end
    if numel(perturbation) ~= numel(zReference)
        error('QuadrupedalContinuationStudy_v3:RootPerturbation', ...
            'RootCorrectionPerturbation must be scalar or match the reduced chart.');
    end
    initialGuess = zReference(:) + perturbation;
    result.initial_guess = initialGuess;
    try
        [r0, initialInfo] = residual( ...
            initialGuess, pReference, qReference, struct());
        result.initial_residual_norm = norm(r0, inf);
        % Deliberately omit the Jacobian option.  This is the production
        % regression for RootSolver_v3's default hybrid differentiator.
        solver = RootSolver_v3(struct( ...
            'Algorithm', 'newton', ...
            'FunctionTolerance', options.RootFunctionTolerance, ...
            'ResidualAcceptanceTolerance', options.RootAcceptanceTolerance, ...
            'MaxIterations', options.RootMaxIterations, ...
            'MaxFunctionEvaluations', options.RootMaxFunctionEvaluations));
        [solution, solveInfo] = solver.solve( ...
            residual, initialGuess, pReference, qReference);
        result.solution = solution;
        result.converged = solveInfo.converged;
        result.status = ternary(solveInfo.converged, 'passed', 'failed');
        result.final_residual_norm = solveInfo.residualNorm;
        result.map_evaluations = solveInfo.mapEvaluationCount;
        result.function_evaluations = solveInfo.functionEvaluationCount;
        result.cache_hits = solveInfo.cacheHitCount;
        result.jacobian_evaluations = solveInfo.jacobianEvaluationCount;
        result.mode_candidates = solveInfo.candidateModes;
        result.invalid_trial_count = solveInfo.invalidEvaluationCount;
        output = memberOr(solveInfo, 'output', struct());
        result.accepted_newton_iterations = memberOr( ...
            output, 'acceptedIterations', 0);
        result.invalid_trial_count = max(result.invalid_trial_count, ...
            memberOr(output, 'invalidTrialCount', 0));
        jacobianInfo = memberOr(output, 'jacobianInfo', struct());
        result.selected_steps = memberOr(jacobianInfo, ...
            'selectedSteps', []);
        result.estimated_column_errors = memberOr(jacobianInfo, ...
            'estimatedErrors', []);
        result.per_column_reliability = memberOr(jacobianInfo, ...
            'perColumnReliability', []);
        result.jacobian_class = class(solver.Jacobian);
        if isstruct(initialInfo)
            result.initial_event_cluster_signature = memberOr( ...
                initialInfo, 'event_cluster_signature', '');
        end
        if isstruct(solveInfo.evaluationInfo)
            details = solveInfo.evaluationInfo;
            result.event_cluster_signature = memberOr( ...
                details, 'event_cluster_signature', '');
            mapInfo = memberOr(details, 'map_info', struct());
            result.section_relative_signature = memberOr(mapInfo, ...
                'section_relative_event_signature', memberOr(details, ...
                'physical_section_relative_signature', ''));
            result.cyclic_signature = memberOr(mapInfo, ...
                'cyclic_event_signature', memberOr(details, ...
                'physical_cyclic_event_signature', ''));
        end
        if ~solveInfo.converged
            result.reason = solveInfo.message;
        else
            unknown = unpackLeftRightUnknown(solution);
            [residualCheck, details] = problem.evaluateWithInfo( ...
                unknown, pReference, solveInfo.mode);
            result.full_residual_norm = norm(residualCheck, inf);
            result.cycle_complete = details.cycle_complete;
            result.physically_admissible = details.admissible;
        end
    catch exception
        result.reason = exceptionReport(exception);
    end
end

function result = runPseudoArclength(residual, z0, p0, q0, ...
        activeIndex, options, problem)
    result = struct('attempted', true, 'status', 'failed', ...
        'derivative_model', ...
            'left-right-symmetry-restricted-hybrid-classical', ...
        'active_parameter', options.ActiveParameter, ...
        'active_parameter_index', activeIndex, 'accepted_count', 0, ...
        'failure_count', 0, 'points', struct([]), ...
        'failures', struct([]), 'termination_reason', '', ...
        'topology_compatible', false, 'cyclic_signatures', {{}}, ...
        'section_signatures', {{}}, 'cluster_signatures', {{}}, ...
        'reason', '');
    fd = continuationHybridJacobian(options);
    solver = RootSolver_v3(struct( ...
        'Jacobian', fd, 'Algorithm', 'newton', ...
        'FunctionTolerance', options.RootFunctionTolerance, ...
        'ResidualAcceptanceTolerance', options.RootAcceptanceTolerance, ...
        'MaxIterations', options.RootMaxIterations, ...
        'MaxFunctionEvaluations', options.RootMaxFunctionEvaluations));
    continuation = PseudoArclengthContinuation_v3(struct( ...
        'RootSolver', solver, 'Jacobian', fd, ...
        'ActiveParameterIndex', activeIndex, ...
        'StepSize', options.PseudoStepSize, ...
        'MinimumStepSize', options.PseudoMinimumStepSize, ...
        'MaximumStepSize', options.PseudoMaximumStepSize, ...
        'MaxPoints', options.PseudoPointCount, ...
        'ParameterBounds', p0(activeIndex) + options.PseudoParameterBounds, ...
        'InitialDirection', sign(options.PseudoStepSize), ...
        'ReuseCorrectorJacobian', false));
    try
        branch = continuation.run(residual, z0, p0, q0);
        result.accepted_count = branch.count;
        result.failure_count = numel(branch.failures);
        result.termination_reason = branch.terminationReason;
        result.points = summarizeContinuationPoints( ...
            branch.points, problem, true);
        result.failures = summarizeContinuationPoints( ...
            branch.failures, problem, false);
        result = attachTopologyAudit(result);
        if branch.count >= options.PseudoPointCount && ...
                result.topology_compatible
            result.status = 'passed';
        else
            result.reason = sprintf( ...
                ['Accepted %d of %d requested points (%s); topology ', ...
                 'compatible=%d.'], ...
                branch.count, options.PseudoPointCount, ...
                branch.terminationReason, result.topology_compatible);
        end
    catch exception
        result.reason = exceptionReport(exception);
    end
end

function result = runFloquetGridStudy(map, orbit, schema, simulator, ...
        stepGrids, options)
    result = struct('attempted', true, 'status', 'failed', ...
        'derivative_model', 'left-right-symmetry-restricted-classical', ...
        'step_grids', {stepGrids}, 'grid_results', struct([]), ...
        'matrix_differences', [], 'matched_multiplier_differences', [], ...
        'converged', false, 'reason', '');
    subspace = SymmetrySubspace_v3.quadrupedSectionTangent(schema);
    entries = repmat(emptyFloquetGrid(), 1, numel(stepGrids));
    rawMatrices = cell(1, numel(stepGrids));
    rawMultipliers = cell(1, numel(stepGrids));
    for index = 1:numel(stepGrids)
        grid = stepGrids{index};
        try
            fd = HybridFiniteDifferenceJacobian_v3(struct( ...
                'RelativeCandidateSteps', grid, ...
                'MaximumRelativeError', options.HybridMaximumRelativeError, ...
                'RequireCompatibleCyclicSignature', true, ...
                'RequireCompatibleSectionSignature', true, ...
                'FailurePolicy', 'nan'));
            baseAnalyzer = FloquetAnalysis_v3(struct( ...
                'Jacobian', fd, 'ComputeAmbientJacobian', false, ...
                'RequireCompatibleSectionSignature', true, ...
                'RequireMatchingEventSignature', true));
            analyzer = SymmetryRestrictedFloquet_v3(subspace, struct( ...
                'Analyzer', baseAnalyzer, ...
                'BlockName', 'left-right-invariant-section', ...
                'RequireClusterPreservation', true));
            value = analyzer.analyze(map, orbit.initial_state, ...
                orbit.initial_mode, orbit.parameter);
            entries(index) = summarizeFloquet(value, grid, simulator);
            rawMatrices{index} = value.poincareMatrix;
            rawMultipliers{index} = value.multipliers;
        catch exception
            entries(index).step_grid = grid;
            entries(index).reason = exceptionReport(exception);
        end
    end
    result.grid_results = entries;
    differences = NaN(1, max(0, numel(entries) - 1));
    multiplierDifferences = differences;
    for index = 1:numel(differences)
        if ~isempty(rawMatrices{index}) && ~isempty(rawMatrices{index + 1})
            differences(index) = norm( ...
                rawMatrices{index} - rawMatrices{index + 1}, 'fro');
            multiplierDifferences(index) = matchedMultiplierDistance( ...
                rawMultipliers{index}, rawMultipliers{index + 1});
        end
    end
    result.matrix_differences = differences;
    result.matched_multiplier_differences = multiplierDifferences;
    reliable = [entries.reliable];
    finiteComparisons = all(isfinite(differences)) && ...
        all(isfinite(multiplierDifferences));
    fineMatrix = isempty(differences) || ...
        differences(end) <= options.FloquetMatrixConvergenceTolerance;
    fineMultipliers = isempty(multiplierDifferences) || ...
        multiplierDifferences(end) <= ...
        options.FloquetMultiplierConvergenceTolerance;
    result.converged = all(reliable) && finiteComparisons && ...
        fineMatrix && fineMultipliers;
    if result.converged
        result.status = 'passed';
    else
        result.reason = sprintf( ...
            'reliable=%s, matrix differences=%s, multiplier differences=%s', ...
            mat2str(reliable), mat2str(differences, 5), ...
            mat2str(multiplierDifferences, 5));
    end
end

function study = resumePhysicalSearch(study, options)
    timer = tic;
    [~, ~, framework] = QuadrupedalExample_v3(struct( ...
        'FixtureFile', options.FixtureFile, ...
        'FixtureColumn', options.FixtureColumn, ...
        'LegacyParameterPolicy', options.LegacyParameterPolicy, ...
        'Refine', false));
    reference = study.reference_orbit;
    study.physical_search = runPhysicalSearch( ...
        framework.residual, reference.unknown, reference.parameter, ...
        reference.mode, framework.schema, options);
    study.physical_search.elapsed_seconds = toc(timer);
    study.requirements = requirementSummary(study, options);
    study.total_elapsed_seconds = study.total_elapsed_seconds + ...
        study.physical_search.elapsed_seconds;
    saveStudyCheckpoint(study, options, 'physical-search-resumed');
end

function search = runPhysicalSearch(problem, u0, p0, q0, schema, options)
    search = emptyPhysicalSearch('');
    search.attempted = true;
    search.status = 'completed-no-requested-case-found';
    definitions = physicalSearchDefinitions(p0, schema, options);
    search.parameter_ranges = definitions;
    search.seed_unknown = u0;
    search.seed_parameter = p0;
    search.seed_mode = q0;
    search.derivative_model = ...
        'topology-aware-unrestricted-hybrid-classical-or-rejected';
    search.outcomes = repmat(struct('parameter_name', '', ...
        'requested_values', [], 'accepted_count', 0, 'failure_count', 0, ...
        'points', struct([]), 'failures', struct([]), 'reason', ''), ...
        1, numel(definitions));

    fd = continuationHybridJacobian(options);
    solver = RootSolver_v3(struct( ...
        'Jacobian', fd, 'Algorithm', 'newton', ...
        'FunctionTolerance', options.RootFunctionTolerance, ...
        'ResidualAcceptanceTolerance', options.RootAcceptanceTolerance, ...
        'MaxIterations', options.SearchMaxIterations, ...
        'MaxFunctionEvaluations', options.RootMaxFunctionEvaluations));
    searchResidual = fullClusterResidualInterface(problem);
    observations = struct([]);
    for definitionIndex = 1:numel(definitions)
        definition = definitions(definitionIndex);
        continuation = NumericalContinuation1D_v3(struct( ...
            'RootSolver', solver, ...
            'ActiveParameterIndex', definition.parameter_index, ...
            'StopOnFailure', false));
        outcome = search.outcomes(definitionIndex);
        outcome.parameter_name = definition.parameter_name;
        outcome.requested_values = definition.values;
        try
            branch = continuation.run(searchResidual, u0, p0, q0, ...
                definition.values);
            outcome.accepted_count = branch.count;
            outcome.failure_count = numel(branch.failures);
            outcome.points = summarizeContinuationPoints( ...
                branch.points, problem, true);
            outcome.failures = summarizeContinuationPoints( ...
                branch.failures, problem, false);
            observations = [observations, outcome.points]; %#ok<AGROW>
        catch exception
            outcome.reason = exceptionReport(exception);
        end
        search.outcomes(definitionIndex) = outcome;
    end
    search.observations = observations;
    search.accepted_orbit_count = numel(observations);
    search.rejection_count = sum([search.outcomes.failure_count]);
    search.rejection_causes = collectRejectionCauses(search.outcomes);
    search.non_simultaneous_orbit_search = runNonSimultaneousSearch( ...
        searchResidual, problem, u0, p0, q0, options);
    search.found_non_simultaneous_orbit = ...
        search.non_simultaneous_orbit_search.found;

    search.grounded_apex = firstObservation(observations, ...
        @(point) point.converged && any(logical(point.mode(:))));
    search.multiple_apex = firstObservation(observations, ...
        @(point) point.converged && point.candidate_apex_count >= 2 && ...
            point.accepted_apex_index >= 2);
    search.section_mode_transition = detectSectionModeTransition( ...
        search.outcomes, options.SectionCoincidenceTolerance);
    search.found_grounded_apex = ~isempty(search.grounded_apex);
    search.multiple_apex_policy_comparison = struct( ...
        'attempted', false, 'validated', false, ...
        'first_return_is_intermediate', false, ...
        'event_cycle_returns_full_cycle', false, ...
        'reason', 'No validated multiple-apex candidate was found.');
    if ~isempty(search.multiple_apex)
        search.multiple_apex_policy_comparison = ...
            compareMultipleApexPolicies(problem, search.multiple_apex);
    end
    search.found_multiple_apex = ...
        search.multiple_apex_policy_comparison.validated;
    search.found_section_mode_transition = ...
        search.section_mode_transition.found;
    search.refined_section_coincidence = ...
        search.section_mode_transition.found && ...
        search.section_mode_transition.exact_coincidence;
    if search.found_grounded_apex || search.found_multiple_apex || ...
            search.found_section_mode_transition
        search.status = 'completed-one-or-more-cases-found';
    end
end

function search = runNonSimultaneousSearch( ...
        residual, problem, u0, p0, q0, options)
    search = struct('attempted', true, 'found', false, ...
        'derivative_model', ...
            'unrestricted-topology-aware-hybrid-classical-or-rejected', ...
        'amplitudes', options.NonSimultaneousSearchAmplitudes, ...
        'direction_names', {{'paired-angle-antisymmetry', ...
            'crossed-angle-antisymmetry'}}, ...
        'attempts', struct([]), ...
        'reason', 'No validated non-simultaneous orbit was found.');
    directions = zeros(13, 2);
    directions([6, 8, 10, 12], 1) = [1, -1, 1, -1];
    directions([6, 8, 10, 12], 2) = [1, -1, -1, 1];
    attempts = repmat(struct('amplitude', NaN, 'direction_name', '', ...
        'initial_residual_norm', Inf, 'initial_cluster_signature', '', ...
        'converged', false, 'final_residual_norm', Inf, ...
        'physically_admissible', false, ...
        'all_event_clusters_singleton', false, ...
        'event_cluster_signature', '', 'map_evaluations', 0, ...
        'jacobian_evaluations', 0, 'accepted_iterations', 0, ...
        'failure_reason', ''), 1, 0);
    fd = continuationHybridJacobian(options);
    for directionIndex = 1:size(directions, 2)
        direction = directions(:, directionIndex);
        direction = direction / norm(direction);
        for amplitude = options.NonSimultaneousSearchAmplitudes(:).'
            record = attemptsTemplate();
            record.amplitude = amplitude;
            record.direction_name = search.direction_names{directionIndex};
            guess = u0(:) + amplitude .* direction;
            try
                [initialResidual, initialDetails] = ...
                    residual.evaluateWithInfo(guess, p0, q0, struct());
                record.initial_residual_norm = norm(initialResidual, inf);
                record.initial_cluster_signature = memberOr( ...
                    initialDetails, 'event_cluster_signature', '');
                solver = RootSolver_v3(struct( ...
                    'Jacobian', fd, 'Algorithm', 'newton', ...
                    'FunctionTolerance', options.RootFunctionTolerance, ...
                    'ResidualAcceptanceTolerance', ...
                        options.RootAcceptanceTolerance, ...
                    'MaxIterations', options.NonSimultaneousSearchMaxIterations, ...
                    'MaxFunctionEvaluations', ...
                        options.RootMaxFunctionEvaluations));
                [solution, info] = solver.solve( ...
                    residual, guess, p0, q0);
                record.converged = info.converged;
                record.final_residual_norm = info.residualNorm;
                record.map_evaluations = info.mapEvaluationCount;
                record.jacobian_evaluations = info.jacobianEvaluationCount;
                record.accepted_iterations = memberOr( ...
                    info.output, 'acceptedIterations', 0);
                if info.converged
                    [~, details] = problem.evaluateWithInfo( ...
                        solution, p0, info.mode);
                    record.physically_admissible = details.admissible;
                    record.event_cluster_signature = ...
                        details.event_cluster_signature;
                    clusters = details.event_clusters;
                    record.all_event_clusters_singleton = ...
                        ~isempty(clusters) && all(arrayfun( ...
                        @(cluster) isscalar(cluster.names), clusters));
                    if record.physically_admissible && ...
                            record.all_event_clusters_singleton && ...
                            info.residualNorm <= options.RootAcceptanceTolerance
                        search.found = true;
                        search.solution = solution;
                        search.mode = info.mode;
                    end
                else
                    record.failure_reason = info.message;
                end
            catch exception
                record.failure_reason = exceptionReport(exception);
            end
            attempts(end + 1) = record; %#ok<AGROW>
        end
    end
    search.attempts = attempts;
    if search.found
        search.reason = '';
    end
end

function record = attemptsTemplate()
    record = struct('amplitude', NaN, 'direction_name', '', ...
        'initial_residual_norm', Inf, 'initial_cluster_signature', '', ...
        'converged', false, 'final_residual_norm', Inf, ...
        'physically_admissible', false, ...
        'all_event_clusters_singleton', false, ...
        'event_cluster_signature', '', 'map_evaluations', 0, ...
        'jacobian_evaluations', 0, 'accepted_iterations', 0, ...
        'failure_reason', '');
end

function result = assessPhysicalBranchSwitchCandidates(floquet, mu, options)
    result = struct('attempted', true, ...
        'parameter_value', mu, 'reliable_source', false, ...
        'nearest_plus_one_distance', Inf, ...
        'nearest_minus_one_distance', Inf, ...
        'nearest_unit_circle_distance', Inf, ...
        'validated_bracket', false, 'switch_attempted', false, ...
        'outcome', 'no reliable Floquet grid available');
    if ~isstruct(floquet) || ~isfield(floquet, 'grid_results') || ...
            isempty(floquet.grid_results)
        return
    end
    reliable = find([floquet.grid_results.reliable], 1, 'last');
    if isempty(reliable)
        result.outcome = ['No reliable symmetry-restricted matrix was ', ...
            'available; no branch switch was attempted.'];
        return
    end
    multipliers = floquet.grid_results(reliable).multipliers(:);
    result.reliable_source = true;
    result.nearest_plus_one_distance = min(abs(multipliers - 1));
    result.nearest_minus_one_distance = min(abs(multipliers + 1));
    result.nearest_unit_circle_distance = min(abs(abs(multipliers) - 1));
    candidate = min([result.nearest_plus_one_distance, ...
        result.nearest_minus_one_distance, ...
        result.nearest_unit_circle_distance]);
    if candidate <= options.PhysicalBifurcationScreeningTolerance
        result.outcome = ['A single-point spectral proximity was found, ', ...
            'but no parameter bracket/refined critical point was available; ', ...
            'branch switching is mathematically inadmissible.'];
    else
        result.outcome = ['The actual orbit was screened for +1, -1, and ', ...
            'unit-circle candidates; none met the screening tolerance.'];
    end
end

function summaries = summarizeContinuationPoints(points, problem, converged)
    summaries = repmat(emptyContinuationPoint(), 1, numel(points));
    for index = 1:numel(points)
        point = points(index);
        summary = emptyContinuationPoint();
        summary.index = memberOr(point, 'index', index);
        summary.converged = logical(memberOr(point, 'converged', converged));
        summary.reduced_unknown = memberOr(point, 'x', []);
        summary.parameter = memberOr(point, 'p', []);
        summary.mode = memberOr(point, 'mode', []);
        summary.residual_norm = memberOr(point, 'residualNorm', Inf);
        summary.period = memberOr(point, 'period', NaN);
        summary.return_multiplicity = memberOr( ...
            point, 'return_multiplicity', NaN);
        summary.candidate_apex_count = memberOr( ...
            point, 'candidate_apex_count', NaN);
        summary.accepted_apex_index = memberOr( ...
            point, 'accepted_apex_index', NaN);
        summary.section_relative_signature = memberOr( ...
            point, 'section_relative_signature', '');
        summary.cyclic_signature = memberOr(point, 'cyclic_signature', '');
        summary.event_cluster_signature = memberOr( ...
            point, 'event_cluster_signature', '');
        summary.section_cluster_coincidence = logical(memberOr( ...
            point, 'section_cluster_coincidence', false));
        summary.minimum_intercluster_gap = memberOr( ...
            point, 'minimum_intercluster_gap', NaN);
        summary.minimum_physical_margin = memberOr( ...
            point, 'minimum_physical_margin', NaN);
        summary.event_history = memberOr(point, 'event_history', struct([]));
        summary.mode_candidates = numel(memberOr( ...
            memberOr(point, 'solverInfo', struct()), 'candidateModes', {}));
        solveInfo = memberOr(point, 'solverInfo', struct());
        summary.map_evaluations = memberOr( ...
            solveInfo, 'mapEvaluationCount', 0);
        summary.function_evaluations = memberOr( ...
            solveInfo, 'functionEvaluationCount', 0);
        summary.cache_hits = memberOr(solveInfo, 'cacheHitCount', 0);
        summary.invalid_trials = memberOr( ...
            solveInfo, 'invalidEvaluationCount', 0);
        summary.failure_reason = memberOr(solveInfo, 'message', '');
        if summary.converged && numel(summary.reduced_unknown) == 9
            unknown = unpackLeftRightUnknown(summary.reduced_unknown);
            try
                [~, details] = problem.evaluateWithInfo( ...
                    unknown, summary.parameter, summary.mode);
                summary.full_unknown = unknown;
                summary.mode = details.map_info.initial_mode;
                summary.period = details.map_info.period;
                summary.return_multiplicity = details.return_multiplicity;
                summary.candidate_apex_count = details.candidate_apex_count;
                summary.accepted_apex_index = details.accepted_apex_index;
                summary.section_relative_signature = ...
                    details.section_relative_event_signature;
                summary.cyclic_signature = details.cyclic_event_signature;
                summary.event_cluster_signature = ...
                    details.event_cluster_signature;
                summary.section_cluster_coincidence = ...
                    details.section_cluster_coincidence;
                summary.minimum_intercluster_gap = ...
                    details.minimum_intercluster_gap;
                summary.minimum_physical_margin = ...
                    details.minimum_physical_margin;
                summary.event_history = details.map_info.event_history;
            catch exception
                summary.converged = false;
                summary.failure_reason = exceptionReport(exception);
            end
        elseif summary.converged && numel(summary.reduced_unknown) == 13
            summary.full_unknown = summary.reduced_unknown;
        end
        summary.circular_event_phase = circularEventPhase( ...
            summary.event_history, summary.period);
        summaries(index) = summary;
    end
end

function summary = summarizeFloquet(result, grid, simulator)
    summary = emptyFloquetGrid();
    summary.step_grid = grid;
    summary.reliable = logical(result.reliable);
    summary.derivative_model = result.derivativeModel;
    summary.poincare_matrix = result.poincareMatrix;
    summary.multipliers = result.multipliers;
    summary.selected_steps = result.finiteDifference.selectedSteps;
    summary.estimated_column_errors = ...
        result.finiteDifference.estimatedErrors;
    summary.per_column_reliability = result.perColumnReliability;
    summary.cyclic_signature = result.eventSignature;
    summary.section_relative_signature = ...
        result.sectionRelativeSignature;
    summary.event_cluster_signature = memberOr( ...
        result.baseMapInfo, 'event_cluster_signature', '');
    summary.return_multiplicity = result.returnMultiplicity;
    summary.guard_transversality = ...
        result.transversalityMargins.guard;
    summary.section_transversality = ...
        result.transversalityMargins.section;
    summary.map_evaluations = result.finiteDifference.mapEvaluations;
    summary.cluster_preserved = result.clusterPreserved;
    summary.hybrid_chart_boundary = result.hybridChartBoundary;
    summary.warning = result.warning;
    summary.ode_tolerances = struct( ...
        'RelTol', simulator.Options.RelTol, ...
        'AbsTol', simulator.Options.AbsTol, ...
        'EventValueTolerance', simulator.Options.EventValueTolerance, ...
        'EventTimeTolerance', simulator.Options.EventTimeTolerance, ...
        'SimultaneousTimeTolerance', ...
            simulator.Options.SimultaneousTimeTolerance);
end

function summary = orbitSummary(orbit, residualNorm)
    summary = struct( ...
        'period', orbit.period, 'residual_norm', residualNorm, ...
        'return_multiplicity', orbit.return_multiplicity, ...
        'candidate_apex_count', orbit.candidate_apex_count, ...
        'accepted_apex_index', orbit.accepted_apex_index, ...
        'section_relative_signature', ...
            char(orbit.section_relative_event_signature), ...
        'cyclic_signature', char(orbit.cyclic_event_signature), ...
        'event_cluster_signature', char(orbit.event_cluster_signature), ...
        'event_cluster_count', orbit.event_cluster_count, ...
        'event_cluster_members', {orbit.event_cluster_members}, ...
        'minimum_intercluster_gap', orbit.minimum_intercluster_gap, ...
        'section_cluster_coincidence', ...
            orbit.section_cluster_coincidence, ...
        'minimum_guard_transversality', ...
            orbit.minimum_guard_transversality, ...
        'section_transversality', orbit.section_transversality, ...
        'minimum_physical_margin', orbit.minimum_physical_margin, ...
        'event_history', orbit.event_history, ...
        'event_counts_per_leg', orbit.event_counts_per_leg);
end

function [z, p, q] = selectAsymmetricReference(simple, z0, p0, q0, index)
    z = z0;
    p = p0;
    q = q0;
    if ~isfield(simple, 'points') || isempty(simple.points)
        p(index) = p(index) + 0.02;
        return
    end
    values = arrayfun(@(entry) entry.parameter(index), simple.points);
    % Use the most asymmetric accepted point.  A small front/back split can
    % lie within the event-cluster tolerance at the larger external
    % Floquet steps even though the left/right cluster is structural.
    candidate = find(abs(values - p0(index)) > 1e-12 & ...
        [simple.points.converged], 1, 'last');
    if isempty(candidate)
        candidate = find([simple.points.converged], 1, 'last');
    end
    if ~isempty(candidate)
        z = simple.points(candidate).reduced_unknown(:);
        p = simple.points(candidate).parameter(:);
        q = simple.points(candidate).mode;
    end
end

function [residual, details] = evaluateLeftRightResidual( ...
        reduced, p, q, problem, context)
    if nargin < 5 || isempty(context)
        context = struct();
    end
    unknown = unpackLeftRightUnknown(reduced);
    [fullResidual, details] = problem.evaluateWithInfo( ...
        unknown, p, q, context);
    % Full residual ordering is [dx,y,phi,dphi,BL,BLdot,BR,BRdot,
    % FL,FLdot,FR,FRdot,dy].  One equation from each left/right pair is
    % retained on Fix(left-right), yielding a square nine-dimensional chart.
    residual = fullResidual([1, 2, 3, 4, 5, 6, 9, 10, 13]);
    details.derivative_subspace = 'left-right-invariant';
    % HybridFiniteDifferenceJacobian_v3 compares cyclic and section
    % signatures.  Include the cluster partition in those differentiation
    % signatures so a persistent pair cluster cannot silently split while
    % retaining the same scalar event ordering.  The physical signatures
    % remain unchanged in details.map_info and in the explicitly named
    % fields below.
    details.physical_cyclic_event_signature = ...
        details.cyclic_event_signature;
    details.physical_section_relative_signature = ...
        details.section_relative_event_signature;
    details.hybrid_fd_event_cluster_signature = ...
        details.event_cluster_signature;
    details.cyclic_event_signature = sprintf('%s||clusters:%s', ...
        char(details.physical_cyclic_event_signature), ...
        char(details.event_cluster_signature));
    details.section_relative_event_signature = sprintf( ...
        '%s||clusters:%s', ...
        char(details.physical_section_relative_signature), ...
        char(details.event_cluster_signature));
end

function fd = continuationHybridJacobian(options)
    fd = HybridFiniteDifferenceJacobian_v3(struct( ...
        'RelativeCandidateSteps', options.ContinuationHybridStepGrid, ...
        'MaximumRelativeError', options.HybridMaximumRelativeError, ...
        'RequireCompatibleCyclicSignature', true, ...
        'RequireCompatibleSectionSignature', true, ...
        'RequireMatchingReturnMultiplicity', true, ...
        'FailurePolicy', 'nan'));
end

function interface = fullClusterResidualInterface(problem)
    interface = struct();
    interface.Map = problem.Map;
    interface.evaluateWithInfo = @(u, p, q, context) ...
        evaluateFullClusterResidual(problem, u, p, q, context);
    interface.modeCandidates = @(u, q, p) ...
        fullModeCandidates(problem, u, q, p);
    interface.fullState = @(u, p, q) problem.fullState(u);
end

function [residual, details] = evaluateFullClusterResidual( ...
        problem, u, p, q, context)
    if nargin < 5 || isempty(context)
        context = struct();
    end
    [residual, details] = problem.evaluateWithInfo(u, p, q, context);
    details.physical_cyclic_event_signature = ...
        details.cyclic_event_signature;
    details.physical_section_relative_signature = ...
        details.section_relative_event_signature;
    details.cyclic_event_signature = sprintf('%s||clusters:%s', ...
        char(details.physical_cyclic_event_signature), ...
        char(details.event_cluster_signature));
    details.section_relative_event_signature = sprintf( ...
        '%s||clusters:%s', ...
        char(details.physical_section_relative_signature), ...
        char(details.event_cluster_signature));
end

function [candidates, diagnostics] = fullModeCandidates(problem, u, q, p)
    [candidates, diagnostics] = problem.modeCandidates(u, p, q);
end

function result = attachTopologyAudit(result)
    if isempty(result.points)
        return
    end
    result.cyclic_signatures = {result.points.cyclic_signature};
    result.section_signatures = ...
        {result.points.section_relative_signature};
    result.cluster_signatures = ...
        {result.points.event_cluster_signature};
    noBoundaries = ~any([result.points.section_cluster_coincidence]);
    cyclicCompatible = isscalar(unique(string( ...
        result.cyclic_signatures)));
    sectionCompatible = isscalar(unique(string( ...
        result.section_signatures)));
    clusterCompatible = isscalar(unique(string( ...
        result.cluster_signatures)));
    result.topology_compatible = noBoundaries && cyclicCompatible && ...
        sectionCompatible && clusterCompatible;
    result.topology_audit = struct( ...
        'no_section_cluster_coincidence', noBoundaries, ...
        'cyclic_signature_compatible', cyclicCompatible, ...
        'section_signature_compatible', sectionCompatible, ...
        'cluster_signature_compatible', clusterCompatible);
end

function reduced = packLeftRightUnknown(unknown)
    unknown = unknown(:);
    if numel(unknown) ~= 13
        error('QuadrupedalContinuationStudy_v3:UnknownDimension', ...
            'The quadruped unknown vector must have 13 entries.');
    end
    reduced = unknown([1, 2, 3, 4, 5, 6, 7, 10, 11]);
end

function unknown = unpackLeftRightUnknown(reduced)
    reduced = reduced(:);
    if numel(reduced) ~= 9
        error('QuadrupedalContinuationStudy_v3:ReducedDimension', ...
            'The left/right-invariant root chart has nine entries.');
    end
    unknown = [reduced(1:7); reduced(6:7); ...
        reduced(8:9); reduced(8:9)];
end

function direction = defaultRootDirection(dimension)
    direction = zeros(dimension, 1);
    direction(min(2, dimension)) = 1;
end

function definitions = physicalSearchDefinitions(p, schema, options)
    if ~isempty(options.PhysicalSearchDefinitions)
        definitions = options.PhysicalSearchDefinitions;
        return
    end
    definitions = repmat(struct('parameter_name', '', ...
        'parameter_index', 0, 'values', []), 1, 3);
    definitions(1) = struct('parameter_name', 'k_l_f', ...
        'parameter_index', schema.Parameter.k_l_f, ...
        'values', linspace(p(schema.Parameter.k_l_f), ...
            max(2, 0.2 * p(schema.Parameter.k_l_f)), ...
            options.SearchPointsPerPath));
    definitions(2) = struct('parameter_name', 'l_l_f', ...
        'parameter_index', schema.Parameter.l_l_f, ...
        'values', linspace(p(schema.Parameter.l_l_f), ...
            1.45 * p(schema.Parameter.l_l_f), ...
            options.SearchPointsPerPath));
    definitions(3) = struct('parameter_name', 'k_s_f', ...
        'parameter_index', schema.Parameter.k_s_f, ...
        'values', linspace(p(schema.Parameter.k_s_f), 0, ...
            options.SearchPointsPerPath));
end

function transition = detectSectionModeTransition(outcomes, tolerance)
    transition = struct('found', false, 'parameter_name', '', ...
        'left_point', struct(), 'right_point', struct(), ...
        'event_name', '', 'bracket', [], 'exact_coincidence', false, ...
        'reason', 'No accepted neighboring section charts changed mode.');
    for outcomeIndex = 1:numel(outcomes)
        points = outcomes(outcomeIndex).points;
        for pointIndex = 2:numel(points)
            left = points(pointIndex - 1);
            right = points(pointIndex);
            if ~left.converged || ~right.converged || ...
                    isequal(logical(left.mode(:)), logical(right.mode(:)))
                continue
            end
            [eventName, signedLeft, signedRight] = ...
                crossingEvent(left, right);
            if isempty(eventName)
                continue
            end
            transition.found = true;
            transition.parameter_name = outcomes(outcomeIndex).parameter_name;
            transition.left_point = left;
            transition.right_point = right;
            transition.event_name = eventName;
            parameterIndex = find(left.parameter ~= right.parameter, 1);
            if isempty(parameterIndex)
                transition.bracket = [];
            else
                transition.bracket = [left.parameter(parameterIndex), ...
                    right.parameter(parameterIndex)];
            end
            transition.signed_event_phase = [signedLeft, signedRight];
            transition.exact_coincidence = ...
                left.section_cluster_coincidence || ...
                right.section_cluster_coincidence || ...
                min(abs([signedLeft, signedRight])) <= tolerance;
            transition.reason = '';
            return
        end
    end
end

function comparison = compareMultipleApexPolicies(problem, point)
    comparison = struct('attempted', true, 'validated', false, ...
        'first_return_is_intermediate', false, ...
        'event_cycle_returns_full_cycle', false, ...
        'first_return_period', NaN, 'event_cycle_period', NaN, ...
        'first_return_candidate_index', NaN, ...
        'event_cycle_accepted_index', NaN, 'reason', '');
    try
        cycleMap = problem.Map;
        firstMap = PoincareMap_v3( ...
            cycleMap.System, cycleMap.Section, cycleMap.Simulator, ...
            FirstReturnPolicy_v3(), struct( ...
                'ModeResolver', cycleMap.ModeResolver, ...
                'MaxReturnTime', cycleMap.MaxReturnTime, ...
                'MaxSectionCrossings', cycleMap.MaxSectionCrossings, ...
                'MaxCycleEvents', cycleMap.MaxCycleEvents, ...
                'ArmTolerance', cycleMap.ArmTolerance, ...
                'InitialTime', cycleMap.InitialTime));
        state = problem.fullState(point.full_unknown);
        [~, firstInfo] = firstMap.evaluate( ...
            state, point.mode, point.parameter);
        [~, cycleInfo] = cycleMap.evaluate( ...
            state, point.mode, point.parameter);
        comparison.first_return_period = firstInfo.period;
        comparison.event_cycle_period = cycleInfo.period;
        comparison.first_return_candidate_index = ...
            firstInfo.accepted_crossing_index;
        comparison.event_cycle_accepted_index = ...
            cycleInfo.accepted_crossing_index;
        comparison.first_return_is_intermediate = ...
            firstInfo.accepted_crossing_index == 1 && ...
            firstInfo.period < cycleInfo.period && ...
            cycleInfo.accepted_crossing_index >= 2;
        comparison.event_cycle_returns_full_cycle = ...
            cycleInfo.cycle_complete && ...
            cycleInfo.return_policy_accepted;
        comparison.validated = ...
            comparison.first_return_is_intermediate && ...
            comparison.event_cycle_returns_full_cycle;
        if ~comparison.validated
            comparison.reason = ['The two policies did not establish an ', ...
                'intermediate first apex and a completed later cycle.'];
        end
    catch exception
        comparison.reason = exceptionReport(exception);
    end
end

function [name, leftPhase, rightPhase] = crossingEvent(left, right)
    name = '';
    leftPhase = NaN;
    rightPhase = NaN;
    leftNames = {left.circular_event_phase.name};
    rightNames = {right.circular_event_phase.name};
    common = intersect(leftNames, rightNames, 'stable');
    for index = 1:numel(common)
        leftEntry = left.circular_event_phase(strcmp(leftNames, common{index}));
        rightEntry = right.circular_event_phase(strcmp(rightNames, common{index}));
        if leftEntry.signed_time * rightEntry.signed_time <= 0
            name = common{index};
            leftPhase = leftEntry.signed_time;
            rightPhase = rightEntry.signed_time;
            return
        end
    end
end

function phases = circularEventPhase(history, period)
    phases = repmat(struct('name', '', 'time', NaN, ...
        'phase', NaN, 'signed_time', NaN), 1, numel(history));
    if ~(isscalar(period) && isfinite(period) && period > 0)
        return
    end
    for index = 1:numel(history)
        time = memberOr(history(index), 'time', NaN);
        phase = time / period;
        phases(index).name = char(memberOr(history(index), 'type', ''));
        phases(index).time = time;
        phases(index).phase = phase;
        phases(index).signed_time = ...
            (mod(phase + 0.5, 1) - 0.5) * period;
    end
end

function entry = firstObservation(observations, predicate)
    entry = struct([]);
    for index = 1:numel(observations)
        if predicate(observations(index))
            entry = observations(index);
            return
        end
    end
end

function causes = collectRejectionCauses(outcomes)
    causes = {};
    for index = 1:numel(outcomes)
        failures = outcomes(index).failures;
        for failureIndex = 1:numel(failures)
            causes{end + 1} = failures(failureIndex).failure_reason; %#ok<AGROW>
        end
        if ~isempty(outcomes(index).reason)
            causes{end + 1} = outcomes(index).reason; %#ok<AGROW>
        end
    end
    causes = unique(causes(~cellfun(@isempty, causes)), 'stable');
end

function search = emptyPhysicalSearch(reason)
    search = struct('attempted', false, 'status', 'not-run', ...
        'derivative_model', '', ...
        'parameter_ranges', struct([]), 'seed_unknown', [], ...
        'seed_parameter', [], 'seed_mode', [], 'outcomes', struct([]), ...
        'observations', struct([]), 'accepted_orbit_count', 0, ...
        'rejection_count', 0, 'rejection_causes', {{}}, ...
        'grounded_apex', struct([]), 'multiple_apex', struct([]), ...
        'multiple_apex_policy_comparison', struct( ...
            'attempted', false, 'validated', false), ...
        'non_simultaneous_orbit_search', struct( ...
            'attempted', false, 'found', false, 'attempts', struct([])), ...
        'found_non_simultaneous_orbit', false, ...
        'section_mode_transition', struct('found', false), ...
        'found_grounded_apex', false, 'found_multiple_apex', false, ...
        'found_section_mode_transition', false, ...
        'refined_section_coincidence', false, 'reason', reason);
end

function summary = requirementSummary(study, options)
    summary = struct();
    summary.default_hybrid_root_correction = ...
        study.default_hybrid_root.converged && ...
        study.default_hybrid_root.initial_residual_norm > ...
            options.RootAcceptanceTolerance && ...
        study.default_hybrid_root.accepted_newton_iterations >= 1 && ...
        study.default_hybrid_root.jacobian_evaluations >= 1;
    summary.simple_continuation_20_points = ...
        study.simple_continuation.accepted_count >= 20;
    summary.pseudo_arclength_20_points = ...
        study.pseudo_arclength.accepted_count >= 20;
    summary.production_floquet_converged = ...
        isfield(study.floquet, 'converged') && study.floquet.converged;
    summary.grounded_apex_found = ...
        study.physical_search.found_grounded_apex;
    summary.multiple_apex_found = ...
        study.physical_search.found_multiple_apex;
    summary.section_mode_transition_found = ...
        study.physical_search.refined_section_coincidence;
    summary.physical_branch_switch_validated = ...
        study.branch_switch_candidate_search.validated_bracket;
end

function point = emptyContinuationPoint()
    point = struct('index', 0, 'converged', false, ...
        'reduced_unknown', [], 'full_unknown', [], 'parameter', [], ...
        'mode', [], 'residual_norm', Inf, 'period', NaN, ...
        'return_multiplicity', NaN, 'candidate_apex_count', NaN, ...
        'accepted_apex_index', NaN, 'section_relative_signature', '', ...
        'cyclic_signature', '', 'event_cluster_signature', '', ...
        'section_cluster_coincidence', false, ...
        'minimum_intercluster_gap', NaN, 'minimum_physical_margin', NaN, ...
        'event_history', struct([]), 'circular_event_phase', struct([]), ...
        'mode_candidates', 0, 'map_evaluations', 0, ...
        'function_evaluations', 0, 'cache_hits', 0, ...
        'invalid_trials', 0, 'failure_reason', '');
end

function entry = emptyFloquetGrid()
    entry = struct('step_grid', [], 'reliable', false, ...
        'derivative_model', '', 'poincare_matrix', [], 'multipliers', [], ...
        'selected_steps', [], 'estimated_column_errors', [], ...
        'per_column_reliability', [], 'cyclic_signature', '', ...
        'section_relative_signature', '', 'event_cluster_signature', '', ...
        'return_multiplicity', NaN, 'guard_transversality', NaN, ...
        'section_transversality', NaN, 'ode_tolerances', struct(), ...
        'map_evaluations', 0, 'cluster_preserved', false, ...
        'hybrid_chart_boundary', false, 'warning', '', 'reason', '');
end

function distance = matchedMultiplierDistance(left, right)
    left = left(:);
    right = right(:);
    if numel(left) ~= numel(right) || isempty(left) || ...
            any(~isfinite(left)) || any(~isfinite(right))
        distance = Inf;
        return
    end
    remaining = right;
    distances = zeros(numel(left), 1);
    [~, order] = sort(abs(left), 'descend');
    for index = 1:numel(order)
        value = left(order(index));
        [distances(index), match] = min(abs(remaining - value));
        remaining(match) = [];
    end
    distance = max(distances);
end

function defaults = defaultOptions(v3Root)
    defaults = struct( ...
        'FixtureFile', 'PK_20_2.mat', ...
        'FixtureColumn', 1, ...
        'LegacyParameterPolicy', 'v2-exact', ...
        'ActiveParameter', 'k_l_f', ...
        'SeedParameterOffset', 0.16, ...
        'SeedPreparationPointCount', 9, ...
        'SimplePointCount', 20, ...
        'SimpleParameterOffset', [0, -0.02], ...
        'PseudoPointCount', 20, ...
        'PseudoStepSize', 0.003, ...
        'PseudoMinimumStepSize', 1e-5, ...
        'PseudoMaximumStepSize', 0.01, ...
        'PseudoParameterBounds', [-2, 2], ...
        'SecantRelativeStep', 1e-7, ...
        'ContinuationHybridStepGrid', 1e-4, ...
        'RootCorrectionPerturbation', 1e-4, ...
        'RootHybridStepGrid', [3e-4, 1e-4, 3e-5], ...
        'RootFunctionTolerance', 1e-8, ...
        'RootAcceptanceTolerance', 1e-7, ...
        'RootMaxIterations', 20, ...
        'RootMaxFunctionEvaluations', 2000, ...
        'HybridMaximumRelativeError', 5e-2, ...
        'RunFloquet', true, ...
        'FloquetStepGrids', {{ ...
            [3e-3, 1e-3, 3e-4], ...
            [1e-3, 3e-4, 1e-4], ...
            [3e-4, 1e-4, 3e-5]}}, ...
        'FloquetMatrixConvergenceTolerance', 5e-2, ...
        'FloquetMultiplierConvergenceTolerance', 5e-2, ...
        'RunPhysicalSearch', true, ...
        'SearchPointsPerPath', 3, ...
        'SearchMaxIterations', 12, ...
        'NonSimultaneousSearchAmplitudes', [1e-3, 1e-2], ...
        'NonSimultaneousSearchMaxIterations', 3, ...
        'PhysicalSearchDefinitions', [], ...
        'SectionCoincidenceTolerance', 1e-6, ...
        'PhysicalBifurcationScreeningTolerance', 5e-2, ...
        'SaveResults', true, ...
        'SaveFile', fullfile(v3Root, 'Examples_v3', 'Results_v3', ...
            'Round4_Quadruped_Production_Study_v3.mat'), ...
        'ReuseSaved', false, ...
        'ResumePhysicalSearch', false);
end

function addStudyPaths(v3Root)
    folders = {'Schema_v3', 'Adapters_v3', 'Dynamics_v3', ...
        'Simulation_v3', 'Orbit_v3', 'Numerics_v3', ...
        'Stability_v3', 'Examples_v3'};
    for index = 1:numel(folders)
        addpath(fullfile(v3Root, folders{index}));
    end
end

function saveStudyCheckpoint(study, options, stage)
    if ~options.SaveResults
        return
    end
    resultDirectory = fileparts(options.SaveFile);
    if ~isfolder(resultDirectory)
        mkdir(resultDirectory);
    end
    study.checkpoint_stage = stage;
    study.checkpoint_time = char(datetime('now', 'TimeZone', 'local', ...
        'Format', 'yyyy-MM-dd HH:mm:ss Z'));
    save(options.SaveFile, 'study', '-v7.3');
end

function result = mergeOptions(defaults, supplied)
    if ~isstruct(supplied) || ~isscalar(supplied)
        error('QuadrupedalContinuationStudy_v3:Options', ...
            'Options must be a scalar structure.');
    end
    result = defaults;
    names = fieldnames(supplied);
    for index = 1:numel(names)
        if ~isfield(defaults, names{index})
            error('QuadrupedalContinuationStudy_v3:UnknownOption', ...
                'Unknown option "%s".', names{index});
        end
        result.(names{index}) = supplied.(names{index});
    end
end

function value = memberOr(source, name, fallback)
    value = fallback;
    if isstruct(source) && isfield(source, name)
        value = source.(name);
    elseif isobject(source) && isprop(source, name)
        value = source.(name);
    end
end

function value = ternary(condition, yes, no)
    if condition
        value = yes;
    else
        value = no;
    end
end

function message = exceptionReport(exception)
    message = sprintf('%s: %s', exception.identifier, exception.message);
end
