function tests = test_continue_daughter_branch
%TEST_CONTINUE_DAUGHTER_BRANCH Geometry and adapter regression tests.
    tests = functiontests(localfunctions);
end

function setupOnce(testCase)
    testRoot = fileparts(mfilename('fullpath'));
    root = fileparts(fileparts(testRoot));
    originalPath = path;
    testCase.addTeardown(@() path(originalPath));
    addpath(root);
end

function testTwoSameRaySeedsAreForwarded(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, 'ValidateSeeds', false, ...
        'ValidateOutput', false, ...
        'RequireConsistentOutputTopology', false, ...
        'MinimumOutputPoints', 3, ...
        'ContinuationFunction', @FakeContinuation);
    [results, info] = floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options);
    testCase.verifySize(results, [29 3]);
    testCase.verifyFalse(info.accepted);
    testCase.verifyEqual(info.status, ...
        'unvalidated-test-or-diagnostic-output');
    testCase.verifyFalse(info.validationEvidenceComplete);
    testCase.verifyTrue(info.rayGeometry.checked);
    testCase.verifyTrue(info.rayGeometry.sameRay);
    testCase.verifyGreaterThan(prod(info.rayGeometry.projection), 0);
    testCase.verifyTrue(info.daughterGeometry.checked);
    testCase.verifyGreaterThanOrEqual( ...
        info.daughterGeometry.sameRayAlignedCount, 3);
    testCase.verifyGreaterThanOrEqual( ...
        info.daughterGeometry.sameRayAlignedDistinctCount, 3);
    testCase.verifyGreaterThanOrEqual( ...
        info.daughterGeometry.maximumConsecutiveAlignedDistinctCount, 3);
end

function testTransverseOrReversedSeedsAreRejected(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, 'ValidateSeeds', false, ...
        'ValidateOutput', false, ...
        'RequireConsistentOutputTopology', false, ...
        'ContinuationFunction', @FakeContinuation);
    transverse = seed1;
    transverse(2) = transverse(2) + 0.2;
    testCase.verifyError(@() floquet.continueDaughterBranch( ...
        transverse, seed2, parameters, options), ...
        'ContinueDaughterBranch:OppositeOrDegenerateRays');
    testCase.verifyError(@() floquet.continueDaughterBranch( ...
        seed2, seed1, parameters, options), ...
        'ContinueDaughterBranch:OppositeOrDegenerateRays');
end

function testTopologyConsistencyRequiresValidatedSeeds(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, 'ValidateSeeds', false, ...
        'ValidateOutput', true, ...
        'RequireConsistentOutputTopology', true, ...
        'ContinuationFunction', @FakeContinuation);
    testCase.verifyError(@() floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options), ...
        'ContinueDaughterBranch:TopologyReferenceRequiresSeedValidation');
end

function testTopologyConsistencyRequiresSeedsEvenWithoutOutputValidation(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, 'ValidateSeeds', false, ...
        'ValidateOutput', false, ...
        'RequireConsistentOutputTopology', true, ...
        'ContinuationFunction', @FakeContinuation);
    testCase.verifyError(@() floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options), ...
        'ContinueDaughterBranch:TopologyReferenceRequiresSeedValidation');
end

function testAcceptedSeedWithoutValidTopologyIsRejected(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, ...
        'ValidationFunction', @FakeValidationWithoutTopology, ...
        'ContinuationFunction', @FakeContinuation);
    testCase.verifyError(@() floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options), ...
        'ContinueDaughterBranch:MissingSeedTopology');
end

function testCustomTopologyCheckIsRecordedButRemainsDiagnostic(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, ...
        'ValidationFunction', @FakeAcceptedValidation, ...
        'ContinuationFunction', @FakeContinuation);
    [~, info] = floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options);
    testCase.verifyFalse(info.accepted);
    testCase.verifyTrue(info.seedTopologyEvidenceValid);
    testCase.verifyFalse(info.validationEvidenceComplete);
    testCase.verifyNotEmpty(info.referenceTopology.signature);
    testCase.verifyEqual(info.validationAuthority.classification, ...
        ['custom-validator-with-independent-topology-check-' ...
         'nonauthoritative']);
    testCase.verifyTrue( ...
        info.validationAuthority.independentTopologyChecked);
    testCase.verifyFalse( ...
        info.validationAuthority.scientificAcceptanceEligible);
    testCase.verifyEqual( ...
        info.daughterGeometry.maximumConsecutiveValidatedAlignedDistinctCount, ...
        3);
end

function testStrideSampledValidationCannotEstablishAcceptance(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, ...
        'ValidationFunction', @FakeAcceptedValidation, ...
        'ContinuationFunction', @FakeFivePointContinuation, ...
        'OutputValidationStride', 2);
    [~, info] = floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options);

    testCase.verifyFalse(info.accepted);
    testCase.verifyFalse(info.validationEvidenceComplete);
    testCase.verifyFalse(info.outputValidationCoverageComplete);
    testCase.verifyEqual(info.outputValidatedMask, ...
        [true false true false true]);
    testCase.verifyEqual( ...
        info.daughterGeometry.maximumConsecutiveAlignedDistinctCount, 5);
    testCase.verifyEqual( ...
        info.daughterGeometry.maximumConsecutiveValidatedAlignedDistinctCount, ...
        1);
end

function testAcceptedCustomOutputWithoutTopologyIsRejected(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, ...
        'ValidationFunction', @FakeSeedTopologyOnlyValidation, ...
        'ContinuationFunction', @FakeContinuation);
    [~, info] = floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options);

    testCase.verifyFalse(info.accepted);
    testCase.verifyFalse(info.validationEvidenceComplete);
    testCase.verifyTrue(info.outputValidation(3).evaluatorAccepted);
    testCase.verifyFalse(info.outputValidation(3).accepted);
    testCase.verifyFalse(info.outputValidation(3).topologyEvidenceValid);
    testCase.verifyEqual(info.outputValidation(3).status, ...
        'rejected-missing-topology-evidence');
end

function testAcceptedCustomOutputWithChangedTopologyIsRejected(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, ...
        'ValidationFunction', @FakeChangedOutputTopologyValidation, ...
        'ContinuationFunction', @FakeContinuation);
    [~, info] = floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options);

    testCase.verifyFalse(info.accepted);
    testCase.verifyFalse(info.validationEvidenceComplete);
    testCase.verifyTrue(info.outputValidation(3).evaluatorAccepted);
    testCase.verifyTrue(info.outputValidation(3).topologyEvidenceValid);
    testCase.verifyFalse(info.outputValidation(3).topologyConsistent);
    testCase.verifyEqual(info.outputValidation(3).status, ...
        'rejected-topology-change');
end

function testCustomValidationWithoutTopologyNeedsExplicitOptIn(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, ...
        'ValidationFunction', @FakeValidationWithoutTopology, ...
        'RequireConsistentOutputTopology', false, ...
        'ContinuationFunction', @FakeContinuation);
    testCase.verifyError(@() floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options), ...
        'ContinueDaughterBranch:CustomValidationRequiresOptIn');
end

function testExplicitNonproductionCustomValidationRemainsDiagnostic(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, ...
        'ValidationFunction', @FakeValidationWithoutTopology, ...
        'RequireConsistentOutputTopology', false, ...
        'AllowNonProductionValidationFunction', true, ...
        'ContinuationFunction', @FakeContinuation);
    [~, info] = floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options);

    testCase.verifyFalse(info.accepted);
    testCase.verifyFalse(info.validationEvidenceComplete);
    testCase.verifyEqual(info.validationAuthority.classification, ...
        'explicit-nonproduction-custom-validator');
    testCase.verifyTrue( ...
        info.validationAuthority.nonProductionExplicitlyAllowed);
    testCase.verifyFalse( ...
        info.validationAuthority.scientificAcceptanceEligible);
end

function testContinuationThatLeavesSelectedRayIsRejected(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, 'ValidateSeeds', false, ...
        'ValidateOutput', false, ...
        'RequireConsistentOutputTopology', false, ...
        'MinimumOutputPoints', 3, ...
        'ContinuationFunction', @FakeOrthogonalContinuation);
    [~, info] = floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options);
    testCase.verifyFalse(info.accepted);
    testCase.verifyTrue(info.daughterGeometry.checked);
    testCase.verifyEqual(info.daughterGeometry.sameRayAlignedCount, 0);
end

function testDuplicateOutputDoesNotEstablishThreePointCurve(testCase)
    [critical, direction, seed1, seed2, parameters] = Fixture();
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, 'ValidateSeeds', false, ...
        'ValidateOutput', false, ...
        'RequireConsistentOutputTopology', false, ...
        'MinimumOutputPoints', 3, ...
        'ContinuationFunction', @FakeDuplicateContinuation);
    [~, info] = floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options);
    testCase.verifyFalse(info.accepted);
    testCase.verifyEqual(info.pointCount, 3);
    testCase.verifyEqual(info.distinctPointCount, 2);
end

function testOppositeRaySeedsAreRejected(testCase)
    [critical, direction, seed1, ~, parameters] = Fixture();
    seedOpposite = critical;
    seedOpposite(1) = seedOpposite(1) - 0.02;
    options = struct('CriticalSolution', critical, ...
        'Direction', direction, 'ValidateSeeds', false, ...
        'ValidateOutput', false, ...
        'RequireConsistentOutputTopology', false, ...
        'ContinuationFunction', @FakeContinuation);
    testCase.verifyError(@() floquet.continueDaughterBranch( ...
        seed1, seedOpposite, parameters, options), ...
        'ContinueDaughterBranch:OppositeOrDegenerateRays');
end

function testOnlyInertiaMayBeInfinite(testCase)
    [~, ~, seed1, seed2, parameters] = Fixture();
    parameters(2) = Inf;
    options = struct('RequireSameRay', false, ...
        'ValidateSeeds', false, 'ValidateOutput', false, ...
        'RequireConsistentOutputTopology', false, ...
        'ContinuationFunction', @FakeContinuation);
    testCase.verifyError(@() floquet.continueDaughterBranch( ...
        seed1, seed2, parameters, options), ...
        'ContinueDaughterBranch:InvalidParameters');
end

function [critical, direction, seed1, seed2, parameters] = Fixture()
    critical = zeros(22, 1);
    critical(2) = 1;
    critical(14:21) = (0.1:0.1:0.8).';
    critical(22) = 1;
    direction = zeros(12, 1);
    direction(1) = 1;
    seed1 = critical;
    seed2 = critical;
    seed1(1) = 0.01;
    seed2(1) = 0.02;
    parameters = [10; 20; 2; 1; 0; 0.5; 1];
end

function [results, flags, info] = FakeContinuation(z1, z2, Para, ~, ~, ~)
    z3 = z2 + 0.5 * (z2 - z1);
    results = [[z1; Para], [z2; Para], [z3; Para]];
    flags = ["fixture complete", "fixture complete"];
    info = struct('fixture', true);
end

function [results, flags, info] = FakeFivePointContinuation( ...
        z1, z2, Para, ~, ~, ~)
    increment = z2 - z1;
    points = [z1, z2, z2 + increment, z2 + 2 * increment, ...
        z2 + 3 * increment];
    results = [points; repmat(Para, 1, size(points, 2))];
    flags = ["fixture complete", "fixture complete"];
    info = struct('fixture', true);
end


function [results, flags, info] = FakeOrthogonalContinuation(z1, ~, Para, ~, ~, ~)
    base = z1;
    base(1) = 0;
    points = repmat(base, 1, 3);
    points(2, :) = base(2) + [0.01 0.02 0.03];
    results = [points; repmat(Para, 1, 3)];
    flags = ["fixture left ray", "fixture left ray"];
    info = struct('fixture', true);
end


function [results, flags, info] = FakeDuplicateContinuation(z1, z2, Para, ~, ~, ~)
    results = [[z1; Para], [z2; Para], [z2; Para]];
    flags = ["fixture duplicate", "fixture duplicate"];
    info = struct('fixture', true);
end

function report = FakeValidationWithoutTopology(~, ~, ~)
    report = struct('accepted', true, 'status', 'accepted', ...
        'rejectionReasons', {{}}, 'periodicResidualNormInf', 0, ...
        'mapInfo', struct('timingResidualNormInf', 0));
end

function report = FakeAcceptedValidation(solution, ~, options)
    topology = floquet.internal.events.classifyTopology( ...
        solution(14:22), options);
    report = struct('accepted', true, 'status', 'accepted', ...
        'rejectionReasons', {{}}, 'periodicResidualNormInf', 0, ...
        'mapInfo', struct('timingResidualNormInf', 0, ...
            'eventTopology', topology));
end

function report = FakeSeedTopologyOnlyValidation(solution, ~, options)
    report = FakeAcceptedValidation(solution, [], options);
    if solution(1) > 0.0201
        report.mapInfo = rmfield(report.mapInfo, 'eventTopology');
    end
end

function report = FakeChangedOutputTopologyValidation(solution, ~, options)
    report = FakeAcceptedValidation(solution, [], options);
    if solution(1) > 0.0201
        topology = report.mapInfo.eventTopology;
        labels = topology.sortedEventNumbers([1 2]);
        topology.normalizedPhases(labels) = ...
            topology.normalizedPhases(labels([2 1]));
        topology.sortedEventNumbers([1 2]) = ...
            topology.sortedEventNumbers([2 1]);
        topology.signature = ['changed: ' topology.signature];
        report.mapInfo.eventTopology = topology;
    end
end
