function results = run_all_tests_v3(outputDirectory)
%RUN_ALL_TESTS_V3 Deterministic entry point for the complete v3 test suite.
%   RESULTS = RUN_ALL_TESTS_V3() establishes only the framework paths owned
%   by SLIP_Quadruped_v3, executes Tests_v3 recursively, writes JUnit XML
%   and a MATLAB result artifact, and throws when any test fails or remains
%   incomplete.  MATLAB -batch therefore returns a failing process status.

    v3Root = fileparts(mfilename('fullpath'));
    if nargin < 1 || isempty(outputDirectory)
        outputDirectory = fullfile( ...
            v3Root, 'Docs_v3', 'TestResults_v3');
    end
    if ~(ischar(outputDirectory) || ...
            (isstring(outputDirectory) && isscalar(outputDirectory)))
        error('run_all_tests_v3:OutputDirectory', ...
            'Output directory must be a text scalar.');
    end
    outputDirectory = char(outputDirectory);
    if ~isfolder(outputDirectory)
        mkdir(outputDirectory);
    end

    originalPath = path;
    restorePath = onCleanup(@() path(originalPath));
    ownedFolders = { ...
        v3Root, ...
        fullfile(v3Root, 'Schema_v3'), ...
        fullfile(v3Root, 'Adapters_v3'), ...
        fullfile(v3Root, 'Dynamics_v3'), ...
        fullfile(v3Root, 'Simulation_v3'), ...
        fullfile(v3Root, 'Orbit_v3'), ...
        fullfile(v3Root, 'Numerics_v3'), ...
        fullfile(v3Root, 'Stability_v3'), ...
        fullfile(v3Root, 'Graphics_v3'), ...
        fullfile(v3Root, 'Migration_v3'), ...
        fullfile(v3Root, 'Examples_v3'), ...
        fullfile(v3Root, 'Examples_v3', 'Models'), ...
        fullfile(v3Root, 'Tests_v3')};
    ownedFolders = ownedFolders(cellfun(@isfolder, ownedFolders));
    addpath(ownedFolders{:});

    import matlab.unittest.TestRunner
    import matlab.unittest.TestSuite
    import matlab.unittest.Verbosity
    import matlab.unittest.plugins.XMLPlugin

    suite = TestSuite.fromFolder(fullfile(v3Root, 'Tests_v3'), ...
        'IncludingSubfolders', true);
    runner = TestRunner.withTextOutput('Verbosity', Verbosity.Detailed);
    junitPath = fullfile(outputDirectory, 'junit-results-v3.xml');
    runner.addPlugin(XMLPlugin.producingJUnitFormat(junitPath));

    startedAt = datetime('now', 'TimeZone', 'local');
    timer = tic;
    results = runner.run(suite);
    elapsedSeconds = toc(timer);
    finishedAt = datetime('now', 'TimeZone', 'local');

    metadata = struct( ...
        'v3Root', v3Root, ...
        'matlabVersion', version, ...
        'matlabRelease', version('-release'), ...
        'computer', computer, ...
        'startedAt', startedAt, ...
        'finishedAt', finishedAt, ...
        'elapsedSeconds', elapsedSeconds, ...
        'testCount', numel(results), ...
        'passedCount', sum([results.Passed]), ...
        'failedCount', sum([results.Failed]), ...
        'incompleteCount', sum([results.Incomplete]), ...
        'junitPath', junitPath);
    save(fullfile(outputDirectory, 'matlab-test-results-v3.mat'), ...
        'results', 'metadata');

    summaryPath = fullfile(outputDirectory, 'test-summary-v3.txt');
    summaryFile = fopen(summaryPath, 'w');
    if summaryFile < 0
        error('run_all_tests_v3:SummaryFile', ...
            'Could not create %s.', summaryPath);
    end
    closeSummary = onCleanup(@() fclose(summaryFile));
    fprintf(summaryFile, 'MATLAB: %s\n', metadata.matlabVersion);
    fprintf(summaryFile, 'Platform: %s\n', metadata.computer);
    fprintf(summaryFile, 'Elapsed seconds: %.9f\n', elapsedSeconds);
    fprintf(summaryFile, 'Total: %d\n', metadata.testCount);
    fprintf(summaryFile, 'Passed: %d\n', metadata.passedCount);
    fprintf(summaryFile, 'Failed: %d\n', metadata.failedCount);
    fprintf(summaryFile, 'Incomplete: %d\n', metadata.incompleteCount);

    if any([results.Failed]) || any([results.Incomplete])
        error('run_all_tests_v3:TestFailure', ...
            ['v3 suite was not successful: %d failed and %d incomplete ', ...
             'out of %d tests.'], metadata.failedCount, ...
            metadata.incompleteCount, metadata.testCount);
    end
end
