function [dalphaF,ddalphaF] = Func_alphaF_VA_v2(in1)
%FUNC_ALPHAF_VA_V2
%    [DALPHAF,DDALPHAF] = FUNC_ALPHAF_VA_V2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Feb-2023 22:36:08

alphaF = in1(5,:);
dalphaF = in1(10,:);
ddphi = in1(13,:);
ddx = in1(11,:);
ddy = in1(12,:);
dphi = in1(8,:);
dx = in1(6,:);
dy = in1(7,:);
lb = in1(16,:);
phi = in1(3,:);
y = in1(2,:);
t2 = cos(phi);
t3 = sin(phi);
t4 = alphaF+phi;
t6 = lb-1.0;
t5 = tan(t4);
t8 = t3.*t6;
t7 = t5.^2;
t10 = -t8;
t12 = t2.*t5.*t6;
t16 = -1.0./(t8-y);
t9 = t7+1.0;
t14 = t10+y;
t15 = -t12;
t11 = dy.*t9;
t13 = 1.0./t9;
dalphaF = (t13.*(dx+dy.*t5-dphi.*(t10+t12+t9.*(t8-y))))./(t8-y);
if nargout > 1
    t17 = -t9.*(t8-y);
    t18 = t5.*t9.*(t8-y).*-2.0;
    t19 = dalphaF.*t18;
    ddalphaF = (t13.*(ddx+dphi.*(t11+t19+dphi.*(t18+t2.*t6+t5.*t8-t2.*t6.*t9.*2.0)-dalphaF.*t2.*t6.*t9)-dalphaF.*(-t11+dphi.*(t2.*t6.*t9+t5.*t9.*(t8-y).*2.0)+dalphaF.*t5.*t9.*(t8-y).*2.0)+ddy.*t5-ddphi.*(t10+t12+t9.*(t8-y))+dy.*(dalphaF.*t9+dphi.*t9)))./(t8-y);
end
