function audit=AuditRestrictedOddQuarterProof_v3()
%AUDITRESTRICTEDODDQUARTERPROOF_V3 Independent numerical algebra/sign checks.
% The analytic inequality in the accompanying proof is not inferred from
% these samples. Three resonances test the implemented variational model.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    V3LegacyAddPath_v3(fullfile(v3,'Numerics_v3'));
    p=[10;10;20;20;1;1;0;0;2;.5];omega=sqrt(20);records=struct([]);
    audit=struct('schema_version','restricted-odd-quarter-proof-audit-v3-1', ...
        'registered_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version, ...
        'physical_parameters',p,'resonance_indices',[0,1,2], ...
        'finite_energy_step',1e-6,'relative_identity_tolerance',1e-7, ...
        'relative_slope_tolerance',1e-5,'scope','Numerical checks of algebra and generator signs; analytic restricted existence is proved separately.');
    for n=audit.resonance_indices
        energy=1+(2*n+1)^2*pi^2/160;
        [matrix,info]=RestrictedPIPParentMatrix_v3(energy,p);
        stance=info.stance_matrix;A=.5*(stance(1,1)+stance(2,2));B=stance(1,2);C=stance(2,1);
        t=info.flight_time;theta=omega*t;
        Q=[1,0;-sin(2*theta)/omega,cos(2*theta)-t*sin(2*theta)/omega];
        D=det(stance*Q-eye(2));factored=2*cos(theta)*((1-A)*cos(theta)+((A-1)*t+B)/omega*sin(theta));
        predictedSlope=-2*((A-1)*t+B)/t;
        h=audit.finite_energy_step;measured=zeros(1,2);signs=[-1,1];
        for index=1:2
            e=energy+signs(index)*h;
            [m,d]=RestrictedPIPParentMatrix_v3(e,p); %#ok<ASGLU>
            phase=omega*d.flight_time;
            rotation=[1,0;-sin(2*phase)/omega,cos(2*phase)-d.flight_time*sin(2*phase)/omega];
            measured(index)=det(d.stance_matrix*rotation-eye(2));
        end
        numericalSlope=diff(measured)/(2*h);
        entry=struct('n',n,'energy',energy,'minimum_height',info.minimum_vertical_height, ...
            'stance_matrix',stance,'det_stance',det(stance),'symmetric_diagonal_error',abs(stance(1,1)-stance(2,2)), ...
            'A',A,'B',B,'C',C,'B_plus_A_plus_one_t',B+(A+1)*t, ...
            'SQ_matrix',stance*Q,'det_SQ_minus_I',D,'factored_determinant',factored, ...
            'det_M_minus_I',det(matrix-eye(3)), ...
            'determinant_identity_error',abs(D-factored)/max(1,norm(stance,inf)^2), ...
            'determinant_sign_relation_error',abs(det(matrix-eye(3))+D)/max(1,norm(matrix,inf)^3), ...
            'exact_algebraic_slope_formula',predictedSlope,'numerical_energy_slope',numericalSlope, ...
            'relative_slope_difference',abs(numericalSlope-predictedSlope)/max(1,abs(predictedSlope)), ...
            'restricted_matrix',matrix,'restricted_multipliers',eig(matrix));
        if isempty(records),records=entry;else,records(end+1)=entry;end %#ok<AGROW>
        fprintf('Odd-quarter n%d E%.12g Dprime%.9g finite%.9g inequalitymargin%.3g\n', ...
            n,energy,predictedSlope,numericalSlope,B+(A+1)*t);
    end
    audit.records=records;
    audit.passed=all([records.minimum_height]>0)&&all([records.A]>1) ...
        &&all([records.B]<0)&&all([records.C]<0)&&all([records.B_plus_A_plus_one_t]<0) ...
        &&all([records.exact_algebraic_slope_formula]>4) ...
        &&max([records.determinant_identity_error])<audit.relative_identity_tolerance ...
        &&max([records.determinant_sign_relation_error])<audit.relative_identity_tolerance ...
        &&max([records.relative_slope_difference])<audit.relative_slope_tolerance;
    save(V3Path_v3(fullfile(here,'restricted_odd_quarter_proof_audit.mat')),'audit','-v7');
    document=audit;
    for k=1:numel(records)
        numerical=records(k).restricted_multipliers;
        document.records(k).restricted_multipliers=struct('real',real(numerical),'imag',imag(numerical));
    end
    fid=fopen(V3Path_v3(fullfile(here,'restricted_odd_quarter_proof_audit.json')),'w');assert(fid>=0);
    cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(document,'PrettyPrint',true));assert(audit.passed);
end
