function audit=AuditLowEnergyPIPCritical_v3()
%AUDITLOWENERGYPIPCRITICAL_V3 Independent finite restricted/PK comparison.
% Immutable byte snapshots precede focused model evaluations. No campaign,
% root solver, engine, config or master checkpoint is changed.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    for folder={'Schema_v3','Dynamics_v3','Simulation_v3','Orbit_v3','Numerics_v3','Research_v3/Drivers_v3'}
        V3LegacyAddPath_v3(fullfile(v3,folder{1}));
    end
    stamp=char(datetime('now','TimeZone','UTC','Format','yyyyMMdd''T''HHmmssSSS'));
    directory=fullfile(here,['low_energy_critical_',stamp]);mkdir(V3Path_v3(directory));
    task='Research_v3/next_round/tasks/full/PIP_PK_low_energy_neighborhood/';
    sources={[task,'phase_checkpoint.mat'],'Research_v3/runs/full/family_-1.mat', ...
        'Research_v3/runs/full/family_+1.mat','Research_v3/next_round/tasks/validation/PK_continuation_m1/branch.mat'};
    daughterFiles=V3Dir_v3(fullfile(v3,task,'daughter_*.mat'));
    for k=1:numel(daughterFiles),sources{end+1}=[task,daughterFiles(k).name];end %#ok<AGROW>
    manifest=struct('source',{},'snapshot',{},'sha256',{},'bytes',{});snapshots=cell(size(sources));
    for k=1:numel(sources)
        original=fullfile(v3,sources{k});[~,name,extension]=fileparts(original);
        destination=fullfile(directory,sprintf('%02d_%s%s',k,name,extension));
        for attempt=1:3
            before=RoundSHA256_v3(original);copyfile(V3Path_v3(original),V3Path_v3(destination));
            copied=RoundSHA256_v3(destination);after=RoundSHA256_v3(original);
            if strcmp(before,copied)&&strcmp(copied,after),break;end
        end
        assert(strcmp(before,copied)&&strcmp(copied,after),'LowEnergyAudit:MovingSource','Source changed while being snapshotted.');
        inventory=V3Dir_v3(destination);assert(inventory.bytes<1e8,'Snapshot exceeds the repository file-size contract.');
        snapshots{k}=destination;
        manifest(k)=struct('source',sources{k},'snapshot',strrep(destination,[v3,filesep],''), ...
            'sha256',copied,'bytes',inventory.bytes);
    end
    loaded=load(V3Path_v3(snapshots{1}),'record');record=loaded.record;p=record.physical_parameter(:);
    energy=record.critical_energy;settings=struct('RelTol',1e-12,'AbsTol',1e-14,'MaxStep',.005, ...
        'EventValueTolerance',1e-10,'EventTimeTolerance',1e-12, ...
        'SimultaneousTimeTolerance',1e-10,'ArmingTolerance',1e-11);
    engineFiles={'Numerics_v3/RestrictedPIPParentMatrix_v3.m','Dynamics_v3/ContinuousDynamics_v3.m', ...
        'Dynamics_v3/GuardFunctions_v3.m','Dynamics_v3/ResetMap_v3.m','Dynamics_v3/QuadrupedEnergy_v3.m', ...
        'Simulation_v3/EventDetector_v3.m','Simulation_v3/HybridSimulator_v3.m', ...
        'Orbit_v3/PoincareMap_v3.m','Orbit_v3/BLMarkedApexReturnPolicy_v3.m'};
    engineHashes=struct('path',{},'sha256',{});
    for k=1:numel(engineFiles),engineHashes(k)=struct('path',engineFiles{k},'sha256',RoundSHA256_v3(fullfile(v3,engineFiles{k})));end
    registration=struct('schema_version','focused-low-energy-critical-audit-v3-1', ...
        'registered_utc',stamp,'maximum_wall_seconds',120,'source_snapshots',manifest, ...
        'source_critical_energy',energy,'physical_parameter',p,'settings',settings, ...
        'fd_steps',[1e-5,5e-6],'energy_slope_steps',[1e-4,5e-5], ...
        'matrix_gate',1e-6,'slope_agreement_gate',.01,'closure_gate',1e-8, ...
        'engine_hashes',engineHashes,'helper_path','Research_v3/next_round/theory/AuditLowEnergyPIPCritical_v3.m', ...
        'helper_sha256',RoundSHA256_v3([mfilename('fullpath'),'.m']), ...
        'scope','Finite numerical evidence for a restricted critical point; no interval certification, imported-PK identity or attachment.');
    RoundJSON_v3(fullfile(directory,'registration.json'),registration);timer=tic;
    derivativeOptions=struct('RelTol',1e-13,'AbsTol',1e-15);
    [model,modelInfo]=RestrictedPIPParentMatrix_v3(energy,p,derivativeOptions);
    [coarse,~]=RestrictedPIPParentMatrix_v3(energy,p);
    rootEnergy=fzero(@(E)localDeterminant(E,p,derivativeOptions),[1.105,1.13],optimset('TolX',1e-13));
    [atRoot,rootInfo]=RestrictedPIPParentMatrix_v3(rootEnergy,p,derivativeOptions);
    [U,D,V]=svd(atRoot-eye(3));v=V(:,end);left=U(:,end);
    if v(3)<0,v=-v;end;if left(1)<0,left=-left;end
    slopes=zeros(1,2);
    for k=1:2
        h=registration.energy_slope_steps(k);
        plus=RestrictedPIPParentMatrix_v3(rootEnergy+h,p,derivativeOptions);
        minus=RestrictedPIPParentMatrix_v3(rootEnergy-h,p,derivativeOptions);
        slopes(k)=left.'*((plus-minus)/(2*h))*v;
    end
    map=PoincareMap_v3(Quadrupedal_Dynamics_v3(),PoincareSection_v3.apex(4), ...
        HybridSimulator_v3(settings),BLMarkedApexReturnPolicy_v3(),struct('MaxReturnTime',20));
    measured=zeros(3,3,2);observations=struct([]);calls=0;
    for level=1:2
        h=registration.fd_steps(level);
        for column=1:3
            direction=zeros(3,1);direction(column)=h;values=zeros(3,2);
            for signIndex=1:2
                signs=[-1,1];initial=localLift(energy,signs(signIndex)*direction);
                localDeadline(timer,120);[next,info]=map.evaluate(initial,false(4,1),p);calls=calls+1;
                values(:,signIndex)=next([2,7,8]);events=info.event_history;events=events(~[events.is_stop]);
                observation=struct('fd_level',level,'column',column,'signed_step',signs(signIndex)*h, ...
                    'initial_state',initial,'actual_return_state',next,'actual_event_ids',[events.guard_id], ...
                    'actual_event_times',[events.time],'physical_admissible',info.admissible, ...
                    'minimum_guard_transversality',info.minimum_guard_transversality, ...
                    'section_chart',info.section_chart);
                if isempty(observations),observations=observation;else,observations(end+1)=observation;end %#ok<AGROW>
            end
            measured(:,column,level)=diff(values,1,2)/(2*h);
        end
    end
    parent=localLift(energy,zeros(3,1));localDeadline(timer,120);
    [returned,parentInfo]=map.evaluate(parent,false(4,1),p);calls=calls+1;
    numerical=struct('source_energy',energy,'independent_numerical_root_energy',rootEnergy, ...
        'root_energy_difference',rootEnergy-energy,'root_determinant',det(atRoot-eye(3)), ...
        'source_model_matrix',model,'independent_root_matrix',atRoot, ...
        'actual_fd_matrices',measured,'actual_fd_refinement_difference',norm(measured(:,:,2)-measured(:,:,1),inf), ...
        'actual_vs_model_matrix_error',norm(measured(:,:,2)-model,inf), ...
        'restricted_integrator_refinement_difference',norm(model-coarse,inf), ...
        'source_saved_matrix_difference',norm(model-record.critical_derivatives{3}.matrix,inf), ...
        'independent_singular_values',diag(D),'independent_unit_kernel',v,'independent_left_kernel',left, ...
        'independent_transversality_estimates',slopes,'source_transversality_estimate',record.transversality_estimate, ...
        'source_transversality_uncertainty_estimate',record.transversality_uncertainty_estimate, ...
        'kernel_alignment_with_source',abs(v.'*record.critical_direction), ...
        'parent_minimum_height',rootInfo.minimum_vertical_height,'parent_actual_full_closure',norm(returned-parent,inf), ...
        'parent_actual_period',parentInfo.period,'restricted_predicted_period',modelInfo.period, ...
        'root_matrix_multipliers',struct('real',real(eig(atRoot)),'imag',imag(eig(atRoot))), ...
        'finite_difference_observations',observations,'interval_error_bound_supplied',false);
    imports=struct([]);
    for k=2:4
        loaded=load(V3Path_v3(snapshots{k}),'branch');points=loaded.branch.points;
        for index=1:numel(points)
            if isempty(points(index).orbit),continue;end
            item=localPoint(points(index).orbit,sources{k},index);
            if isempty(imports),imports=item;else,imports(end+1)=item;end %#ok<AGROW>
        end
    end
    daughters=struct([]);
    for k=5:numel(snapshots)
        loaded=load(V3Path_v3(snapshots{k}),'entry','orbit','replayOrbit');
        if ~isfield(loaded,'entry')||~loaded.entry.accepted,continue;end
        orbit=loaded.orbit;if isfield(loaded,'replayOrbit')&&~isempty(loaded.replayOrbit),orbit=loaded.replayOrbit;end
        item=localPoint(orbit,sources{k},1);item.signed_amplitude=loaded.entry.signed_amplitude;
        item.accepted_newton_steps=loaded.entry.accepted_newton_iterations;
        item.saved_entry=loaded.entry;
        if isempty(daughters),daughters=item;else,daughters(end+1)=item;end %#ok<AGROW>
    end
    assert(~isempty(daughters),'No accepted low-energy daughter was snapshotted.');
    comparisons=struct([]);
    for k=1:numel(daughters)
        distances=zeros(1,numel(imports));reflections=false(size(distances));
        for j=1:numel(imports)
            assert(isequal(daughters(k).parameter,imports(j).parameter));
            direct=norm(daughters(k).state(2:end)-imports(j).state(2:end),inf);
            reflected=localReflect(imports(j).state);
            reflectedDistance=norm(daughters(k).state(2:end)-reflected(2:end),inf);
            distances(j)=min(direct,reflectedDistance);reflections(j)=reflectedDistance<direct;
        end
        [distance,index]=min(distances);a=daughters(k);b=imports(index);
        pair=struct('signed_amplitude',a.signed_amplitude,'daughter_artifact',a.artifact, ...
            'daughter_state',a.state,'daughter_energy',a.energy,'daughter_period',a.period,'daughter_drift',a.drift, ...
            'closest_imported_artifact',b.artifact,'closest_imported_point_index',b.point_index, ...
            'closest_imported_state',b.state,'closest_imported_energy',b.energy, ...
            'closest_imported_period',b.period,'closest_imported_drift',b.drift, ...
            'horizontal_reflection_applied',reflections(index),'closest_apex_distance',distance, ...
            'energy_gap',abs(a.energy-b.energy),'period_gap',abs(a.period-b.period), ...
            'reflected_drift_gap',abs(a.drift-(-1)^reflections(index)*b.drift), ...
            'same_saved_contact_count',isequal(a.contact_counts,b.contact_counts), ...
            'identity_or_imported_attachment_established',false);
        if isempty(comparisons),comparisons=pair;else,comparisons(end+1)=pair;end %#ok<AGROW>
    end
    validation=find(strcmp({imports.artifact},sources{4}));[~,localIndex]=min([imports(validation).energy]);turnIndex=validation(localIndex);
    turn=imports(turnIndex);turnComparison=localStateComparison(parent,energy,parentInfo.period,0,turn);
    endpointComparisons=struct([]);
    for sourceIndex=2:4
        selected=find(strcmp({imports.artifact},sources{sourceIndex}));
        for index=unique(selected([1,end]))
            pair=localStateComparison(parent,energy,parentInfo.period,0,imports(index));
            if isempty(endpointComparisons),endpointComparisons=pair;else,endpointComparisons(end+1)=pair;end %#ok<AGROW>
        end
    end
    replayTargets=[find([daughters.signed_amplitude]>0,1),find([daughters.signed_amplitude]==min([daughters.signed_amplitude]),1)];
    traces=struct('id',{},'state',{},'returned',{},'info',{},'full_closure',{});
    for k=unique(replayTargets)
        point=daughters(k);localDeadline(timer,120);
        [next,info]=map.evaluate(point.state,point.mode,p);calls=calls+1;
        traces(end+1)=struct('id',point.artifact,'state',point.state,'returned',next, ...
            'info',info,'full_closure',norm(next(2:end)-point.state(2:end),inf)); %#ok<AGROW>
    end
    localDeadline(timer,120);[next,info]=map.evaluate(turn.state,turn.mode,p);calls=calls+1;
    traces(end+1)=struct('id',[turn.artifact,' minimum sampled energy'],'state',turn.state, ...
        'returned',next,'info',info,'full_closure',norm(next(2:end)-turn.state(2:end),inf));
    unchanged=true;
    for k=1:numel(engineHashes),unchanged=unchanged&&V3HashMatches_v3(engineHashes(k).sha256, fullfile(v3,engineHashes(k).path));end
    audit=struct('schema_version','executed-low-energy-critical-independent-audit-v3-1', ...
        'created_utc',stamp,'matlab_version',version,'registration',registration,'numerical',numerical, ...
        'accepted_daughter_snapshots',numel(daughters),'imported_saved_point_records',numel(imports), ...
        'daughter_imported_comparisons',comparisons,'parent_validation_imported_turn_comparison',turnComparison, ...
        'parent_imported_endpoint_comparisons',endpointComparisons,'fresh_replay_closures',[traces.full_closure], ...
        'engine_hashes_unchanged',unchanged,'explicit_map_evaluations',calls,'elapsed_seconds',toc(timer), ...
        'restricted_C2_analyticity_established',true,'interval_certification_performed',false, ...
        'conditional_simple_local_branch_theorem_applicable',true,'imported_identity_established',false, ...
        'imported_attachment_established',false,'unrestricted_C2_or_branch_claimed',false, ...
        'interpretation','The exact restriction is analytic. The numerically identified simple unit crossing and corrected nontrivial daughters support a restricted local branch candidate. Exact simple-kernel/transversality validation would complete the conditional local theorem; sampled imported PK nearness does not prove identity or a connecting branch.');
    audit.passed=unchanged&&numerical.actual_vs_model_matrix_error<registration.matrix_gate ...
        &&numerical.actual_fd_refinement_difference<registration.matrix_gate ...
        &&max(abs(slopes-record.transversality_estimate))<registration.slope_agreement_gate ...
        &&max([traces.full_closure])<registration.closure_gate&&numerical.parent_actual_full_closure<registration.closure_gate ...
        &&all([observations.physical_admissible])&&audit.elapsed_seconds<120;
    save(V3Path_v3(fullfile(directory,'audit.mat')),'audit','traces','parentInfo','daughters','imports','-v7');
    RoundJSON_v3(fullfile(directory,'audit.json'),audit);
    RoundJSON_v3(fullfile(here,'low_energy_critical_audit_latest.json'),struct('artifact',strrep(fullfile(directory,'audit.mat'),[v3,filesep],''), ...
        'json_artifact',strrep(fullfile(directory,'audit.json'),[v3,filesep],''),'passed',audit.passed,'created_utc',stamp));
    fprintf('Low-E critical root %.15g versus source %.15g; actual matrix error %.3g, slopes %.9g/%.9g\n', ...
        rootEnergy,energy,numerical.actual_vs_model_matrix_error,slopes(1),slopes(2));
    fprintf('Saved imported turn E%.15g, parent gap%.3g stategap%.3g; %d daughter/%d imported records; %.2fs, pass%d\n', ...
        turn.energy,turnComparison.energy_gap,turnComparison.apex_distance,numel(daughters),numel(imports),audit.elapsed_seconds,audit.passed);
    assert(audit.passed,'LowEnergyAudit:Failed','Focused low-energy independent audit failed a registered numerical gate.');
end
function value=localDeterminant(E,p,options)
    matrix=RestrictedPIPParentMatrix_v3(E,p,options);value=det(matrix-eye(3));
end
function state=localLift(E,u)
    state=zeros(14,1);state(2)=u(1);state(3)=E-u(1)^2/2;
    state([7,9,11,13])=u(2);state([8,10,12,14])=u(3);
end
function state=localReflect(state)
    old=state;state([1,2,5,6])=-old([1,2,5,6]);
    state([7,9,11,13])=-old([11,13,7,9]);state([8,10,12,14])=-old([12,14,8,10]);
end
function point=localPoint(orbit,artifact,index)
    state=orbit.initial_state(:);state(1)=0;p=orbit.parameter(:);
    data=HybridCycleData_v3.unpack(orbit);angles=data.state(:,[7,9,11,13]);rates=data.state(:,[8,10,12,14]);
    sync=max([abs(angles-angles(:,1)),abs(rates-rates(:,1)),abs(data.state(:,[5,6]))],[],'all');
    assert(isequal(p,[10;10;20;20;1;1;0;0;2;.5])&&sync<1e-7,'Imported comparison requires the baseline synchronized-pronk reflection chart.');
    history=data.history;ids=[history.guard_id];counts=arrayfun(@(id)sum(ids==id),1:8);
    point=struct('artifact',artifact,'point_index',index,'state',state,'mode',orbit.initial_mode(:), ...
        'parameter',p,'energy',QuadrupedEnergy_v3.evaluate(state,orbit.initial_mode,p), ...
        'period',orbit.period,'drift',data.state(end,1)-data.state(1,1), ...
        'saved_full_closure',norm(orbit.poincare_state(2:end)-state(2:end),inf), ...
        'synchronization_error',sync,'contact_counts',counts);
end
function comparison=localStateComparison(state,energy,period,drift,point)
    reflected=localReflect(point.state);direct=norm(state(2:end)-point.state(2:end),inf);
    reflectedGap=norm(state(2:end)-reflected(2:end),inf);reflection=reflectedGap<direct;
    comparison=struct('imported_artifact',point.artifact,'imported_point_index',point.point_index, ...
        'imported_state',point.state,'imported_energy',point.energy,'imported_period',point.period,'imported_drift',point.drift, ...
        'horizontal_reflection_applied',reflection,'apex_distance',min(direct,reflectedGap), ...
        'energy_gap',abs(energy-point.energy),'period_gap',abs(period-point.period), ...
        'reflected_drift_gap',abs(drift-(-1)^reflection*point.drift), ...
        'identity_or_imported_attachment_established',false);
end
function localDeadline(timer,limit)
    assert(toc(timer)<limit-4,'LowEnergyAudit:TimeBudget','The registered standalone audit limit was reached.');
end
