function result=FinalizeAdditionalTheoryAudits_v3()
%FINALIZEADDITIONALTHEORYAUDITS_V3 Hash verified chart and analyze saved DP.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    for folder={'Schema_v3','Dynamics_v3','Simulation_v3','Orbit_v3','Numerics_v3','Research_v3/Drivers_v3'}
        V3LegacyAddPath_v3(fullfile(v3,folder{1}));
    end
    helper='Numerics_v3/EventOrderChartJacobian_v3.m';
    path=fullfile(here,'two_BL_chart_validation.mat');saved=load(V3Path_v3(path),'audit');audit=saved.audit;
    assert(audit.passed);audit.jacobian_helper_sha256=RoundSHA256_v3(fullfile(v3,helper));
    audit.jacobian_helper_path=helper;
    audit.helper_sha256=audit.jacobian_helper_sha256;
    audit.helper_path=helper;
    audit.hash_capture_note='Captured after successful physical gate; helper source unchanged between gate and capture.';
    save(V3Path_v3(path),'audit','-v7');RoundJSON_v3(fullfile(here,'two_BL_chart_validation.json'),audit);
    saved=load(V3Path_v3(fullfile(here,'directional_floquet_n0_parent.mat')),'value');value=saved.value;
    assert(value.reliable_numerical_full_derivative);
    source=load(V3Path_v3(fullfile(here,'arming_n0_parent_03.mat')),'x','q','parameters','parentProvenance');
    [~,energy]=QuadrupedEnergy_v3.evaluate(source.x,source.q,source.parameters);
    gradient=energy.gradient(value.physical_chart.independent_indices).';basis=null(gradient);
    matrix=basis.'*value.common_coordinate_matrix*basis;
    coarse=basis.'*value.coarse_matrix*basis;
    spectrum=eig(matrix);coarseSpectrum=eig(coarse);
    distance=abs(spectrum(:)-coarseSpectrum(:).');
    result=struct('schema_version','n0-full-energy-leaf-spectrum-v3-1', ...
        'created_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version, ...
        'source_artifact','Research_v3/next_round/theory/directional_floquet_n0_parent.mat', ...
        'source_sha256',RoundSHA256_v3(fullfile(here,'directional_floquet_n0_parent.mat')), ...
        'parent_provenance',source.parentProvenance,'energy',source.x(3), ...
        'physical_parameters',source.parameters,'full_dimension',12,'energy_leaf_dimension',11, ...
        'full_matrix',value.common_coordinate_matrix,'energy_gradient',gradient,'energy_basis',basis, ...
        'energy_leaf_matrix',matrix,'energy_leaf_multipliers',spectrum, ...
        'energy_leaf_spectral_radius',max(abs(spectrum)), ...
        'energy_leaf_invariance_residual',norm(value.common_coordinate_matrix*basis-basis*matrix,inf), ...
        'coarse_spectrum',coarseSpectrum, ...
        'spectrum_step_change',max([max(min(distance,[],1)),max(min(distance,[],2))]), ...
        'plus_one_singular_values',svd(matrix-eye(11)), ...
        'minus_one_singular_values',svd(matrix+eye(11)), ...
        'registered_neutral_diagnostic_tolerance',1e-6, ...
        'near_plus_one_count',sum(abs(spectrum-1)<1e-6), ...
        'near_minus_one_count',sum(abs(spectrum+1)<1e-6), ...
        'scope','Numerical full physical derivative; conserved-energy direction removed by ker(DE). Counts use recorded finite tolerance and do not prove exact multiplicity, C2, or full-space branch existence.');
    save(V3Path_v3(fullfile(here,'n0_full_physical_spectrum.mat')),'result','-v7');
    document=result;document.energy_leaf_multipliers=complexRecord(spectrum);document.coarse_spectrum=complexRecord(coarseSpectrum);
    RoundJSON_v3(fullfile(here,'n0_full_physical_spectrum.json'),document);
    % The continued imported branch's minimum sampled energy is distinct
    % from its lowest-energy historical fixture column. Read it separately.
    branchPath='Research_v3/next_round/tasks/validation/PK_continuation_m1/branch.mat';
    loaded=load(V3Path_v3(fullfile(v3,branchPath)),'branch');points=loaded.branch.points;
    energies=arrayfun(@(point)point.p(11),points);[~,index]=min(energies);point=points(index);
    save(V3Path_v3(fullfile(here,'imported_PK_sampled_turn_point.mat')),'point','-v7');
    previous=load(V3Path_v3(fullfile(here,'n0_source_comparison.mat')),'comparison');comparison=previous.comparison;
    turn=point.orbit;
    map=PoincareMap_v3(Quadrupedal_Dynamics_v3(),PoincareSection_v3.apex(4), ...
        HybridSimulator_v3(comparison.settings),BLMarkedApexReturnPolicy_v3(),struct('MaxReturnTime',10));
    [next,info]=map.evaluate(turn.initial_state,turn.initial_mode,turn.parameter);
    comparison.continued_imported_PK_sampled_turn=struct( ...
        'source_artifact',branchPath,'source_sha256',RoundSHA256_v3(fullfile(v3,branchPath)), ...
        'source_point_index',index,'sampled_branch_point_count',numel(points), ...
        'energy',QuadrupedEnergy_v3.evaluate(turn.initial_state,turn.initial_mode,turn.parameter), ...
        'state',turn.initial_state,'physical_parameter',turn.parameter,'period',info.period, ...
        'mean_speed',(info.raw_return_state(1)-info.initial_state(1))/info.period, ...
        'fresh_full_closure',norm(next-turn.initial_state,inf), ...
        'energy_gap_from_n0_daughter',energies(index)-comparison.daughter_energy, ...
        'scope','Minimum sampled continuation energy, not a certified exact fold. No n0 ancestry implied.');
    save(V3Path_v3(fullfile(here,'n0_source_comparison.mat')),'comparison','-v7');RoundJSON_v3(fullfile(here,'n0_source_comparison.json'),comparison);
    fprintf('n0 full11D: near+1=%d near-1=%d energy-leak%.3g spectrumchange%.3g\n', ...
        result.near_plus_one_count,result.near_minus_one_count,result.energy_leaf_invariance_residual,result.spectrum_step_change);
    fprintf('Continued imported PK sampled turn E%.12g differs from n0 daughter by%.6g\n',energies(index),comparison.continued_imported_PK_sampled_turn.energy_gap_from_n0_daughter);
    function value=complexRecord(numbers)
        value=struct('real',real(numbers),'imag',imag(numbers));
    end
end
