function reports=FinalizeFloquetServiceAudit_v3()
%FINALIZEFLOQUETSERVICEAUDIT_V3 Postprocess executed matrices without new maps.
% Spectrum changes across saved steps are empirical precision diagnostics,
% not interval bounds or a stability/existence certificate.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    V3LegacyAddPath_v3(fullfile(v3,'Dynamics_v3'));V3LegacyAddPath_v3(fullfile(v3,'Schema_v3'));
    targets={'imported_PK','PIP'};reports=cell(2,1);
    engineFiles={'Dynamics_v3/QuadrupedPhysicalChart_v3.m', ...
        'Dynamics_v3/QuadrupedEnergy_v3.m','Dynamics_v3/ContinuousDynamics_v3.m', ...
        'Dynamics_v3/GuardFunctions_v3.m','Dynamics_v3/ResetMap_v3.m', ...
        'Simulation_v3/EventDetector_v3.m','Simulation_v3/HybridSimulator_v3.m', ...
        'Orbit_v3/PoincareMap_v3.m','Orbit_v3/BLMarkedApexReturnPolicy_v3.m', ...
        'Numerics_v3/HybridFiniteDifferenceJacobian_v3.m', ...
        'Numerics_v3/EventOrderChartJacobian_v3.m','Stability_v3/FloquetAnalysis_v3.m'};
    hashes=struct('relative_path',{},'sha256',{});
    for k=1:numel(engineFiles)
        hashes(k)=struct('relative_path',engineFiles{k}, ...
            'sha256',fileHash(fullfile(v3,engineFiles{k})));
    end
    for k=1:numel(targets)
        target=targets{k};path=fullfile(here,['floquet_service_',target,'.mat']);
        saved=load(V3Path_v3(path),'report');report=saved.report;assert(report.passed);
        old=load(V3Path_v3(fullfile(here,['directional_floquet_',target,'.mat'])),'value');
        basis=report.energy_leaf.basis;
        coarseLeaf=basis.'*old.value.common_coordinate_matrix*basis;
        coarseMultipliers=eig(coarseLeaf);
        fineMultipliers=report.energy_leaf.multipliers;
        distances=abs(fineMultipliers(:)-coarseMultipliers(:).');
        [vectors,~]=eig(report.energy_leaf.matrix);
        report.mechanical_energy=QuadrupedEnergy_v3.evaluate( ...
            report.base_state,report.base_mode,report.physical_parameters);
        report.energy_leaf_refinement=struct( ...
            'coarse_matrix',coarseLeaf,'coarse_multipliers',coarseMultipliers, ...
            'coarse_spectral_radius',max(abs(coarseMultipliers)), ...
            'fine_spectral_radius',report.energy_leaf.spectral_radius, ...
            'absolute_matrix_change',norm(report.energy_leaf.matrix-coarseLeaf,inf), ...
            'relative_matrix_change',norm(report.energy_leaf.matrix-coarseLeaf,inf) ...
                /max(1,norm(report.energy_leaf.matrix,inf)), ...
            'spectrum_Hausdorff_change',max([max(min(distances,[],1)),max(min(distances,[],2))]), ...
            'fine_eigenvector_condition_number',cond(vectors), ...
            'nearest_plus_one_distance',min(abs(fineMultipliers-1)), ...
            'nearest_minus_one_distance',min(abs(fineMultipliers+1)), ...
            'diagnostic_note',['Saved-step comparison is empirical; it does not bound ', ...
                'all integration/differentiation errors or prove exact neutral multipliers. ', ...
                'No asymptotic-stability or branching certificate is inferred.']);
        report.source_hashes_captured_after_execution=hashes;
        report.postprocessing_utc=char(datetime('now','TimeZone','UTC'));
        reports{k}=report;save(V3Path_v3(path),'report','-v7');
        document=report;document.multipliers=complexRecord(report.multipliers);
        document.energy_leaf.multipliers=complexRecord(fineMultipliers);
        document.energy_leaf_refinement.coarse_multipliers=complexRecord(coarseMultipliers);
        fid=fopen(V3Path_v3(fullfile(here,['floquet_service_',target,'.json'])),'w');assert(fid>=0);
        fprintf(fid,'%s\n',jsonencode(document,'PrettyPrint',true));fclose(fid);
        fprintf('%s energy %.12g, leaf spectral step-change %.3g, nearest +1 %.3g/-1 %.3g\n', ...
            target,report.mechanical_energy,report.energy_leaf_refinement.spectrum_Hausdorff_change, ...
            report.energy_leaf_refinement.nearest_plus_one_distance, ...
            report.energy_leaf_refinement.nearest_minus_one_distance);
    end
    function value=complexRecord(numbers)
        value=struct('real',real(numbers),'imag',imag(numbers));
    end
    function digest=fileHash(path)
        fid=fopen(V3Path_v3(path),'rb');assert(fid>=0);cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
        engine=java.security.MessageDigest.getInstance('SHA-256');
        while ~feof(fid),engine.update(fread(fid,1024*1024,'*uint8'));end
        digest=lower(reshape(dec2hex(typecast(engine.digest(),'uint8'),2).',1,[]));
    end
end
