function registration=FreezeOpposedSpreadPeriodTwo_v3()
%FREEZEOPPOSEDSPREADPERIODTWO_V3 Freeze analytic hypotheses before any replay.
% Separate from unrestricted front/hind sector experiments. No solver,
% simulation, shared checkpoint or campaign budget is changed here.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    V3LegacyAddPath_v3(fullfile(v3,'Research_v3','Drivers_v3'));
    registrationPath=fullfile(v3,'Research_v3/next_round/opposed_spread_period_two_registration.json');
    assert(~isfile(V3Path_v3(registrationPath)),'The prospective opposed-spread registration already exists.');
    p=[10;10;20;20;1;1;0;0;2;.5];w=sqrt(20);pattern=[1;-1;1;-1];
    sourceFiles={'Dynamics_v3/ContinuousDynamics_v3.m','Dynamics_v3/GuardFunctions_v3.m', ...
        'Dynamics_v3/ResetMap_v3.m','Dynamics_v3/QuadrupedEnergy_v3.m', ...
        'Simulation_v3/EventDetector_v3.m','Simulation_v3/HybridSimulator_v3.m', ...
        'Orbit_v3/PoincareMap_v3.m','Orbit_v3/BLMarkedApexReturnPolicy_v3.m', ...
        'Orbit_v3/GaitIdentification_v3.m','Orbit_v3/PrimitiveCycleCheck_v3.m'};
    hashes=struct('path',{},'sha256',{});
    for k=1:numel(sourceFiles)
        hashes(k)=struct('path',sourceFiles{k},'sha256',RoundSHA256_v3(fullfile(v3,sourceFiles{k})));
    end
    settings=struct('RelTol',1e-12,'AbsTol',1e-14,'MaxStep',.005, ...
        'EventValueTolerance',1e-10,'EventTimeTolerance',1e-12, ...
        'SimultaneousTimeTolerance',1e-10,'ArmingTolerance',1e-11);
    registration=struct('schema_version','prospective-opposed-side-spread-period-two-v3-1', ...
        'registered_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version, ...
        'physical_parameter',p,'resonance_indices',[0,1],'signed_TD_angles',[-1e-3,1e-3], ...
        'analytic_formula','E=cos(A)+t_n^2/2; [a;b]=(-1)^n*[t_n*sin(A)/sqrt(20);sqrt(20)*A]', ...
        'phase_coordinates',{{'a','b','E'}},'leg_order',{{'BL','BR','FL','FR'}}, ...
        'leg_signs',pattern,'return_policy','BL-marked-apex-return','BL_occurrence',2, ...
        'minimum_primitive_BL_occurrence',2,'required_actual_flights',2, ...
        'claimed_target_gait','No automatic B2/F2/G2 assignment; actual classifier is authoritative.', ...
        'settings',settings,'fd_steps',[2e-5,1e-5],'slope_energy_step',1e-4, ...
        'slope_direction_step',1e-5,'matrix_error_tolerance',1e-6, ...
        'matrix_refinement_tolerance',1e-7,'slope_error_tolerance',1e-3, ...
        'full_closure_tolerance',1e-8,'energy_tolerance',1e-8, ...
        'maximum_audit_wall_seconds',150,'engine_hashes',hashes, ...
        'audit_source_path','Research_v3/next_round/theory/AuditOpposedSpreadPeriodTwo_v3.m', ...
        'audit_source_sha256',RoundSHA256_v3(fullfile(here,'AuditOpposedSpreadPeriodTwo_v3.m')), ...
        'proof_document','Docs_v3/Restricted_PIP_Opposed_Spread_Period_Two_v3.md', ...
        'predictor_admission_is_nonlinear_correction',false, ...
        'unrestricted_C2_claimed',false,'global_connection_claimed',false, ...
        'full_stability_claimed',false,'candidates',struct([]));
    catalog=struct('registration',registration,'predictors',struct([]));
    for n=registration.resonance_indices
        t=(2*n+1)*pi/(2*w);parentEnergy=1+t^2/2;
        normal=[t/20;1];normal=normal/norm(normal);
        for A=registration.signed_TD_angles
            energy=cos(A)+t^2/2;u=(-1)^n*[t*sin(A)/w;w*A];
            initial=zeros(14,1);initial(3)=energy;
            initial([7,9,11,13])=u(1)*pattern;initial([8,10,12,14])=u(2)*pattern;
            signName='negative';if A>0,signName='positive';end
            id=sprintf('opposed_spread_n%d_%s_A1e-3',n,signName);
            relativeArtifact=['Research_v3/next_round/theory/',id,'_predictor.mat'];
            assert(~isfile(V3Path_v3(fullfile(v3,relativeArtifact))),'A frozen predictor already exists.');
            predictor=struct('id',id,'state',initial,'mode',false(4,1),'parameter',p, ...
                'a',u(1),'b',u(2),'energy',energy,'touchdown_angle',A, ...
                'flight_time',t,'resonance_index',n,'parent_energy',parentEnergy, ...
                'restricted_unknown',[u;energy],'coordinate_order',{{'a','b','E'}}, ...
                'amplitude_normal',[normal;0],'amplitude_reference',[0;0;parentEnergy], ...
                'signed_kernel_coordinate',normal.'*u,'return_policy','BL-marked-apex-return', ...
                'occurrence',2,'required_actual_flights',2, ...
                'theoretical_label','opposed-side-spread standing primitive BL2 hypothesis', ...
                'actual_gait_label','pending physical audit','numerically_admitted',false, ...
                'audit_artifact','Research_v3/next_round/theory/opposed_spread_period_two_audit.mat', ...
                'registration_artifact','Research_v3/next_round/opposed_spread_period_two_registration.json', ...
                'frozen_utc',registration.registered_utc,'provenance',struct( ...
                    'source','Explicit exact-restriction formula proved in the companion document', ...
                    'existence_scope','Ideal exact p10 opposed-side-spread restriction only', ...
                    'existing_front_hind_experiment_changed',false));
            save(V3Path_v3(fullfile(v3,relativeArtifact)),'predictor','-v7');
            if isempty(catalog.predictors),catalog.predictors=predictor;
            else,catalog.predictors(end+1)=predictor;end %#ok<AGROW>
            entry=struct('id',id,'artifact',relativeArtifact,'variable','predictor', ...
                'sha256',RoundSHA256_v3(fullfile(v3,relativeArtifact)), ...
                'resonance_index',n,'touchdown_angle',A,'energy',energy);
            if isempty(registration.candidates),registration.candidates=entry;
            else,registration.candidates(end+1)=entry;end %#ok<AGROW>
        end
    end
    catalog.registration=registration;
    save(V3Path_v3(fullfile(here,'opposed_spread_period_two_candidates.mat')),'catalog','-v7');
    RoundJSON_v3(registrationPath,registration);
    fprintf('Froze four signed opposed-spread predictors at n0/n1 before numerical replay.\n');
end
