function catalog=FreezePIPFlipSectorCandidates_v3()
%FREEZEPIPFLIPSECTORCANDIDATES_V3 Freeze measured physical flip predictors.
% No two-cycle existence, primitiveness or genealogy is presumed.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    V3LegacyAddPath_v3(fullfile(v3,'Dynamics_v3'));V3LegacyAddPath_v3(fullfile(v3,'Schema_v3'));
    sourceFile=fullfile(here,'floquet_service_PIP.mat');loaded=load(V3Path_v3(sourceFile),'report');source=loaded.report;
    assert(source.passed&&source.energy_leaf.dimension==11);
    chart=QuadrupedPhysicalChart_v3.create(source.base_state,source.base_mode,source.physical_parameters);
    indices=chart.independent_indices;matrix=source.matrix;
    catalog=struct('schema_version','measured-PIP-flip-sector-candidates-v3-1', ...
        'frozen_utc',char(datetime('now','TimeZone','UTC')),'matlab_version',version, ...
        'source_artifact','Research_v3/next_round/theory/floquet_service_PIP.mat', ...
        'source_sha256',fileHash(sourceFile),'source_energy',source.mechanical_energy, ...
        'source_full_matrix',matrix,'source_energy_leaf_matrix',source.energy_leaf.matrix, ...
        'physical_parameters',source.physical_parameters,'physical_chart',chart, ...
        'signed_amplitudes',[-1e-3,1e-3],'BL_touchdowns_per_return',2, ...
        'required_primitive_return',2,'required_positive_duration_flights',2, ...
        'registration_scope',['Finite explicitly two-BL-return signed-sector experiment. ', ...
            'Amplitude belongs inside augmented physical-coordinate/energy unknowns. ', ...
            'One-return parent reconvergence and lower-period covers must be rejected. ', ...
            'No daughter existence, C2 or ancestry is presumed.'], ...
        'candidates',struct([]));
    [~,D,V]=svd(source.energy_leaf.matrix+eye(11));
    catalog.flip_singular_values=diag(D);
    catalog.measured_four_dimensional_flip_basis=source.energy_leaf.basis*V(:,end-3:end);
    catalog.flip_basis_residual=norm((matrix+eye(12))*catalog.measured_four_dimensional_flip_basis,inf);
    for sector=1:2
        physical=zeros(14,2);
        if sector==1
            physical([11,13],1)=[1;-1]/sqrt(2);physical([12,14],2)=[1;-1]/sqrt(2);
            name='front_antisymmetric';label='HB_front';leadState=11;
        else
            physical([7,9],1)=[1;-1]/sqrt(2);physical([8,10],2)=[1;-1]/sqrt(2);
            name='hind_antisymmetric';label='HB_hind';leadState=7;
        end
        basis=physical(indices,:);sectorMatrix=basis.'*matrix*basis;
        [vectors,values]=eig(sectorMatrix);values=diag(values);
        [~,selected]=min(abs(values+1));direction=basis*real(vectors(:,selected));direction=direction/norm(direction);
        lead=find(indices==leadState);if direction(lead)<0,direction=-direction;end
        ambient=zeros(14,1);ambient(indices)=direction;
        leakage=norm(matrix*basis-basis*sectorMatrix,inf);
        residual=norm(matrix*direction+direction,inf);
        assert(leakage<1e-6&&residual<1e-6,'Measured flip-sector decomposition failed.');
        E=source.mechanical_energy;reference=[source.base_state(indices);E];
        for signed=catalog.signed_amplitudes
            prediction=struct('sector_index',sector,'target_label',label, ...
                'target_positive_duration_flights',2,'signed_amplitude',signed, ...
                'independent_indices',indices,'reference',reference,'normal',[direction;0], ...
                'seed_state',QuadrupedPhysicalChart_v3.lift(chart,reference(1:end-1)+signed*direction), ...
                'frozen_utc',catalog.frozen_utc,'direction_origin','Measured unrestricted energy-leaf flip eigenvector in invariant leg-exchange sector');
            seed=struct('state',prediction.seed_state,'mode',source.base_mode, ...
                'parameter',source.physical_parameters,'return_policy','BL-marked-apex-return', ...
                'occurrence',2,'provenance',struct('source_spectral_artifact',catalog.source_artifact, ...
                    'source_spectral_sha256',catalog.source_sha256,'sector',name, ...
                    'measured_multiplier',values(selected),'signed_prediction',prediction));
            entry=struct('id',sprintf('PIP_flip_BL2_%s_%+.4g',name,signed), ...
                'sector',name,'target_label',label,'physical_direction',ambient, ...
                'independent_direction',direction,'sector_basis',basis,'sector_matrix',sectorMatrix, ...
                'measured_multiplier',values(selected),'sector_leakage',leakage, ...
                'flip_eigenvector_residual',residual,'prediction',prediction,'seed',seed);
            if isempty(catalog.candidates),catalog.candidates=entry;else,catalog.candidates(end+1)=entry;end %#ok<AGROW>
        end
        fprintf('%s measured flip %.12g residual %.3g leakage %.3g\n',name,real(values(selected)),residual,leakage);
    end
    path=fullfile(here,'PIP_flip_BL2_sector_candidates.mat');save(V3Path_v3(path),'catalog','-v7');
    fid=fopen(V3Path_v3(fullfile(here,'PIP_flip_BL2_sector_candidates.json')),'w');assert(fid>=0);
    cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(catalog,'PrettyPrint',true));
    function digest=fileHash(path)
        fid=fopen(V3Path_v3(path),'rb');assert(fid>=0);cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
        engine=java.security.MessageDigest.getInstance('SHA-256');
        while ~feof(fid),engine.update(fread(fid,1024*1024,'*uint8'));end
        digest=lower(reshape(dec2hex(typecast(engine.digest(),'uint8'),2).',1,[]));
    end
end
