function revision=RegisterLowEnergyPKBridgeDomainRepair_v3()
%REGISTERLOWENERGYPKBRIDGEDOMAINREPAIR_V3 Preserve inputs; fix scalar observable.
% No simulations, return maps, solver calls or master checkpoint writes.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    for folder={'Schema_v3','Dynamics_v3','Simulation_v3','Orbit_v3','Numerics_v3', ...
            'Stability_v3','Research_v3/Drivers_v3'},V3LegacyAddPath_v3(fullfile(v3,folder{1}));end
    file='Research_v3/next_round/low_energy_PK_bridge_method_revision_001.json';
    assert(~isfile(V3Path_v3(fullfile(v3,file))),'The prospective bridge repair was already registered.');
    registrationPath='Research_v3/next_round/low_energy_PK_bridge_registration.json';
    original=jsondecode(fileread(V3Path_v3(fullfile(v3,registrationPath))));record=original.candidates;
    assert(V3HashMatches_v3(record.candidate_sha256, fullfile(v3,record.candidate_artifact)));
    loaded=load(V3Path_v3(fullfile(v3,record.candidate_artifact)),'candidate');candidate=loaded.candidate;
    driver='Research_v3/Drivers_v3/RunLowEnergyPKBridge_v3.m';
    item=candidate.source_hashes(strcmp({candidate.source_hashes.path},driver));
    assert(isscalar(item));
    originalOrbit=load(V3Path_v3(fullfile(v3,candidate.seed.provenance.source_artifact)),'branch');
    source=originalOrbit.branch.points(candidate.seed.provenance.source_point_index).orbit;
    orbits={source,candidate.target_orbit};shapes=struct([]);
    for k=1:numel(orbits)
        orbit=orbits{k};data=HybridCycleData_v3.unpack(orbit);displacement=orbit.stride_displacement;
        speed=displacement(1)/orbit.period;
        assert(isvector(displacement)&&numel(displacement)==14&&isscalar(speed)&&isfinite(speed));
        assert(abs(displacement(1)-(data.state(end,1)-data.state(1,1)))<1e-10);
        shape=struct('role',k,'class',class(orbit),'stride_displacement_size',size(displacement), ...
            'horizontal_displacement',displacement(1),'mean_speed',speed, ...
            'maximum_saved_pitch',max(abs(data.state(:,5))),'actual_contact_event_count',numel(data.history));
        assert(shape.maximum_saved_pitch<1e-7&&shape.actual_contact_event_count==8);
        if isempty(shapes),shapes=shape;else,shapes(end+1)=shape;end %#ok<AGROW>
    end
    revision=struct('schema_version','prospective-local-PK-bridge-domain-repair-v3-1', ...
        'registered_utc',char(datetime('now','TimeZone','UTC')),'candidate_id',record.id, ...
        'candidate_sha256',record.candidate_sha256,'original_registration',registrationPath, ...
        'original_registration_sha256',RoundSHA256_v3(fullfile(v3,registrationPath)), ...
        'diagnosis','PoincareMap stride_displacement is rawReturnState minus sectionState (14D), so an unindexed && mean-speed gate throws after a valid service return.', ...
        'repair','Use horizontal component (1) for scalar speed/drift; explicitly check saved pitch and eight actual contact events against the registered domain.', ...
        'replaced_source',struct('path',driver,'original_sha256',item.sha256, ...
            'repaired_sha256',RoundSHA256_v3(fullfile(v3,driver))), ...
        'saved_actual_orbit_shapes',shapes,'full_closure_or_physics_changed',false, ...
        'amplitude_grid_or_budget_changed',false,'maps_executed',0,'new_simulations',0, ...
        'proof_of_shape_source','Orbit_v3/PoincareMap_v3.m:261', ...
        'proof_of_shape_source_sha256',RoundSHA256_v3(fullfile(v3,'Orbit_v3/PoincareMap_v3.m')));
    RoundJSON_v3(fullfile(v3,file),revision);
    fprintf('Registered no-map bridge domain repair: both actual saved displacements are 14D, horizontal speed scalar.\n');
end
