function candidate=RegisterPIPFlipBL2_v3()
%REGISTERPIPFLIPBL2_V3 Freeze explicit measured sector correction inputs.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    loaded=load(V3Path_v3(fullfile(here,'PIP_flip_BL2_sector_candidates.mat')),'catalog');catalog=loaded.catalog;
    saved=load(V3Path_v3(fullfile(here,'floquet_service_PIP.mat')),'report');source=saved.report;
    gate=load(V3Path_v3(fullfile(here,'two_BL_chart_validation.mat')),'audit');assert(gate.audit.passed);
    candidate=struct('id','PIP_measured_flip_BL2_front_hind', ...
        'seed',struct('state',source.base_state,'mode',source.base_mode, ...
            'parameter',source.physical_parameters,'return_policy','BL-marked-apex-return', ...
            'occurrence',2,'provenance',struct('source_spectral_artifact',catalog.source_artifact, ...
                'source_spectral_sha256',catalog.source_sha256, ...
                'chart_validation','Research_v3/next_round/theory/two_BL_chart_validation.mat')), ...
        'parent_label','PIP','parent_independently_admitted',true, ...
        'evidence','Research_v3/next_round/theory/PIP_flip_BL2_sector_candidates.mat', ...
        'physical_directions',[catalog.candidates(1).physical_direction,catalog.candidates(3).physical_direction], ...
        'target_labels',{{'HB_front','HB_hind'}},'target_flight_counts',[2,2], ...
        'signed_amplitudes',[-1e-3,1e-3], ...
        'direction_origin','Measured full physical energy-leaf -1 eigenvectors, projected into invariant front/hind antisymmetric sectors', ...
        'source_energy',source.mechanical_energy,'required_primitive_BL_occurrence',2, ...
        'contact_count_hypothesis','Two TD and LO per leg over the two-BL cycle; this is distinct from archived B2 one-TD-per-leg two-flight cycles.', ...
        'gait_typing','Actual corrected state/contact classifier and positive flight count determine the node type; two BL returns alone do not imply B2.', ...
        'frozen_utc',char(datetime('now','TimeZone','UTC')), ...
        'regular_bifurcation_claimed',false,'ancestry_claimed',false);
    artifact='Research_v3/next_round/theory/PIP_flip_BL2_candidate.mat';save(V3Path_v3(fullfile(v3,artifact)),'candidate','-v7');
    registration=struct('schema_version','prospective-measured-flip-BL2-experiment-v3-1', ...
        'registered_utc',candidate.frozen_utc,'source_spectral_artifact',catalog.source_artifact, ...
        'measured_front_multiplier',catalog.candidates(1).measured_multiplier, ...
        'measured_hind_multiplier',catalog.candidates(3).measured_multiplier, ...
        'signed_amplitudes',candidate.signed_amplitudes, ...
        'constraint','Signed amplitude inside the full physical-coordinate/energy augmented corrector; symmetry none', ...
        'BL_touchdowns_per_return',2,'required_primitive_BL_occurrence',2, ...
        'actual_flight_count_required',2,'acceptance_tolerances_changed',false, ...
        'candidates',struct('id',candidate.id,'candidate_artifact',artifact,'candidate_variable','candidate'), ...
        'hypothesis_scope',candidate.contact_count_hypothesis,'ancestry_claimed',false);
    fid=fopen(V3Path_v3(fullfile(v3,'Research_v3/next_round/period_two_candidate_registration.json')),'w');assert(fid>=0);
    cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(registration,'PrettyPrint',true));
    fprintf('Registered measured BL2 front/hind signed-sector candidate; no correction has run in this registrar.\n');
end
