function candidate=RegisterN0FlipBL2_v3()
%REGISTERN0FLIPBL2_V3 Register a distinct parent without changing n1 inputs.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    for folder={'Schema_v3','Dynamics_v3','Simulation_v3','Orbit_v3','Numerics_v3','Stability_v3','Research_v3/Drivers_v3'}
        V3LegacyAddPath_v3(fullfile(v3,folder{1}));
    end
    loaded=load(V3Path_v3(fullfile(here,'n0_flip_BL2_sector_candidates.mat')),'catalog');catalog=loaded.catalog;
    source=load(V3Path_v3(fullfile(here,'arming_n0_parent_03.mat')),'x','q','parameters');
    saved=load(V3Path_v3(fullfile(here,'two_BL_n0_chart_validation.mat')),'audit');assert(saved.audit.passed);
    helperPath='Numerics_v3/EventOrderChartJacobian_v3.m';helperHash=RoundSHA256_v3(fullfile(v3,helperPath));
    assert(strcmp(helperHash,saved.audit.helper_sha256),'Helper changed after the n0 BL2 physical gate.');
    parentSeed=struct('state',source.x,'mode',source.q,'parameter',source.parameters, ...
        'return_policy','BL-marked-apex-return','occurrence',1, ...
        'provenance',struct('source_spectral_artifact',catalog.source_artifact,'source_spectral_sha256',catalog.source_sha256));
    options=struct('Symmetry','none','Energy',catalog.source_energy, ...
        'Integration',struct('RelTol',1e-12,'AbsTol',1e-14,'MaxStep',.005), ...
        'ReplayIntegration',struct('RelTol',1e-13,'AbsTol',1e-15,'MaxStep',.0025), ...
        'Acceptance',struct('FullClosureTolerance',1e-8,'EnergyTolerance',1e-8), ...
        'MaxReturnTime',10,'MaxWallSeconds',60);
    [parentOrbit,parentReport]=PeriodicSolutionSolver_v3(parentSeed,options);
    save(V3Path_v3(fullfile(here,'n0_parent_service_admission.mat')),'parentOrbit','parentReport','parentSeed','options','-v7');
    assert(~isempty(parentOrbit)&&parentReport.accepted,'n0 parent did not pass shared-service fresh admission.');
    seed=parentSeed;seed.occurrence=2;seed.provenance.chart_validation='Research_v3/next_round/theory/two_BL_n0_chart_validation.mat';
    candidate=struct('id','PIP_n0_measured_flip_BL2_front_hind','seed',seed, ...
        'parent_label','PIP','parent_independently_admitted',true, ...
        'parent_admission_artifact','Research_v3/next_round/theory/n0_parent_service_admission.mat', ...
        'evidence','Research_v3/next_round/theory/n0_flip_BL2_sector_candidates.mat', ...
        'physical_directions',[catalog.candidates(1).physical_direction,catalog.candidates(3).physical_direction], ...
        'target_labels',{{'HB_front','HB_hind'}},'target_flight_counts',[2,2], ...
        'signed_amplitudes',catalog.signed_amplitudes,'source_energy',catalog.source_energy, ...
        'direction_origin','Measured n0 unrestricted physical energy-leaf flip eigenvectors in invariant front/hind antisymmetric sectors', ...
        'required_primitive_BL_occurrence',2, ...
        'contact_count_hypothesis','Two actual TD and LO per leg over the two-BL cycle; no automatic promotion to archived one-TD-per-leg B2.', ...
        'gait_typing','Actual corrected state/contact classifier and positive flight count determine the node type.', ...
        'frozen_utc',char(datetime('now','TimeZone','UTC')), ...
        'full_map_regularity','Numerical common C1 derivative under recorded hypotheses; unrestricted C2 unproved.', ...
        'regular_bifurcation_claimed',false,'ancestry_claimed',false);
    artifact='Research_v3/next_round/theory/n0_flip_BL2_candidate.mat';save(V3Path_v3(fullfile(v3,artifact)),'candidate','-v7');
    registration=struct('schema_version','prospective-n0-measured-flip-BL2-experiment-v3-1', ...
        'registered_utc',candidate.frozen_utc,'source_spectral_artifact',catalog.source_artifact, ...
        'source_spectral_sha256',catalog.source_sha256,'helper_path',helperPath,'helper_sha256',helperHash, ...
        'chart_validation_artifact','Research_v3/next_round/theory/two_BL_n0_chart_validation.mat', ...
        'parent_admission_artifact',candidate.parent_admission_artifact, ...
        'parent_admission_full_closure',parentReport.full_closure, ...
        'source_energy',catalog.source_energy, ...
        'measured_front_multiplier',catalog.candidates(1).measured_multiplier, ...
        'measured_hind_multiplier',catalog.candidates(3).measured_multiplier, ...
        'signed_amplitudes',candidate.signed_amplitudes, ...
        'constraint','Signed amplitude inside full physical-coordinate/energy augmented corrector; symmetry none', ...
        'BL_touchdowns_per_return',2,'required_primitive_BL_occurrence',2, ...
        'actual_flight_count_required',2,'acceptance_tolerances_changed',false, ...
        'candidates',struct('id',candidate.id,'candidate_artifact',artifact,'candidate_variable','candidate'), ...
        'hypothesis_scope',candidate.contact_count_hypothesis,'ancestry_claimed',false);
    RoundJSON_v3(fullfile(v3,'Research_v3/next_round/period_two_n0_candidate_registration.json'),registration);
    fprintf('Registered n0 BL2 front/hind candidate atE%.12g; parent fresh shared-service closure%.3g.\n',catalog.source_energy,parentReport.full_closure);
end
