function report=RunDirectionalFloquetAudit_v3(target)
%RUNDIRECTIONALFLOQUETAUDIT_V3 Full physical tangent in a common order chart.
% This is a registered derivative audit, not a change of physical guards.
% Within a TD/LO cohort, different regular zero-compression leg saltations
% commute. Raw split orders are retained; compatibility uses the declared
% common C1 chart only after all physical/occurrence gates pass.
    if nargin<1,target='imported_PK';end
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    folders={'Schema_v3','Dynamics_v3','Simulation_v3','Orbit_v3','Numerics_v3'};
    for k=1:numel(folders),V3LegacyAddPath_v3(fullfile(v3,folders{k}));end
    source=load(V3Path_v3(fullfile(here,['arming_',char(target),'_03.mat'])),'x','q','parameters');
    x=source.x;q=source.q;p=source.parameters;
    chart=QuadrupedPhysicalChart_v3.create(x,q,p);u=x(chart.independent_indices);
    settings=struct('RelTol',1e-12,'AbsTol',1e-14,'MaxStep',.005, ...
        'EventValueTolerance',1e-10,'EventTimeTolerance',1e-12, ...
        'SimultaneousTimeTolerance',1e-10,'ArmingTolerance',1e-11);
    map=PoincareMap_v3(Quadrupedal_Dynamics_v3(),PoincareSection_v3.apex(4), ...
        HybridSimulator_v3(settings),BLMarkedApexReturnPolicy_v3(), ...
        struct('MaxReturnTime',10));
    observations=struct('coordinates',{},'next_coordinates',{},'period',{}, ...
        'raw_cyclic_signature',{},'raw_section_signature',{}, ...
        'raw_cluster_signature',{},'event_ids',{},'event_times',{}, ...
        'minimum_guard_transversality',{},'section_transversality',{}, ...
        'cohort_gap',{},'energy_difference',{},'failure',{});
    [base,baseMetadata]=commonReturn(u);
    baseClosure=norm(base-u,inf);assert(baseClosure<1e-8);
    clock=tic;
    report=struct('schema_version','full-physical-directional-floquet-v3-1', ...
        'target',char(target),'matlab_version',version, ...
        'created_utc',char(datetime('now','TimeZone','UTC')), ...
        'physical_parameters',p,'physical_chart',chart,'integration_settings',settings, ...
        'relative_steps',[2e-4,1e-4], ...
        'registered_relative_matrix_tolerance',1e-3, ...
        'registered_energy_covector_tolerance',1e-6, ...
        'base_full_physical_closure',baseClosure,'state','running');
    write(report);
    fd=HybridFiniteDifferenceJacobian_v3(struct('RelativeCandidateSteps',[2e-4,1e-4], ...
        'UseRichardson',false,'MaximumRelativeError',1e-3,'FailurePolicy','nan'));
    [defaultMatrix,~,differentiation]=fd.compute(@commonReturn,u);
    matrix=NaN(chart.dimension);coarse=matrix;forward=matrix;backward=matrix;
    columnGates=false(chart.dimension,1);
    for column=1:chart.dimension
        candidates=differentiation.columns(column).candidates;
        if ~isempty(candidates(1).derivative),coarse(:,column)=candidates(1).derivative;end
        last=candidates(end);
        if ~isempty(last.derivative),matrix(:,column)=last.derivative;end
        if last.forwardOneSided.available,forward(:,column)=last.forwardOneSided.derivative;end
        if last.backwardOneSided.available,backward(:,column)=last.backwardOneSided.derivative;end
        columnGates(column)=last.reliable&&last.forwardOneSided.available&&last.backwardOneSided.available;
    end
    report.finite_difference=differentiation;report.default_selected_matrix=defaultMatrix;
    report.common_coordinate_matrix=matrix;report.coarse_matrix=coarse;
    report.forward_matrix=forward;report.backward_matrix=backward;
    report.column_gates=columnGates;
    report.matrix_refinement_error=norm(matrix-coarse,inf)/max(1,norm(matrix,inf));
    report.one_sided_agreement_error=norm(forward-backward,inf)/max(1,norm(matrix,inf));
    report.observations=observations;report.elapsed_seconds=toc(clock);write(report);
    rng(1729,'twister');mixed=cell(8,1);recordIndex=0;
    for directionIndex=1:4
        direction=randn(chart.dimension,1);direction=direction/norm(direction);
        for step=[1e-4,5e-5]
            plus=commonReturn(u+step*direction);minus=commonReturn(u-step*direction);
            measured=(plus-minus)/(2*step);prediction=matrix*direction;
            recordIndex=recordIndex+1;
            mixed{recordIndex}=struct('direction',direction,'step',step, ...
                'measured',measured,'predicted',prediction, ...
                'relative_error',norm(measured-prediction,inf)/max(1,norm(prediction,inf)));
        end
    end
    report.mixed_directions=vertcat(mixed{:});
    report.max_mixed_direction_error=max([report.mixed_directions.relative_error]);
    [~,energy]=QuadrupedEnergy_v3.evaluate(x,q,p);
    gradient=energy.gradient(chart.independent_indices).';
    report.energy_covector_residual=norm(gradient*matrix-gradient,inf);
    report.reliable_numerical_full_derivative=all(columnGates)&& ...
        report.matrix_refinement_error<report.registered_relative_matrix_tolerance&& ...
        report.one_sided_agreement_error<report.registered_relative_matrix_tolerance&& ...
        report.max_mixed_direction_error<report.registered_relative_matrix_tolerance&& ...
        report.energy_covector_residual<report.registered_energy_covector_tolerance;
    if all(isfinite(matrix(:)))
        report.multipliers=eig(matrix);report.coarse_multipliers=eig(coarse);
        report.spectral_radius=max(abs(report.multipliers));
    else
        report.multipliers=NaN(chart.dimension,1);report.spectral_radius=NaN;
    end
    report.interpretation=['Full admissible physical section tangent, including energy. ', ...
        'Reliability is numerical under regular common-order C1 chart hypotheses; ', ...
        'no C2, certified existence, global coverage, or transverse restricted-spectrum substitution.'];
    report.base_metadata=baseMetadata;report.observations=observations;
    report.elapsed_seconds=toc(clock);report.state='completed';write(report);
    fprintf('%s full%dD reliable=%d refine%.3g +/-%.3g mixed%.3g energycovector%.3g radius%.12g\n', ...
        target,chart.dimension,report.reliable_numerical_full_derivative, ...
        report.matrix_refinement_error,report.one_sided_agreement_error, ...
        report.max_mixed_direction_error,report.energy_covector_residual,report.spectral_radius);
    function [value,metadata]=commonReturn(coordinates,varargin) %#ok<INUSD>
        trial=QuadrupedPhysicalChart_v3.lift(chart,coordinates);
        [next,info]=map.evaluate(trial,q,p);
        history=info.event_history;history=history(~[history.is_stop]);
        ids=[history.guard_id];times=[history.time];
        assert(numel(ids)==8&&isequal(sort(ids),1:8), ...
            'The regular full TD/LO cohort identity was lost.');
        assert(all(ismember(ids(1:4),[1,3,5,7]))&& ...
            all(ismember(ids(5:8),[2,4,6,8])), ...
            'A leg entered another cohort before the previous cohort completed.');
        gap=min(times(5:8))-max(times(1:4));assert(gap>1e-4);
        assert(info.discrete_closed&&info.cycle_complete&&info.admissible&& ...
            info.minimum_guard_transversality>1e-7&&info.section_transversality>1e-8, ...
            'Physical chart or transverse return requirements failed.');
        assert(info.section_chart.BL_touchdowns_per_return==1&& ...
            info.section_chart.selected_return_BL_occurrence==2, ...
            'The marked return occurrence changed.');
        assert(all(abs([history.value])<settings.EventValueTolerance*2), ...
            'A physical reset is not on its zero-compression surface.');
        value=next(chart.independent_indices);
        energyDifference=QuadrupedEnergy_v3.evaluate(next,info.final_mode,p)- ...
            QuadrupedEnergy_v3.evaluate(trial,q,p);
        assert(abs(energyDifference)<1e-9,'Energy changed under the trial return.');
        metadata=struct('success',true,'valid',true,'admissible',true, ...
            'integration_success',true,'discrete_closed',true,'cycle_complete',true, ...
            'return_policy_accepted',true,'return_multiplicity',info.return_multiplicity, ...
            'minimum_guard_transversality',info.minimum_guard_transversality, ...
            'section_transversality',info.section_transversality, ...
            'cyclic_event_signature','common-C1-TD-BLBRFLFR-LO-BLBRFLFR', ...
            'section_relative_event_signature','BL-marked-common-C1-TD-LO', ...
            'event_cluster_signature','common-C1-independent-zero-compression-leg-cohorts', ...
            'raw_cyclic_signature',char(info.cyclic_event_signature), ...
            'raw_section_signature',char(info.section_relative_event_signature), ...
            'raw_cluster_signature',char(info.event_cluster_signature));
        observations(end+1)=struct('coordinates',coordinates,'next_coordinates',value, ...
            'period',info.period,'raw_cyclic_signature',metadata.raw_cyclic_signature, ...
            'raw_section_signature',metadata.raw_section_signature, ...
            'raw_cluster_signature',metadata.raw_cluster_signature, ...
            'event_ids',ids,'event_times',times, ...
            'minimum_guard_transversality',info.minimum_guard_transversality, ...
            'section_transversality',info.section_transversality,'cohort_gap',gap, ...
            'energy_difference',energyDifference,'failure','');
        if mod(numel(observations),12)==0
            fprintf('%s physical order-chart returns %d elapsed%.1fs\n',target,numel(observations),toc(clock));
            checkpoint=struct('state','partial-checkpoint','target',target, ...
                'observations',observations,'elapsed_seconds',toc(clock));write(checkpoint);
        end
    end
    function write(value)
        file=fullfile(here,['directional_floquet_',char(target),'.mat']);
        temporary=[file,'.partial.mat'];save(V3Path_v3(temporary),'value','-v7');movefile(V3Path_v3(temporary),V3Path_v3(file),'f');
        fid=fopen(V3Path_v3(fullfile(here,['directional_floquet_',char(target),'.json'])),'w');assert(fid>=0);
        cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
        document=value;
        for name={'multipliers','coarse_multipliers'}
            if isfield(document,name{1})
                numerical=document.(name{1});
                document.(name{1})=struct('real',real(numerical),'imag',imag(numerical));
            end
        end
        fprintf(fid,'%s\n',jsonencode(document,'PrettyPrint',true));
    end
end
