function summary=RunEventOrderJacobianValidation_v3()
%RUNEVENTORDERJACOBIANVALIDATION_V3 Execute the opt-in reusable helper.
    here=fileparts(mfilename('fullpath'));v3=fileparts(fileparts(fileparts(here)));
    paths={'Schema_v3','Dynamics_v3','Simulation_v3','Orbit_v3','Numerics_v3'};
    for k=1:numel(paths),V3LegacyAddPath_v3(fullfile(v3,paths{k}));end
    d=load(V3Path_v3(fullfile(here,'arming_imported_PK_03.mat')),'x','q','parameters');
    chart=QuadrupedPhysicalChart_v3.create(d.x,d.q,d.parameters);
    u=d.x(chart.independent_indices);[~,column]=ismember(5,chart.independent_indices);
    settings=struct('RelTol',1e-12,'AbsTol',1e-14,'MaxStep',.005, ...
        'EventValueTolerance',1e-10,'EventTimeTolerance',1e-12, ...
        'SimultaneousTimeTolerance',1e-10,'ArmingTolerance',1e-11);
    map=PoincareMap_v3(Quadrupedal_Dynamics_v3(),PoincareSection_v3.apex(4), ...
        HybridSimulator_v3(settings),BLMarkedApexReturnPolicy_v3(),struct('MaxReturnTime',10));
    options=struct('RelativeCandidateSteps',[1e-4,5e-5], ...
        'UseRichardson',false,'MaximumRelativeError',1e-3);
    strict=HybridFiniteDifferenceJacobian_v3(options);
    [strictMatrix,~,strictReport]=strict.compute(@reduced,u(column));
    options.PhysicalParameter=d.parameters;
    common=EventOrderChartJacobian_v3(options);
    [commonMatrix,~,commonReport]=common.compute(@reduced,u(column));
    [~,baseline]=reduced(u(column));
    [~,baselineDiagnostic]=common.normalizeMetadata(baseline);
    malformed=baseline;malformed.event_history=malformed.event_history([]);
    [~,malformedDiagnostic]=common.normalizeMetadata(malformed);
    summary=struct('schema_version','event-order-chart-helper-validation-v3-1', ...
        'matlab_version',version,'state_index',5,'target','imported_PK', ...
        'strict_reliable',strictReport.allReliable, ...
        'strict_failures',{strictReport.columns(1).failureReasons}, ...
        'common_reliable',commonReport.allReliable, ...
        'common_classical_first_derivative',commonReport.classicalDerivative, ...
        'common_chart_verified',commonReport.commonC1EventOrderChart, ...
        'common_matrix',commonMatrix,'common_estimated_error',commonReport.estimatedErrors, ...
        'baseline_chart_admitted',baselineDiagnostic.accepted, ...
        'missing_actual_events_rejected',~malformedDiagnostic.accepted, ...
        'missing_actual_events_reason',malformedDiagnostic.reason);
    assert(summary.common_reliable&&summary.common_chart_verified&& ...
        summary.baseline_chart_admitted&&summary.missing_actual_events_rejected);
    save(V3Path_v3(fullfile(here,'event_order_chart_validation.mat')), ...
        'summary','strictMatrix','strictReport','commonMatrix','commonReport','-v7');
    fid=fopen(V3Path_v3(fullfile(here,'event_order_chart_validation.json')),'w');assert(fid>=0);
    cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(summary,'PrettyPrint',true));
    fprintf('Opt-in commonC1 helper strictreliable%d -> commonreliable%d error%.3g\n', ...
        summary.strict_reliable,summary.common_reliable,summary.common_estimated_error);
    function [value,metadata]=reduced(coordinate,varargin) %#ok<INUSD>
        point=u;point(column)=coordinate;
        initial=QuadrupedPhysicalChart_v3.lift(chart,point);
        [next,metadata]=map.evaluate(initial,d.q,d.parameters);
        value=next(chart.independent_indices);
    end
end
