function [orbit, report, framework] = BipedalHybridExample_v3(options)
%BIPEDALHYBRIDEXAMPLE_V3 Generic-pipeline demonstration with a second model.
%   This factory uses the same simulator, map, residual, root solver,
%   continuation, and Floquet implementation as the quadruped framework.

    if nargin < 1
        options = struct();
    end
    defaults = struct( ...
        'Parameter', BipedalHybridModel_v3.defaultParameters(), ...
        'InitialGuess', BipedalHybridModel_v3.defaultApexGuess(), ...
        'InitialMode', BipedalHybridModel_v3.LEFT_FLIGHT, ...
        'ContinuationValues', [0.80, 0.81, 0.82], ...
        'RootSolverOptions', struct(), ...
        'SimulatorOptions', struct( ...
            'RelTol', 1e-10, 'AbsTol', 1e-12, 'MaxStep', 0.01), ...
        'MapOptions', struct( ...
            'MaxReturnTime', 5, 'MaxSectionCrossings', 4, ...
            'MaxCycleEvents', 16, 'ArmTolerance', 1e-8));
    options = mergeOptions(defaults, options);

    system = BipedalHybridModel_v3();
    p = system.validateParameter(options.Parameter);
    q = system.validateMode(options.InitialMode);
    simulator = HybridSimulator_v3(options.SimulatorOptions);
    section = system.apexSection();
    policy = system.strideReturnPolicy();
    map = PoincareMap_v3(system, section, simulator, policy, ...
        options.MapOptions);
    residual = PeriodicOrbitResidual_v3(map, [0; 0]);

    rootDefaults = struct( ...
        'Algorithm', 'newton', ...
        'Jacobian', FiniteDifferenceJacobian_v3(struct( ...
            'Method', 'central', 'RelativeStep', 1e-6)), ...
        'FunctionTolerance', 1e-9, ...
        'ResidualAcceptanceTolerance', 1e-8, ...
        'MaxIterations', 30, ...
        'MaxFunctionEvaluations', 1500, ...
        'StateScale', [0.1; 1]);
    rootOptions = mergeOptions(rootDefaults, options.RootSolverOptions);
    solver = RootSolver_v3(rootOptions);
    u0 = residual.packState(options.InitialGuess);
    [u, solveInfo] = solver.solve(residual, u0, p, q);
    if ~solveInfo.converged
        error('BipedalHybridExample_v3:RootSolveFailed', ...
            'Biped periodic-orbit solve failed: %s', solveInfo.message);
    end
    orbit = solveInfo.orbit;

    continuation = NumericalContinuation1D_v3(struct( ...
        'RootSolver', solver, ...
        'ActiveParameter', 'liftoff_impulse', ...
        'StopOnFailure', true));
    branch = continuation.run(residual, u, p, q, ...
        options.ContinuationValues);
    floquet = FloquetAnalysis_v3(struct( ...
        'TangentIndices', 1, ...
        'RelativeStep', 1e-4)).analyze(map, ...
            orbit.initial_state, orbit.initial_mode, orbit.parameter);

    report = struct( ...
        'converged', solveInfo.converged, ...
        'initial_residual_norm', norm(residual.evaluate(u0, p, q), inf), ...
        'residual_norm', solveInfo.residualNorm, ...
        'solve_info', solveInfo, ...
        'branch', branch, ...
        'floquet', floquet, ...
        'event_sequence', string({orbit.event_history.type}).', ...
        'candidate_apex_count', orbit.candidate_apex_count, ...
        'accepted_apex_index', orbit.accepted_apex_index);
    framework = struct( ...
        'system', system, 'simulator', simulator, ...
        'section', section, 'return_policy', policy, ...
        'map', map, 'residual', residual, 'root_solver', solver, ...
        'continuation', continuation);
end

function output = mergeOptions(defaults, supplied)
    if ~isstruct(supplied) || ~isscalar(supplied)
        error('BipedalHybridExample_v3:InvalidOptions', ...
            'Options must be a scalar structure.');
    end
    output = defaults;
    names = fieldnames(supplied);
    for index = 1:numel(names)
        output.(names{index}) = supplied.(names{index});
    end
end
