function [FloquetData, loadInfo] = LoadFloquetDataset(source)
%LOADFLOQUETDATASET Load and validate a reusable Floquet-v2 dataset.
%
%   DATA = LOADFLOQUETDATASET(FILE) loads the top-level scalar structure
%   FloquetData from FILE. DATA may also be supplied directly, or wrapped
%   in a scalar structure with a FloquetData field. This function never
%   computes a Floquet matrix.
%
%   The loader deliberately rejects legacy FDM_v2 spectra and structures
%   without reduced Poincare-map provenance. It also checks array shapes,
%   solved event times, distance indicators, and the eigenpair residual at
%   every accepted point.

    if nargin < 1 || isempty(source)
        error('LoadFloquetDataset:MissingSource', ...
            'A Floquet dataset filename or structure is required.');
    end

    loadInfo = struct('source_file', '', 'point_count', 0, ...
        'accepted_count', 0, 'status', 'not-loaded', ...
        'schema_version', '', 'converted_from_analysis', false, ...
        'authority_downgraded', false);
    if ischar(source) || (isstring(source) && isscalar(source))
        filename = char(source);
        if ~isfile(filename)
            error('LoadFloquetDataset:MissingFile', ...
                'Floquet dataset file does not exist: %s', filename);
        end
        variables = whos('-file', filename);
        names = {variables.name};
        if any(strcmp(names, 'FloquetData'))
            payload = load(filename, 'FloquetData');
            FloquetData = payload.FloquetData;
        elseif any(strcmp(names, 'analysis'))
            payload = load(filename, 'analysis');
            FloquetData = ...
                floquet.io.internal.BuildFloquetDatasetFromAnalysis( ...
                    payload.analysis);
            loadInfo.converted_from_analysis = true;
        else
            error('LoadFloquetDataset:MissingVariable', ...
                ['MAT file must contain FloquetData or a canonical ' ...
                 'AnalyzeFloquetBranch variable named analysis.']);
        end
        loadInfo.source_file = CanonicalFile(filename);
    elseif isstruct(source) && isscalar(source)
        if isfield(source, 'FloquetData')
            FloquetData = source.FloquetData;
        elseif isfield(source, 'analysis')
            FloquetData = ...
                floquet.io.internal.BuildFloquetDatasetFromAnalysis( ...
                    source.analysis);
            loadInfo.converted_from_analysis = true;
        elseif isfield(source, 'version') && ...
                startsWith(char(string(source.version)), ...
                    'floquet-branch-analysis-')
            FloquetData = ...
                floquet.io.internal.BuildFloquetDatasetFromAnalysis(source);
            loadInfo.converted_from_analysis = true;
        else
            FloquetData = source;
        end
    else
        error('LoadFloquetDataset:InvalidSource', ...
            'Source must be a filename or scalar structure.');
    end

    ValidateRequiredFields(FloquetData);
    FloquetData = NormalizeVectors(FloquetData);
    schemaVersion = ValidateSchemaVersion(FloquetData);
    [FloquetData,loadInfo.authority_downgraded] = ...
        NormalizeDatasetAuthority(FloquetData,schemaVersion);
    ValidateProvenance(FloquetData.computation_info,schemaVersion);
    pointCount = numel(FloquetData.branch_index);
    ValidateShapes(FloquetData, pointCount);
    accepted = ResolveAccepted(FloquetData.computation_info, pointCount);
    baseEventTimeValid = ResolveBaseEventTimeValid( ...
        FloquetData.computation_info, accepted, pointCount);
    ValidateComputationSummary(FloquetData.computation_info, accepted);
    ValidateNumericalContent(FloquetData, accepted, baseEventTimeValid);
    ValidateCrossFieldProvenance(FloquetData.computation_info, ...
        FloquetData.branch_index, accepted, schemaVersion);
    ValidateIndicators(FloquetData.bifurcation_indicator, ...
        FloquetData.branch_index, accepted, FloquetData.computation_info);

    loadInfo.point_count = pointCount;
    loadInfo.accepted_count = nnz(accepted);
    loadInfo.status = DatasetStatus(accepted);
    if isfield(FloquetData, 'schema_version')
        loadInfo.schema_version = char(string(FloquetData.schema_version));
    elseif isfield(FloquetData.computation_info, 'schema_version')
        loadInfo.schema_version = ...
            char(string(FloquetData.computation_info.schema_version));
    end
end

function [data,downgraded] = NormalizeDatasetAuthority(data,schemaVersion)
%NORMALIZEDATASETAUTHORITY Safely interpret schema-1.0 diagnostic metadata.
% Schema 1.0 was produced by the retired diagnostic generator. It remains
% loadable for frozen viewer datasets, but can never be a second scientific
% authority. Older caches that claimed otherwise are downgraded in memory
% and explicitly marked. No current writer emits schema 1.0.
    downgraded = false;
    if ~strcmp(schemaVersion,'1.0')
        return
    end
    info = data.computation_info;
    if isfield(info,'scientific_authority')
        if ~IsBooleanScalar(info.scientific_authority)
            error('LoadFloquetDataset:InvalidScientificAuthority', ...
                'scientific_authority must be scalar logical.');
        end
        downgraded = IsTrueScalar(info.scientific_authority);
        info.original_scientific_authority = ...
            logical(info.scientific_authority);
    else
        info.original_scientific_authority = false;
    end
    if ~isfield(info,'production_evaluator')
        algorithm = char(string(info.algorithm_id));
        info.production_evaluator = strcmp( ...
            algorithm,'reduced-poincare-fdm-v2');
    elseif ~IsBooleanScalar(info.production_evaluator)
        error('LoadFloquetDataset:InvalidProductionEvaluator', ...
            'production_evaluator must be scalar logical.');
    end
    info.scientific_authority = false;
    info.dataset_role = 'diagnostic-gui-cache';
    info.authority_normalized_by_loader = downgraded;
    info.scientific_authority_basis = [ ...
        'schema 1.0 is a historical diagnostic viewer cache; ' ...
        'canonical authority requires AnalyzeFloquetBranch'];
    data.computation_info = info;
end

function value = ValidateSchemaVersion(data)
    if isfield(data, 'schema_version')
        value = char(string(data.schema_version));
    elseif isfield(data.computation_info, 'schema_version')
        value = char(string(data.computation_info.schema_version));
    else
        error('LoadFloquetDataset:MissingSchemaVersion', ...
            'FloquetData must identify a supported schema version.');
    end
    supported = {'1.0', '1.1-analysis-view'};
    if ~any(strcmp(value, supported))
        error('LoadFloquetDataset:UnsupportedSchemaVersion', ...
            'Unsupported FloquetData schema version: %s', value);
    end
end

function ValidateCrossFieldProvenance( ...
        info, branchIndices, accepted, schemaVersion)
    pointCount = numel(branchIndices);
    if strcmp(schemaVersion,'1.1-analysis-view') && ...
            isfield(info,'scientific_authority') && ...
            IsTrueScalar(info.scientific_authority) && ...
            ~isequal(double(branchIndices(:).'),1:pointCount)
        error('LoadFloquetDataset:AuthoritativeCoverageMismatch', ...
            ['An authoritative analysis view must contain every source ' ...
             'branch column exactly once in original order (1:N).']);
    end
    if isfield(info, 'selected_columns') && ...
            ~isequal(double(info.selected_columns(:).'), ...
                double(branchIndices(:).'))
        error('LoadFloquetDataset:SelectedColumnsMismatch', ...
            'computation_info.selected_columns must equal branch_index.');
    end
    hasIntervalReliability = isfield(info, 'interval_reliability');
    if strcmp(schemaVersion, '1.1-analysis-view') && ...
            ~hasIntervalReliability
        error('LoadFloquetDataset:MissingIntervalReliability', ...
            ['Schema 1.1 analysis views must retain the canonical adjacent-' ...
             'interval reliability mask.']);
    end
    if hasIntervalReliability
        value = info.interval_reliability;
        if numel(value) ~= max(0, pointCount - 1) || ...
                ~IsBooleanArray(value)
            error('LoadFloquetDataset:IntervalReliability', ...
                ['computation_info.interval_reliability must contain one ' ...
                 'logical 0/1 value per adjacent stored interval.']);
        end
        value = logical(value(:).');
        admissible = accepted(1:end-1) & accepted(2:end) & ...
            diff(branchIndices) == 1;
        if any(value & ~admissible)
            error('LoadFloquetDataset:InconsistentIntervalReliability', ...
                ['A reliable interval requires two accepted endpoints and ' ...
                 'consecutive original branch columns.']);
        end
    end
    if isfield(info, 'adjacent_event_topology_consistent')
        topology = info.adjacent_event_topology_consistent;
        if numel(topology) ~= max(0, pointCount - 1) || ...
                ~IsBooleanArray(topology)
            error('LoadFloquetDataset:AdjacentTopologyConsistency', ...
                ['adjacent_event_topology_consistent must contain one ' ...
                 'logical 0/1 value per adjacent stored interval.']);
        end
        if hasIntervalReliability && any(logical( ...
                info.interval_reliability(:).') & ...
                ~logical(topology(:).'))
            error('LoadFloquetDataset:ReliabilityTopologyMismatch', ...
                ['A reliable interval cannot be marked event-topology ' ...
                 'inconsistent.']);
        end
    end
end

function ValidateRequiredFields(data)
    required = {'branch_index', 'continuation_parameter', ...
        'solution_state', 'event_time', 'floquet_matrix', ...
        'eigenvalues', 'eigenvectors', 'distance_plus_one', ...
        'distance_minus_one', 'unit_circle_distance', ...
        'bifurcation_indicator', 'computation_info'};
    if ~isstruct(data) || ~isscalar(data)
        error('LoadFloquetDataset:InvalidData', ...
            'FloquetData must be a scalar structure.');
    end
    missing = required(~isfield(data, required));
    if ~isempty(missing)
        error('LoadFloquetDataset:MissingFields', ...
            'FloquetData is missing required fields: %s', ...
            strjoin(missing, ', '));
    end
end

function data = NormalizeVectors(data)
    vectorFields = {'branch_index', 'continuation_parameter', ...
        'distance_plus_one', 'distance_minus_one', ...
        'unit_circle_distance'};
    for i = 1:numel(vectorFields)
        value = data.(vectorFields{i});
        if ~isnumeric(value) || ~isvector(value)
            error('LoadFloquetDataset:InvalidVectorShape', ...
                '%s must be a numeric row or column vector.', ...
                vectorFields{i});
        end
    end
    data.branch_index = data.branch_index(:).';
    data.continuation_parameter = data.continuation_parameter(:).';
    data.distance_plus_one = data.distance_plus_one(:).';
    data.distance_minus_one = data.distance_minus_one(:).';
    data.unit_circle_distance = data.unit_circle_distance(:).';
end

function ValidateProvenance(info,schemaVersion)
    if ~isstruct(info) || ~isscalar(info)
        error('LoadFloquetDataset:InvalidComputationInfo', ...
            'computation_info must be a scalar structure.');
    end
    if ~isfield(info, 'floquet_method') || ...
            ~(ischar(info.floquet_method) || ...
              (isstring(info.floquet_method) && isscalar(info.floquet_method)))
        error('LoadFloquetDataset:MissingProvenance', ...
            ['Dataset does not identify the corrected reduced Poincare-map ' ...
             'Floquet method. Legacy FDM_v2 files are not accepted.']);
    end
    method = lower(char(string(info.floquet_method)));
    method = strrep(method, char(233), 'e');
    if ~contains(method, 'poincare') || ~contains(method, 'reduced')
        error('LoadFloquetDataset:LegacyMethodRejected', ...
            ['Dataset is not marked as output of the corrected reduced ' ...
             'Poincare-map Floquet algorithm.']);
    end
    if ~isfield(info, 'event_time_policy') || ...
            ~contains(lower(char(string(info.event_time_policy))), ...
                'not included')
        error('LoadFloquetDataset:InvalidEventTimePolicy', ...
            ['Dataset must state that solved event times are not included ' ...
             'in the Floquet state.']);
    end
    machineFields = {'algorithm_id', 'reduced_state_indices', ...
        'section_normal_state_index', ...
        'floquet_state_includes_event_times'};
    if ~all(isfield(info, machineFields))
        error('LoadFloquetDataset:MissingMachineProvenance', ...
            ['Dataset is missing machine-readable reduced-map ' ...
             'provenance fields.']);
    end
    algorithm = char(string(info.algorithm_id));
    requiredFlags = {'production_evaluator','scientific_authority'};
    if ~all(isfield(info, requiredFlags)) || ...
            ~IsBooleanScalar(info.production_evaluator) || ...
            ~IsBooleanScalar(info.scientific_authority)
        error('LoadFloquetDataset:MissingAuthorityProvenance', ...
            ['Dataset must explicitly record scalar production_evaluator ' ...
             'and scientific_authority flags.']);
    end
    if strcmp(algorithm, 'nonproduction-evaluator')
        if ~IsFalseScalar(info.production_evaluator) || ...
                ~IsFalseScalar(info.scientific_authority)
            error('LoadFloquetDataset:InvalidNonProductionProvenance', ...
                ['A nonproduction evaluator must be explicitly marked as ' ...
                 'nonproduction and non-authoritative.']);
        end
    elseif ~strcmp(algorithm, 'reduced-poincare-fdm-v2')
        error('LoadFloquetDataset:InvalidAlgorithmIdentifier', ...
            'Unsupported Floquet algorithm identifier.');
    elseif ~IsTrueScalar(info.production_evaluator)
        error('LoadFloquetDataset:InvalidProductionProvenance', ...
            ['The reduced-poincare-fdm-v2 algorithm identifier requires ' ...
             'the production evaluator flag.']);
    end
    if strcmp(schemaVersion,'1.0')
        if ~IsFalseScalar(info.scientific_authority) || ...
                ~isfield(info,'dataset_role') || ...
                ~strcmp(char(string(info.dataset_role)), ...
                    'diagnostic-gui-cache')
            error('LoadFloquetDataset:DiagnosticCacheAuthority', ...
                'Schema 1.0 GUI caches must be diagnostic and non-authoritative.');
        end
    elseif IsTrueScalar(info.scientific_authority)
        requiredSourceAuthority = { ...
            'source_analysis_algorithm_id', ...
            'source_analysis_production_evaluator', ...
            'source_analysis_scientific_authority', ...
            'source_analysis_full_parent_coverage', ...
            'source_analysis_ordered_parent_coverage', ...
            'source_analysis_parent_only'};
        if ~all(isfield(info,requiredSourceAuthority)) || ...
                ~strcmp(char(string(info.source_analysis_algorithm_id)), ...
                    'reduced-poincare-fdm-v2-canonical-branch-scan') || ...
                ~all(cellfun(@(name) IsTrueScalar(info.(name)), ...
                    requiredSourceAuthority(2:end)))
            error('LoadFloquetDataset:InvalidAnalysisViewAuthority', ...
                ['An authoritative analysis view requires explicit canonical ' ...
                 'full-parent, ordered, parent-only source provenance.']);
        end
    end
    if ~isequal(info.reduced_state_indices(:).', [1 2 4:13]) || ...
            ~(isnumeric(info.section_normal_state_index) && ...
            isscalar(info.section_normal_state_index) && ...
            info.section_normal_state_index == 3)
        error('LoadFloquetDataset:InvalidReducedChart', ...
            ['Dataset must use reduced coordinates [1 2 4:13] with ' ...
             'state 3 normal to the apex section.']);
    end
    value = info.floquet_state_includes_event_times;
    validFalse = (islogical(value) && isscalar(value) && ~value) || ...
        (isnumeric(value) && isreal(value) && isscalar(value) && ...
        isfinite(value) && value == 0);
    if ~validFalse
        error('LoadFloquetDataset:EventTimesInFloquetState', ...
            'Solved event times must not be declared as Floquet states.');
    end
end

function tf = IsFalseScalar(value)
    tf = (islogical(value) && isscalar(value) && ~value) || ...
        (isnumeric(value) && isreal(value) && isscalar(value) && ...
         isfinite(value) && value == 0);
end

function tf = IsTrueScalar(value)
    tf = (islogical(value) && isscalar(value) && value) || ...
        (isnumeric(value) && isreal(value) && isscalar(value) && ...
         isfinite(value) && value == 1);
end

function tf = IsBooleanScalar(value)
    tf = IsFalseScalar(value) || IsTrueScalar(value);
end

function ValidateShapes(data, pointCount)
    if pointCount < 1 || ~isnumeric(data.branch_index) || ...
            any(~isfinite(data.branch_index)) || ...
            any(data.branch_index ~= floor(data.branch_index)) || ...
            any(data.branch_index < 1) || ...
            numel(unique(data.branch_index)) ~= pointCount || ...
            any(diff(data.branch_index) <= 0)
        error('LoadFloquetDataset:InvalidBranchIndex', ...
            'branch_index must contain unique positive integer columns.');
    end
    if ~isnumeric(data.continuation_parameter) || ...
            ~isreal(data.continuation_parameter) || ...
            numel(data.continuation_parameter) ~= pointCount || ...
            any(~isfinite(data.continuation_parameter))
        error('LoadFloquetDataset:InvalidContinuationParameter', ...
            'continuation_parameter must contain one finite real value per point.');
    end
    RequireSize(data.solution_state, [13 pointCount], 'solution_state');
    RequireSize(data.event_time, [9 pointCount], 'event_time');
    RequireSize3(data.floquet_matrix, [12 12 pointCount], 'floquet_matrix');
    RequireSize(data.eigenvalues, [12 pointCount], 'eigenvalues');
    RequireSize3(data.eigenvectors, [12 12 pointCount], 'eigenvectors');
    distanceFields = {'distance_plus_one', 'distance_minus_one', ...
        'unit_circle_distance'};
    for i = 1:numel(distanceFields)
        value = data.(distanceFields{i});
        if ~isnumeric(value) || ~isreal(value) || numel(value) ~= pointCount
            error('LoadFloquetDataset:InvalidDistanceShape', ...
                '%s must contain one real value per point.', distanceFields{i});
        end
    end
end

function baseValid = ResolveBaseEventTimeValid(info, accepted, count)
    if ~isfield(info, 'base_event_time_valid')
        baseValid = accepted;
        return;
    end
    values = info.base_event_time_valid;
    if numel(values) ~= count || ~IsBooleanArray(values)
        error('LoadFloquetDataset:InvalidBaseEventTimeValidity', ...
            ['computation_info.base_event_time_valid must contain one ' ...
             'logical 0/1 value per point.']);
    end
    baseValid = logical(values(:).');
    if any(accepted & ~baseValid)
        error('LoadFloquetDataset:AcceptedPointWithoutBaseTiming', ...
            'Every accepted Floquet point must have valid solved base event times.');
    end
end

function ValidateComputationSummary(info, accepted)
    expectedAccepted = nnz(accepted);
    expectedRejected = numel(accepted) - expectedAccepted;
    expectedStatus = DatasetStatus(accepted);
    if ~isfield(info, 'status') || ...
            ~strcmp(char(string(info.status)), expectedStatus)
        error('LoadFloquetDataset:InconsistentStatus', ...
            'computation_info.status is inconsistent with the acceptance mask.');
    end
    if isfield(info, 'accepted_count') && ...
            (~isnumeric(info.accepted_count) || ...
            ~isscalar(info.accepted_count) || ...
            info.accepted_count ~= expectedAccepted)
        error('LoadFloquetDataset:InconsistentAcceptedCount', ...
            'computation_info.accepted_count is inconsistent.');
    end
    if isfield(info, 'rejected_count') && ...
            (~isnumeric(info.rejected_count) || ...
            ~isscalar(info.rejected_count) || ...
            info.rejected_count ~= expectedRejected)
        error('LoadFloquetDataset:InconsistentRejectedCount', ...
            'computation_info.rejected_count is inconsistent.');
    end
    if isfield(info, 'point') && ...
            (~isstruct(info.point) || numel(info.point) ~= numel(accepted))
        error('LoadFloquetDataset:InvalidPointSummary', ...
            'computation_info.point must contain one structure per point.');
    end
    if isfield(info, 'point') && isfield(info.point, 'accepted')
        values = [info.point.accepted];
        if ~IsBooleanArray(values) || ...
                ~isequal(logical(values(:).'), accepted)
            error('LoadFloquetDataset:InconsistentPointAcceptance', ...
                'computation_info.point.accepted is inconsistent.');
        end
    end
end

function RequireSize(value, expected, name)
    if ~isnumeric(value) || ~isequal(size(value), expected)
        error('LoadFloquetDataset:InvalidArrayShape', ...
            '%s must have size %s.', name, mat2str(expected));
    end
end

function RequireSize3(value, expected, name)
    actual = [size(value, 1), size(value, 2), size(value, 3)];
    if ~isnumeric(value) || ~isequal(actual, expected)
        error('LoadFloquetDataset:InvalidArrayShape', ...
            '%s must have size %s.', name, mat2str(expected));
    end
end

function accepted = ResolveAccepted(info, count)
    if ~isfield(info, 'accepted') || ...
            numel(info.accepted) ~= count
        error('LoadFloquetDataset:MissingAcceptance', ...
            'computation_info.accepted must contain one value per point.');
    end
    values = info.accepted;
    validType = islogical(values) || ...
        (isnumeric(values) && isreal(values) && ...
         all(isfinite(values(:))) && all(ismember(values(:), [0 1])));
    if ~validType
        error('LoadFloquetDataset:InvalidAcceptance', ...
            'computation_info.accepted must contain only logical 0/1 values.');
    end
    accepted = logical(values(:).');
end

function ValidateNumericalContent(data, accepted, baseEventTimeValid)
    if ~isreal(data.solution_state) || ...
            any(~isfinite(data.solution_state), 'all')
        error('LoadFloquetDataset:NonfiniteState', ...
            'solution_state must be finite at every stored branch point.');
    end
    for k = 1:numel(accepted)
        M = data.floquet_matrix(:, :, k);
        lambda = data.eigenvalues(:, k);
        V = data.eigenvectors(:, :, k);
        eventTime = data.event_time(:, k);
        if baseEventTimeValid(k)
            if ~isreal(eventTime) || any(~isfinite(eventTime)) || ...
                    eventTime(9) <= 0
                error('LoadFloquetDataset:InvalidSolvedEventTime', ...
                    ['Point %d is marked as having valid base timing but ' ...
                     'does not store nine finite solved event times.'], k);
            end
        elseif ~isreal(eventTime) || any(~isnan(eventTime))
            error('LoadFloquetDataset:UnexpectedSolvedEventTime', ...
                ['Point %d has no valid base timing and must use NaN ' ...
                 'event-time entries.'], k);
        end
        if accepted(k)
            finite = isreal(M) && all(isfinite(M(:))) && ...
                all(isfinite(real(lambda(:)))) && ...
                all(isfinite(imag(lambda(:)))) && ...
                all(isfinite(real(V(:)))) && ...
                all(isfinite(imag(V(:))));
            if ~finite
                error('LoadFloquetDataset:InvalidAcceptedPoint', ...
                    ['Accepted point %d must contain finite matrix/eigendata ' ...
                     'and nine solved event times with positive period.'], k);
            end
            vectorNorms = vecnorm(V, 2, 1);
            if any(~isfinite(vectorNorms)) || any(vectorNorms <= ...
                    100 * eps(max(1, norm(V, 'fro'))))
                error('LoadFloquetDataset:NullEigenvector', ...
                    'Stored eigendata contain a null vector at point %d.', k);
            end
            residual = norm(M * V - V * diag(lambda), 'fro') / ...
                max(1, norm(M, 'fro') * norm(V, 'fro'));
            if ~isfinite(residual) || residual > 1e-6
                error('LoadFloquetDataset:EigenpairMismatch', ...
                    'Stored eigendata fail the matrix residual check at point %d.', k);
            end
            expected = [min(abs(lambda - 1)), min(abs(lambda + 1)), ...
                min(abs(abs(lambda) - 1))];
            actual = [data.distance_plus_one(k), ...
                data.distance_minus_one(k), data.unit_circle_distance(k)];
            tolerance = 1e-10 * max(1, max(expected));
            if any(~isfinite(actual)) || any(abs(expected - actual) > tolerance)
                error('LoadFloquetDataset:DistanceMismatch', ...
                    'Stored distance indicators are inconsistent at point %d.', k);
            end
        else
            arrays = [M(:); lambda(:); V(:)];
            hasStoredValue = any(~isnan(real(arrays))) || ...
                any(isfinite(imag(arrays)) & imag(arrays) ~= 0);
            distances = [data.distance_plus_one(k), ...
                data.distance_minus_one(k), data.unit_circle_distance(k)];
            indicator = data.bifurcation_indicator(k);
            hasCandidate = IndicatorHasPayload(indicator);
            if hasStoredValue || any(~isnan(distances)) || hasCandidate
                error('LoadFloquetDataset:RejectedPointContainsData', ...
                    ['Rejected point %d must use NaN matrix, eigendata, ' ...
                     'distance entries, and no candidate marker. Solved ' ...
                     'base event times may be retained when separately valid.'], k);
            end
        end
    end
end

function ValidateIndicators(indicators, branchIndices, accepted, info)
    count = numel(branchIndices);
    if ~isstruct(indicators) || numel(indicators) ~= count
        error('LoadFloquetDataset:InvalidIndicators', ...
            'bifurcation_indicator must be a structure array with one entry per point.');
    end
    required = {'is_candidate', 'candidate_plus_one', ...
        'candidate_minus_one', 'candidate_unit_circle', 'labels'};
    if ~all(isfield(indicators, required))
        error('LoadFloquetDataset:InvalidIndicatorFields', ...
            'Each bifurcation indicator is missing required candidate fields.');
    end
    branchPointTestAvailable = false;
    if isfield(info, 'branch_point_test_available')
        value = info.branch_point_test_available;
        if ~IsBooleanArray(value) || ~isscalar(value)
            error('LoadFloquetDataset:InvalidBranchPointTestFlag', ...
                'branch_point_test_available must be a logical scalar.');
        end
        branchPointTestAvailable = logical(value);
    end
    for k = 1:count
        if isfield(indicators, 'branch_index') && ...
                ~(isnumeric(indicators(k).branch_index) && ...
                  isscalar(indicators(k).branch_index) && ...
                  indicators(k).branch_index == branchIndices(k))
            error('LoadFloquetDataset:IndicatorBranchIndex', ...
                'Each indicator branch_index must match branch_index.');
        end
        flagValues = {indicators(k).is_candidate, ...
            indicators(k).candidate_plus_one, ...
            indicators(k).candidate_minus_one, ...
            indicators(k).candidate_unit_circle};
        validFlags = cellfun(@(value) isscalar(value) && ...
            IsBooleanArray(value), flagValues);
        if ~all(validFlags)
            error('LoadFloquetDataset:InvalidIndicatorFlags', ...
                'Each candidate flag must be one logical 0/1 scalar.');
        end
        typeFlags = cellfun(@logical, flagValues(2:end));
        if logical(flagValues{1}) ~= any(typeFlags)
            error('LoadFloquetDataset:InconsistentIndicatorSummary', ...
                ['is_candidate must equal the logical OR of the typed ' ...
                 'candidate flags.']);
        end
        if isfield(indicators, 'candidate_torus')
            torus = indicators(k).candidate_torus;
            if ~(isscalar(torus) && IsBooleanArray(torus)) || ...
                    (logical(torus) && ...
                    ~logical(indicators(k).candidate_unit_circle))
                error('LoadFloquetDataset:InvalidTorusFlag', ...
                    ['candidate_torus must be a Boolean scalar and implies ' ...
                     'candidate_unit_circle.']);
            end
        end
        if ~iscell(indicators(k).labels) || ...
                ~all(cellfun(@(value) ischar(value) || ...
                (isstring(value) && isscalar(value)), ...
                indicators(k).labels))
            error('LoadFloquetDataset:InvalidIndicatorLabels', ...
                'Indicator labels must be a cell array of text scalars.');
        end
        if ~logical(indicators(k).is_candidate) && ...
                (~isempty(indicators(k).labels) || ...
                (isfield(indicators, 'details') && ...
                ~isempty(indicators(k).details)))
            error('LoadFloquetDataset:UnexpectedIndicatorPayload', ...
                'A noncandidate indicator cannot contain labels or details.');
        end
        if indicators(k).candidate_plus_one && ...
                ~branchPointTestAvailable && ...
                ~any(strcmp(indicators(k).labels, ...
                    'candidate +1 Floquet degeneracy'))
            error('LoadFloquetDataset:UnsafePlusOneLabel', ...
                ['A +1 crossing must be labelled ''candidate +1 Floquet ' ...
                 'degeneracy'', not asserted as a true bifurcation.']);
        end
    end
    ValidateAuthoritativeCandidateProjection( ...
        indicators, branchIndices, accepted, info, count);
end

function ValidateAuthoritativeCandidateProjection( ...
        indicators, branchIndices, accepted, info, count)
    if ~isfield(info, 'authoritative_candidates')
        return
    end
    candidates = info.authoritative_candidates;
    if ~isstruct(candidates)
        error('LoadFloquetDataset:AuthoritativeCandidates', ...
            'authoritative_candidates must be a structure array.');
    end
    expected = false(3, count);
    intervalReliability = true(1, max(0, count - 1));
    if isfield(info, 'interval_reliability')
        intervalReliability = logical(info.interval_reliability(:).');
    end
    for k = 1:numel(candidates)
        required = {'Type','LeftIndex','RightIndex','Fraction'};
        if ~all(isfield(candidates(k), required))
            error('LoadFloquetDataset:AuthoritativeCandidateContract', ...
                'An authoritative candidate is missing projection fields.');
        end
        left = candidates(k).LeftIndex;
        right = candidates(k).RightIndex;
        fraction = candidates(k).Fraction;
        if ~(isnumeric(left) && isscalar(left) && ...
                isnumeric(right) && isscalar(right) && ...
                left >= 1 && right == left + 1 && right <= count && ...
                branchIndices(right) == branchIndices(left) + 1 && ...
                isfinite(fraction) && fraction >= 0 && fraction <= 1 && ...
                accepted(left) && accepted(right) && ...
                intervalReliability(left))
            error('LoadFloquetDataset:UnreliableAuthoritativeCandidate', ...
                ['An authoritative candidate does not lie on one accepted, ' ...
                 'reliable adjacent interval.']);
        end
        local = left + (fraction > 0.5);
        switch char(string(candidates(k).Type))
            case '+1'
                row = 1;
            case '-1'
                row = 2;
            case 'complex-unit-circle'
                row = 3;
            otherwise
                error('LoadFloquetDataset:AuthoritativeCandidateType', ...
                    'Unknown authoritative candidate type.');
        end
        expected(row, local) = true;
    end
    actual = [logical([indicators.candidate_plus_one]); ...
        logical([indicators.candidate_minus_one]); ...
        logical([indicators.candidate_unit_circle])];
    if ~isequal(actual, expected)
        error('LoadFloquetDataset:CandidateProjectionMismatch', ...
            ['GUI candidate flags must exactly project the authoritative ' ...
             'candidate inventory.']);
    end
end

function hasPayload = IndicatorHasPayload(indicator)
    names = {'is_candidate', 'candidate_plus_one', ...
        'candidate_minus_one', 'candidate_unit_circle', 'candidate_torus'};
    hasPayload = false;
    for i = 1:numel(names)
        if isfield(indicator, names{i}) && ...
                isscalar(indicator.(names{i})) && ...
                IsBooleanArray(indicator.(names{i}))
            hasPayload = hasPayload || logical(indicator.(names{i}));
        end
    end
    if isfield(indicator, 'labels')
        hasPayload = hasPayload || ~isempty(indicator.labels);
    end
    if isfield(indicator, 'details')
        hasPayload = hasPayload || ~isempty(indicator.details);
    end
end

function valid = IsBooleanArray(values)
    valid = islogical(values) || ...
        (isnumeric(values) && isreal(values) && ...
        all(isfinite(values(:))) && all(ismember(values(:), [0 1])));
end

function status = DatasetStatus(accepted)
    if all(accepted)
        status = 'complete';
    elseif any(accepted)
        status = 'partial';
    else
        status = 'failed';
    end
end

function filename = CanonicalFile(filename)
    [status, attributes] = fileattrib(filename);
    if status
        filename = attributes.Name;
    end
end
