function files = legacyRestoredFiles_v3()
%LEGACYRESTOREDFILES_V3 Manifest restored from the parent v1/v2 commit.

    files = strings(0, 1);
    gaitNames = ["BE", "BG", "FG", "HE", "PK"];

    exactDirectories = ["1e-12", "1e-7"];
    exactSuffixes = ["1e-12", "1e-07"];
    for levelIndex = 1:numel(exactDirectories)
        directory = exactDirectories(levelIndex);
        suffix = exactSuffixes(levelIndex);
        for gait = gaitNames
            prefix = "BD1_20_2_" + gait + "_" + suffix;
            files(end + 1, 1) = directory + "/" + prefix + ".mat"; %#ok<AGROW>
            files(end + 1, 1) = directory + "/" + prefix + "_sorted.mat"; %#ok<AGROW>
        end
    end

    for gait = gaitNames
        if any(gait == ["BE", "BG"])
            prefix = "BD1_20_2_" + gait + ".mat_1e-06";
        else
            prefix = "BD1_20_2_" + gait + "_1e-06";
        end
        files(end + 1, 1) = "1e-6/" + prefix + ".mat"; %#ok<AGROW>
        files(end + 1, 1) = "1e-6/" + prefix + "_sorted.mat"; %#ok<AGROW>
    end

    for gait = gaitNames
        if any(gait == ["BE", "BG"])
            prefix = "BD1_20_2_" + gait + ".mat_1e-09";
        else
            prefix = "BD1_20_2_" + gait + "_1e-09";
        end
        files(end + 1, 1) = "1e-9/" + prefix + ".mat"; %#ok<AGROW>
        files(end + 1, 1) = "1e-9/" + prefix + "_sorted.mat"; %#ok<AGROW>
    end

    rootData = ["BD", "BE", "BG", "FG", "HE", "PK"];
    for gait = rootData
        files(end + 1, 1) = "BD1_20_2_" + gait + ".mat"; %#ok<AGROW>
    end
    files = [files; ...
        "EigenValuePlot_GUI.m"; ...
        "FDM_v2.m"; ...
        "Quadrupedal_ZeroFun_v2_FDM.m"; ...
        "log.text"];

    files = [files; ...
        "Constraint_Test/BD1_20_2_BD_1e-06_BLBR.mat"; ...
        "Constraint_Test/BD1_20_2_BD_1e-06_BLBR_sorted.mat"; ...
        "Constraint_Test/BD1_20_2_BD_1e-06_FLFR.mat"; ...
        "Constraint_Test/BD1_20_2_PK_1e-06_BLBR.mat"; ...
        "Constraint_Test/BD1_20_2_PK_1e-06_FLFR.mat"; ...
        "Constraint_Test/BD1_20_2_PK_1e-06_FLFRBLBR.mat"; ...
        "Constraint_Test/BD1_20_2_PK_1e-06_FLFRBLBR_sorted.mat"];

    files = [files; ...
        "Legacy/EV_PK_20_2.5_v2.5_1e-03.mat"; ...
        "Legacy/EV_PK_20_2.5_v2.5_1e-04.mat"; ...
        "Legacy/EV_PK_20_2.5_v2.5_1e-05.mat"; ...
        "Legacy/EV_PK_20_2.5_v2_1e-03.mat"; ...
        "Legacy/EV_PK_20_2.5_v2_1e-06.mat"; ...
        "Legacy/EV_PK_20_2.5_v2_1e-09.mat"; ...
        "Legacy/EV_PK_20_2.5_v3_1e-03.mat"; ...
        "Legacy/EV_PK_20_2.5_v3_1e-04.mat"; ...
        "Legacy/EV_PK_20_2.5_v3_1e-05.mat"; ...
        "Legacy/EV_PK_20_2.5_v4_1e-02_1e-05.mat"; ...
        "Legacy/EV_PK_20_2.5_v4_1e-02_1e-06.mat"; ...
        "Legacy/EV_PK_20_2.5_v4_1e-03_1e-05.mat"; ...
        "Legacy/FDM.m"];

    files = cellstr(files);
end
