classdef TestBranchSwitching_v3 < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addFrameworkPaths(testCase)
            root = fileparts(fileparts(mfilename('fullpath')));
            addpath(genpath(root));
            testCase.addTeardown(@() rmpath(genpath(root)));
        end
    end

    methods (Test)
        function unitMultiplierPredictorsCorrectToDistinctChild(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2, ...
                'ResidualAcceptanceTolerance', 1e-9));
            critical = TestBranchSwitching_v3.criticalPoint();

            result = switcher.switchUnitMultiplier( ...
                @TestBranchSwitching_v3.branchResidual, critical);

            testCase.verifyTrue(result.accepted, result.message);
            testCase.verifyEqual(sort(result.acceptedSigns), [-1, 1]);
            testCase.verifyEqual(result.predictors.plus.state, 0.05, ...
                'AbsTol', 1e-14);
            testCase.verifyEqual(result.predictors.minus.state, -0.05, ...
                'AbsTol', 1e-14);
            testCase.verifyEqual(sort([result.solutions.state]), ...
                [-0.05, 0.05], 'AbsTol', 2e-7);
            testCase.verifyEqual(sort([result.solutions.parameter]), ...
                [-0.05, 0.05], 'AbsTol', 2e-7);
            testCase.verifyGreaterThan([result.solutions.parentDistance], ...
                switcher.ParentDistanceTolerance .* ones(1, 2));
            testCase.verifyTrue(all([result.solutions.cycleClosed]));
            testCase.verifyTrue(all([result.solutions.admissible]));
            testCase.verifyTrue(all([result.solutions.topologyRecorded]));
            testCase.verifyTrue(all(arrayfun( ...
                @(solution) solution.topology.complete, ...
                result.solutions)));
            testCase.verifyLessThan([result.solutions.residualNorm], ...
                switcher.ResidualAcceptanceTolerance .* ones(1, 2));
        end

        function childTopologyRequiresEveryClosureDatum(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2));
            callbacks = { ...
                @TestBranchSwitching_v3.missingCyclicSignatureResidual, ...
                @TestBranchSwitching_v3.missingSectionSignatureResidual, ...
                @TestBranchSwitching_v3.missingClusterSignatureResidual, ...
                @TestBranchSwitching_v3.missingMultiplicityResidual, ...
                @TestBranchSwitching_v3.invalidMultiplicityResidual, ...
                @TestBranchSwitching_v3.missingSectionClusterEvidenceResidual};

            for index = 1:numel(callbacks)
                result = switcher.switchUnitMultiplier( ...
                    callbacks{index}, ...
                    TestBranchSwitching_v3.criticalPoint());
                testCase.verifyFalse(result.accepted, ...
                    sprintf('Incomplete topology case %d was accepted.', index));
                testCase.verifyTrue(all([result.attempts.converged]));
                testCase.verifyFalse(any([result.attempts.topologyRecorded]));
                testCase.verifyTrue(all(contains( ...
                    string({result.attempts.message}), ...
                    'complete, reliable, compatible hybrid topology')));
            end
        end

        function childTopologyRejectsEveryBoundaryFlag(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2));
            callbacks = { ...
                @TestBranchSwitching_v3.hybridBoundaryResidual, ...
                @TestBranchSwitching_v3.sectionEventCoincidenceResidual, ...
                @TestBranchSwitching_v3.sectionClusterCoincidenceResidual, ...
                @TestBranchSwitching_v3.unresolvedOrderingResidual};

            for index = 1:numel(callbacks)
                result = switcher.switchUnitMultiplier( ...
                    callbacks{index}, ...
                    TestBranchSwitching_v3.criticalPoint());
                testCase.verifyFalse(result.accepted, ...
                    sprintf('Hybrid-boundary case %d was accepted.', index));
                testCase.verifyTrue(all([result.attempts.converged]), ...
                    sprintf(['Hybrid-boundary case %d must reach a ', ...
                    'numerically converged but topology-ineligible child.'], ...
                    index));
                testCase.verifyFalse(any([result.attempts.topologyRecorded]));
                testCase.verifyTrue(all(contains( ...
                    string({result.attempts.message}), ...
                    'complete, reliable, compatible hybrid topology')));
            end
        end

        function doubledMapPropagatesTopologyHazardsAndEvidence(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PeriodOneExclusionTolerance', 1e-6));
            [~, complete] = switcher.doubledReturnResidual( ...
                @TestBranchSwitching_v3.topologyProbeMap, 0.05, 0, 0);
            testCase.verifyEqual(complete.return_multiplicity, 2);
            testCase.verifyTrue(complete.return_multiplicity_evidence);
            testCase.verifyFalse(complete.hybridChartBoundary);
            testCase.verifyTrue(complete.hybridChartBoundaryEvidence);
            testCase.verifyFalse(complete.section_event_coincidence);
            testCase.verifyTrue(complete.section_event_coincidenceEvidence);
            testCase.verifyFalse(complete.section_cluster_coincidence);
            testCase.verifyTrue(complete.section_cluster_coincidenceEvidence);
            testCase.verifyFalse(complete.unresolvedSimultaneousOrdering);
            testCase.verifyTrue( ...
                complete.unresolvedSimultaneousOrderingEvidence);

            [~, boundary] = switcher.doubledReturnResidual( ...
                @TestBranchSwitching_v3.topologyProbeBoundaryMap, ...
                0.05, 0, 0);
            testCase.verifyTrue(boundary.hybridChartBoundary);
            testCase.verifyTrue(boundary.hybridChartBoundaryEvidence);
        end

        function doubledReturnAcceptsTruePeriodTwoOrbit(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2, ...
                'PeriodOneExclusionTolerance', 1e-3, ...
                'ResidualAcceptanceTolerance', 1e-9));
            critical = TestBranchSwitching_v3.periodDoublingCriticalPoint();

            result = switcher.switchPeriodDoubling( ...
                @TestBranchSwitching_v3.flipNormalForm, critical);

            testCase.verifyTrue(result.accepted, result.message);
            testCase.verifyEqual(numel(result.solutions), 2);
            testCase.verifyEqual(sort([result.solutions.parameter]), ...
                [0.0025, 0.0025], 'AbsTol', 2e-7);
            testCase.verifyTrue(all([result.solutions.periodOneExcluded]));
            testCase.verifyGreaterThan([result.solutions.periodOneDistance], ...
                switcher.PeriodOneExclusionTolerance .* ones(1, 2));
            testCase.verifyLessThan([result.solutions.residualNorm], ...
                switcher.ResidualAcceptanceTolerance .* ones(1, 2));

            solution = result.solutions(1);
            [first, ~] = TestBranchSwitching_v3.flipNormalForm( ...
                solution.state, solution.parameter, solution.mode);
            [second, ~] = TestBranchSwitching_v3.flipNormalForm( ...
                first, solution.parameter, solution.mode);
            testCase.verifyGreaterThan(abs(first - solution.state), ...
                switcher.PeriodOneExclusionTolerance);
            testCase.verifyEqual(second, solution.state, 'AbsTol', 2e-8);
        end

        function periodOneOrbitIsNeverAcceptedAsPeriodTwo(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2, ...
                'PeriodOneExclusionTolerance', 1e-4));
            result = switcher.switchPeriodDoubling( ...
                @TestBranchSwitching_v3.identityMap, ...
                TestBranchSwitching_v3.periodDoublingCriticalPoint());

            testCase.verifyFalse(result.accepted);
            testCase.verifyFalse(any([result.attempts.converged]));
            testCase.verifyFalse(any([result.attempts.periodOneExcluded]));
            testCase.verifyEqual([result.attempts.periodOneDistance], [0, 0], ...
                'AbsTol', eps);
            messages = string({result.attempts.message});
            testCase.verifyTrue(all(contains(messages, ...
                'period-one exclusion failed')));

            [~, info] = switcher.doubledReturnResidual( ...
                @TestBranchSwitching_v3.identityMap, 0.05, 0, 0);
            testCase.verifyFalse(info.valid);
            testCase.verifyFalse(info.success);
            testCase.verifyFalse(info.period_two_valid);
            testCase.verifyFalse(info.period_one_excluded);
        end

        function periodTwoChildContinuesWithPseudoArclength(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2, ...
                'PeriodOneExclusionTolerance', 1e-3, ...
                'ResidualAcceptanceTolerance', 1e-8));
            switched = switcher.switchPeriodDoubling( ...
                @TestBranchSwitching_v3.flipNormalForm, ...
                TestBranchSwitching_v3.periodDoublingCriticalPoint());
            continuation = PseudoArclengthContinuation_v3(struct( ...
                'StepSize', 5e-3, ...
                'MinimumStepSize', 1e-5, ...
                'MaximumStepSize', 1e-2, ...
                'MaxPoints', 3, ...
                'ReuseCorrectorJacobian', false));

            branch = switcher.continuePeriodDoubledBranch( ...
                @TestBranchSwitching_v3.flipNormalForm, ...
                switched, continuation);

            testCase.verifyTrue(branch.success, branch.terminationReason);
            testCase.verifyEqual(branch.count, 3);
            testCase.verifyTrue(all(branch.periodTwoValid));
            testCase.verifyGreaterThan(branch.periodOneDistances, ...
                switcher.PeriodOneExclusionTolerance .* ones(1, 3));
            testCase.verifyLessThan( ...
                max([branch.points.residualNorm]), 1e-7);
            testCase.verifyEqual(branch.branchSwitch.type, ...
                'period_doubling');
        end

        function symmetryMetadataDoesNotInferPitchfork(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2));
            result = switcher.switchSymmetryBreaking( ...
                @TestBranchSwitching_v3.branchResidual, ...
                TestBranchSwitching_v3.criticalPoint(), -1);

            testCase.verifyTrue(result.accepted, result.message);
            testCase.verifyTrue(result.symmetry.criticalVectorBreaksSymmetry);
            testCase.verifyEqual(result.symmetry. ...
                criticalVectorRepresentation.characters, -1, ...
                'AbsTol', 1e-14);
            testCase.verifyEqual(result.symmetry.parentStabilizer, {'g1'});
            for index = 1:numel(result.solutions)
                testCase.verifyEmpty(result.solutions(index).childStabilizer);
            end
            testCase.verifyEqual(result.symmetry.bifurcationClassification, ...
                'not_inferred_from_unit_multiplier');
            testCase.verifyFalse(contains(lower(result.classification), ...
                'pitchfork'));
        end

        function missingAcceptanceEvidenceIsRejected(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2));
            result = switcher.switchUnitMultiplier( ...
                @TestBranchSwitching_v3.metadataFreeResidual, ...
                TestBranchSwitching_v3.criticalPoint());

            testCase.verifyFalse(result.accepted);
            testCase.verifyTrue(all([result.attempts.converged]));
            messages = string({result.attempts.message});
            testCase.verifyTrue(all(contains(messages, ...
                'physical admissibility')));
            testCase.verifyTrue(all(contains(messages, ...
                'event-cycle closure')));
        end

        function missingCriticalEvidenceFailsClosed(testCase)
            critical = TestBranchSwitching_v3.criticalPoint();
            critical = rmfield(critical, 'converged');
            result = BranchSwitching_v3().switchUnitMultiplier( ...
                @TestBranchSwitching_v3.branchResidual, critical);

            testCase.verifyFalse(result.accepted);
            testCase.verifyEqual(result.classification, 'switch_rejected');
            testCase.verifySubstring(result.message, 'converged');

            critical = TestBranchSwitching_v3.criticalPoint();
            critical.topology = rmfield(critical.topology, 'reliable');
            result = BranchSwitching_v3().switchUnitMultiplier( ...
                @TestBranchSwitching_v3.branchResidual, critical);
            testCase.verifyFalse(result.accepted);
            testCase.verifySubstring(result.message, 'reliable');

            critical = TestBranchSwitching_v3.criticalPoint();
            critical.topology = rmfield( ...
                critical.topology, 'topologyCompatible');
            result = BranchSwitching_v3().switchUnitMultiplier( ...
                @TestBranchSwitching_v3.branchResidual, critical);
            testCase.verifyFalse(result.accepted);
            testCase.verifySubstring(result.message, 'compatible-topology');
        end

        function criticalMultiplierTypeIsRequiredAndFailsClosed(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'CriticalMultiplierTolerance', 1e-5));

            wrongUnit = TestBranchSwitching_v3.criticalPoint();
            wrongUnit.criticalMultiplier = -1;
            result = switcher.switchUnitMultiplier( ...
                @TestBranchSwitching_v3.branchResidual, wrongUnit);
            testCase.verifyFalse(result.accepted);
            testCase.verifyEmpty(result.attempts);
            testCase.verifyEqual(result.requiredCriticalMultiplier, 1);
            testCase.verifySubstring(result.message, 'required value +1');

            wrongPeriodDoubling = TestBranchSwitching_v3.criticalPoint();
            result = switcher.switchPeriodDoubling( ...
                @TestBranchSwitching_v3.flipNormalForm, ...
                wrongPeriodDoubling);
            testCase.verifyFalse(result.accepted);
            testCase.verifyEmpty(result.attempts);
            testCase.verifyEqual(result.requiredCriticalMultiplier, -1);
            testCase.verifySubstring(result.message, 'required value -1');

            missing = rmfield( ...
                TestBranchSwitching_v3.criticalPoint(), ...
                'criticalMultiplier');
            result = switcher.switchUnitMultiplier( ...
                @TestBranchSwitching_v3.branchResidual, missing);
            testCase.verifyFalse(result.accepted);
            testCase.verifyEmpty(result.attempts);
            testCase.verifySubstring(result.message, ...
                'explicit finite scalar critical multiplier');
        end

        function mixedVectorUsesSymmetryBreakingProjection(testCase)
            switcher = BranchSwitching_v3(struct( ...
                'PredictorAmplitude', 5e-2, ...
                'ResidualAcceptanceTolerance', 1e-9));
            exchange = [0, 1; 1, 0];
            critical = TestBranchSwitching_v3.exchangeCriticalPoint();

            result = switcher.switchSymmetryBreaking( ...
                @TestBranchSwitching_v3.exchangeBranchResidual, ...
                critical, exchange);

            expectedDirection = [1; -1] ./ sqrt(2);
            expectedFixedProjector = 0.5 .* [1, 1; 1, 1];
            expectedBreakingProjector = 0.5 .* [1, -1; -1, 1];
            testCase.verifyTrue(result.accepted, result.message);
            testCase.verifyEqual(result.predictors.plus.direction, ...
                expectedDirection, 'AbsTol', 2e-14);
            testCase.verifyEqual(result.predictors.plus.state, ...
                0.05 .* expectedDirection, 'AbsTol', 2e-14);
            testCase.verifyEqual(result.symmetry.fixedSubspaceProjector, ...
                expectedFixedProjector, 'AbsTol', 2e-14);
            testCase.verifyEqual( ...
                result.symmetry.symmetryBreakingProjector, ...
                expectedBreakingProjector, 'AbsTol', 2e-14);
            testCase.verifyEqual(result.symmetry.originalCriticalVector, ...
                [2; 0], 'AbsTol', eps);
            testCase.verifyEqual(result.symmetry.projectedCriticalVector, ...
                expectedDirection, 'AbsTol', 2e-14);
            testCase.verifyEqual(result.symmetry.fixedSubspaceDimension, 1);
            testCase.verifyEqual( ...
                result.symmetry.symmetryBreakingDimension, 1);
            testCase.verifyEqual(result.symmetry. ...
                originalCriticalVectorRepresentation.characters, 0, ...
                'AbsTol', 2e-14);
            testCase.verifyEqual(result.symmetry. ...
                criticalVectorRepresentation.characters, -1, ...
                'AbsTol', 2e-14);
            testCase.verifyLessThan( ...
                result.symmetry.projectionOrthogonalityResidual, 1e-14);
            for index = 1:numel(result.solutions)
                testCase.verifyEqual(sum(result.solutions(index).state), ...
                    0, 'AbsTol', 2e-8);
                testCase.verifyEmpty( ...
                    result.solutions(index).childStabilizer);
            end
            testCase.verifyEqual( ...
                result.symmetry.bifurcationClassification, ...
                'not_inferred_from_unit_multiplier');
            testCase.verifyFalse(contains(lower(result.classification), ...
                'pitchfork'));
        end

        function invariantCriticalVectorCannotSwitchSymmetry(testCase)
            critical = TestBranchSwitching_v3.exchangeCriticalPoint();
            critical.rightVector = [1; 1];
            result = BranchSwitching_v3().switchSymmetryBreaking( ...
                @TestBranchSwitching_v3.exchangeBranchResidual, ...
                critical, [0, 1; 1, 0]);

            testCase.verifyFalse(result.accepted);
            testCase.verifyEmpty(result.attempts);
            testCase.verifyFalse( ...
                result.symmetry.hasNonzeroBreakingComponent);
            testCase.verifySubstring(result.message, ...
                'no resolvable component');
        end
    end

    methods (Static, Access = private)
        function critical = criticalPoint()
            critical = struct( ...
                'converged', true, ...
                'state', 0, ...
                'parameter', 0, ...
                'mode', 0, ...
                'rightVector', 1, ...
                'criticalMultiplier', 1, ...
                'topology', struct( ...
                    'reliable', true, ...
                    'topologyCompatible', true, ...
                    'hybridChartBoundary', false, ...
                    'section_event_coincidence', false, ...
                    'unresolvedSimultaneousOrdering', false, ...
                    'cyclic_event_signature', 'TD>LO', ...
                'section_relative_event_signature', 'TD>LO>Apex'));
        end

        function critical = periodDoublingCriticalPoint()
            critical = TestBranchSwitching_v3.criticalPoint();
            critical.criticalMultiplier = -1;
        end

        function critical = exchangeCriticalPoint()
            critical = TestBranchSwitching_v3.criticalPoint();
            critical.state = zeros(2, 1);
            critical.rightVector = [2; 0];
        end

        function [value, info] = branchResidual(u, p, q) %#ok<INUSD>
            value = u .* (u - p(1));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
        end

        function [value, info] = topologyProbeMap(u, p, q) %#ok<INUSD>
            value = -u;
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
        end

        function [value, info] = topologyProbeBoundaryMap(u, p, q)
            [value, info] = TestBranchSwitching_v3.topologyProbeMap(u, p, q);
            info.hybridChartBoundary = true;
        end

        function [value, info] = missingCyclicSignatureResidual(u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info = rmfield(info, 'cyclic_event_signature');
        end

        function [value, info] = missingSectionSignatureResidual(u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info = rmfield(info, 'section_relative_event_signature');
        end

        function [value, info] = missingClusterSignatureResidual(u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info = rmfield(info, 'event_cluster_signature');
        end

        function [value, info] = missingMultiplicityResidual(u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info = rmfield(info, 'return_multiplicity');
        end

        function [value, info] = invalidMultiplicityResidual(u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info.return_multiplicity = Inf;
        end

        function [value, info] = missingSectionClusterEvidenceResidual( ...
                u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info = rmfield(info, 'section_cluster_coincidence');
        end

        function [value, info] = hybridBoundaryResidual(u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info.hybridChartBoundary = true;
        end

        function [value, info] = sectionEventCoincidenceResidual( ...
                u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info.section_event_coincidence = true;
        end

        function [value, info] = sectionClusterCoincidenceResidual( ...
                u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info.section_cluster_coincidence = true;
        end

        function [value, info] = unresolvedOrderingResidual(u, p, q) %#ok<INUSD>
            value = zeros(size(u));
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
            info.unresolvedSimultaneousOrdering = true;
        end

        function value = metadataFreeResidual(u, p, q) %#ok<INUSD>
            value = u .* (u - p(1));
        end

        function [value, info] = flipNormalForm(u, p, q) %#ok<INUSD>
            value = -(1 + p(1)) .* u + u.^3;
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
        end

        function [value, info] = identityMap(u, p, q) %#ok<INUSD>
            value = u;
            info = TestBranchSwitching_v3.acceptedInfo('identity-cycle');
        end

        function [value, info] = exchangeBranchResidual(u, p, q) %#ok<INUSD>
            fixedCoordinate = (u(1) + u(2)) ./ sqrt(2);
            breakingCoordinate = (u(1) - u(2)) ./ sqrt(2);
            basis = [1, 1; 1, -1] ./ sqrt(2);
            value = basis * [fixedCoordinate; ...
                breakingCoordinate .* (breakingCoordinate - p(1))];
            info = TestBranchSwitching_v3.acceptedInfo('TD>LO>Apex');
        end

        function info = acceptedInfo(sectionSignature)
            info = struct( ...
                'success', true, ...
                'valid', true, ...
                'integration_success', true, ...
                'reliable', true, ...
                'topologyCompatible', true, ...
                'hybridChartBoundary', false, ...
                'section_event_coincidence', false, ...
                'section_cluster_coincidence', false, ...
                'unresolvedSimultaneousOrdering', false, ...
                'admissible', true, ...
                'cycle_complete', true, ...
                'mode_closed', true, ...
                'return_multiplicity', 1, ...
                'cyclic_event_signature', 'TD>LO', ...
                'section_relative_event_signature', sectionSignature, ...
                'event_cluster_signature', '{TD}>{LO}', ...
                'guard_transversality_margin', 1, ...
                'section_transversality', 1);
        end
    end
end
