classdef TestHybridFramework_v3 < matlab.unittest.TestCase
    properties
        RepositoryRoot
        V3Root
        QuadrupedOrbit
        QuadrupedReport
        QuadrupedFramework
    end

    methods (TestClassSetup)
        function configurePathsAndRefineFixture(testCase)
            testCase.V3Root = fileparts(fileparts(mfilename('fullpath')));
            testCase.RepositoryRoot = fileparts(testCase.V3Root);
            folders = {'Schema_v3', 'Adapters_v3', 'Dynamics_v3', ...
                'Simulation_v3', 'Orbit_v3', 'Numerics_v3', ...
                'Stability_v3', 'Graphics_v3', 'Examples_v3', 'Tests_v3'};
            for i = 1:numel(folders)
                addpath(fullfile(testCase.V3Root, folders{i}));
            end
            perturbation = zeros(13, 1);
            perturbation(1) = 1e-6;
            finiteDifference = FiniteDifferenceJacobian_v3(struct( ...
                'Method', 'forward', 'RelativeStep', 1e-8, ...
                'FailurePolicy', 'nan'));
            solverOptions = struct( ...
                'Jacobian', finiteDifference, ...
                'Algorithm', 'newton', ...
                'FunctionTolerance', 1e-7, ...
                'ResidualAcceptanceTolerance', 1e-7, ...
                'MaxIterations', 15, ...
                'MaxFunctionEvaluations', 1000);
            [testCase.QuadrupedOrbit, testCase.QuadrupedReport, ...
                    testCase.QuadrupedFramework] = ...
                QuadrupedalExample_v3(struct( ...
                    'FixtureFile', 'PK_20_2.mat', ...
                    'FixtureColumn', 1, ...
                    'LegacyParameterPolicy', 'v2-exact', ...
                    'InitialUnknownPerturbation', perturbation, ...
                    'Refine', true, ...
                    'ResidualTolerance', 1e-7, ...
                    'SolverOptions', solverOptions));
        end
    end

    methods (Test)
        function actualQuadrupedRootRefinesConvertedSeed(testCase)
            % Requirement K: this is an actual solve, not stored-seed replay.
            report = testCase.QuadrupedReport;
            testCase.verifyTrue(report.recovered);
            testCase.verifyTrue(report.converged);
            testCase.verifyTrue(report.solve_info.used);
            testCase.verifyTrue(report.solve_info.converged);
            testCase.verifyGreaterThan( ...
                norm(report.initial_unknown_perturbation, inf), 0);
            testCase.verifyGreaterThan(report.seed_residual_norm, ...
                report.residual_norm);
            testCase.verifyGreaterThanOrEqual( ...
                report.solve_info.output.acceptedIterations, 1);
            testCase.verifyGreaterThanOrEqual( ...
                report.solve_info.jacobianEvaluationCount, 1);
            testCase.verifyGreaterThan( ...
                norm(report.solve_info.state - report.initial_guess, inf), 0);
            testCase.verifyLessThan(report.residual_norm, 1e-7);
            testCase.verifyGreaterThanOrEqual(report.map_evaluations, 1);
            testCase.verifyGreaterThanOrEqual( ...
                report.function_evaluations, report.map_evaluations);
            testCase.verifyGreaterThanOrEqual(report.cache_hits, 0);
            testCase.verifyGreaterThanOrEqual(report.modes_attempted, 1);
            testCase.verifyLessThan(report.modes_attempted, 16);
            testCase.verifyEqual(report.period, 1.564520214497, ...
                'AbsTol', 2e-4);
            testCase.verifyEqual(numel(testCase.QuadrupedOrbit.parameter), 10);
            testCase.verifyEqual( ...
                report.legacy_parameter_conversion.policy, 'v2-exact');
        end

        function continuationCarriesFRLOThroughApexChart(testCase)
            % Requirement I: the same full cycle survives a section chart swap.
            [problem, map] = testCase.orderingProblem();
            solver = RootSolver_v3(struct( ...
                'Algorithm', 'newton', ...
                'FunctionTolerance', 1e-9, ...
                'ResidualAcceptanceTolerance', 1e-7));
            continuation = NumericalContinuation1D_v3(struct( ...
                'RootSolver', solver, ...
                'ActiveParameter', 'mu', ...
                'StopOnFailure', true));
            parameterValues = [0.10, 0.05, 0, -0.05, -0.10];
            branch = continuation.run( ...
                problem, [1; 0], 0.10, 1, parameterValues);

            testCase.verifyEqual(branch.count, numel(parameterValues));
            testCase.verifyTrue(branch.success);
            modes = cellfun(@double, branch.mode);
            testCase.verifyEqual(modes, [1, 1, 0, 0, 0]);
            testCase.verifyEqual(branch.period, ones(1, 5), ...
                'AbsTol', 2e-6);
            testCase.verifyEqual(branch.return_multiplicity, ones(1, 5));
            testCase.verifyEqual(branch.return_policy, repmat( ...
                {'EventCycleReturnPolicy_v3'}, 1, 5));
            testCase.verifyEqual(branch.return_policy_name, repmat( ...
                {'event-cycle-return'}, 1, 5));
            testCase.verifyEqual(branch.cycle_return_policy, ...
                branch.return_policy);
            testCase.verifyEqual(branch.candidate_section_count, ...
                ones(1, 5));
            testCase.verifyEqual(branch.candidate_apex_count, ones(1, 5));
            testCase.verifyEqual(branch.accepted_crossing_index, ...
                ones(1, 5));
            testCase.verifyEqual(branch.accepted_apex_index, ones(1, 5));
            testCase.verifyLessThan( ...
                max(abs([branch.points.residualNorm])), 1e-7);

            afterApex = string({branch.event_history{1}.type});
            beforeApex = string({branch.event_history{end}.type});
            testCase.verifyEqual(afterApex, ["FR_LO", "FR_TD"]);
            testCase.verifyEqual(beforeApex, ["FR_TD", "FR_LO"]);
            testCase.verifyTrue(isa(map.ReturnPolicy, ...
                'EventCycleReturnPolicy_v3'));
            testCase.verifyEqual(branch.topology_boundary, ...
                logical([0, 0, 1, 0, 0]));

            transitionSolve = branch.solver_info{3};
            testCase.verifyEqual(numel(transitionSolve.candidateModes), 2);
            testCase.verifyEqual(double(transitionSolve.selectedMode), 0);
            testCase.verifyLessThan( ...
                numel(transitionSolve.candidateModes), 16);
            testCase.verifyNotEmpty(transitionSolve.modeResolution);
            testCase.verifyTrue(any(string( ...
                {transitionSolve.modeResolution.source}) == ...
                "local-section-mode-resolver"));
            coincident = branch.points(3).orbit.section_coincident_events;
            testCase.verifyNotEmpty(coincident);
            testCase.verifyTrue(any(string({coincident.type}) == "FR_LO"));
            boundaryDetector = HybridBoundaryDetector_v3();
            boundaries = boundaryDetector.detect(branch);
            boundaryTypes = string({boundaries.type});
            testCase.verifyTrue(any(boundaryTypes == ...
                "section_event_coincidence"));
            testCase.verifyTrue(any(boundaryTypes == "section_mode_change"));

            boundaryFloquet = FloquetAnalysis_v3(struct( ...
                'TangentIndices', 1, ...
                'RelativeStep', 1e-4)).analyze(map, [1; 0], 0, 0);
            testCase.verifyFalse(boundaryFloquet.reliable);
            testCase.verifyTrue(boundaryFloquet.sectionEventCoincidence);
            testCase.verifyNotEmpty(boundaryFloquet.sectionCoincidentEvents);
        end

        function fullCycleFloquetMultiplierIsProductOfLocalReturns(testCase)
            % Requirement N: differentiate the accepted two-apex hybrid map.
            gamma = 0.3;
            system = createSyntheticReturnPolicySystem_v3( ...
                'two-apex-radial');
            simulator = HybridSimulator_v3(struct( ...
                'RelTol', 1e-11, 'AbsTol', 1e-13));
            section = PoincareSection_v3.apex(2);
            options = struct('MaxReturnTime', 2.5, ...
                'MaxSectionCrossings', 4, 'MaxCycleEvents', 8, ...
                'ArmTolerance', 1e-7);
            firstMap = PoincareMap_v3(system, section, simulator, ...
                FirstReturnPolicy_v3(), options);
            cycleMap = PoincareMap_v3(system, section, simulator, ...
                EventCycleReturnPolicy_v3(), options);

            localAnalyzer = FloquetAnalysis_v3(struct( ...
                'TangentIndices', 1, 'RelativeStep', 1e-4, ...
                'RequireDiscreteClosure', false));
            local0 = localAnalyzer.analyze(firstMap, [1; 0], 0, gamma);
            local1 = localAnalyzer.analyze(firstMap, [1; 0], 1, gamma);
            full = FloquetAnalysis_v3(struct( ...
                'TangentIndices', 1, ...
                'RelativeStep', 1e-4)).analyze( ...
                    cycleMap, [1; 0], 0, gamma);

            expectedLocal = exp(-2 * gamma);
            expectedCycle = exp(-4 * gamma);
            testCase.verifyEqual(local0.multipliers, expectedLocal, ...
                'AbsTol', 3e-8);
            testCase.verifyEqual(local1.multipliers, expectedLocal, ...
                'AbsTol', 3e-8);
            testCase.verifyEqual(full.multipliers, expectedCycle, ...
                'AbsTol', 3e-8);
            testCase.verifyEqual(full.multipliers, ...
                local0.multipliers * local1.multipliers, 'AbsTol', 3e-8);
            testCase.verifyEqual(full.return_multiplicity, 2);
            testCase.verifyEqual(full.baseMapInfo.period, 2, ...
                'AbsTol', 3e-7);
            testCase.verifyTrue(full.reliable);
            testCase.verifyTrue(full.finiteDifference.allReliable);
            testCase.verifyGreaterThan( ...
                full.finiteDifference.selectedSteps(1), sqrt(eps));
            testCase.verifyEmpty(full.ambientPoincareMatrix);
        end

        function detectsNamedCandidatesAndRejectsUnreliableInterval(testCase)
            % Requirement O: bracketed smooth candidates need reliable data.
            angle = 0.4;
            multipliers = [ ...
                 0.8,  1.2; ...
                -0.8, -1.2; ...
                 0.9 * exp(1i * angle), 1.1 * exp(1i * angle); ...
                 0.9 * exp(-1i * angle), 1.1 * exp(-1i * angle)];
            detector = BifurcationDetector_v3();
            [events, tracks] = detector.detect(multipliers, [0, 1]);

            types = string({events.type});
            testCase.verifyTrue(any(types == "unit_multiplier_candidate"));
            testCase.verifyTrue(any(types == ...
                "period_doubling_candidate"));
            testCase.verifyTrue(any(types == "Neimark_Sacker_candidate"));
            testCase.verifyEqual(size(tracks.multipliers), [4, 2]);
            testCase.verifyEqual([events.location], ...
                0.5 * ones(1, numel(events)), 'AbsTol', 1e-12);

            branch = struct();
            branch.stability = { ...
                struct('multipliers', 0.8, 'eigenvectors', 1, ...
                    'reliable', true), ...
                struct('multipliers', 1.2, 'eigenvectors', 1, ...
                    'reliable', false)};
            branch.continuationCoordinate = [0, 1];
            branch.cyclic_signature = {'A', 'A'};
            branch.return_multiplicity = [1, 1];
            branch.topology_boundary = [false, false];
            [rejected, rejectedTracks] = detector.detect(branch);
            testCase.verifyEmpty(rejected);
            testCase.verifyEqual(rejectedTracks.reliable, [true, false]);

            topologyBranch = branch;
            topologyBranch.stability{2}.reliable = true;
            topologyBranch.topology_boundary = [false, true];
            topologyRejected = detector.detect(topologyBranch);
            testCase.verifyEmpty(topologyRejected);

            nanBranch = struct();
            nanBranch.stability = { ...
                struct('multipliers', 0.8, 'eigenvectors', 1, ...
                    'reliable', true), ...
                struct('multipliers', NaN, 'eigenvectors', NaN, ...
                    'reliable', false), ...
                struct('multipliers', 1.2, 'eigenvectors', 1, ...
                    'reliable', true)};
            nanBranch.continuationCoordinate = [0, 0.5, 1];
            nanBranch.cyclic_signature = {'A', 'A', 'A'};
            nanBranch.return_multiplicity = [1, 1, 1];
            nanBranch.topology_boundary = [false, false, false];
            [nanEvents, nanTracks] = detector.detect(nanBranch);
            testCase.verifyEmpty(nanEvents);
            testCase.verifyEqual(nanTracks.reliable, [true, false, true]);
        end

        function actualEventCycleIsGeneratedWithoutAGaitSchedule(testCase)
            % Requirements H/K: physical history, not a gait label, closes it.
            expected = ["BL_TD"; "BR_TD"; "FL_TD"; "FR_TD"; ...
                        "BL_LO"; "BR_LO"; "FL_LO"; "FR_LO"];
            report = testCase.QuadrupedReport;
            actual = reshape(string({report.event_history.type}), [], 1);
            testCase.verifyEqual(actual, expected);
            testCase.verifyEqual(report.initial_mode, report.final_mode);
            testCase.verifyEqual(report.return_multiplicity, 1);
            counts = report.event_counts_per_leg;
            testCase.verifyEqual({counts.leg_name}, ...
                {'BL', 'BR', 'FL', 'FR'});
            testCase.verifyEqual([counts.touchdown_count], ones(1, 4));
            testCase.verifyEqual([counts.liftoff_count], ones(1, 4));
            testCase.verifyTrue( ...
                report.cycle_completion_diagnostics.complete);
            testCase.verifyNumElements( ...
                testCase.QuadrupedOrbit.mode_history, 9);
            testCase.verifyFalse(isprop( ...
                testCase.QuadrupedOrbit, 'gait_type'));
        end

        function actualParameterAsymmetricQuadrupedOrbitClosesCycle(testCase)
            % Requirement L coverage for a genuinely event-discovered,
            % non-pronking v3 orbit. The old asymmetric fixtures remain a
            % separate migration incompatibility because they suppress
            % additional guard crossings before their prescribed endpoint.
            schema = testCase.QuadrupedFramework.schema;
            finiteDifference = FiniteDifferenceJacobian_v3(struct( ...
                'Method', 'forward', 'RelativeStep', 1e-7, ...
                'FailurePolicy', 'nan'));
            solver = RootSolver_v3(struct( ...
                'Jacobian', finiteDifference, ...
                'Algorithm', 'newton', ...
                'FunctionTolerance', 1e-8, ...
                'ResidualAcceptanceTolerance', 1e-7, ...
                'MaxIterations', 20, ...
                'MaxFunctionEvaluations', 1200));
            continuation = NumericalContinuation1D_v3(struct( ...
                'RootSolver', solver, ...
                'ActiveParameter', 'k_l_f', ...
                'StopOnFailure', true));

            baseOrbit = testCase.QuadrupedOrbit;
            targetFrontStiffness = ...
                baseOrbit.parameter(schema.Parameter.k_l_f) + 0.02;
            branch = continuation.run( ...
                testCase.QuadrupedFramework.residual, ...
                baseOrbit.initial_state(schema.Root.UnknownIndices), ...
                baseOrbit.parameter, baseOrbit.initial_mode, ...
                targetFrontStiffness);

            testCase.verifyTrue(branch.success);
            testCase.verifyEqual(branch.count, 1);
            point = branch.points(1);
            testCase.verifyLessThan(point.residualNorm, 1e-7);
            testCase.verifyEqual(point.return_multiplicity, 1);
            testCase.verifyGreaterThan(point.period, 0);
            testCase.verifyEqual(point.p(schema.Parameter.k_l_f), ...
                targetFrontStiffness, 'AbsTol', eps(targetFrontStiffness));
            testCase.verifyNotEqual( ...
                point.p(schema.Parameter.k_l_b), ...
                point.p(schema.Parameter.k_l_f));

            events = point.event_history;
            eventNames = string({events.type});
            testCase.verifyEqual(numel(events), 8);
            for expectedName = string(schema.Event.Names)
                testCase.verifyEqual(sum(eventNames == expectedName), 1);
            end
            eventCounts = point.event_counts;
            testCase.verifyEqual([eventCounts.touchdown_count], ones(1, 4));
            testCase.verifyEqual([eventCounts.liftoff_count], ones(1, 4));

            backTouchdown = events(find(eventNames == "BL_TD", 1)).time;
            frontTouchdown = events(find(eventNames == "FL_TD", 1)).time;
            backLiftoff = events(find(eventNames == "BL_LO", 1)).time;
            frontLiftoff = events(find(eventNames == "FL_LO", 1)).time;
            testCase.verifyGreaterThan( ...
                abs(frontTouchdown - backTouchdown), 1e-5);
            testCase.verifyGreaterThan( ...
                abs(frontLiftoff - backLiftoff), 1e-5);

            mapInfo = point.solverInfo.evaluationInfo.map_info;
            testCase.verifyEqual(mapInfo.initial_mode, mapInfo.final_mode);
            testCase.verifyTrue(mapInfo.cycle_complete);
            testCase.verifyLessThan( ...
                numel(point.solverInfo.candidateModes), 16);
            testCase.verifyFalse(isprop(point.orbit, 'gait_type'));
        end

        function availableAsymmetricFixtureIsExplicitlyAudited(testCase)
            % Requirement L fixture audit. A representative point is also
            % replayed so the documented migration incompatibility is an
            % executed result, not an inference from stored event times.
            fixture = fullfile(testCase.RepositoryRoot, 'SLIP_Quadruped', ...
                'P1_Breaking_Symmetries_Leads_to_Diverse_Qudrupedal_Gaits', ...
                '1_Roadmap', 'BD1_20_2_BG.mat');
            testCase.verifyTrue(isfile(fixture));
            data = load(fixture, 'results');
            testCase.verifySize(data.results, [29, 474]);
            storedEventTimes = data.results(14:21, end);
            testCase.verifyGreaterThan( ...
                max(storedEventTimes) - min(storedEventTimes), 1e-3);

            legacyPoint = data.results(:, 204);
            unknown = LegacyStateAdapter_v3.toV3Unknown( ...
                legacyPoint(1:13));
            schema = testCase.QuadrupedFramework.schema;
            state = zeros(schema.State.Dimension, 1);
            state(schema.Root.UnknownIndices) = unknown;
            parameter = LegacyParameterAdapter_v3.toV3( ...
                legacyPoint(23:29), 'v2-exact');
            eventTimes = legacyPoint(14:21);
            oldMode = logical([ ...
                eventTimes(1) > eventTimes(2); ...
                eventTimes(3) > eventTimes(4); ...
                eventTimes(5) > eventTimes(6); ...
                eventTimes(7) > eventTimes(8)]);
            mode = LegacyModeAdapter_v3.toV3(oldMode);
            guardValues = ...
                testCase.QuadrupedFramework.system.GuardFunctionsComponent ...
                .legValues(state, parameter);
            testCase.verifyGreaterThan(min(guardValues), 0.1);
            testCase.verifyError(@() ...
                testCase.QuadrupedFramework.map.evaluate( ...
                    state, mode, parameter), ...
                'ContinuousDynamics_v3:TensileStance');
        end

        function pseudoArclengthCorrectsStateAndParameter(testCase)
            crossings = repmat(struct('index', 0), 2, 1);
            crossings(1).index = 1;
            crossings(2).index = 2;
            metadata = struct( ...
                'integration_success', true, ...
                'discrete_closed', true, ...
                'cycle_complete', true, ...
                'return_policy_accepted', true, ...
                'return_policy', 'EventCycleReturnPolicy_v3', ...
                'return_policy_name', 'event-cycle-return', ...
                'candidate_section_crossings', {crossings}, ...
                'candidate_apex_count', 2, ...
                'accepted_crossing_index', 2, ...
                'accepted_apex_index', 2, ...
                'return_multiplicity', 2, ...
                'section_relative_event_signature', 'A>B', ...
                'cyclic_event_signature', 'A>B', ...
                'guard_transversality_margin', 1, ...
                'section_transversality', 1, ...
                'topology_margins', struct('guard_transversality', 1));
            residual = @(u, p, q, context) deal( ...
                u - p(1) + 0 * numel(fieldnames(context)), metadata);
            solver = RootSolver_v3(struct('Algorithm', 'newton'));
            continuation = PseudoArclengthContinuation_v3(struct( ...
                'RootSolver', solver, ...
                'ActiveParameterIndex', 1, ...
                'StepSize', 0.1, ...
                'MaxPoints', 4, ...
                'InitialDirection', 1));
            branch = continuation.run(residual, 0, 0, []);
            testCase.verifyEqual(branch.count, 4);
            testCase.verifyLessThan(max(abs(branch.x - branch.p)), 1e-8);
            testCase.verifyEqual(branch.return_policy, repmat( ...
                {'EventCycleReturnPolicy_v3'}, 1, 4));
            testCase.verifyEqual(branch.return_policy_name, repmat( ...
                {'event-cycle-return'}, 1, 4));
            testCase.verifyEqual(branch.cycle_return_policy, ...
                branch.return_policy);
            testCase.verifyEqual(branch.candidate_section_count, ...
                2 * ones(1, 4));
            testCase.verifyEqual(branch.candidate_apex_count, ...
                2 * ones(1, 4));
            testCase.verifyEqual(branch.accepted_crossing_index, ...
                2 * ones(1, 4));
            testCase.verifyEqual(branch.accepted_apex_index, ...
                2 * ones(1, 4));
            testCase.verifyEqual([branch.points.return_multiplicity], ...
                2 * ones(1, 4));
        end

        function classicalFiniteDifferenceUsesAdaptiveCoordinateScale(testCase)
            finiteDifference = FiniteDifferenceJacobian_v3();
            x = [0; 3];
            [jacobian, ~, info] = finiteDifference.compute( ...
                @(z) [z(1)^2; sin(z(2))], x);
            expectedSteps = sqrt(eps) * (1 + abs(x));
            testCase.verifyEqual(info.steps, expectedSteps, ...
                'AbsTol', 10 * eps);
            testCase.verifyEqual(jacobian(2, 2), cos(3), ...
                'AbsTol', 2e-7);
        end

        function everyRestoredLegacyFileRemainsPresent(testCase)
            % Requirement Q: all 70 parent-commit files are in place.
            legacyFolder = fullfile(testCase.RepositoryRoot, ...
                'SLIP_Quadruped', '3_Numerical_Continuation', ...
                '2_FloquetAnalysis');
            manifest = legacyRestoredFiles_v3();
            testCase.verifyNumElements(manifest, 70);
            present = cellfun(@(name) isfile( ...
                fullfile(legacyFolder, name)), manifest);
            missing = manifest(~present);
            testCase.verifyTrue(all(present), sprintf( ...
                'Missing restored legacy file(s): %s', ...
                strjoin(missing, ', ')));
            testCase.verifyTrue(isfile(fullfile(legacyFolder, 'FDM_v2.m')));
        end
    end

    methods (Access = private)
        function [problem, map] = orderingProblem(~)
            system = createSyntheticHybridSystem_v3('ordering');
            simulator = HybridSimulator_v3(struct( ...
                'RelTol', 1e-10, 'AbsTol', 1e-12));
            section = PoincareSection_v3.apex(2);
            policy = EventCycleReturnPolicy_v3(struct( ...
                'LegCount', 1, 'LegNames', {{'FR'}}));
            map = PoincareMap_v3(system, section, simulator, policy, struct( ...
                'MaxReturnTime', 3.5, ...
                'MaxSectionCrossings', 3, ...
                'MaxCycleEvents', 8, ...
                'ArmTolerance', 1e-7));
            problem = PeriodicOrbitResidual_v3(map, [1; 0]);
        end
    end
end
