classdef TestEventClusters_v3 < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addFrameworkPaths(testCase)
            root = fileparts(fileparts(mfilename('fullpath')));
            folders = {'Schema_v3', 'Dynamics_v3', 'Simulation_v3', ...
                'Orbit_v3', 'Numerics_v3', 'Stability_v3', 'Tests_v3'};
            for index = 1:numel(folders)
                addpath(fullfile(root, folders{index}));
            end
        end
    end

    methods (Test)
        function pronkTouchdownAndLiftoffAreStructuralClusters(testCase)
            names = ["BL_TD", "BR_TD", "FL_TD", "FR_TD", ...
                "BL_LO", "BR_LO", "FL_LO", "FR_LO"];
            times = [0.2, 0.2 + 2e-11, 0.2 + 4e-11, 0.2 + 6e-11, ...
                0.8, 0.8 + 2e-11, 0.8 + 4e-11, 0.8 + 6e-11];
            clusterer = EventCluster_v3(struct( ...
                'AbsoluteTimeTolerance', 1e-9));
            report = clusterer.analyze( ...
                TestEventClusters_v3.history(names, times), ...
                struct('Period', 1, 'SectionTimes', 0.2, ...
                'SectionNames', "apex"));

            testCase.verifyEqual(report.cluster_count, 2);
            testCase.verifyEqual(cellfun(@numel, report.members), [4, 4]);
            testCase.verifyLessThanOrEqual( ...
                report.maximum_intra_cluster_spread, 7e-11);
            testCase.verifyGreaterThan(report.minimum_intercluster_gap, 0.39);
            testCase.verifyTrue(report.section_cluster_coincidence);
            testCase.verifyEqual( ...
                report.section_coincident_cluster_indices, 1);
            testCase.verifyTrue(contains( ...
                report.cluster_signature, "BL_TD"));
            testCase.verifyTrue(contains( ...
                report.cluster_signature, "FR_LO"));
        end

        function bilateralPairPersistsWithoutFalseCollision(testCase)
            clusterer = EventCluster_v3(struct( ...
                'AbsoluteTimeTolerance', 1e-9));
            left = clusterer.analyze(TestEventClusters_v3.history( ...
                ["BL_TD", "BR_TD"], [0.2, 0.2 + 1e-11]), 1);
            right = clusterer.analyze(TestEventClusters_v3.history( ...
                ["BL_TD", "BR_TD"], [0.24, 0.24 + 2e-11]), 1);
            comparison = clusterer.compare(left, right);

            testCase.verifyTrue( ...
                comparison.has_persistent_simultaneous_cluster);
            testCase.verifyFalse(comparison.has_split);
            testCase.verifyFalse(comparison.has_merge);

            points = [TestEventClusters_v3.point(left, 0), ...
                TestEventClusters_v3.point(right, 1)];
            types = string({HybridBoundaryDetector_v3().detect(points).type});
            testCase.verifyTrue(any(types == ...
                "persistent_simultaneous_cluster"));
            testCase.verifyFalse(any(types == "event_cluster_collision"));
            testCase.verifyFalse(any(types == "event_collision"));
        end

        function parameterChangeSplitsAndMergesCluster(testCase)
            clusterer = EventCluster_v3(struct( ...
                'AbsoluteTimeTolerance', 1e-9));
            together = clusterer.analyze(TestEventClusters_v3.history( ...
                ["BL_TD", "BR_TD"], [0.2, 0.2 + 1e-11]), 1);
            separated = clusterer.analyze(TestEventClusters_v3.history( ...
                ["BL_TD", "BR_TD"], [0.19, 0.21]), 1);

            split = clusterer.compare(together, separated);
            merge = clusterer.compare(separated, together);
            testCase.verifyTrue(split.has_split);
            testCase.verifyFalse(split.has_merge);
            testCase.verifyTrue(merge.has_merge);
            testCase.verifyFalse(merge.has_collision);

            points = [TestEventClusters_v3.point(together, -1), ...
                TestEventClusters_v3.point(separated, 0), ...
                TestEventClusters_v3.point(together, 1)];
            types = string({HybridBoundaryDetector_v3().detect(points).type});
            testCase.verifyTrue(any(types == "event_cluster_split"));
            testCase.verifyTrue(any(types == "event_cluster_merge"));
            testCase.verifyFalse(any(types == "event_cluster_collision"));
        end

        function distinctClusterApproachIsGenuineCollision(testCase)
            clusterer = EventCluster_v3(struct( ...
                'AbsoluteTimeTolerance', 1e-10));
            far = clusterer.analyze(TestEventClusters_v3.history( ...
                ["BL_TD", "BR_TD"], [0.2, 0.21]), 1);
            near = clusterer.analyze(TestEventClusters_v3.history( ...
                ["BL_TD", "BR_TD"], [0.2, 0.200005]), 1);
            merged = clusterer.analyze(TestEventClusters_v3.history( ...
                ["BL_TD", "BR_TD"], [0.2, 0.2 + 5e-11]), 1);
            detector = HybridBoundaryDetector_v3(struct( ...
                'ClusterTimeTolerance', 1e-10, ...
                'EventCollisionTolerance', 1e-5));
            approachEvents = detector.detect([ ...
                TestEventClusters_v3.point(far, -1), ...
                TestEventClusters_v3.point(near, 0)]);
            approachTypes = string({approachEvents.type});
            collisionEvents = detector.detect([ ...
                TestEventClusters_v3.point(near, 0), ...
                TestEventClusters_v3.point(merged, 1)]);
            collisionTypes = string({collisionEvents.type});

            testCase.verifyEqual(near.cluster_count, 2);
            testCase.verifyEqual(near.minimum_intercluster_gap, 5e-6, ...
                'AbsTol', 1e-12);
            testCase.verifyTrue(any(approachTypes == ...
                "event_cluster_approach"));
            testCase.verifyFalse(any(approachTypes == ...
                "event_cluster_collision"));
            testCase.verifyTrue(any(collisionTypes == ...
                "event_cluster_merge"));
            testCase.verifyTrue(any(collisionTypes == ...
                "event_cluster_collision"));
            testCase.verifyTrue(any(collisionTypes == "event_collision"));
            testCase.verifyFalse(any(collisionTypes == ...
                "persistent_simultaneous_cluster"));
            testCase.verifyFalse(any([collisionEvents. ...
                reliableSmoothBifurcation]));
        end

        function mapOrbitAndTopologyMarginsCarryClusterMetadata(testCase)
            system = createSyntheticReturnPolicySystem_v3('two-apex');
            simulator = HybridSimulator_v3(struct( ...
                'RelTol', 1e-10, 'AbsTol', 1e-12));
            map = PoincareMap_v3(system, PoincareSection_v3.apex(2), ...
                simulator, EventCycleReturnPolicy_v3(), struct( ...
                'MaxReturnTime', 3, 'MaxSectionCrossings', 4, ...
                'MaxCycleEvents', 8, 'ArmTolerance', 1e-7));
            residual = PeriodicOrbitResidual_v3(map, [1; 0]);

            [~, details] = residual.evaluateWithInfo([1; 0], [], 0);
            orbit = residual.createOrbit([1; 0], [], 0, details);
            info = details.map_info;

            testCase.verifyEqual(info.event_cluster_count, 2);
            testCase.verifyNumElements(info.event_clusters, 2);
            testCase.verifyEqual(info.minimum_event_time_separation, ...
                info.minimum_intercluster_gap);
            testCase.verifyEqual(info.topology_margins. ...
                minimum_intercluster_gap, info.minimum_intercluster_gap);
            testCase.verifyEqual(orbit.event_cluster_count, 2);
            testCase.verifyEqual(orbit.event_cluster_signature, ...
                info.event_cluster_signature);
            testCase.verifyEqual(orbit.minimum_intercluster_gap, ...
                info.minimum_intercluster_gap);
            testCase.verifyTrue(isfield( ...
                orbit.event_cluster_split_merge_diagnostics, ...
                'reference_supplied'));
        end
    end

    methods (Static, Access = private)
        function history = history(names, times)
            names = string(names(:));
            times = times(:);
            history = repmat(struct('time', NaN, 'type', ""), ...
                numel(times), 1);
            for index = 1:numel(times)
                history(index).time = times(index);
                history(index).type = names(index);
            end
        end

        function point = point(report, coordinate)
            members = report.clusters;
            history = struct([]);
            for clusterIndex = 1:numel(members)
                history = [history; members(clusterIndex).members(:)]; %#ok<AGROW>
            end
            point = struct('event_cluster_report', report, ...
                'event_history', history, 'period', report.period, ...
                'continuationCoordinate', coordinate, ...
                'mode', 0, 'return_multiplicity', 1, ...
                'cyclic_signature', char(report.cyclic_cluster_signature), ...
                'event_counts', [], 'guard_transversality', Inf, ...
                'topology_margins', struct());
        end
    end
end
